
{_LABEL_FECHA_SALIDA}:           {DIA_SALIDA} {FECHA_SALIDA}
{_LABEL_HORA_SALIDA}:            {HORA_SALIDA}
{_LABEL_FECHA_LLEGADA}:          {DIA_LLEGADA} {FECHA_LLEGADA}
{_LABEL_HORA_LLEGADA}:           {HORA_LLEGADA}
{_LABEL_ORIGEN_AEROPUERTO}:    {CIUDAD_ORIGEN} ({CODIGO_AEROPUERTO_ORIGEN})
{_LABEL_DESTINO_AEROPUERTO}:   {CIUDAD_DESTINO} ({CODIGO_AEROPUERTO_DESTINO})
{_LABEL_ESCALAS}:                {ESCALAS}
{_LABEL_VUELO}:                  {AIRLINE_CODE}{NUMERO_VUELO} {OPERADO_POR}
{_LABEL_CABINA}:                 {CABINA_TXT}-{CLASE}
{_TXT_TIPO_AVION}:             {MATERIAL_DE_VUELO}

