<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>T&eacute;rminos y Condiciones</title>
<link rel="stylesheet" href="/es_cl/css/base.css" type="text/css"> 
<link rel="stylesheet" href="/es_cl/css/contenido.css" type="text/css">
<style type="text/css">
<!--
.Estilo1 {font-weight: bold}
-->
</style>
</head>
<body>
<div id="contenido">
<div id="contenido_popup">
  <h2>LANPASS Nutzungsbedingungen</h2>

         <h3>1. Definitionen </h3>
<ul><li><strong>1.1 Vielfliegerprogramm, LANPASS-Programm, Programm oder LANPASS</strong>: ist das Vielfliegerprogramm von LAN, mit dessen Hilfe man bei Reisen auf allen Flugrouten von LAN und den Partnerfluggesellschaften und bei der Inanspruchnahme der Dienstleistungen von Partnerunternehmen Kilometer sammeln kann. Dies alles unterliegt den Nutzungsbedingungen und -voraussetzungen, die im Anschluss erl&auml;utert werden.<br>
  Das LANPASS-Programm stellt keinen Vertrag jeglicher Natur zwischen LAN und dem Mitglied dar, da es sich bei den Pr&auml;mien oder Privilegien und Pr&auml;mien oder Privilegien oder LANPASS Privilegien um rein freiwillige Serviceleistungen von LAN f&uuml;r Mitglieder handelt, die sich aus freien St&uuml;cken bei dem LANPASS-Programm angemeldet haben. F&uuml;r diese Mitglieder sind die Pr&auml;mien oder Privilegien und Pr&auml;mien oder Privilegien oder LANPASS Privilegien kostenlos, es sei denn, es ist in den Bedingungen etwas Gegenteiliges angegeben.</li>
   <li><strong>1.2 Mitglied des LANPASS-Programms oder Mitglied</strong>: ist die Person, die die Voraussetzungen f&uuml;r das Programm erf&uuml;llt, die das Anmeldeformular ausgef&uuml;llt und es in irgendeiner der in Klausel 2.2. festgesetzten Formen eingereicht hat, deren Antrag von LANPASS akzeptiert wurde und deren Eigenschaft als Mitglied weder widerrufen noch nach den Normen der gegenw&auml;rtigen Regelungen ung&uuml;ltig ist. Im Falle der Premium, Premium Silver und Comodoro Kategorien erscheint der Name des Mitglieds auf seiner Mitgliedskarte mit der entsprechenden Mitgliedsnummer, die gleichzeitig die Kontonummer darstellt.<br>
   Jedes Konto besteht nur f&uuml;r eine einzelne Person und erkennt nur einen einzigen Kontoinhaber an, wobei es nicht m&ouml;glich ist, zus&auml;tzliche Mitglieder aufzunehmen.</li>
   <li><strong>1.3 LANPASS-Kilometer oder schlicht Kilometer</strong>: sind die Ma&szlig;einheiten des LANPASS-Programms. Diese k&ouml;nnen gem&auml;&szlig; Kapitel 7 dieses Regelwerkes ausschlie&szlig;lich gegen Flugtickets eingel&ouml;st werden.</li>
   <li><strong>1.4 Kontostand</strong>: ist die Information, die LANPASS regelm&auml;&szlig;ig an die Mitglieder des LANPASS-Programms sendet. Darin werden die verf&uuml;gbare Kilometeranzahl, alle Kontobewegungen, die mit Aktivit&auml;ten des LANPASS-Programms verbunden sind, und alle anderen dazugeh&ouml;rigen Informationen aufgezeigt. Diese Kontostandanzeige und jene, die online abrufbar ist, stellen die einzigen g&uuml;ltigen Informationen, was die Bewegungen auf dem Mitgliedskonto betrifft, dar.</li>
   <li><strong>1.5 Mitgliedskarte oder LANPASS-Karte</strong>: ist der Mitgliedsausweis des LANPASS-Programms f&uuml;r die Mitgliedskategorien Premium, Premium Silver und Comodoro, der von LANPASS f&uuml;r die entsprechende Mitgliedskategorie ausgestellt und an die Mitglieder ausgegeben wird.</li>
   <li><strong>1.6 Partnerfluggesellschaften</strong>: sind die Fluggesellschaften abgesehen von LAN, deren Fl&uuml;ge das Sammeln von Kilometern und/oder die Nutzung von Pr&auml;mien oder Privilegien oder Privilegien des LANPASS-Programms erlauben. Dies alles unterliegt den Nutzungsbedingungen und &ndash;voraussetzungen dieses Regelwerkes und jenen, auf die diese Fluggesellschaften verweisen.</li>
   <li><strong>1.7 Partnerunternehmen</strong>: sind alle am LANPASS-Programm teilnehmenden Unternehmen, au&szlig;er den Partnerfluggesellschaften, deren Dienstleistungen, das Sammeln von Kilometern und/oder die Nutzung von Pr&auml;mien oder Privilegien oder Privilegien des LANPASS-Programms erlauben. Dies alles unterliegt den Nutzungsbedingungen und &ndash;voraussetzungen dieses Regelwerkes und jenen, auf die diese Partnerunternehmen verweisen.</li>
   <li><strong>1.8 Pr&auml;mien oder Privilegien oder LANPASS Privilegien</strong>: Jene Flugtickets, die man gegen eingel&ouml;ste LANPASS Kilometer erhalten kann, wie im Leitfaden zu den Privilegien f&uuml;r Mitglieder beschrieben wird.</li>
   <li><strong>1.9 Leitfaden zu den Privilegien f&uuml;r Mitglieder</strong>: Dieses Dokument erl&auml;utert den Mitgliedern die Pr&auml;mien oder Privilegien und Pr&auml;mien oder Privilegien des LANPASS-Programms und die Art und Weise der Inanspruchnahme und die Voraussetzungen f&uuml;r die Nutzung dieser Pr&auml;mien oder Privilegien und Pr&auml;mien und die grundlegenden Begriffe und die Mindestbedingungen, die erf&uuml;llt werden m&uuml;ssen. Dieser Leitfaden ist unter www.lan.com verf&uuml;gbar.</li>
   <li><strong>1.10 Pr&auml;mien- oder Privilegientabelle</strong>: ist die von LAN erstellte Tabelle, die in regelm&auml;&szlig;igen Abst&auml;nden ver&auml;ndert werden kann, falls es LAN f&uuml;r n&ouml;tig h&auml;lt, und die die notwendigen LANPASS Kilometer angibt, um eine bestimmte Pr&auml;mie oder ein bestimmtes Privileg zu beantragen.</li>
   <li><strong>1.11 Pr&auml;mienzertifikat</strong>: Zertifikat, das von LANPASS ausgestellt wird und die Gew&auml;hrung einer bestimmten Pr&auml;mie anzeigt, welche, so wie im Zertifikat angegeben, gegen ein bestimmtes Flugticket eingel&ouml;st werden kann.</li>
   <li><strong>1.12 Embargo</strong>: Zeitraum, in dem die Pr&auml;mien oder Privilegien aus LANPASS Kilometern &ndash; ob bei LAN, bei den Partnerfluggesellschaften und/oder den Partnerunternehmen &ndash; nicht genutzt werden k&ouml;nnen.<br>
   Die Embargodaten jeder Einheit werden zu gegebenem Anlass den Mitgliedern mitgeteilt.</li>
   <li><strong>1.13 Stop-Over</strong>: ist ein Aufenthaltspunkt zwischen der Start- und Zieldestination, an dem sich der Passagier eine bestimmte Zeit lang aufh&auml;lt, um sp&auml;ter mit derselben Fluggesellschaft die Reise zu seiner Enddestination fortzusetzen.</li>
   <li><strong>1.14 Open-Jaw</strong>: Flug, bei dem die Zieldestination auf dem Hinflug eine andere als der Abflugort der R&uuml;ckreise ist (Beispiel: Hinflug von Santiago nach New York, R&uuml;ckflug von Los Angeles nach Santiago).</li>
   <li><strong>1.15 Zwischenlandung</strong>: ist einer technischer Halt zwischen der Start- und Zieldestination, w&auml;hrend der der Passagier im Allgemeinen f&uuml;r kurze Zeit im Flugzeug oder am Flughafen bleibt, um dann die Weiterreise zu seinem Zielort fortzusetzen.</li>
   <li><strong>1.16 Umsteigepunkt</strong>: ist ein Aufenthalt zwischen der Start- und Zieldestination, an dem der Passagier maximal 24 Stunden bleibt, um dann mit derselben Fluggesellschaft die Weiterreise zu seinem Zielort fortzusetzen.</li>
   <li><strong>1.17 Segment</strong>: Als Segment bezeichnet man einen Direktflug zwischen zwei Orten, der Zwischenlandungen beinhalten kann oder nicht.</li>
   <li><strong>1.18 Upgrade</strong>: erlaubt einem Passagier den Zugang zur n&auml;chsth&ouml;heren Kabinenklasse, ohne dass er ein Ticket f&uuml;r diese erworben hat.</li></ul>
   <h3>2. AUFNAHMEBEDINGUNGEN </h3>
   <ul><li><strong>2.1</strong> Mitglied im LANPASS Programm k&ouml;nnen - unabh&auml;ngig von ihrer Nationalit&auml;t und ihrem Wohnort - nur &uuml;ber 2 Jahre alte, nat&uuml;rliche Personen werden, sofern sie (i) alle Anforderungen des Programms erf&uuml;llen, (ii) das entsprechende Anmeldeformular ausgef&uuml;llt und einreicht haben, (iii) ausdr&uuml;cklich vom LANPASS Programm akzeptiert wurden und ihr Status als Mitglied weder widerrufen noch nach den Normen der gegenw&auml;rtigen Regelungen ung&uuml;ltig ist.</li>
   <li><strong>2.2 </strong>Der Antrag auf Aufnahme im LANPASS-Programm wird durch das Ausf&uuml;llen des entsprechenden Anmeldeformulars gestellt, das in allen LAN Verkaufsb&uuml;ros und bei den Partnerunternehmen erh&auml;ltlich ist. Au&szlig;erdem kann die Anmeldung telefonisch bei der LAN Reservierungszentrale oder &uuml;ber das Internet unter www.lan.com geschehen.</li>
   <li><strong>2.3</strong> Nachdem der Aufnahmeantrag bei LANPASS eingegangen ist, wird der Antragsteller durch eine E-mail an die von ihm angegebene Adresse im Programm willkommen gehei&szlig;en und dar&uuml;ber informiert, dass er als Mitglied akzeptiert wurde. Falls der Antragsteller keine Best&auml;tigung seiner Anmeldung erh&auml;lt, sollte er LANPASS telefonisch kontaktieren, um sich &uuml;ber das Ergebnis des Antrags zu informieren.</li>
   <li><strong>2.4 </strong>Diese Willkommens-Email liefert die grundlegenden Informationen zum Programm, best&auml;tigt die Mitgliedsnummer des neu angemeldeten LANPASS Mitglieds und enth&auml;lt einen Link auf die Seite von www.lan.com, auf der das Mitglied sein LANPASS Passwort kreieren kann, falls die Anmeldung mit einem Antragsformular aus Papier oder auf anderem Wege geschehen ist, bei dem ebenfalls kein Zugangspasswort f&uuml;r die LANPASS Website ausgeh&auml;ndigt wurde.</li>
   <li><strong>2.5</strong> LANPASS Kilometer, die vor der ausdr&uuml;cklichen Aufnahme eines Antragstellers gesammelt wurden, k&ouml;nnen nicht gegen Pr&auml;mien eingel&ouml;st werden, au&szlig;er diese Person ist zwischenzeitlich ausdr&uuml;cklich als Mitglied akzeptiert worden.</li>
   <li><strong>2.6 </strong>Die Korrektheit der Daten, die im Aufnahmeantrag oder bei einer Aktualisierung angegeben werden, liegt in der ausschlie&szlig;lichen Verantwortung des Mitglieds.</li>
   <li><strong>2.7</strong> Bei der Postadresse, die von dem Mitglied angegeben wird, darf es sich weder um ein Postfach noch um eine Adresse, die nicht von der Post bedient wird, handeln. LANPASS lehnt jede Verantwortung f&uuml;r die nicht ordnungsgem&auml;&szlig;e Zustellung von Postsendungen an solche Adressen ab.</li>
   <li><strong>2.8</strong> Jede LANPASS-Mitgliedskarte ist streng pers&ouml;nlich und nicht &uuml;bertragbar. Jeder unangemessene, unsachgem&auml;&szlig;e oder gegen das Regelwerk versto&szlig;ende Gebrauch einer LANPASS-Mitgliedskarte kann den Ausschluss aus dem LANPASS Programm bedeuten und die L&ouml;schung aller angesammelten LANPASS Kilometer zur Folge haben. Dies gilt unbeschadet der sonstigen rechtlichen Schritte, die in einem solchen Fall eingeleitet werden.</li>
   <li><strong>2.9 </strong>Der Antragsteller und/oder das Mitglied erkennen an und akzeptieren, die einzige Person zu sein, die f&uuml;r jeglichen Geldbetrag verantwortlich ist, der in Form u.a. von Steuern, Geb&uuml;hren und Rechten an irgendeine nat&uuml;rliche oder juristische, &ouml;ffentliche oder private Person entrichtet werden muss. Dies kann Konsequenz aus der Sammlung oder Nutzung von LANPASS Kilometern, aus der Aufnahme im LANPASS Programm oder aus der Nutzung einer Pr&auml;mie oder eines Privilegs desselben sein.</li>
   <li><strong>2.10</strong> Jede &Auml;nderung der angegebenen Daten muss schriftlich mit der Unterschrift des entsprechenden Mitglieds, &uuml;ber das Call-Center unter Identit&auml;tspr&uuml;fung oder &uuml;ber die Website des Programms mitgeteilt werden. Es werden keine m&uuml;ndlichen &Auml;nderungsmitteilungen akzeptiert, au&szlig;er um den Wohnsitz oder die Telefonnummer zu &auml;ndern. Um die entsprechenden &Auml;nderungen in die Wege zu leiten, kann das Mitglied LANPASS postalisch oder &uuml;ber das Internet kontaktieren.</li>
   <li><strong>2.11</strong> Es ist nur ein Konto pro Mitglied erlaubt. Falls zwei oder mehr Konten existieren sollten, werden die neueren gel&ouml;scht. Alle LANPASS Kilometer, die auf den gel&ouml;schten Konten angesammelt waren, werden auf das Originalkonto &uuml;bertragen, vorausgesetzt dass diese Kilometer nicht auf beiden Konten gutgeschrieben waren.</li>
   <li><strong>2.12</strong> Es ist weder erlaubt, LANPASS Kilometer von einem LANPASS Konto auf ein anderes, noch auf Konten von Partnerfluggesellschaften und/oder Partnerunternehmen zu &uuml;bertragen.<br>
   Der Verkauf, die Abtretung oder &Uuml;bertragung von LANPASS Kilometern oder von den damit verbundenen Pr&auml;mien ist auf allen Wegen, inklusive &uuml;ber das Internet, strikt verboten.</li>
   <li><strong>2.13 </strong>Um eine Pr&auml;mie zu beantragen, ist es nicht m&ouml;glich, LANPASS Kilometer von verschiedenen LANPASS Konten oder Konten von Partnerfluggesellschaften und/oder Partnerunternehmen zu b&uuml;ndeln.</li>
   <li><strong>2.14</strong> Mit dem Ausf&uuml;llen des Anmeldeformulars akzeptiert das Mitglied Informationen zum Programm und andere Mitteilungen von LAN, die mit dem LANPASS Programm verbunden sind oder nicht, an seine Email-Adresse oder Postadresse zu erhalten.</li>
   <li><strong>2.15</strong> Die Form und H&auml;ufigkeit der Versendung von Kontost&auml;nden, Informationen zu Privilegien f&uuml;r Mitglieder und andere Mitteilungen bleibt LAN freigestellt, wobei als Kommunikationsmedien physische (wie &ouml;ffentliche oder private Postsendungen) oder elektronische (E-mails) m&ouml;glich sind.</li>
   <li><strong>2.16 </strong>Zus&auml;tzlich zu den im vorangegangenen Abschnitt genannten Bedingungen akzeptiert der Antragsteller oder das Mitglied durch das Ausf&uuml;llen des Anmeldeformulars, dass LAN frei &uuml;ber die in diesem Formular angegebenen Daten zu Gunsten des Programms, von LAN oder Dritten, verf&uuml;gen kann.<br>
   Grunds&auml;tzliche Voraussetzung f&uuml;r die Teilnahme am LANPASS Programm ist, dass die Kilometersammlung gem&auml;&beta; den Nutzungsbedingungen dieses Programms geschieht und die jeweils geltenden Regelungen voll und ganz eingehalten werden.</li></ul>
   <h3>3. ENDE DER TEILNAHME AM PROGRAMM</h3>
   <ul><li><strong>3.1</strong> Die Teilnahme eines Mitglieds am LANPASS Programm endet in den folgenden F&auml;llen:</li>
   <li><strong>3.1.1</strong> Falls ein Mitglied eine hier aufgef&uuml;hrte Nutzungsbedingung nicht einh&auml;lt oder falls die Nutzung des LANPASS Programms oder die Kilometersammlung gesetzeswidrig oder mit Versto&beta; gegen die geltenden Regelungen geschieht.</li>
   <li><strong>3.1.2 </strong>Falls das Mitglied wissentlich inkorrekte oder falsche Angaben (inklusive zu Fl&uuml;gen) macht. Sei es bei Anmeldung f&uuml;r das Programm oder bei Beantragung der entsprechenden Pr&auml;mien.</li>
   <li><strong>3.1.3</strong> Falls das Mitglied nicht die Bedingungen des Bef&ouml;rderungsvertrags f&uuml;r Passagiere erf&uuml;llt (der f&uuml;r alle Passagiere Anwendung findet).</li>
   <li><strong>3.1.4</strong> Falls das Mitglied einen unangemessenen oder unsachgem&auml;&szlig;en Gebrauch von den ausgeh&auml;ndigten Pr&auml;mien und/oder Privilegien macht.</li>
   <li><strong>3.1.5</strong> Falls das Mitglied f&auml;llige Schulden bei LAN, ihren Tochter- oder Partnerunternehmen hat oder wenn Anzeichen f&uuml;r die Verwicklung des Mitglieds in Delikte gegen diese Gesellschaften bestehen, wie u.a. vors&auml;tzlicher Scheckbetrug.</li>
   <li><strong>3.1.6</strong> Auf ausdr&uuml;cklichen Wunsch des Mitglieds, den es jederzeit schriftlich aussprechen kann. Elite-Mitglieder m&uuml;ssen dabei au&szlig;erdem ihre in der Mitte durchgeschnittene Mitgliedskarte beilegen.</li>
   <li><strong>3.1.7</strong> Bei Ableben des Mitglieds.</li>
   <li><strong>3.1.8</strong> Falls das LANPASS Programm aus irgendeinem Grund endet.</li>
   <li><strong>3.1.9</strong> Auf einseitigen Wunsch von LANPASS, jederzeit, bei vorheriger Ank&uuml;ndigung.</li>
   <li><strong>3.2</strong>. Falls die Teilnahme am LANPASS Programm oder das Programm selbst endet, werden alle gesammelten Kilometer gel&ouml;scht und k&ouml;nnen unter keinen Umst&auml;nden weder genutzt noch gegen Flugtickets und/oder Geld eingel&ouml;st werden. </li></ul>
   <h3>4. ZEITWEILIGE AUSSETZUNG DER MITGLIEDSRECHTE</h3>
   <ul><li><strong>4.1</strong> LANPASS kann die Rechte und Privilegien eines Mitglieds zeitweilig aussetzen, ohne dass die Mitgliedschaft endet. D.h. das Mitglied kann weiterhin Kilometer sammeln, aber es ist ihm nicht erlaubt, Tickets einzul&ouml;sen oder ein Programmprivileg einzufordern, solange LANPASS seine Mitgliedsrechte nicht wieder voll herstellt. </li>
   <li><strong>4.2</strong> LANPASS kann von dem Recht auf Aussetzung Gebrauch machen, wenn das Mitglied f&auml;llige Schulden gegen&uuml;ber LAN oder einem Tochter- oder Partnerunternehmen hat. Oder wenn es Indizien gibt, dass das Mitglied in Delikte gegen eine dieser Gesellschaften verwickelt ist, wie u.a. vors&auml;tzlicher Scheckbetrug. </li>
   <li><strong>4.3</strong> Unbeschadet dessen ist es m&ouml;glich, dass das Mitglied seinen Status komplett verliert, wenn ein Fall eintritt, der in diesem Regelwerk genannt wird. </li></ul>
   <h3>5. MITGLIEDSKARTE ODER LANPASS-KARTE</h3>
   <ul><li><strong>5.1</strong> Die LANPASS Mitgliedskarte hat unbegrenzte G&uuml;ltigkeit. Jedoch besitzen die Mitgliedskarten f&uuml;r LANPASS Premium, LANPASS Premium Silver und LANPASS Comodoro die G&uuml;ltigkeit, die der Laufzeit der Kategorie entspricht, so wie sie in den Details des Programms unter www.lan.com angegeben ist. Die G&uuml;ltigkeit kann gem&auml;&szlig; den Angaben in Absatz 6 verl&auml;ngert werden. F&uuml;r alle Regelungen gilt, dass das &quot;Kalenderjahr&quot; dem Zeitraum vom 1. Januar bis 31. Dezember jeden Jahres entspricht.</li>
   <li><strong>5.2 </strong>Karten, die von Partnerunternehmen ausgestellt werden, sind den Nutzungsbedingungen des jeweiligen Unternehmens unterworfen. Unbeschadet dessen m&uuml;ssen die hier festgesetzten Regelungen, was Partnerunternehmen betrifft, eingehalten werden. </li>
   <li><strong>5.3 </strong>Die Person, deren Name auf der Mitgliedskarte steht, ist die einzige, die das Recht hat, diese f&uuml;r jegliche Zwecke zu nutzen. </li>
   <li><strong>5.4</strong> Die Mitgliedskarte ist weder eine Kreditkarte noch ein Identifikationsdokument, so dass sie keine au&szlig;er den in diesem Regelwerk aufgef&uuml;hrten Rechten gew&auml;hrt. </li>
   <li><strong>5.5</strong> Alle Mitgliedskarten sind exklusives Eigentum von LANPASS.</li>
   <li><strong>5.6 </strong>Das Mitglied hat die Pflicht, unverz&uuml;glich dem n&auml;chsten LAN Verkaufsb&uuml;ro pers&ouml;nlich oder per Telefon mitzuteilen, dass seine Mitgliedskarte verloren oder gestohlen wurde. Nachdem LANPASS den Fall evaluiert hat, kann innerhalb von 30 Tagen eine neue Karte ausgestellt werden. </li></ul>
   <h3>6. MITGLIEDERKATEGORIEN</h3>
   <ul><li><strong>6.1</strong> Das LANPASS Programm besitzt vier Mitgliederkategorien: (a) LANPASS, (b) Premium, (c) Premium Silver und (d) Comodoro. Dabei existiert nur f&uuml;r die drei letzteren eine zugeh&ouml;rige Mitgliedskarte.   
   <li><strong>6.2 </strong>Die verschiedenen Mitgliederkategorien sind durch die Erf&uuml;llung der Anforderungen f&uuml;r die Zulassung zu jeder Kategorie bestimmt, die im Abschnitt LANPASS der Homepage von www.lan.com beschrieben werden.   
   <li><strong>6.3</strong> Die Kategorie, die einem Mitglied zusteht, wird in erster Linie durch die Anzahl der mit sammelf&auml;higen Tarifen bei LAN oder bei <strong>one</strong>world Partnerfluggesellschaften geflogenen Kilometer festgelegt. Dazu kommen Kabinenklassenboni (f&uuml;r Business  Class), die das Mitglied auf LAN Fl&uuml;gen verdient hat. Diese haben nur G&uuml;ltigkeit, wenn mindestens vier Flugsegmente mit sammelf&auml;higen Tarifen auf LAN geflogen werden. Die andere Variante, die die Mitgliedskategorie bestimmt, ist die Anzahl der mit sammelf&auml;higen Tarifen bei LAN geflogenen Flugsegmente. Die entscheidenden Anforderungen m&uuml;ssen innerhalb eines Kalenderjahres erf&uuml;llt werden.<br>
   F&uuml;r die Kategorien Comodoro und Premium Silver gibt es au&szlig;erdem eine spezielle Regelung, die eine geringere Kilometeranzahl bei einer bestimmten Anzahl von Segmenten erlaubt, wenn es sich um LAN Langstreckenfl&uuml;ge in Business Class handelt. Welche Fl&uuml;ge als Langstreckenfl&uuml;ge definiert sind und welche Anzahl an Kilometern f&uuml;r die jeweilige Kategorie notwendig ist, wird unter www.lan.com detailliert ausgef&uuml;hrt.   
   <li><strong>6.4</strong> F&uuml;r die Feststellung der zutreffenden Mitgliedskategorie werden keine LANPASS Kilometer gez&auml;hlt, die bei Partnerunternehmen und/oder Partnerfluggesellschaften gesammelt wurden (au&szlig;er das Gegenteil ist ausdr&uuml;cklich angegeben).   
   <li><strong>6.5</strong> F&uuml;r die Feststellung der zutreffenden Mitgliedskategorie werden au&szlig;erdem keine Strecken angerechnet, die mit Pr&auml;mientickets oder einem anderen, nicht f&uuml;r die Sammlung von LANPASS Kilometern qualifizierten Ticket geflogen wurden.   
   <li><strong>6.6</strong> Die Laufzeit einer Mitgliedskategorie entspricht dem Folgejahr und dem Rest des Jahres, in dem das Mitglied die Anforderungen erf&uuml;llt hat, um sich f&uuml;r eine Kategorie zu qualifizieren.   
   <li><strong>6.7</strong> Es liegt im Ermessen von LANPASS einem Mitglied zu erm&ouml;glichen, in einer Kategorie zu bleiben oder in einen h&ouml;here aufzusteigen, auch wenn das Mitglied nicht alle notwendigen Anforderungen erf&uuml;llt. Jedoch ist es nicht m&ouml;glich, in eine niedrigere Kategorie eingeordnet zu werden, wenn das Mitglied die Anforderungen erf&uuml;llt, um in der derzeitigen Kategorie zu bleiben.   
   <li><strong>6.8</strong> Wenn Mitglieder nicht mehr die Anforderungen erf&uuml;llen, um die Zugeh&ouml;rigkeit zu einer Mitgliedskategorie zu verl&auml;ngern, wechseln sie im darauf folgenden Jahr in die n&auml;chstniedrigere Kategorie, unabh&auml;ngig davon, ob die Anforderungen daf&uuml;r erf&uuml;llt werden.   
   <li><strong>6.9</strong> Ab 2004 treten Verl&auml;ngerungen am 31. M&auml;rz jeden Jahres ein, wobei die Erf&uuml;llung der Anforderungen durch das Mitglied im letzten Kalenderjahr zugrunde gelegt wird.   
   <li><strong>6.10 </strong>&Auml;nderungen, was die Mitgliedskategorie betrifft, haben keinen Einfluss auf den Kilometerstand f&uuml;r die Einl&ouml;sung von Pr&auml;mien und umgekehrt.</li></ul>
     <h3>7. KILOMETER</h3>
     <ul><li><strong>7.1</strong> Die Ma&szlig;einheit des LANPASS Programms ist Kilometer.</li>
     <li><strong>7.2</strong> Die Kilometer besitzen die folgenden Eigenschaften und sind den folgenden Bedingungen unterworfen:</li>
     <li><strong>7.2.1</strong> Sie besitzen keinen Handelswert, da sie weder umsetzbar sind noch gegen Geld oder etwas Anderes eingetauscht werden k&ouml;nnen. </li>
     <li><strong>7.2.2</strong> Sie sind weder kostenlos noch gegen Entgelt abtretbar.</li>
     <li><strong>7.2.3</strong> Sie sind nicht &uuml;bertragbar. Im Falle des Todes des Mitglieds werden das Konto und die gesammelten Kilometer gel&ouml;scht.</li>
     <li><strong>7.2.4</strong> Sie k&ouml;nnen nicht gepf&auml;ndet werden, da es sich um rein pers&ouml;nliche Rechte handelt.</li>
     <li><strong>7.2.5</strong> Sie k&ouml;nnen weder Objekt eines Rechtsstreits noch einer gerichtlichen Ma&szlig;nahme sein und geh&ouml;ren ausschlie&szlig;lich dem Kontoinhaber als rein pers&ouml;nliches Recht.</li>
     <li><strong>7.2.6</strong> Die vom Mitglied eingel&ouml;sten Pr&auml;mien k&ouml;nnen nicht zur&uuml;ckerstattet warden. Falls ein Mitglied die R&uuml;ckerstattung einer ausgestellten Pr&auml;mie fordert, muss eine Kilometergeb&uuml;hr entrichtet werden. Die Geb&uuml;hr variiert je nach Pr&auml;mie und entspricht den unter www.lan.com ver&ouml;ffentlichten Informationen. Die R&uuml;ckerstattung der Pr&auml;mie setzt voraus, dass das ausgestellte Ticket g&uuml;ltig ist (die G&uuml;ltigkeitsfrist beginnt ab der Ticketausstellung), dass die R&uuml;ckerstattung vor dem Abflugtag geschieht, bevor irgendeine Strecke geflogen wurde - au&beta;er bei oneworld Upgrades - und dass die f&uuml;r die Ausstellung genutzten Kilometer zum Zeitpunkt der Anforderung der R&uuml;ckerstattung nicht abgelaufen sind. </li>
     <li><strong>7.2.7 </strong>Pr&auml;mien sind nicht indossierbar, daher k&ouml;nnen Sie nicht bei Gesellschaften genutzt werden, die nicht LAN oder die Partnerfluggesellschaften sind. Au&szlig;erdem k&ouml;nnen sie von keiner anderen Person genutzt werden, als von derjenigen, die vom Inhaber des Kontos bei der Einl&ouml;sung angegeben wurde. Sobald ein Pr&auml;mienticket ausgestellt ist, kann es ausschlie&szlig;lich bei der angegebenen Fluggesellschaft benutzt werden. </li></ul>
     <h3>8. DAS SAMMELN VON KILOMETERN</h3>
     <ul><li><strong>8.1</strong> Es werden Kilometer gutgeschrieben, wenn ein Mitglied mit LAN oder einer Partnerfluggesellschaft fliegt (nur wenn die Fl&uuml;ge auch von denselben operiert werden) oder wenn ein Mitglied die berechtigten Dienstleistungen eines Partnerunternehmens nutzt. Im Falle dass ein Mitglied dem LANPASS Programm und gleichzeitig einem Vielfliegerprogramm einer Partnerfluggesellschaft oder eines Partnerunternehmens angeh&ouml;rt, k&ouml;nnen die Kilometer nur auf einem Konto, je nach Wunsch des Mitglieds, gutgeschrieben werden. Unter keinen Umst&auml;nden k&ouml;nnen die Kilometer auf mehr als einem Konto gutgeschrieben werden. Das Mitglied muss daf&uuml;r seine Mitgliedsnummer angeben, die auf der Bordkarte erscheint.<br>
       Wenn es sich um Fl&uuml;ge handelt, die von einer anderen Fluggesellschaft operiert werden, aber aus irgendeinem Grund eine LAN Flugnummer besitzen, werden diese Fl&uuml;ge als g&uuml;ltig erachtet, um Kilometer zu sammeln und um sich f&uuml;r die Kategorien Premium, Premium Silver und Comodoro zu qualifizieren. Immer unter der Voraussetzung, dass die Fl&uuml;ge mit Tarifen, auf Routen und an Terminen stattfinden, die die Sammlung von LANPASS Kilometern erlauben.</li>
       <li><strong>8.2 </strong>Die durch die Partnerfluggesellschaften festgesetzten Bedingungen dar&uuml;ber, wie und wie viele Kilometer auf ihren Fl&uuml;gen gesammelt werden k&ouml;nnen, m&uuml;ssen nicht unbedingt mit den von LAN f&uuml;r eigene Fl&uuml;ge festgesetzten Bedingungen &uuml;bereinstimmen. Die Zahl der gesammelten Kilometer h&auml;ngt vom bezahlten Tarif und von den dazugeh&ouml;rigen Bedingungen ab. So kann es Tarife oder Fl&uuml;ge geben, die vorgeben, dass nur einen Prozentsatz der geflogenen Kilometerdistanz gesammelt werden kann oder dass andere Restriktionen bestehen k&ouml;nnen. Es liegt in der Verantwortung des Mitglieds, in Erfahrung zu bringen, wie viele Kilometer er f&uuml;r seine Fl&uuml;ge mit Partnerfluggesellschaften sammeln kann.</li>
       <li><strong>8.3 </strong>Fl&uuml;ge von dritten Fluggesellschaften, die von LAN operiert werden, sind nicht f&uuml;r die Kilometersammlung qualifiziert. Ebenso wenig wie Fl&uuml;ge mit einer Flugnummer von einer <strong>one</strong>world Fluggesellschaft, die von einer dritten Fluggesellschaft operiert werden.</li>
       <li><strong>8.4</strong> Die nachtr&auml;gliche Gutschrift von Kilometern ist nur m&ouml;glich, wenn es sich um LAN Fl&uuml;ge handelt, die nicht mehr als 60 Tage vor Anmeldung bei LANPASS stattfanden.</li>
       <li><strong>8.5 </strong>Kilometer werden erst auf dem Mitgliedskonto gutgeschrieben, wenn das Ticket bezahlt und die Reise durchgef&uuml;hrt wurde. Daher werden keine Kilometer f&uuml;r Tickets gesammelt, die zwar erworben, aber entweder nicht geflogen oder bezahlt wurden. Aus diesem Grund ist es die Pflicht des Mitglieds Dokumente, die die Durchf&uuml;hrung seiner Reise belegen, aufzubewahren und falls gefordert, diese einzureichen (Flugticket und Bordkarte).</li>
       <li><strong>8.6</strong> Kilometer, die bei Partnerfluggesellschaften oder Partnerunternehmen generiert werden, k&ouml;nnen erst auf dem Mitgliedskonto gutgeschrieben werden, wenn das jeweilige Unternehmen die f&uuml;r LAN f&uuml;r die Verbuchung der Kilometer n&ouml;tige Information weitergeleitet hat. Dies kann in der Regel bis zu 30 Tage nach der Kilometergenerierung dauern. </li>
       <li><strong>8.7</strong> Die gesammelten Kilometer entsprechen der Distanz zwischen Startpunkt und Zielort des Fluges, welche von IATA bereitgestellt wird. <br>
         Unbeschadet dessen beh&auml;lt sich LANPASS das Recht vor, als tempor&auml;re oder permanente Ma&szlig;nahme, Distanzen zwischen Startpunkt und Zielort mit zus&auml;tzlichen Kilometern zu bonifizieren. </li>
       <li><strong>8.8 </strong>Kilometer, die auf LAN Fl&uuml;gen gesammelt werden, besitzen eine G&uuml;ltigkeit von 36 fortlaufenden Monaten seit dem Abflugdatum. Jedoch verfallen die Kilometer erst am letzten Tag des Verfallsmonats. <br>
       Kilometer, die auf Fl&uuml;gen von Partnerfluggesellschaften und durch die Nutzung von Dienstleistungen von Partnerunternehmen oder durch Spezialangebotsboni gesammelt werden, besitzen eine G&uuml;ltigkeit von 3 Kalenderjahren. Das bedeutet, dass sie am 31. Dezember des dritten Jahres, nachdem sie gesammelt wurden, verfallen.<br>
       Zu beachten ist, dass, jedes Mal wenn der Passagier mit LAN fliegt und mindestens 1 Kilometer dabei sammelt, sich die G&uuml;ltigkeit aller bereits vorher gesammelten Kilometer um weitere 36 fortlaufende Monate seit dem Abflugdatum verl&auml;ngert und dass diese Kilometer erst am letzten Tag des Verfallsmonats verfallen. <br>
       Ungeachtet dessen sind Kilometer, die vor dem 1. Mai 1998 gesammelt wurden, bis 31. Dezember des dritten Jahres seit dem effektiven Abflugjahr g&uuml;ltig. Unabh&auml;ngig davon, welche Regelung dem Mitglied mehr Privilegien bringt. <br>
     Es liegt nicht in der Verantwortung von LANPASS das Verfallsdatum der Kilometer, gem&auml;&szlig; den hier aufgef&uuml;hrten Regeln zum Verfall, mitzuteilen.</li>
       <li><strong>8.9 </strong>Alle Kilometer, die auf dem Kontostand erscheinen, k&ouml;nnen gegen Pr&auml;mien eingel&ouml;st werden. Die Kilometer, die auf LAN und <strong>one</strong>world Fl&uuml;gen erworben wurden, inklusive Serviceklassenboni, werden au&szlig;erdem benutzt, um die LANPASS Mitgliedskategorie festzustellen.</li>
       <li><strong>8.10</strong> Pr&auml;mientickets des LANPASS Programms, die auf Fl&uuml;gen mit LAN oder einer Partnerfluggesellschaft genutzt werden, genauso wie Pr&auml;mien, die der Nutzung von Dienstleistungen von Partnerunternehmen entsprechen, dienen nicht der Sammlung von Kilometern. <br>
       Ebenso von der Kilometersammlung ausgeschlossen sind Tickets, die mit reduzierten Tarifen der Tourismusindustrie ausgestellt werden, wie Charterflugtickets, Tickets f&uuml;r Angestellte von Fluggesellschaften, Tickets mit Regierungsrabatten, kostenlose Tickets oder jedes andere Ticket, das keinen publizierten Tarif aufweist. Der Ausschluss von weiteren Tickettypen ist dem Ermessen von LANPASS exklusiv vorbehalten und wird gegebenenfalls den Mitgliedern auf angemessene Weise mitgeteilt.</li>
       <li><strong>8.11 </strong>Von LAN auf andere Fluggesellschaften indossierte Tickets sammeln dieselben Kilometer, als wenn der Passagier tats&auml;chlich auf LAN geflogen w&auml;re. Dies findet nur Anwendung, wenn es sich ein unfreiwilliges Ereignis handelt. Von <strong>one</strong>world Fluggesellschaften oder Partnerfluggesellschaften auf Dritte indossierte Tickets sind nicht f&uuml;r die Kilometersammlung qualifiziert.</li>
       <li><strong>8.12</strong> Falls der Passagier in den Genuss eines Upgrades kommt, sei es aufgrund einer Pr&auml;mie oder als Aufmerksamkeit von LAN oder einer Partnerfluggesellschaft oder einem Partnerunternehmen, dann werden trotzdem nur die Kilometer gesammelt, die der Serviceklasse des von dem Mitglied bezahlten Tickets entsprechen und nicht die der tats&auml;chlich geflogenen Serviceklasse.</li>
       <li><strong>8.13</strong> Es liegt ausschlie&szlig;lich in der Verantwortung des Mitglieds zu pr&uuml;fen, ob die korrekte Anzahl an Kilometern, die seinen Fl&uuml;gen mit LAN und/oder mit den Partnerfluggesellschaften entsprechen, genauso wie die Anzahl der Kilometer, die aus der Nutzung von Dienstleistungen von Partnerunternehmen resultieren, auf seinem Konto gutgeschrieben wurde. <br>
       Aus diesem Grund ist es die Pflicht des Mitglieds Dokumente, die die Durchf&uuml;hrung seiner Reise belegen, aufzubewahren (Flugticket und Bordkarte), ebenso wie Rechnungen oder Vertr&auml;ge, um eventuell eine nachtr&auml;gliche Gutschrift der Kilometer zu fordern. Unter keinen Umst&auml;nden k&ouml;nnen Kilometer nach mehr als einem (1) Jahr nach Abflug oder nach dem Generierungsakt angerechnet werden, au&szlig;er Partnerunternehmen erlauben dies speziell f&uuml;r ihre eigenen Kilometer.<br>
       Antr&auml;ge auf r&uuml;ckwirkende Kilometergutschrift bei Serviceleistungen, die durch Partnerfluggesellschaften erbracht wurden, werden nur dann bearbeitet, wenn das Mitglied seine Flugdokumente (Bordkarten und Flugscheinbeleg des Passagiers) einreicht. Ohne die Vorlage der entsprechenden Dokumente, die den Antritt des Fluges best&auml;tigen, kann der Antrag nicht ber&uuml;cksichtigt werden.</li>
       <li><strong>8.14</strong> LANPASS beh&auml;lt sich das Recht vor, die Mitgliedskonten jederzeit und ohne vorherige Ank&uuml;ndigung zu pr&uuml;fen und gegebenenfalls zu revidieren, um die Einhaltung der Nutzungsbedingungen sicher zu stellen. LANPASS kann Kilometer abziehen, die dem Mitglied nicht rechtm&auml;&szlig;ig zustehen und die Ausgabe von Pr&auml;mien oder Zertifikaten zur&uuml;ckhalten, bis sich Unstimmigkeiten gekl&auml;rt haben, wobei das Mitglied dar&uuml;ber informiert werden muss.</li>
       <li><strong>8.15 </strong>Falls die Tickets, die zur Sammlung von LANPASS Kilometern erm&auml;chtigen, auf Kredit erworben wurden oder die Bezahlung aufgeschoben wurde, kann ein Mitglied nur Pr&auml;mien in dem Ma&szlig;e mit diesen Kilometern einl&ouml;sen, wie beim Erwerb vereinbart wurde. </li>
       <li><strong>8.16 </strong>Die Verantwortung f&uuml;r die Einhaltung der Gesetze und Regelungen, die f&uuml;r die Teilnahme am LANPASS Programm und f&uuml;r die Kilometersammlung gelten, liegt ausschlie&beta;lich beim Mitglied. Insbesondere gilt dies f&uuml;r Mitglieder, die ein &ouml;ffentliches Amt bekleiden. </li></ul>
<h3><strong>9. FLEXIBLE LANPASS EINL&Ouml;SUNG </strong></h3>
    <ul> <li><strong>9.1 </strong> Um eine Pr&auml;mie zu beantragen, muss das Mitglied, eine g&uuml;ltige Mitgliedsnummer und die f&uuml;r die gew&uuml;nschte Einl&ouml;sung erforderliche Kilometeranzahl besitzen. Die erforderliche Kilometeranzahl, um eine Pr&auml;mie zu erhalten, ist in der Pr&auml;mientabelle zu finden, die jeweils zum Zeitpunkt der Pr&auml;mienbeantragung g&uuml;ltig ist.    
    <li><strong>9.2 </strong>Die f&uuml;r die Pr&auml;mieneinl&ouml;sung notwendige Kilometeranzahl variiert je nach Pr&auml;mientyp und der Kabinenklasse. In der Economy Class Kabine existieren 3 Pr&auml;mienniveaus: Classic, Plus und Full (in aufsteigender Reihenfolge, was sie Kilometeranzahl betrifft, die zur Einl&ouml;sung erforderlich ist). In der Premium Business Class Kabine gibt es nur ein einziges Pr&auml;mienniveau.    
    <li><strong>9.3 </strong>Es k&ouml;nnen ausschlie&szlig;lich Upgrades f&uuml;r die Premium Business Class Kabine angefordert werden.    
    <li><strong>9.4 </strong>F&uuml;r jeden Pr&auml;mientyp besteht eine begrenzte Anzahl an Sitzpl&auml;tzen.    
    <li><strong>9.5 </strong> Um eine Pr&auml;mie zu beantragen, kann das Mitglied das LAN Call Center (Option LANPASS) kontaktieren, auf die Website www.lan.com gehen oder sich an ein LAN Verkaufsb&uuml;ro oder ein Reiseb&uuml;ro wenden. In jedem Falle muss ein Dokument vorgewiesen werden, dass die Identit&auml;t des Mitglieds ausweist. Bei Lan.com sind ein Benutzername und ein Passwort notwendig.    
    <li><strong>9.6 </strong> Bei Pr&auml;mieneinl&ouml;sungen &uuml;ber das LAN Call Center (Option LANPASS), &uuml;ber ein LAN Verkaufsb&uuml;ro oder ein Reiseb&uuml;ro muss das Mitglied eine Ausstellungsgeb&uuml;hr (Service Fee LANPASS) f&uuml;r jedes ausgestellte Ticket entrichten. Falls die Pr&auml;mie &uuml;ber www.lan.com eingel&ouml;st wird, wird die Ausstellungsgeb&uuml;hr nicht f&auml;llig. Die LANPASS Servicegeb&uuml;hr versteht sich zus&auml;tzlich zu den Flughafensteuern- und -geb&uuml;hren und variiert je nach Pr&auml;mientyp gem&auml;&szlig; der unter www.lan.com ver&ouml;ffentlichten Pr&auml;mientabelle.    
    <li><strong>9.7 </strong> Den Pr&auml;mienantrag kann jeder stellen, der eine ordnungsgem&auml;&szlig; ausgef&uuml;llte Vollmacht des Mitglieds mit folgenden Daten vorweisen kann: kompletter Name des Mitglieds, Kontonummer und/oder Ausweisnummer und Bezeichnung der Pr&auml;mie, die angefordert wird. Au&szlig;erdem muss eine einfache Kopie des Ausweisdokuments des Mitglieds (Personalausweis, Reisepass oder Gleichwertiges) beigef&uuml;gt werden.    
    <li><strong>9.8 </strong> Die Pr&auml;mien besitzen ab dem Ausstellungsdatum eine G&uuml;ltigkeit von einem Jahr (12 Monate), nach Ablauf dieser Frist verfallen diese sofort.    
    <li><strong>9.9 </strong> Pr&auml;mien werden nur f&uuml;r &quot;Hin- und R&uuml;ckfl&uuml;ge&quot; gew&auml;hrt. Keine Einl&ouml;sung f&uuml;r oneway Pr&auml;mien m&ouml;glich. Dem Mitglied wird der Antritt des R&uuml;ckfluges verweigert, wenn der entsprechende Hinflug nicht angetreten wurde. Falls das Mitglied nur den Hinflug der Pr&auml;mie nutzt, wird der entsprechende Kilometerbetrag f&uuml;r den nicht genutzten R&uuml;ckflug nicht zur&uuml;ckerstattet.    
    <li><strong>9.10 </strong>Upgrades k&ouml;nnen oneway (nur f&uuml;r Hin- oder R&uuml;ckflugstrecken) oder f&uuml;r &quot;Hin- und R&uuml;ckflug&quot; eingel&ouml;st werden.    
    <li><strong>9.11 </strong> Bei den ausgestellten Pr&auml;mien handelt es sich um Namenspapiere, sie k&ouml;nnen weder abgetreten noch auf Dritte &uuml;bertragen werden.    
    <li><strong>9.13 </strong> Die Reservierung und die Ausstellung einer Pr&auml;mie m&uuml;ssen gleichzeitig geschehen.    
    <li><strong>9.14 </strong> LANPASS beh&auml;lt sich das Recht vor, Pr&auml;mien im Falle von Unregelm&auml;&szlig;igkeiten in der Beantragung oder Nutzung zur&uuml;ckzuhalten. Jeglicher Versto&szlig; gegen die vorliegenden Nutzungsbedingungen kann dazu f&uuml;hren, dass LANPASS die Ausstellung einer Pr&auml;mie verweigert und/oder dass ein Mitglied vom LANPASS Programm ausgeschlossen wird, wobei dessen Kilometer auf dem Konto augenblicklich verfallen.    
    <li><strong>9.15 </strong> Das Mitglied kann Pr&auml;mien bis zu 48 Stunden vor Reiseantritt umbuchen lassen. Keine Umbuchung von angebrochenen Pr&auml;mien (nach Beginn der Reise) mehr m&ouml;glich. Im Falle von Umbuchungen verl&auml;ngert sich die G&uuml;ltigkeit der Pr&auml;mie nicht. Daraus folgt, dass die ge&auml;nderte Pr&auml;mie dieselbe G&uuml;ltigkeit besitzt wie das Originalpr&auml;mienticket hatte.    
    <li><strong>9.16 </strong> &Auml;nderungen sind bei Pr&auml;mien nur dann m&ouml;glich, wenn die aktuelle Pr&auml;mie derselben oder einer niedrigeren Kilometeranzahl entspricht.    
    <li><strong>9.17 </strong>Datums&auml;nderungen k&ouml;nnen nur dann durchgef&uuml;hrt werden, wenn eine andere Pr&auml;mie verf&uuml;gbar ist, die derselben oder einer niedrigeren Kilometeranzahl entspricht.    
    <li><strong>9.18 </strong>Bei &Auml;nderungen gegen eine Pr&auml;mie, die eine geringere Kilometeranzahl erfordert, wird die nicht gebrauchte Kilometerdifferenz dem Mitglied nicht zur&uuml;ckerstattet. Bei weiteren sp&auml;teren &Auml;nderungen bleibt diese Kilometeranzahl bestehen.    
    <li><strong>9.19 </strong>Freiwillige &Auml;nderungen m&uuml;ssen innerhalb derselben Kabine stattfinden, die urspr&uuml;nglich ausgestellt wurde, au&szlig;er auf dem neuen Flug existiert diese Kabine nicht. In diesem Fall kann die Pr&auml;mie f&uuml;r eine niedrigere Kabinenklasse ausgestellt werden, sofern das Mitglied auf die nicht genutzte Kilometerdifferenz verzichtet.    
    <li><strong>9.20 </strong>&Auml;nderungen bei Pr&auml;mien, die vor dem 4. August 2009 ausgestellt wurden, richten sich nach den zum Ausstellungsdatum g&uuml;ltigen Nutzungsbedingungen.    
    <li><strong>9.21 </strong> Datums-, Routen- oder Flug&auml;nderungen sind bei Pr&auml;mien nur dann erlaubt, wenn noch kein Kupon genutzt wurde. Jede &Auml;nderung ist mit einer Geb&uuml;hr verbunden, die je nach Ticketausstellungsland und Route variiert. Die Umbuchungsgeb&uuml;hren sind unter www.lan.com ver&ouml;ffentlicht. Pr&auml;mien, die dazu ausgestellt wurden, um mit Partnerfluggesellschaften der <strong>one</strong>world Allianz zu fliegen, erlauben lediglich &Auml;nderungen des Reisedatums und/oder der Uhrzeit. Es sind keine &Auml;nderungen der Route, der Fluggesellschaft oder der vorab festgelegten Stopover m&ouml;glich.
    <li><strong>9.22 </strong> Im Falle dass das Mitglied die R&uuml;ckerstattung einer ausgestellten Pr&auml;mie beantragt, muss eine Geb&uuml;hr in Kilometern entrichtet werden. Die Geb&uuml;hr variiert je nach Pr&auml;mie und gem&auml;&szlig; der auf www.lan.com ver&ouml;ffentlichten Daten. Die R&uuml;ckerstattung der Pr&auml;mie setzt voraus, dass das ausgestellte Ticket g&uuml;ltig ist (die G&uuml;ltigkeitsfrist beginnt ab der Ticketausstellung), dass die R&uuml;ckerstattung vor dem Abflugtag geschieht, bevor irgendeine Strecke geflogen wurde - au&beta;er bei oneworld Upgrades - und dass die f&uuml;r die Ausstellung genutzten Kilometer zum Zeitpunkt der Anforderung der R&uuml;ckerstattung nicht abgelaufen sind.  Die R&uuml;ckerstattung kann &uuml;ber das LAN Call Center (Option LANPASS) oder bei einem LAN Verkaufsb&uuml;ro beantragt werden. Sobald die R&uuml;ckerstattung verarbeitet wurde, werden die nicht verfallenen Kilometer erneut dem LANPASS Kilometerkonto des Mitglieds gutgeschrieben.    
    <li><strong>9.23 </strong> Pr&auml;mien sind Namenspapiere, sie besitzen keinen monet&auml;ren Gegenwert und sind nicht &uuml;bertragbar. Falls eine Pr&auml;mie - aus welchem Grund auch immer - ganz oder teilweise - innerhalb der ausgestellten zeitlichen Frist nicht genutzt wurde, verliert diese Pr&auml;mie ihren Wert vollst&auml;ndig.</li>
    <li><strong>9.24</strong> Das Mitglied ist verantwortlich f&uuml;r die &Uuml;berpr&uuml;fung der notwendigen LANPASS-Kilometer f&uuml;r einen Pr&auml;mienflug mit LAN und bei Fl&uuml;gen mit <strong>one</strong>world und verbundenen Fluggesellschaften, da die erforderlichen Kilometer f&uuml;r ein und dieselbe Flugstrecke variieren k&ouml;nnen.</li>
    </ul>
    <h3>10. NUTZUNGSBESCHR&Auml;NKUNGEN F&Uuml;R PR&Auml;MIEN</h3>
      <ul><li><strong>10.1 </strong> Pr&auml;mien sind Platzverf&uuml;gbarkeit unterworfen, so dass diese erst zum Zeitpunkt der Ausstellung als best&auml;tigt gelten.</li>
      <li><strong>10.2</strong> Die Pr&auml;mien erlauben einen (1) Stopover (Freiwilliger Stopp des Passagiers auf einem Zwischenstopp auf dem Hin- oder R&uuml;ckflug) oder einen (1) Gabelfl&uuml;ge (der Zielort ist ein anderer als der Abflugsort auf dem R&uuml;ckflug) auf nationalen und internationalen Fl&uuml;gen. Einige <strong>one</strong>world oder verbundene Fluglinien erlauben Stopover und Gabelfl&uuml;ge nicht. F&uuml;r weitere Informationen informieren Sie sich unter</li>
      <li><strong>10.3 </strong> Pr&auml;mien erlauben einen (1) Stopover (freiwilligen Aufenthalt des Passagiers an einem Umsteigepunkt auf Hin- oder R&uuml;ckflug) oder einen (1) Openjaw (dabei ist die Zieldestination des Hinflugs nicht identisch mit dem Abflugort des R&uuml;ckflugs) sowohl auf nationalen als auch auf internationalen Routen.</li>
      <li><strong>10.4 </strong> Es ist nicht erlaubt, Pr&auml;mien offen auszustellen, d.h. das Datum des Abflugs oder R&uuml;ckflugs nicht vorab festzulegen.</li>
      <li><strong>10.5 </strong>In keinem Falle k&ouml;nnen Pr&auml;mien mit anderen Fluggesellschaften genutzt werden, als mit denjenigen, die auf der Pr&auml;mie angegeben sind.<br>
      Falls der auf der Pr&auml;mie angegebene Flug ohne Verschulden von LAN, aus Sicherheitsgr&uuml;nden, unvorhergesehen oder wegen h&ouml;herer Gewalt gestrichen wird, wird LAN alles tun, um den Passagier mit dem n&auml;chstm&ouml;glichen Flug oder einer anderen Verbindung, die zum selben Ziel f&uuml;hrt, zu bef&ouml;rdern. Das Mitglied wird jedoch keinesfalls - aus diesen oder anderen Gr&uuml;nden - mit einer anderen Fluggesellschaft bef&ouml;rdert.</li>
      <li><strong>10.6 </strong> Bei Pr&auml;mien mit Fl&uuml;gen, die Umsteigeverbindungen mit Flugzeugwechsel vorsehen, m&uuml;ssen alle Geb&uuml;hren, die durch den Aufenthalt am Umsteigepunkt anfallen, komplett vom Passagier &uuml;bernommen werden.</li>
      <li><strong>10.7 </strong> Pr&auml;mien k&ouml;nnen nicht mit anderen Angeboten, Kupons, Rabatten oder Spezialaktionen kombiniert werden. Sie besitzen keine G&uuml;ltigkeit an Orten, wo es das Gesetz verbietet, und sie sind den Bestimmungen der Flugbranche unterworfen.</li>
      <li><strong>10.8 </strong> Die gew&auml;hrten Pr&auml;mien entsprechen ausschlie&szlig;lich dem Nettotarifwert, dabei liegt es in der Verantwortung des Passagiers alle Steuern und Geb&uuml;hren zu entrichten, welche die Ausstellung mit sich bringen, u.a. - jedoch nicht ausschlie&szlig;lich - die entsprechenden Flughafengeb&uuml;hren.</li>
      <li><strong>10.9 </strong>Es liegt ausschlie&szlig;lich in der Verantwortung des Mitglieds, sich angemessen &uuml;ber die Antrags- und Nutzungsbedingungen f&uuml;r die Pr&auml;mien zum Zeitpunkt der Nutzung zu informieren. </li>
      <li><strong>10.10</strong> Wenn die Pr&auml;mie von oneworld oder verbundenen Fluggesllschaften betr&iacute;ebene Fl&uuml;ge beinhaltet, ist es Verantwortung des Mitglieds sich &uuml;ber die Transportbedingungen der f&uuml;r den Flug verantwortlichen Fluggesellschaft zu informieren. Diese Informationen finden sie unter www.lan.com.</li></ul>
      <h3>11. NUTZUNG VON UPGRADE-KUPONS</h3>
      <ul>
      <li><strong>11.1</strong> Ugrade-Kupons haben bis zu dem auf ihnen angegebenen  Datum G&uuml;ltigkeit und gew&auml;hren dem Passagier auf dem Hin- oder R&uuml;ckflug eines  von LAN durchgef&uuml;hrten und verkauften Fluges ein Upgrade in die n&auml;chst h&ouml;here  Kabinenklasse. Dabei m&uuml;ssen die <a href="http://www.lan.com/es_un/sitio_personas/lanpass/como_canjear/familias_tarifarias.html" target="_blank">Tarif-Familien</a><span class="Estilo1">,</span> die Anzahl der je nach Route  erforderlichen Kupons und die Platzverf&uuml;gbarkeit zum Zeitpunkt des Boardings  beachtet werden</li>
      <li><strong>11.2</strong> Die erforderlichen Mindesttarife f&uuml;r das bezahlte Ticket sind unter www.lan.com ersichtlich.</li>
      <li><strong>11.3</strong> Der Upgrade-Kupon ist ung&uuml;ltig im Falle von &Auml;nderung, Vervielf&auml;ltigung oder inkorrekter Nutzung. Er besitzt keinen monet&auml;ren Gegenwert, verliert bei Tauschgesch&auml;ften seinen Wert und wird im Falle von Raub, Diebstahl oder Verlust nicht ersetzt.</li>
      <li><strong>11.4 </strong>Alle Upgrade-Kupons sind f&uuml;r das Mitglied und seine Begleitperson bestimmt. Die Begleitperson kann den Upgrade-Kupon nur nutzen, wenn sie gemeinsam mit dem Mitglied reist (allerdings nicht zwingend in derselben Kabinenklasse).</li>
      <li><strong>11.5</strong> Es liegt in der Verantwortung des Passagiers, die Zahlung aller mit der Nutzung des Upgrades verbundenen Steuern zu leisten. </li></ul>
    <h3>12. ALLGEMEINES</h3>
      <ul><li><strong>12.1 </strong>Die Teilnahme am LANPASS Programm ist den hier festgesetzten Nutzungsbedingungen unterworfen, welche regelm&auml;&szlig;ig nach alleinigem Ermessen von LANPASS &Auml;nderungen unterworfen werden k&ouml;nnen. Alle &Auml;nderungen, was die Nutzungsbedingungen betrifft, m&uuml;ssen von den Mitgliedern zwangsl&auml;ufig eingehalten werden, sobald diese von LANPASS ver&ouml;ffentlicht oder auf irgendeinem Wege bekannt gegeben wurden. Dies beinhaltet das Recht, den Privilegienkatalog f&uuml;r Mitglieder, die Pr&auml;mientabellen, das Kilometersammelsystem und die teilnehmenden Partnerorganisationen an diesem Programm zu &auml;ndern. </li>
      <li><strong>12.2 </strong>LANPASS beh&auml;lt sich das Recht vor, das LANPASS Programm jederzeit, mit oder ohne Vorank&uuml;ndigung, f&uuml;r beendet zu erkl&auml;ren, so dass die von den Mitgliedern gesammelten Kilometer wertlos werden. <br>
  Allerdings wird LANPASS alles M&ouml;gliche tun, um seinen Mitgliedern das Ende des Programms vorab mit ausreichender Frist mitzuteilen, damit sie die angesammelten Kilometer noch nutzen k&ouml;nnen.</li>
      <li><strong>12.3 </strong>LANPASS ist in keinem Fall verantwortlich f&uuml;r Verluste und Sch&auml;den, die aus der Beendigung oder der Ver&auml;nderung des Programms resultieren k&ouml;nnten.</li>
      <li><strong>12.4 </strong>Alle Pr&auml;mien und Privilegien sind Ver&auml;nderungen und Verf&uuml;gbarkeiten unterworfen, wobei es allein in der Verantwortung des Mitglieds liegt, die entsprechende g&uuml;ltige Reservierung zu beantragen und alle weiteren Schritte zu unternehmen, um in den Genuss dieser zu gelangen. </li>
      <li><strong>12.5</strong> Einige Pr&auml;mien, Privilegien oder Angebote, um Kilometer zu sammeln, werden von Organisationen gestellt, mit denen LANPASS Vereinbarungen getroffen hat. &Uuml;ber diese Organisationen besitzt LANPASS jedoch keine Kontrolle.<br>
      Trotzdem versucht LANPASS sicherzustellen, dass die Pr&auml;mien und Privilegien, die den Mitgliedern als verf&uuml;gbar dargestellt werden, auch verf&uuml;gbar sind. Jedoch kann LANPASS weder die Verf&uuml;gbarkeit solcher Pr&auml;mien und Privilegien garantieren, noch ist LANPASS daf&uuml;r verantwortlich. Daher kommt LANPASS auch f&uuml;r keine Sch&auml;den oder Verluste auf, die aus der vollst&auml;ndigen oder teilweisen Bereitstellung oder Nicht-Bereitstellung einer Pr&auml;mie oder eines Privilegs entstehen.<br>
      LANPASS ist au&szlig;erdem nicht verantwortlich, wenn eine dieser Organisationen beschlie&szlig;t, das LANPASS Programm zu verlassen.</li>
      <li><strong>12.6 </strong>Die Bereitstellung der Pr&auml;mien und Privilegien, die von Partnerfluggesellschaften und/oder Partnerunternehmen angeboten werden, sind deren Nutzungsbedingungen unterworfen.</li>
      <li><strong>12.7 </strong>LANPASS ist f&uuml;r keinen Verlust, keine Benachteiligung, Verz&ouml;gerung und keinen Schaden verantwortlich, der aus dem LANPASS Programm resultiert oder der damit oder mit einer seiner angebotenen Pr&auml;mien oder Privilegien verbunden ist, au&szlig;er wenn dieser Verlust, diese Benachteiligung, Verz&ouml;gerung oder dieser Schaden durch grobe Fahrl&auml;ssigkeit von Seiten LANPASS entstanden ist. </li>
      <li><strong>12.8 </strong>LANPASS ist nicht verantwortlich f&uuml;r Fehler oder Vers&auml;umnisse, die trotz aller Sorgfalt in den Informationen zu irgendeinem Bereich des LANPASS Programms auftauchen k&ouml;nnten.<br>
      LANPASS ist auch nicht verantwortlich f&uuml;r die Versp&auml;tung, den Verlust oder die Falschlieferung von Kundenkorrespondenz.</li>
      <li><strong>12.9 </strong>Alle schriftlichen Mitteilungen, die an das LANPASS Programm gerichtet werden, m&uuml;ssen die Unterschrift und Nummer des Mitglieds enthalten.</li>
      <li><strong>12.10 </strong>LANPASS ist der einzige Verantwortliche, was die Interpretation und Anwendung dieser Nutzungsbedingungen betrifft. </li>
      <li><strong>12.11</strong> Au&szlig;er mit ausdr&uuml;cklicher, schriftlicher Erlaubnis von LAN ist der Kauf, Verkauf, Tausch oder die &Uuml;bertragung von Titeln, Pr&auml;mien, Zertifikaten und LANPASS Kilometern strikt verboten. Jede Person, die beim Kauf, Verkauf, Tausch oder bei der &Uuml;bertragung von Titeln, Pr&auml;mien, Zertifikaten und LANPASS Kilometern ertappt wird, kann gezwungen werden, den vollst&auml;ndigen entsprechenden Tarif zu bezahlen, die Kosten aus entstandenen Benachteiligungen und Sch&auml;den und die verbundenen rechtlichen Kosten zu tragen. Dies alles gilt in Verbindung mit der zu dem Zeitpunkt g&uuml;ltigen Gesetzgebung. </li>
      <li><strong>12.12</strong> Zertifikate, Pr&auml;mien und Kilometer, die ohne Einwilligung von LAN verkauft oder von einem Inhaber gekauft worden sind, d&uuml;rfen nicht genutzt werden und Personen, die ertappt werden, wie sie diese Pr&auml;mien benutzen, d&uuml;rfen ihre Reise nicht fortsetzen oder d&uuml;rfen nicht mehr in den Genuss der Dienstleistungen, die mit der Pr&auml;mie verbunden ist, kommen, au&szlig;er wenn sie den kompletten Preis daf&uuml;r bezahlen.</li>
      <li><strong>12.13 </strong>LANPASS ist nicht verantwortlich f&uuml;r die von Partnerunternehmen oder Partnerfluggesellschaften gew&auml;hrten Pr&auml;mien, sondern diese selbst sind die einzigen Verantwortlichen gegen&uuml;ber dem Mitglied, was die Pr&auml;mien betrifft.</li>
      <li><strong>12.14</strong> Die Fl&uuml;ge, die auf den Kontost&auml;nden des LANPASS Programms verbucht erscheinen, stellen keinen Beweis daf&uuml;r dar, dass das Mitglied tats&auml;chlich auf dem angegebenen Flug anwesend war.</li>
      <li><strong>12.15</strong> Die vorliegenden Nutzungsbedingungen k&ouml;nnen ohne vorherige Ank&uuml;ndigung &Auml;nderungen unterworfen werden, wobei jederzeit eine stets aktualisierte elektronische Version unter www.lan.com und in jedem LAN Verkaufsb&uuml;ro verf&uuml;gbar ist. </li>
      <li><strong>12.16 </strong>Diese vorliegenden Nutzungsbedingungen richten sich nach dem Gesetz der Chilenischen Republik und jede Schwierigkeit, jeder Streitfall oder Rechtsstreit, der aus deren Anwendung, Einhaltung, Interpretation oder G&uuml;ltigkeit resultiert, muss von einer gemeinen Schlichtungskommission des Landes gel&ouml;st werden.</li></ul>
      <h2>KLAUSELN F&Uuml;R DEN VERTRAG &Uuml;BER LUFTBEF&Ouml;RDERUNG VON FLUGG&Auml;STEN UND GEP&Auml;CK </h2>

<h3>1.&nbsp;DEFINITIONEN </h3>

  <p>Zum Zweck der vorliegenden Klauseln versteht sich  unter den im Anschluss angef&uuml;hrten Begriffen Folgendes:</p>
  <ul>
<li>1.1<strong> &quot;Ticket&quot;</strong> oder <strong>&quot;Flugticket&quot; </strong>bedeutet  die Gesamtheit der Unterlagen, die Ausfertigung und Bedingungen eines Luftbef&ouml;rderungsvertrags  und der Gep&auml;ckkontrolle angeben und best&auml;tigen, und die alle oder einige der  folgenden Unterlagen umfassen: <strong>(i)</strong> Die vorliegenden Vertragsklauseln der Luftbef&ouml;rderung; <strong>(ii)</strong> die im von der Fluggesellschaft  ausgeh&auml;ndigten Dokument mit der Bezeichnung &quot;Auskunft &uuml;ber Ihren  Kauf&quot; enthaltenen Verordnungen, oder die Buchungsangaben eines Agenten; <strong>(iii)</strong> das magnetisch registrierte  elektronische Ticket;<strong> (iv)</strong> die f&uuml;r  den vom Passagier bezahlten Tarif spezifisch anwendbaren Bedingungen;&nbsp; <strong>(v)</strong> die Bordkarte oder <em>Boarding Pass</em>; und <strong>(vi)</strong> die Verbindungen und  Vertragstarife, die bei den Luftfahrtbeh&ouml;rden der L&auml;nder, die sie anfordern,  angemeldet sind.</li>
<li>1.2 <strong>&quot;Transporteur&quot;  oder &quot;Luftfrachtf&uuml;hrer&quot;</strong> steht f&uuml;r die Fluggesellschaft, die den Fluggast u. / o. sein Gep&auml;ck  bef&ouml;rdert oder sich zu deren Bef&ouml;rderung verpflichtet, oder eine andere  Dienstleistung im Zusammenhang mit dieser Luftbef&ouml;rderung ausf&uuml;hrt.</li>
<li>1.3 <strong>&quot;Warschauer  Abkommen&quot;</strong> bedeutet das Abkommen zur  Vereinheitlichung bestimmter Regeln &uuml;ber die Bef&ouml;rderung im internationalen  Luftverkehr, das 1929 in  Warschau unterzeichnet wurde, sowie die anhand des Haager Protokolls von 1955 und der  Montrealer Protokolle von 1975 eingef&uuml;gten &Auml;nderungen.</li>
<li>1.4 <strong>&quot;Montrealer Abkommen&quot; </strong>bedeutet das Abkommen zur Vereinheitlichung bestimmter Regeln &uuml;ber die  Bef&ouml;rderung im internationalen Luftverkehr, das am 18. Mai 1999 in Montreal, in Kanada,  unterzeichnet wurde. </li>
  </ul>

<h3>2.&nbsp; ALLGEMEINE VORSCHRIFTEN DER LUFTBEF&Ouml;RDERUNG</h3>
<ul><li>2.1 Die Ausgabe eines Flugtickets best&auml;tigt die Ausfertigung und Annahme der  Bedingungen der Luftbef&ouml;rderung und des zwischen Passagier und Luftfrachtf&uuml;hrer,  deren Namen auf dem Ticket erscheinen, unterzeichneten Transportvertrags. Das auf den Namen des Passagiers ausgestellte  Ticket ist namentlich, pers&ouml;nlich und nicht &uuml;bertragbar. Seine Ausgabe kann  ganz oder teilweise &uuml;ber physische oder elektronische Mittel erfolgen. &nbsp;</li>
<li>2.2 Die vereinbarten Zwischenlandungen entsprechen denen, die auf dem  Flugticket oder auf der Passagierroute als auf den Routen des Luftfrachtf&uuml;hrers  vorgesehene Zwischenlandungen angegeben sind. Die auf der Grundlage dieses Vertrags von  mehreren Luftfrachtf&uuml;hrern nacheinander auszuf&uuml;hrenden Bef&ouml;rderungen gelten als  eine einzige Transaktion.</li>
<li>2.3 Stellt der Luftfrachtf&uuml;hrer ein Ticket f&uuml;r den streckenweisen Transport  mit Strecken aus, die von einem anderen Luftfrachtf&uuml;hrer ausgef&uuml;hrt werden,  handelt der Luftfrachtf&uuml;hrer nur als Agent des Letztgenannten.</li>
<li>2.4 Alle Haftungsfreistellungen oder -beschr&auml;nkungen des Luftfrachtf&uuml;hrers  auf der Grundlage geltender lokaler oder internationaler Vorschriften erfolgen zugunsten  der Agenten, Mitarbeiter und Repr&auml;sentanten des Luftfrachtf&uuml;hrers oder anderer  Personen oder Unternehmen, deren Luftschiff vom Luftfrachtf&uuml;hrer zur Ausf&uuml;hrung  der Bef&ouml;rderung eingesetzt wird, sowie die Agenten, Mitarbeiter oder  Repr&auml;sentanten dieser Person oder dieses Unternehmens.</li>
<li>2.5 Der Luftfrachtf&uuml;hrer beh&auml;lt sich die uneingeschr&auml;nkte Befugnis vor, die  Bef&ouml;rderung auf einer der Strecken der vom Passagier vereinbarten Route zu  verweigern, wenn der vertragliche Tarif entweder insgesamt oder teilweise nicht  bezahlt wurde, oder wenn das verwendete Zahlungsmittel abgelehnt, aufgehoben  oder ung&uuml;ltig ist oder das Ticket gesetzeswidrig erstanden wurde.</li>
<li>2.6 Gleicherma&szlig;en wird der Luftfrachtf&uuml;hrer die Aufnahme eines Passagiers an  Bord verweigern oder dessen Verweisung veranlassen, wenn der Passagier die  Sicherheit des Flugs oder der Passagiere beeintr&auml;chtigen k&ouml;nnte. Insbesondere wird die Aufnahme an Bord aller  jener Passagiere verweigert, die Haltungen oder Verhalten zeigen, die am Boden  u. / o. an Bord des Luftschiffs eine <strong>(i)</strong> Zuwiderhandlung gegen die von der  Besatzung des Luftschiffs oder den anderen Mitarbeitern des Luftfrachtf&uuml;hrers  erteilten Anweisungen u. / o. <strong>(ii)</strong> ein dem vern&uuml;nftigen Verhalten einer Person  oder eines Passagiers entgegengesetztes Verhalten u. / o. <strong>(iii)</strong> eine Verletzung  oder ein Verbrechen darstellen, die nach Meinung des Luftfrachtf&uuml;hrers die  Sicherheit des Luftschiffs oder der darin anwesenden Personen oder G&uuml;ter in  Gefahr bringen, oder Ordnung und Disziplin an Bord gef&auml;hrden oder  kompromittieren k&ouml;nnten, u. / o. <strong>(iv)</strong> generell alle Haltungen oder Verhalten,  die nach Meinung des Luftfrachtf&uuml;hrers eine Verweigerung der Einhaltung der von  der Besatzung erteilten Anweisungen darstellen, u. /o. Haltungen, die f&uuml;r  den&nbsp; Flug zur Gefahr oder zu einem Risiko  werden k&ouml;nnen, u. / o.&nbsp; Ordnung und  Disziplin beeintr&auml;chtigen, u. / o. <strong>(v)</strong> Nachweis oder Anzeichen, alkoholische  Getr&auml;nke u. / o. eine psychotrope Substanz im &Uuml;berma&szlig; zu sich genommen zu  haben, u. / o. <strong>(vi)</strong> die Nichteinhaltung eines anwendbaren Gesetzes oder einer  Regelung oder die Nichtbefolgung einer von der jeweiligen Regierungsbeh&ouml;rde erfolgten  Anforderung.</li>
<li>2.7 Bei Bedarf (einschl., aber  nicht auf Zufall oder h&ouml;here Gewalt begrenzt) kann der Luftfrachtf&uuml;hrer den  Flug stornieren, sich durch andere Luftfrachtf&uuml;hrer ersetzen lassen u. / o. das  f&uuml;r den Vorgang bestimmte Luftschiff wechseln, u. / o. bei Bedarf die auf dem  Ticket angegebenen Zwischenlandungen &auml;ndern oder auslassen. Der  Luftfrachtf&uuml;hrer &uuml;bernimmt keinerlei Haftung, die vom Passagier mit einem Dritten  abgeschlossenen Anschlussfl&uuml;ge zu gew&auml;hrleisten.</li>
<li>2.8 Alle Passagiere, die ihre Reise  nicht antreten oder versp&auml;tet zum Boarding u. / o. Einchecken des jeweiligen  Flugs kommen, verlieren ihr Ticket. Sie k&ouml;nnen es f&uuml;r einen anderen Termin  umbuchen, wenn es der bezahlte Tarif laut Vereinbarung auf dem Ticket zul&auml;sst. Alle &Auml;nderungen  an Terminen, Herk&uuml;nften, Zielen und Routen des Flugtickets, wie auch die  R&uuml;ckzahlung des daf&uuml;r bezahlten Betrags, unterliegen den Bedingungen und  Einschr&auml;nkungen des vom Passagier abgeschlossenen Tarifs. &nbsp;Sollte der Passagier die Reise nicht antreten und  sein Tarif keine R&uuml;ckzahlung des Tickets zulassen, kann er vom Luftfrachtf&uuml;hrer  die R&uuml;ckzahlung jener Flughafengeb&uuml;hren anfordern, die laut Vorschriften oder  Einschr&auml;nkungen des jeweiligen Lands zur&uuml;ckgezahlt werden k&ouml;nnen. Sind diese  Geb&uuml;hren nicht im bezahlten Betrag enthalten (d. h., wenn sie unmittelbar vom  Flughafen eingezogen wurden), muss der Passagier deren R&uuml;ckzahlung unmittelbar  bei der jeweiligen Flughafenbeh&ouml;rde unter den o.&nbsp;a. Einschr&auml;nkungen oder  Vorschriften beantragen.</li>
<li>2.9 Die Fl&uuml;ge oder  Strecken, die die Route ausmachen, m&uuml;ssen in der angegebenen Reihenfolge  geflogen werden. Der Luftfrachtf&uuml;hrer kann, unter den in der  anwendbaren Gesetzgebung vorgesehenen Bedingungen, die Aufnahme an Bord eines  Passagiers verweigern, der die o. a. Reihenfolge nicht einh&auml;lt oder eine der  auf seinem Ticket angegebenen Strecken nicht geflogen ist. Der Passagier  nimmt zur Kenntnis, dass, wenn er eine auf der Route angegebene Strecke nicht  fliegt, die Route komplett ohne vorherige Benachrichtigung storniert wird,  wobei keinerlei R&uuml;ckzahlung - au&szlig;er wenn es die Tarifbedingungen seines Tickets  zulassen - erfolgt. Hier ein Beispiel, womit die Bedingung aber nicht  auf diesen spezifischen Fall begrenzt wird: Fliegt ein Passagier die erste auf  der Route spezifizierte Strecke (d.&nbsp;h. Hinflug) nicht, kann er auch keine weitere  Strecke&nbsp; (d.&nbsp;h. Zwischenlandung-  oder R&uuml;ckflug) fliegen.</li>
<li>2.10&nbsp;Rauchen ist in der Kabine der Flugzeuge des  Luftfrachtf&uuml;hrers streng verboten. Der Luftfrachtf&uuml;hrer beh&auml;lt sich das Recht vor, den  Passagieren, die nicht bereit sind, diese Bedingung zu akzeptieren, die  Bef&ouml;rderung zu verweigern.</li>
<li>2.11 Das Ticket ist ab Ausgabedatum ein Jahr oder bis zu dem Datum, das speziell  f&uuml;r den vom Passagier erworbenen Tarif angegeben ist, g&uuml;ltig. Nach dieser Frist oder evtl. nach anderen k&uuml;rzeren  Fristen, die in den Ticketbedingungen angegeben sind, kann das Ticket nicht  mehr benutzt werden.</li>
<li>2.12 Es f&auml;llt unter die  ausschlie&szlig;lichen Zust&auml;ndigkeiten des Passagiers, sich &uuml;ber die von allen  Beh&ouml;rden auferlegten Reiseanforderungen zu informieren, sie zu erhalten und  einzuhalten. Er muss Ausweise, Ausreise-, Transit-, Einreise-, Visa- und  sonstige Unterlagen entsprechend des Ziellands vorlegen. Der Luftfrachtf&uuml;hrer  haftet nicht f&uuml;r Versp&auml;tungen oder Verweigerungen der Aufnahme an Bord, die der  Passagier seinerseits im Zusammenhang oder als Konsequenz der Nichteinhaltung  der o.&nbsp;a. Verpflichtungen erleidet. &nbsp;Der Luftfrachtf&uuml;hrer verweigert jenen  Passagieren, die die erforderlichen Unterlagen nicht vorlegen oder deren  Identit&auml;t nicht mit der auf der Bordkarte oder <em>Boarding Pass</em> angegebenen Identit&auml;t &uuml;bereinstimmt, die Aufnahme an  Bord, ohne dass dadurch weitere Haftungen f&uuml;r den Luftfrachtf&uuml;hrer entstehen. Der  Luftfrachtf&uuml;hrer haftet nicht f&uuml;r Informationen oder Hilfen, die einem  Passagier von einem Agenten, Mitarbeiter oder Repr&auml;sentanten der Fluglinie oder  von Dritten im Zusammenhang mit dem Erwerb dieser Unterlagen u. / o. der  Einhaltung der anwendbaren Gesetze und Regelungen geleistet werden.</li>
<li>2.13 Die vom Luftfrachtf&uuml;hrer  zwischen L&auml;ndern der Europ&auml;ischen Gemeinschaft geleisteten Fl&uuml;ge (d.&nbsp;h.  Fl&uuml;ge zwischen Madrid, Spanien und Frankfurt, Deutschland) werden von den  jeweiligen Beh&ouml;rden dieser L&auml;nder als <em>Nicht-Schengen- </em>(nicht innergemeinschaftliche) <em>Fl&uuml;ge </em>angesehen. Demzufolge m&uuml;ssen die  Passagiere dieser Fl&uuml;ge zwingend durch Zoll und Passkontrolle der jeweiligen  L&auml;nder gehen und alle von den innergemeinschaftlichen L&auml;ndern geforderten  Ausweisunterlagen, Visa, Ausl&auml;ndergenehmigungen und Berechtigungen dabei haben.  Alle Passagiere sind dazu verpflichtet und daf&uuml;r zust&auml;ndig, sich &uuml;ber die erforderlichen  Unterlagen zu erkundigen. Der Luftfrachtf&uuml;hrer haftet nicht f&uuml;r Sch&auml;den oder Beeintr&auml;chtigungen,  die durch die Nichteinhaltung dieser Verpflichtung seitens der Passagiere  entstehen. Die gleichen Bedingungen  gelten f&uuml;r Fl&uuml;ge nach / aus Kanada.</li>
<li>2.14 Der Passagier muss am Boarding- oder Check-in-Schalter zu der vom  Luftfrachtf&uuml;hrer angegebenen Uhrzeit erscheinen. Sollte keine Uhrzeit  festgelegt sein, muss er fr&uuml;h genug erscheinen, um die Ausreiseformalit&auml;ten  erledigen zu k&ouml;nnen. Diese Zeit darf nicht weniger als 2 Stunden vor der f&uuml;r  den Abflug festgelegten Zeit betragen.</li>
<li>2.15 F&uuml;r den Fall,  dass es f&uuml;r einen Flug mehr Passagiere mit best&auml;tigter Buchung als verf&uuml;gbare  Pl&auml;tze geben sollte und vorausgesetzt, dass die Check-in-Formalit&auml;ten mit der  erforderlichen Mindestzeit erfolgt sind, wird der Luftfrachtf&uuml;hrer um  Freiwillige bitten, die ihren best&auml;tigten Platz gegen eine vereinbarte  Entsch&auml;digung abtreten wollen. Sollten nicht ausreichend Freiwillige gefunden  werden und Passagieren gegen ihren Willen nicht an Bord gehen k&ouml;nnen, haben  diese Passagiere Anspr&uuml;che auf die in der g&uuml;ltigen Gesetzgebung festgelegten  Leistungen.</li>
<li>2.16 Der Luftfrachtf&uuml;hrer verpflichtet sich, alle m&ouml;glichen Anstrengungen anzustellen,  um Passagiere und Gep&auml;ck mit angemessener P&uuml;nktlichkeit zu bef&ouml;rdern. Die auf dem Flugticket oder sonstigen  Ver&ouml;ffentlichungen angegebenen Uhrzeiten sind hinsichtlich ihrer Einhaltung  nicht garantiert, da sie sich aufgrund von Vorf&auml;llen wie h&ouml;here Gewalt,  Sicherheitsgr&uuml;nde oder sonstige au&szlig;erordentliche Umst&auml;nde &auml;ndern k&ouml;nnen. &nbsp;Der Luftfrachtf&uuml;hrer  wird alle angemessenen und m&ouml;glichen Ma&szlig;nahmen treffen, um Versp&auml;tungen bei der  Bef&ouml;rderung der Passagiere und Gep&auml;ckst&uuml;cke zu vermeiden. Der Luftfrachtf&uuml;hrer &uuml;bernimmt keinerlei Haftung f&uuml;r die Gew&auml;hrleistung  von Anschl&uuml;ssen aufgrund von Vorf&auml;llen, die ihm nicht zuzuschreiben sind.</li>
<li>2.17 In bestimmten F&auml;llen kann der  Luftfrachtf&uuml;hrer eine vorherige Benachrichtigung im Fall von Reisen bestimmter  Passagiere mit Behinderungen oder Krankheiten (z. B. Notwendigkeit von Bahren,  Sauerstoff, usw.), oder bei Bef&ouml;rderungsbedarf mit einem Begleittier u. / o.  emotionaler Unterst&uuml;tzung, anfordern. Die Passagiere m&uuml;ssen sich rechtzeitig  genug vor der Reise &uuml;ber bestimmte Anforderungen oder Sonderbedingungen der  Bef&ouml;rderung informieren, die vor der Aufnahme dieser Passagiere zur Aufnahme an  Bord erf&uuml;llt oder koordiniert werden m&uuml;ssen (z.&nbsp;B. Bef&ouml;rderung eines  alleinreisenden Minderj&auml;hrigen, Kinder, usw.). Dabei wird der Flugfrachtf&uuml;hrer jetzt  schon von allen Haftungen f&uuml;r den Fall befreit, dass er die Aufnahme an Bord  verweigert, weil die von der Fluggesellschaft jeweils g&uuml;ltigen Vorschriften u.  / o. Politiken nicht befolgt wurden.</li></ul>

<h3>3. VORSCHRIFTEN F&Uuml;R DIE GEP&Auml;CKBEF&Ouml;RDERUNG </h3>
<ul>
<li>3.1 Unter Einhaltung  internationaler und lokaler Vorschriften verweigert der Luftfrachtf&uuml;hrer die  Bef&ouml;rderung als Gep&auml;ck (Handgep&auml;ck oder aufgegebenes Gep&auml;ck) jener Artikel oder  gef&auml;hrlicher Substanzen, die ein bedeutendes Risiko f&uuml;r Gesundheit,  Flugsicherheit oder Eigentum darstellen k&ouml;nnen, wie z.&nbsp;B.: </li>
<ul>
  <li>(Komprimierte, verfl&uuml;ssigte,  aufgel&ouml;ste oder stark gek&uuml;hlte) Gase, inkl. brennbare, giftige oder  unsch&auml;dliche Aerosole wie Butangas, Sauerstoff, fl&uuml;ssiger Stickstoff,  Spraydosen mit l&auml;hmenden Gasen, Nachf&uuml;lltuben f&uuml;r Fl&uuml;ssiggasfeuerzeuge, usw. </li>
  <li>&Auml;tzende Fest- oder  Fl&uuml;ssigstoffe wie S&auml;uren, Alkalien,  Quecksilber, Batterien mit Fl&uuml;ssigelektrolyt, usw. </li>
  <li>Sprengstoffe wie Munition, Feuerwerke und Leuchtraketen, Koffer mit  Alarmger&auml;ten, Z&uuml;nder f&uuml;r Spielzeugpistolen, usw. </li>
  <li>Brennbare Fl&uuml;ssigkeiten wie Kraftstoffe, Lacke, Verd&uuml;nner, usw. </li>
  <li>Radioaktive Stoffe egal welcher Art. </li>
  <li>Oxidierende Stoffe und organische Peroxide wie Bleichmittel, D&uuml;nger, usw. </li>
  <li>Giftige oder ansteckende Substanzen wie Insektizide, Pestizide, biologische Erzeugnisse  mit Krankheitserregern, usw. </li>
  <li>Brennbare Feststoffe wie  Streichh&ouml;lzer </li>
  <li>Waffen, wobei darunter alle  Elemente oder Gegenst&auml;nde, die f&uuml;r Angriff oder Verteidigung geschaffen sind  oder eingesetzt werden k&ouml;nnen, zu verstehen sind, wie z. B. Feuerwaffen, Sto&szlig;waffen, Gase, spitze, schneidende, schlagende und  stromschlagverursachende Elemente, zu denen auch Schlagst&ouml;cke, &Auml;xte oder St&ouml;cke  mit einem Gewicht im Inneren oder in Zapfenform.</li>
</ul>

<li>3.2 Um die Flugsicherheit zu  wahren und die g&uuml;ltigen Vorschriften zu erf&uuml;llen, k&ouml;nnen Luftfrachtf&uuml;hrer und  Flughafensicherheitspersonal die vom Passagier oder in seinem Handgep&auml;ck  bef&ouml;rderten gef&auml;hrlichen Substanzen oder Artikel wegnehmen, um sie den  jeweiligen Beh&ouml;rden entsprechend der diesbez&uuml;glich anwendbaren lokalen  Vorschriften zur Verf&uuml;gung zu stellen.</li>
<li>3.3 Medikamente und Toilettenartikel d&uuml;rfen in begrenzter Menge von den  Passagieren bef&ouml;rdert werden. Bevor sie der Passagier in sein Gep&auml;ck aufnimmt, muss er sich beim  Personal des Luftfrachtf&uuml;hrers dar&uuml;ber erkundigen.</li>
<li>3.4 Einige der o.&nbsp;a. Artikel k&ouml;nnen auf dem Luftweg unter bestimmten  Sonderbedingungen im Rahmen einer Verschiffungsbescheinigung und einer  Luftfrachtgeb&uuml;hr bef&ouml;rdert werden. Zu diesem Zweck muss sich der Passagier  vorher beim Luftfrachtf&uuml;hrer erkundigen.</li>
<li>3.5 Unter Gep&auml;ck  sind nur die pers&ouml;nlichen Gegenst&auml;nde zu verstehen, die f&uuml;r die Reise notwendig  sind.</li>
<li>3.6 Der Passagier kann das zu bef&ouml;rdernde Gep&auml;ck f&uuml;r keinen anderen Flug als  den aufgeben, an Bord dessen er reisen wird.</li>
<li>3.7 Der  Luftfrachtf&uuml;hrer gibt das Gep&auml;ck f&uuml;r kein anderes Ziel als das auf dem Ticket  des Passagiers angegebene Endziel auf.</li>
<li>3.8 Der Passagier ist verpflichtet, die in <a href="/sitio_personas/index.html">www.lan.com</a> und in dem unter 1.1 bezeichneten Dokument &quot;Auskunft &uuml;ber Ihren Kauf&quot;  angegebenen Vorgaben &uuml;ber maximales Gewicht, Gr&ouml;sse und Abmessungen der  Gep&auml;ckst&uuml;cke zu respektieren. Erkundigungen &uuml;ber Freigep&auml;ck und Zahlungen, die  f&uuml;r Gep&auml;ck&uuml;bermengen geleistet werden m&uuml;ssen, sind direkt bei der  Fluggesellschaft oder in <a href="/sitio_personas/index.html">www.lan.com</a> einzuholen.</li>
<li>3.9 Das zul&auml;ssige Gep&auml;ck kann sich entsprechend der  Tarifbedingungen, Kabine und Route &auml;ndern und wird in St&uuml;ckzahlen oder Kilogramm  angegeben. Der Luftfrachtf&uuml;hrer beh&auml;lt sich das Recht vor, diese Freigep&auml;ckregelungen  und Gep&auml;ckabmessungen zu &auml;ndern. Die Bedingungen und Aufgabetarife werden bei den  zust&auml;ndigen lokalen Luftfahrtbeh&ouml;rden gemeldet, soweit dies vorgeschrieben ist. &nbsp; </li>
<li>3.10 Als Vorsichtsma&szlig;nahme und aus Sicherheitsgr&uuml;nden darf in  der Kabine nur ein Gep&auml;ckst&uuml;ck mitgef&uuml;hrt werden. &nbsp;Der Passagier ist verpflichtet, die in <a href="/sitio_personas/index.html">www.lan.com</a> und in dem unter 1.1 bezeichneten Dokument &quot;Auskunft &uuml;ber Ihren Kauf&quot;  angegebenen Vorgaben &uuml;ber maximales Gewicht, Gr&ouml;sse und Abmessungen des Handgep&auml;cks  zu respektieren. &nbsp;</li>
<li>3.11 Das aufgegebene Gep&auml;ck wird  dem &Uuml;berbringer des Gep&auml;ckscheins &uuml;bergeben. Im Fall von Besch&auml;digungen am Gep&auml;ck w&auml;hrend der  Bef&ouml;rderung muss die schriftliche Reklamation sofort nach Schadensfeststellung und  sp&auml;testens 7 Tage nach Empfangsdatum des Gep&auml;cks oder innerhalb der k&uuml;rzesten  Zeit, die die anwendbaren Vorschriften f&uuml;r Inlandfl&uuml;ge festlegen, eingereicht  werden. Bei Versp&auml;tungen muss  die Reklamation innerhalb von 21 Tagen nach &Uuml;bergabedatum des Gep&auml;cks oder  innerhalb der k&uuml;rzesten Zeit, die die anwendbaren Vorschriften f&uuml;r Inlandfl&uuml;ge  festlegen, erfolgen. Im Sinn des obigen Absatzes sind unter &quot;Versp&auml;tung&quot; alle  Verz&ouml;gerungen beim Empfang des Gep&auml;cks zu verstehen, die durch direktes  Verschulden des Luftfrachtf&uuml;hrers entstanden sind. </li></ul>

<h3>4.&nbsp; HAFTUNGSBESCHR&Auml;NKUNGEN  </h3>
<ul><li>4.1 Beginnt und endet die Reise eines Passagiers im gleichen Land, sind  Bef&ouml;rderungsleistungen und Haftungsbeschr&auml;nkungen nach der in diesem Land g&uuml;ltigen  Gesetzgebung geregelt. Im Fall einer internationalen Reise eines Passagiers gelten das  Warschauer Abkommen oder das Montrealer Abkommen oder alle weiteren  internationalen jeweils anwendbaren Vorschriften. Diese Abkommen  und Vorschriften regeln bei Bedarf die Haftungsgrenzen des Luftfrachtf&uuml;hrers im  Todesfall oder bei K&ouml;rperverletzungen des Passagiers und Verlust, Versp&auml;tung  oder Besch&auml;digung des Gep&auml;cks.</li>
<li>4.2 Der Luftfrachtf&uuml;hrer erkl&auml;rt, dass er bei Schadensersatzreklamationen im  Todesfall oder bei K&ouml;rperverletzungen in allen vom Warschauer Abkommen  geregelten Bef&ouml;rderungen die in dessen Artikel 22 (1) vorgeschriebenen  Haftungsgrenzen nicht geltend machen wird. &nbsp;Bei diesen Reklamationen wird der Luftfrachtf&uuml;hrer f&uuml;r Reklamationen  unter 100.000 DEG die Argumente im Artikel 20 (1) des Warschauer Abkommens  nicht anwenden. &nbsp;Abgesehen von den hier  vorgesehenen F&auml;llen kann der Luftfrachtf&uuml;hrer die im Warschauer Abkommen  vorgesehenen Argumente und anwendbaren Mittel gegen Dritte geltend machen.</li>
<li>4.3 Gegenst&auml;nde mit hohem Handelswert und elektronische Artikel m&uuml;ssen vom  Passagier als Handgep&auml;ck getragen werden, damit er sie st&auml;ndig unter Aufsicht  halten kann. Werden sie als aufgegebenes Gep&auml;ck transportiert, haftet der  Luftfrachtf&uuml;hrer nicht &uuml;ber die gesetzlich vorgesehenen Grenzen oder  international anwendbaren Abkommen hinaus.</li>
<li>4.4 Die Haftung des Luftfrachtf&uuml;hrers im Todesfall oder bei K&ouml;rperverletzung  des Passagiers u. / o. Verlust, Versp&auml;tung oder Besch&auml;digung des Gep&auml;cks bei  Bef&ouml;rderungen zwischen zwei Punkten im gleichen Land, ist durch die im  jeweiligen Land anwendbaren Gesetze und Gesetzgebungen begrenzt. Gleicherma&szlig;en  ist die Haftung des Luftfrachtf&uuml;hrers im Todesfall oder bei K&ouml;rperverletzung des Passagiers u. / o. Verlust, Versp&auml;tung oder  Besch&auml;digung des Gep&auml;cks bei internationalen Fl&uuml;gen durch die internationalen  Abkommen &uuml;ber internationale Luftbef&ouml;rderung, d.&nbsp;h. das Warschauer  Abkommen oder das Montrealer Abkommen, je nach Anwendbarkeit, begrenzt.<br>
  Diese Klauseln finden nur f&uuml;r die Regelung der Routen des  Luftfrachtf&uuml;hrers Anwendung. Kein Agent, Mitarbeiter oder Repr&auml;sentant des Luftfrachtf&uuml;hrers ist  befugt, Verordnungen dieser Klauseln zu &auml;ndern oder davon abzusehen. </li></ul>
</div>
</div>
</body>
</html>
