<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>T&eacute;rminos y Condiciones</title>
<link rel="stylesheet" href="/css/base.css" type="text/css"> 
<link rel="stylesheet" href="/css/contenido.css" type="text/css">
</head>
<body>
<div id="contenido">
<div id="contenido_popup">
  <h2>Condiciones </h2>
  <h3>Definiciones</h3>
  <ul>
    <li><strong>1.1 Programa de Pasajero Frecuente, Programa LANPASS, Programa o LANPASS:</strong> es el Programa de pasajeros frecuentes de LAN, mediante el cual, es posible acumular kil&oacute;metros volando en todas las rutas operadas por LAN, las L&iacute;neas A&eacute;reas Asociadas, as&iacute; como utilizando los servicios de otras empresas asociadas; todo ello sujeto a las condiciones y requisitos que m&aacute;s adelante se detallan. El Programa LANPASS, no implica la existencia de un convenio de ninguna naturaleza entre LAN y el socio, siendo los Premios y/o Beneficios LANPASS, una mera liberalidad de LAN para los miembros que se adhieren voluntariamente a &eacute;l. Salvo por lo indicado en este reglamento, tienen un car&aacute;cter gratuito.</li>
    <li><strong>1.2 Socio del Programa LANPASS o socio:</strong> es la persona que cumple con los requisitos del Programa, que ha completado y entregado el formulario de inscripci&oacute;n a trav&eacute;s de cualquiera de las formas establecidas en la cl&aacute;usula 2.2, cuya solicitud ha sido aceptada por LANPASS y que su calidad de socio no ha sido revocada o dejada sin efecto conforme con las normas del presente reglamento. Para el caso de las categor&iacute;as Premium, Premium Silver y Comodoro de LANPASS, su nombre estar&aacute; impreso en la tarjeta, con el respectivo n&uacute;mero de socio, el que a su vez es el n&uacute;mero de su cuenta. El socio del Programa tendr&aacute; una cuenta en donde acumular&aacute; Kil&oacute;metros LANPASS. La cuenta es unipersonal, reconociendo un &uacute;nico titular, no admitiendo la posibilidad de socios adicionales.</li>
    <li><strong>1.3 Kil&oacute;metros LANPASS o simplemente kil&oacute;metros:</strong> son la unidad de medida del Programa LANPASS, y que son canjeables exclusivamente por pasajes a&eacute;reos seg&uacute;n se indica en el cap&iacute;tulo 7 de este Reglamento.</li>
    <li><strong>1.4 Estado de Cuenta:</strong> es la informaci&oacute;n que peri&oacute;dicamente env&iacute;a LANPASS a los socios del Programa LANPASS entregando informaci&oacute;n sobre su cuenta. El estado de cuenta tambi&eacute;n ese encuentra disponible online. En el estado de cuenta se muestra la cantidad de kil&oacute;metros disponibles, todos los movimientos asociados a actividades del Programa LANPASS y toda otra informaci&oacute;n pertinente del mismo. El estado de cuenta constituye la &uacute;nica informaci&oacute;n v&aacute;lida acerca de los movimientos en la cuenta del socio.</li>
    <li><strong>1.5 Tarjeta de Socio o Tarjeta LANPASS:</strong> es la tarjeta que acredita la calidad de socio del Programa LANPASS. S&oacute;lo se emite para categor&iacute;as de socio Premium, Premium Silver y Comodoro y es distribuida por LANPASS directamente al socio una vez que adquiera la correspondiente categor&iacute;a, sin necesidad que la solicite.</li>
    <li><strong>1.6 L&iacute;neas A&eacute;reas Asociadas: </strong>son las compa&ntilde;&iacute;as a&eacute;reas, distintas de LAN, cuyos vuelos permiten acumular kil&oacute;metros y/o disfrutar de los Premios o Beneficios o Beneficios del Programa LANPASS, todo ello sujeto a las condiciones y requisitos de este reglamento y a las que dichas compa&ntilde;&iacute;as a&eacute;reas se&ntilde;alen.</li>
    <li><strong>1.7 Empresas Asociadas:</strong> son todas las empresas participantes en el Programa LANPASS, excepto las L&iacute;neas A&eacute;reas Asociadas, cuyos servicios permiten acumular kil&oacute;metros y/o disfrutar los Premios o Beneficios o Beneficios del Programa LANPASS; ello sujeto a las condiciones y requisitos de este reglamento y a las que dichas empresas se&ntilde;alen.</li>
    <li><strong>1.8 Premios y/o Beneficios:</strong> son aquellos pasajes que pueden obtenerse canjeando los kil&oacute;metros LANPASS, seg&uacute;n se describe en la Gu&iacute;a de Beneficios del Socio.</li>
    <li><strong>1.9 Gu&iacute;a de Beneficios del Socio:</strong> documento que explica a los socios, los Premios y/o Beneficios que otorga el Programa LANPASS, la forma y requisitos necesarios para obtener dichos Premios o Beneficios y los t&eacute;rminos y condiciones m&iacute;nimos que deben satisfacerse para ello. Esta gu&iacute;a est&aacute; disponible en www.lan.com.</li>
    <li><strong>1.10 Tabla de Premios o Beneficios: </strong>es la tabla confeccionada por LAN que indica los kil&oacute;metros LANPASS necesarios para solicitar un determinado Premio y/o Beneficio.</li>
    <li><strong>1.11 Certificado de Premio: </strong>certificado otorgado por LANPASS que da cuenta del otorgamiento de un determinado Premio y/o Beneficio, y que corresponde al canje de uno o m&aacute;s pasajes, seg&uacute;n se indique en el certificado.</li>
    <li><strong>1.12 Embargo:</strong> Per&iacute;odo dentro del cual no se pueden utilizar los Premios y/o Beneficios canjeados por kil&oacute;metros LANPASS, ya sea en LAN, en las L&iacute;neas A&eacute;reas Asociadas y/o en las Empresas Asociadas. Los per&iacute;odos de Embargo de cada entidad son variables y ser&aacute;n informados oportunamente, a los socios. </li>
    <li><strong>1.13 Stop Over:</strong> es una parada entre el punto de origen y el punto de destino, en la cual un pasajero puede permanecer, por un determinado tiempo, para despu&eacute;s continuar el viaje hacia su destino final en la misma l&iacute;nea a&eacute;rea. </li>
    <li><strong>1.14 Open Jaw:</strong> vuelo en el cual el punto de destino del viaje, a la ida, es distinto al punto de origen del tramo de vuelta (ejemplo: un viaje de ida de Santiago a Nueva York, volviendo de Los &Aacute;ngeles a Santiago). </li>
    <li><strong>1.15 Escala:</strong> es una parada t&eacute;cnica entre el punto de origen y el punto de destino, en la cual un pasajero debe permanecer (generalmente en el avi&oacute;n o aeropuerto) por un tiempo breve para despu&eacute;s continuar hacia su destino final. </li>
    <li><strong>1.16 Conexi&oacute;n:</strong> es una parada entre el punto de origen y el punto de destino con el objeto de cambiar el vuelo en que despu&eacute;s continuar&aacute; el viaje hacia su destino final en la misma l&iacute;nea a&eacute;rea. </li>
    <li><strong>1.17 Segmento:</strong> Se considera como segmento, un vuelo directo entre una cuidad y otra, que puede o no considerar escalas. </li>
    <li><strong>1.18 Upgrade:</strong> Es el ascenso de un pasajero a una clase de cabina superior, sin haber adquirido el boleto que corresponda a dicha clase.
    </li></ul>
      <h3>2. Condiciones de ingreso</h3>
      <ul>
      <li><strong>2.1</strong> Pueden ser socios del Programa LANPASS, s&oacute;lo personas naturales, mayores de 2 a&ntilde;os, no importando su nacionalidad ni lugar de residencia, siempre que (i) cumplan con todos los requisitos del Programa, (ii) completen y entreguen el correspondiente formulario de inscripci&oacute;n, (iii) que hayan sido expresamente aceptados en el Programa LANPASS y que su calidad de tal no haya sido cancelada o dejada sin efecto en conformidad con las normas del presente reglamento.</li>
      <li><strong>2.2</strong> La solicitud de ingreso al Programa LANPASS, se efectuar&aacute; a trav&eacute;s del correspondiente formulario de inscripci&oacute;n, disponible en todas las oficinas de LAN, a trav&eacute;s de Empresas Asociadas, o bien, a trav&eacute;s de inscripci&oacute;n telef&oacute;nica en Contact Center de LAN o el formulario de inscripci&oacute;n en www.lan.com. </li>
      <li><strong>2.3 </strong>Recibida la correspondiente solicitud de incorporaci&oacute;n, LANPASS informar&aacute; al solicitante que ha sido aceptado como socio, mediante el env&iacute;o de un correo electr&oacute;nico de bienvenida a la direcci&oacute;n de e-mail indicada por el socio. En caso de que no haya recibido la mencionada confirmaci&oacute;n de aceptaci&oacute;n, el solicitante deber&aacute; llamar al n&uacute;mero de tel&eacute;fono del Programa LANPASS, para informarse del resultado de su solicitud.</li>
      <li><strong>2.4</strong> Ese e-mail de bienvenida, entregar&aacute; informaci&oacute;n b&aacute;sica del programa, confirmar&aacute; el n&uacute;mero de socio LANPASS del reci&eacute;n inscrito y entregar&aacute; un vinculo a www.lan.com donde el socio podr&aacute; crear la clave LANPASS en caso que la inscripci&oacute;n haya sido hecha por una solicitud de inscripci&oacute;n impresa u otro medio que no entregue clave para el acceso al sitio web de LANPASS. </li>
      <li><strong>2.5 </strong>Los kil&oacute;metros LANPASS acumulados por un solicitante de inscripci&oacute;n, antes que sea expresamente aceptado como socio, no podr&aacute;n ser canjeados por Premios a menos que la persona sea expresamente aceptada como socio. </li>
      <li><strong>2.6</strong> Los datos entregados en la solicitud de incorporaci&oacute;n, como asimismo su actualizaci&oacute;n, son de exclusiva responsabilidad del socio. </li>
      <li><strong>2.7</strong> La direcci&oacute;n de correo especificada por el socio no puede ser una casilla postal ni otro tipo de direcci&oacute;n que no tenga cobertura por parte de correos. LANPASS no se hace responsable por la no entrega de correspondencia en este tipo de direcciones. </li>
      <li><strong>2.8</strong> Toda tarjeta LANPASS, es estrictamente personal e intransferible. El uso inadecuado, impropio o en desacuerdo con las condiciones y t&eacute;rminos aqu&iacute; establecidos de cualquier tarjeta LANPASS, podr&aacute; significar la eliminaci&oacute;n del Programa LANPASS, con la correspondiente cancelaci&oacute;n de todos los kil&oacute;metros LANPASS acumulados, sin perjuicio de las acciones legales a que haya lugar.</li>
      <li><strong>2.9</strong> El solicitante y/o el socio reconocen y aceptan ser los &uacute;nicos responsables de cualquier suma de dinero, sea en forma de impuestos, tasas, derechos u otra cualquiera, que deba pagarse a cualquier persona, natural o jur&iacute;dica, p&uacute;blica o privada, como resultado de la acumulaci&oacute;n o uso de los kil&oacute;metros LANPASS o consecuencia de su admisi&oacute;n al Programa LANPASS, o del uso de cualquier Premio o Beneficio del mismo.</li>
      <li><strong>2.10 </strong>Cualquier cambio de los datos entregados deber&aacute; solicitarse por escrito, con la correspondiente firma del socio, a trav&eacute;s del Contact Center LAN una vez validada la identidad del socio, o a trav&eacute;s de la p&aacute;gina web del LAN. No se aceptar&aacute;n cambios solicitados en forma verbal, salvo para cambiar el domicilio y el n&uacute;mero de tel&eacute;fono. Para efectuar los cambios respectivos, el socio puede enviar una carta al programa LANPASS o v&iacute;a Internet. </li>
      <li><strong>2.11</strong> S&oacute;lo se permitir&aacute; una cuenta por socio. En caso de existir dos o m&aacute;s cuentas, las m&aacute;s recientes ser&aacute;n canceladas. Todos los kil&oacute;metros LANPASS acumulados en las cuentas canceladas se traspasar&aacute;n a la cuenta original, siempre y cuando dichos kil&oacute;metros no hayan sido acumulados en ambas cuentas. </li>
      <li><strong>2.12</strong> No se permite el traspaso de kil&oacute;metros LANPASS entre cuentas del Programa LANPASS, como tampoco entre cuentas del programa LANPASS y cuentas de las L&iacute;neas A&eacute;reas Asociadas y/o Empresas Asociadas. Est&aacute; estrictamente prohibida la venta, cesi&oacute;n o transferencia de kil&oacute;metros LANPASS o de premios asociados a los mismos por cualquier medio o canal, incluyendo Internet. </li>
      <li><strong>2.13</strong> Para efectos de solicitar un Premio, no podr&aacute;n sumarse kil&oacute;metros LANPASS de diferentes cuentas del Programa LANPASS, ni de cuentas de las L&iacute;neas A&eacute;reas Asociadas y/o de las Empresas Asociadas. </li>
      <li><strong>2.14</strong> Por el hecho de completar el formulario de inscripci&oacute;n, el socio acepta expresamente recibir en su direcci&oacute;n de correo electr&oacute;nico o domicilio, la informaci&oacute;n del Programa y dem&aacute;s comunicaciones que LAN env&iacute;e peri&oacute;dicamente, sea que se relacionen o no con el Programa LANPASS. </li>
      <li><strong>2.15</strong> La forma y periodicidad de env&iacute;o de los Estados de Cuenta, Informaci&oacute;n de Beneficios o de socios, y dem&aacute;s comunicaciones, la determinar&aacute; libremente LAN; pudiendo al efecto, utilizar medios f&iacute;sicos (tales como correo p&uacute;blico o privado), o electr&oacute;nicos (tales como cuenta e-mail u otros).</li>
      <li><strong>2.16</strong> Adicionalmente a lo establecido en el p&aacute;rrafo anterior, por el hecho de completar el formulario de inscripci&oacute;n, el postulante al programa o el socio, acepta que LAN pueda disponer libremente de los datos incorporados en el referido formulario, sea en beneficio del Programa, de LAN o de terceros. Es condici&oacute;n esencial para la participaci&oacute;n en el programa LANPASS el hecho que la acumulaci&oacute;n de kil&oacute;metros se efect&uacute;e de acuerdo con los t&eacute;rminos y condiciones de este Programa y en pleno cumplimiento de la normativa que sea aplicable.</li></ul>
       
          <h3>3. T&eacute;rmino de la participaci&oacute;n de un socio en el programa</h3>
          <ul><li><strong>3.1</strong> La participaci&oacute;n de un socio en el Programa LANPASS, terminar&aacute; en los siguientes casos:</li>
            <li><strong>3.1.1</strong> Si el socio deja de cumplir cualquiera de los t&eacute;rminos y condiciones aqu&iacute; referidos, o si el uso del Programa LANPASS o la acumulaci&oacute;n de kil&oacute;metros se realiza con infracci&oacute;n a la ley o normativa aplicables. </li>
            <li><strong>3.1.2 </strong>Si el socio, a sabiendas, entrega cualquier informaci&oacute;n incorrecta o err&oacute;nea (incluyendo informaci&oacute;n sobre vuelos), ya sea en la solicitud de incorporaci&oacute;n o al momento de solicitar los Premios correspondientes. </li>
            <li><strong>3.1.3</strong> Si el socio no cumple con las condiciones del contrato de transporte de pasajeros (que se aplican a todos los pasajeros). </li>
            <li><strong>3.1.4 </strong>Si el socio hace un uso inadecuado o impropio de los Premios y/o Beneficios entregados. </li>
            <li><strong>3.1.5 </strong>Si el socio tiene una deuda vencida de la cual LAN, o algunas de sus compa&ntilde;&iacute;as filiales o relacionadas, es acreedora, o bien que existan indicios o presunciones de la participaci&oacute;n del socio en delitos cometidos en contra de dichas sociedades, tal como el giro doloso de cheques, u otros. </li>
            <li><strong>3.1.6 </strong>Por petici&oacute;n expresa del socio, lo que puede hacer en cualquier momento, por escrito, y en caso de socios Elite, adjuntando su tarjeta de socio cortada por la mitad. </li>
            <li><strong>3.1.7</strong> Por fallecimiento del socio. </li>
            <li><strong>3.1.8 </strong>Si el Programa LANPASS terminara por cualquier raz&oacute;n. </li>
            <li><strong>3.1.9 </strong>Por la sola voluntad de LANPASS, en cualquier momento, dando un aviso previo. </li>
            <li><strong>3.2.</strong> En caso de t&eacute;rmino de la participaci&oacute;n en el Programa LANPASS o de t&eacute;rmino del mismo, todos los kil&oacute;metros acumulados ser&aacute;n cancelados y no podr&aacute;n ser utilizados bajo ning&uacute;n concepto, ni podr&aacute;n ser canjeados por boletos y/o dinero.
            </li></ul>
              <h3>4. Suspensi&oacute;n de los derechos de un socio</h3>
    <ul><li><strong>4.1</strong> LANPASS podr&aacute; suspender temporalmente los derechos y beneficios del socio, sin que por ello pierda la calidad de tal pero manteniendo el derecho a acumular sus kil&oacute;metros sin la posibilidad de canjear Premios ni solicitar ning&uacute;n Beneficio propio del Programa, mientras LANPASS no levante la suspensi&oacute;n de su calidad de socio pleno.</li>
                <li><strong>4.2</strong> El derecho de suspensi&oacute;n lo podr&aacute; ejercer LANPASS en los casos en que el socio mantenga una deuda vencida con LAN o algunas de sus compa&ntilde;&iacute;as filiales o relacionadas, o bien que existan indicios o presunciones de la participaci&oacute;n del socio en delitos cometidos en contra de dichas sociedades, tal como el giro doloso de cheques, u otros.</li>
                <li><strong>4.3</strong> Lo se&ntilde;alado precedentemente es sin perjuicio que el socio pierda la calidad de tal, conforme a lo dispuesto en el presente reglamento.
    </li></ul>
                  <h3>5. Tarjeta de socio o tarjeta LANPASS</h3>
                  <ul>
                  <li>
                    <strong>5.1</strong> Solo para las categor&iacute;as que corresponda, la tarjeta de socio LANPASS tiene duraci&oacute;n indefinida. Las tarjetas de socio LANPASS Premium, LANPASS Premium Silver y LANPASS Comodoro tienen la duraci&oacute;n que se indica de acuerdo con los detalles del Programa en www.lan.com, los cuales pueden modificarse de acuerdo a lo establecido en el p&aacute;rrafo 6. Para todos los efectos de este reglamento, &quot;a&ntilde;o calendario&quot; comprende desde el 1 de enero al 31 de diciembre de cada a&ntilde;o.                  </li>
                  <li>
                    <strong>5.2</strong> Las tarjetas emitidas por las Empresas Asociadas ser&aacute;n validas de acuerdo a los t&eacute;rminos y condiciones de la respectiva empresa, sin perjuicio de estar siempre sujetas a lo establecido en la presente reglamentaci&oacute;n, en lo que sea pertinente. </li>
                  <li><strong>5.3 </strong>La persona cuyo nombre figura en la tarjeta de socio es la &uacute;nica que tiene derecho a utilizarla, para cualquier finalidad.</li>
                  <li><strong>5.4 </strong>La tarjeta de socio no es una tarjeta de cr&eacute;dito ni un documento que acredite identidad, por lo que no otorga m&aacute;s derechos que los indicados en el presente reglamento. </li>
                  <li><strong>5.5 </strong>Todas las tarjetas de socio son de exclusiva propiedad de LANPASS.
                    </p>
                    </li>
                  <li><strong>5.6</strong> El socio debe comunicar, inmediatamente, a la oficina de LAN m&aacute;s cercana, personalmente o por v&iacute;a telef&oacute;nica, la p&eacute;rdida o robo de su tarjeta de socio. Evaluados los antecedentes del caso por parte de LANPASS, una nueva tarjeta podr&aacute; ser emitida en un plazo de 30 d&iacute;as, contados desde la fecha en que se comunic&oacute; su p&eacute;rdida.</li>
                  </ul>
<h3>6. Categor&iacute;a de socio</h3><ul>
                      <li><strong>6.1</strong> El Programa LANPASS tiene cuatro categor&iacute;as de socio: (a) LANPASS, (b) Premium, (c) Premium Silver y (d) Comodoro. S&oacute;lo las tres &uacute;ltimas tienen tarjeta de socio asociada.</li>
                        <li><strong>6.2 </strong>Las diferentes categor&iacute;as de socio est&aacute;n determinadas por el cumplimiento de los requisitos establecidos para integrar cada categor&iacute;a, los que se describen en la secci&oacute;n LANPASS de la p&aacute;gina web www.lan.com. </li>
                        <li><strong>6.3</strong> La categor&iacute;a que le corresponde a un socio est&aacute; determinada por: el n&uacute;mero de kil&oacute;metros volados en tarifas que permitan la acumulaci&oacute;n de kil&oacute;metros en LAN o cualquiera de las L&iacute;neas A&eacute;reas Asociadas a <strong>one</strong>world, adem&aacute;s de las bonificaciones por clase de servicio de vuelos LAN (clase ejecutiva) a que se haya hecho merecedor el socio. Lo anterior, con la condici&oacute;n de tener un m&iacute;nimo de cuatro segmentos volados en LAN; o, por la cantidad de segmentos volados en LAN en tarifas que permitan la acumulaci&oacute;n de kil&oacute;metros. Cualquiera de las condiciones anteriores, debe ser cumplida en un a&ntilde;o calendario. Tambi&eacute;n se determinan las categor&iacute;as Comodoro y Premium Silver por una cantidad menor de kil&oacute;metros de los cuales debe haber una cantidad de segmentos volados en LAN en Clase Ejecutiva en vuelos de largo alcance. El detalle de los vuelos definidos como de largo alcance y la cantidad de kms. requeridos para cada categor&iacute;a se detallan en www.lan.com. </li>
                        <li><strong>6.4 </strong>No se contabilizar&aacute;n para determinar una categor&iacute;a de socio los kil&oacute;metros LANPASS acumulados en las Empresas Asociadas y/o en las L&iacute;neas A&eacute;reas Asociadas (excepto que se indique expresamente lo contrario). </li>
                        <li><strong>6.5</strong> Tampoco se contabilizar&aacute;n para determinar una categor&iacute;a de socio, los tramos volados haciendo uso de un Premio y/o Beneficio o cualquier otro pasaje que no califique para acumular kil&oacute;metros LANPASS. </li>
                        <li><strong>6.6</strong> La permanencia de un socio en una determinada categor&iacute;a corresponde al a&ntilde;o siguiente y a lo que resta del a&ntilde;o en el cual cumpli&oacute; los requisitos suficientes para calificar en dicha categor&iacute;a.</li>
                        <li><strong>6.7</strong> LANPASS podr&aacute;, discrecionalmente, mantener o subir la categor&iacute;a de un socio, a&uacute;n cuando no haya cumplido con alguno de los requisitos para ello, pero nunca podr&aacute; bajarlo de categor&iacute;a, en la medida que cumpla con los requisitos establecidos para permanecer en ella.</li>
                        <li><strong>6.8</strong> Si un socio no cumple con los requerimientos para renovar su categor&iacute;a, pertenecer&aacute; al a&ntilde;o siguiente a la categor&iacute;a inmediatamente anterior a la que pertenec&iacute;a, aunque no cumpla con los requisitos para calificar a &eacute;sta. </li>
                        <li><strong>6.9 </strong>A partir del a&ntilde;o 2004, las renovaciones se efectuar&aacute;n los d&iacute;as 31 de marzo de cada a&ntilde;o, considerando los requisitos cumplidos por el socio el a&ntilde;o calendario anterior.</li>
                        <li><strong>6.10 </strong>Los cambios en la categor&iacute;a de socio, no afectar&aacute;n el saldo de kil&oacute;metros canjeables por Premios y viceversa.
                        </li></ul>
                          <h3>7. Kil&oacute;metros </h3>
                          <ul><li><strong>7.1</strong> La unidad de medida del Programa LANPASS son los kil&oacute;metros.</li>
                            <li><strong>7.1.1</strong> Las solicitudes para acreditaci&oacute;n de kil&oacute;metros de manera retroactiva originadas por servicios prestados por L&iacute;neas A&eacute;reas Asociadas, s&oacute;lo ser&aacute;n procesadas si el socio entrega sus documentos de vuelo (tarjetas de embarque y recibo del pasajero del billete de vuelo). En caso de no entregar documentos que respalden que el vuelo fue realizado, la solicitud no ser&aacute; procesada. </li>
                            <li><strong>7.2</strong> Los kil&oacute;metros presentan las siguientes caracter&iacute;sticas y est&aacute;n sujetos a los siguientes t&eacute;rminos: </li>
                            <li><strong>7.2.1</strong> No tienen ning&uacute;n valor comercial, no siendo negociables ni canjeables por dinero ni por ning&uacute;n otro bien. </li>
                            <li><strong>7.2.2</strong> Son intransferibles, tanto a t&iacute;tulo gratuito como a t&iacute;tulo oneroso. </li>
                            <li><strong>7.2.3</strong> No son transmisibles, por lo que, en el evento de la muerte del socio, la cuenta y los kil&oacute;metros en ella acumulados ser&aacute;n cancelados. </li>
                            <li><strong>7.2.4</strong> No son embargables, por tratarse de derechos cuyo ejercicio es enteramente personal. </li>
                            <li><strong>7.2.5</strong> No son objeto de disputa legal ni de medida judicial alguna, y s&oacute;lo pertenecen al socio titular de la cuenta, como un derecho personal. </li>
                            <li><strong>7.2.6</strong> Los Premios canjeados por el socio no ser&aacute;n reembolsables, en caso que el socio solicite la devoluci&oacute;n de un Premio emitido, deber&aacute; pagar un cargo en kil&oacute;metros. El cargo es variable dependiendo del Premio y de acuerdo a la informaci&oacute;n publicada en www.lan.com. La devoluci&oacute;n de un premio requiere que el pasaje emitido est&eacute; vigente (la vigencia comienza a regir a partir de la fecha de emisi&oacute;n del boleto), que sea antes de la salida del vuelo y, sin ning&uacute;n tramo volado, excepto para Upgrades en <strong>One</strong>world y que los kil&oacute;metros utilizados para su emisi&oacute;n no est&eacute;n vencidos al momento de solicitar la devoluci&oacute;n.</li>
                            <li><strong>7.2.7</strong> Los Premios no son endosables, por lo que no pueden ser utilizados en otras compa&ntilde;&iacute;as que no sean LAN o las L&iacute;neas A&eacute;reas Asociadas, ni por otras personas que las designadas por el socio, seg&uacute;n el Premio canjeado. Emitido un pasaje premio, &eacute;ste podr&aacute; ser utilizado &uacute;nicamente en la l&iacute;nea a&eacute;rea en &eacute;l indicada.
                            </li></ul>
                              <h3>8. Acumulaci&oacute;n de kil&oacute;metros</h3>
                              <ul><li><strong>8.1</strong> Se acreditar&aacute;n los kil&oacute;metros cuando un socio viaje en vuelos de LAN o de las L&iacute;neas A&eacute;reas Asociadas, siempre que se trate de vuelos operados por &eacute;sta (s), o bien, haga uso de los servicios habilitados de cualquiera de las Empresas Asociadas. En caso que el socio pertenezca al Programa LANPASS y al mismo tiempo al Programa de Pasajero Frecuente de la Empresa Asociada, los kil&oacute;metros s&oacute;lo podr&aacute;n ser acreditados en una de las cuentas, a elecci&oacute;n del socio. En ning&uacute;n caso se podr&aacute;n acreditar los kil&oacute;metros en m&aacute;s de una cuenta. El socio deber&aacute; informar su n&uacute;mero de socio, el cual deber&aacute; aparecer en la tarjeta de embarque. <br>
                                Para efectos de acumulaci&oacute;n de kilometraje, todo vuelo operado por cualquier l&iacute;nea a&eacute;rea, pero que utilice, por cualquier raz&oacute;n, c&oacute;digo de LAN en su pasaje, ser&aacute; considerado como vuelo v&aacute;lido para acumular kilometraje y para calificar en las categor&iacute;as Premium, Premium Silver y Comodoro, siempre que se haya realizado en tarifas, rutas y fechas que permitan la acumulaci&oacute;n de kil&oacute;metros LANPASS.</li>
                                <li><strong>8.2 </strong>En atenci&oacute;n a restricciones establecidas por las L&iacute;neas A&eacute;reas Asociadas, la forma y cantidad de kil&oacute;metros a acumular por vuelos realizados en &eacute;stas, no necesariamente coincidir&aacute;n con las establecidas por LAN para sus vuelos y depender&aacute;n de las restricciones de la tarifa pagada o las condiciones fijadas para dicha L&iacute;nea A&eacute;rea Asociada, pudiendo haber tarifas o vuelos que permitan acumular s&oacute;lo un porcentaje de la distancia volada u otras restricciones. Corresponder&aacute; al socio averiguar los kil&oacute;metros a acumular por los vuelos que realice con L&iacute;neas A&eacute;reas Asociadas. </li>
                                <li><strong>8.3</strong> Los vuelos de terceras compa&ntilde;&iacute;as a&eacute;reas operados por LAN, no acumulan kil&oacute;metros. Tampoco acumulan kil&oacute;metros aquellos vuelos marketeados por l&iacute;neas <strong>one</strong>world y operados por terceras compa&ntilde;&iacute;as. </li>
                                <li><strong>8.4 </strong>S&oacute;lo podr&aacute; acreditarse kilometraje volado previo a la inscripci&oacute;n, siempre que los vuelos se hayan realizado en LAN y no m&aacute;s de dos meses antes de la fecha de inscripci&oacute;n. </li>
                                <li><strong>8.5</strong> Los kil&oacute;metros se contabilizar&aacute;n en la cuenta del socio s&oacute;lo una vez realizado el viaje y pagado el boleto respectivo. Por lo tanto, no se acumular&aacute;n kil&oacute;metros por boletos adquiridos pero no volados o no pagados. En raz&oacute;n de lo anterior, el socio deber&aacute; mantener, y entregar de serle requerido, documentos que acrediten el vuelo realizado (boleto y tarjeta de embarque).</li>
                                <li><strong>8.6</strong> Los kil&oacute;metros generados por servicios prestados por L&iacute;neas A&eacute;reas Asociadas o Empresas Asociadas, se contabilizar&aacute;n en la cuenta del socio, s&oacute;lo una vez que la respectiva L&iacute;nea A&eacute;rea Asociada o Empresa Asociada, remitan la informaci&oacute;n requerida por LAN para tal contabilizaci&oacute;n, la cual, por lo general, no se har&aacute; despu&eacute;s de 30 d&iacute;as desde que se prest&oacute; el respectivo servicio al socio. </li>
                                <li><strong>8.7</strong> Los kil&oacute;metros acumulados corresponden a la distancia entre el punto de origen y el de destino del vuelo, distancias que son entregadas por IATA. Sin perjuicio de lo anterior, y como medida temporal o permanente, LANPASS podr&aacute; bonificar la distancia entre el punto de origen y el punto de destino con kilometraje adicional. </li>
                                <li><strong>8.8</strong> Los kil&oacute;metros acumulados por vuelo en LAN tienen una vigencia de 36 meses corridos, contados desde la fecha del vuelo. En todo caso, los kil&oacute;metros vencer&aacute;n, efectivamente, el &uacute;ltimo d&iacute;a del mes correspondiente al mes de vencimiento. <br>
                                  Los kil&oacute;metros acumulados por vuelo en las L&iacute;neas A&eacute;reas Asociadas, al utilizar cualquiera de los servicios de las empresas asociadas o bonos promocionales, tienen vigencia de 3 a&ntilde;os calendario, lo que significa que vencen el d&iacute;a 31 de diciembre del tercer a&ntilde;o en el cual fueron acumulados. <br>
                                  Ahora bien, cada vez que el pasajero vuele en LAN y acumule 1 o m&aacute;s kil&oacute;metros por ese vuelo, todos los kil&oacute;metros acumulados vigentes en su cuenta hasta la fecha de dicho vuelo autom&aacute;ticamente se renuevan, pasando a tener una vigencia de 36 meses corridos, contados desde la fecha del mencionado vuelo y vencer&aacute;n, efectivamente, el &uacute;ltimo d&iacute;a del trig&eacute;simo sexto mes. <br>
                                  En todo caso, los kil&oacute;metros acumulados antes del 1 de mayo de 1998 ser&aacute;n v&aacute;lidos hasta el d&iacute;a 31 de diciembre del tercer a&ntilde;o en que los kil&oacute;metros fueron efectivamente volados seg&uacute;n las reglas indicadas en los p&aacute;rrafos anteriores, cualquiera sea la que m&aacute;s beneficie al socio. <br>
                                No es responsabilidad de LANPASS informar la fecha de expiraci&oacute;n de los kil&oacute;metros, conforme a las reglas de expiraci&oacute;n de kil&oacute;metros que aqu&iacute; se se&ntilde;alan. </li>
                                <li><strong>8.9 </strong>Todos los kil&oacute;metros que aparecen en el estado de cuenta son canjeables por Premios y/ Beneficios. Los kil&oacute;metros volados en LAN y l&iacute;neas a&eacute;reas <strong>one</strong>world, incluyendo los bonos por clase de servicio en LAN, se utilizan tambi&eacute;n para determinar la categor&iacute;a de socio LANPASS.</li>
                                <li><strong>8.10 </strong>Los Premios y/o Beneficios del programa LANPASS volados en LAN o en cualquiera de las L&iacute;neas A&eacute;reas Asociadas, as&iacute; como los premios correspondientes a servicios de las empresas asociadas, no acumulan kilometraje. <br>
                                Tampoco acumulan kilometraje los Premios y/o Beneficios emitidos con tarifas reducidas de la industria del turismo, vuelos charter, pasajes para empleados de l&iacute;neas a&eacute;reas, descuentos gubernamentales, pasajes gratuitos o cualquier otro pasaje que no indique una tarifa publicada. La exclusi&oacute;n de otros tipos de pasajes queda a la exclusiva discreci&oacute;n de LANPASS, lo que ser&aacute; informado oportuna y adecuadamente a los socios. </li>
                                <li><strong>8.11</strong> Los Premios y/o Beneficios endosados a otras compa&ntilde;&iacute;as por LAN acumular&aacute;n el kilometraje equivalente, como si hubieran sido efectivamente volados en LAN, s&oacute;lo en caso de tratarse de un evento involuntario. Los Premios y/o Beneficios endosados por l&iacute;neas a&eacute;reas <strong>one</strong>world o asociadas a terceros no acumulan kil&oacute;metros. </li>
                                <li><strong>8.12</strong> En caso de un Upgrade de clase obtenido como premio o cortes&iacute;a de LAN o de cualquiera de las L&iacute;neas A&eacute;reas Asociadas o Empresas Asociadas, s&oacute;lo se acumular&aacute;n en la cuenta los kil&oacute;metros correspondientes a la clase pagada por el socio, y no los correspondientes a la clase a la cual fue promovido. </li>
                                <li><strong>8.13</strong> Ser&aacute; de exclusiva responsabilidad del socio verificar que los kil&oacute;metros correspondientes a sus vuelos en LAN y/o en las L&iacute;neas A&eacute;reas Asociadas, as&iacute; como los provenientes de servicios de las Empresas Asociadas, est&aacute;n acreditados correctamente en su cuenta. <br>
                                Para esto, el socio deber&aacute; guardar todos sus documentos de vuelo (tarjetas de embarque, recibo del pasajero del billete de vuelo) as&iacute; como, los originales de facturas o contratos, a fin de poder reclamar una acreditaci&oacute;n retroactiva de kil&oacute;metros. En ning&uacute;n caso se podr&aacute;n acumular kil&oacute;metros despu&eacute;s de un (1) a&ntilde;o de ocurrido el vuelo o acto que los generaron, salvo que empresas asociadas lo permitan para kil&oacute;metros provenientes de ellas mismas. </li>
                                <li><strong>8.14</strong> LANPASS se reserva el derecho de auditar la cuenta de un socio en cualquier momento y sin previo aviso, con el fin de asegurarse el cumplimiento de estos t&eacute;rminos y condiciones. LANPASS podr&aacute; descontar los kil&oacute;metros acreditados indebidamente a un socio, as&iacute; como demorar la entrega de Premios o certificados mientras se resuelve cualquier discrepancia, debiendo informarse de ello al socio.</li>
                                <li><strong>8.15</strong> En el caso que los Premios y/o Beneficios que habilitan a acumular kil&oacute;metros LANPASS sean adquiridos a cr&eacute;dito, o su pago est&eacute; diferido en el tiempo, el socio podr&aacute; canjear un Premio y/o Beneficio utilizando los kil&oacute;metros, sean los correspondientes al pasaje adquirido o cualquier otro, s&oacute;lo en la medida que los pasajes respectivos est&eacute;n siendo pagados en la forma y tiempo en que se haya acordado, al momento de comprar el Premio y/o Beneficio. </li>
                                <li><strong>8.16</strong> Ser&aacute; de exclusiva responsabilidad del socio dar cumplimiento a la ley y regulaci&oacute;n que le pudiera ser aplicable para efectos de su participaci&oacute;n en el Programa LANPASS y la acumulaci&oacute;n de kil&oacute;metros, en especial, respecto de aquellos socios que tengan la calidad de funcionarios p&uacute;blicos.
                                </li></ul>
                                  <h3>9. Canje Flexible LANPASS </h3>
                                  <ul><li><strong>9.1</strong> Para solicitar un Premio y/o Beneficio, el socio debe tener un n&uacute;mero de socio vigente y la cantidad de kil&oacute;metros necesaria para canjear el Premio solicitado. La cantidad de kil&oacute;metros necesaria para acceder a un Premio y/o Beneficio es la indicada en la Tabla de Premios vigente en la fecha en que se presente la solicitud.</li>
                                    <li><strong>9.2</strong> Los kil&oacute;metros necesarios para cobrar un Premio y/o Beneficio var&iacute;an dependiendo de tipo de Premio y de la cabina cotizada. La cabina Economy tiene 3 niveles de Premios: Classic, Plus y Full (ordenados de menor a mayor cantidad de kil&oacute;metros requeridos para cobrarlos). La cabina Premium Bussiness tiene un solo nivel de Premios. </li>
                                    <li><strong>9.3</strong> Solo pueden solicitarse Upgrade para cabina Premium Bussiness. </li>
                                    <li><strong>9.4</strong>Para cada tipo de Premio y/o Beneficio hay disponibilidad limitada de asientos. </li>
                                    <li><strong>9.5 </strong>Para solicitar un Premio, el Socio puede llamar al Contact Center de LAN (opci&oacute;n LANPASS), ingresar a la p&aacute;gina web www.lan.com, o dirigirse a las Oficinas de LAN o agencias de viaje. En todos los casos hay que mostrar un documento que acredite la identidad del socio. En Lan.com se necesita usuario y clave.</li>
                                    <li><strong>9.6 </strong>Para el canje de Premios a trav&eacute;s de Contact Center LAN (opci&oacute;n LANPASS u Oficinas LAN o agencias de viaje, el Socio debe pagar un cargo por emisi&oacute;n (Service Fee LANPASS) por cada pasaje emitido. Si el Premio es canjeado a trav&eacute;s de www.lan.com, no se aplica el cargo por emisi&oacute;n. El Service Fee LANPASS es adicional a las tasas de embarque e impuestos aplicables y variar&aacute; seg&uacute;n el tipo de Premio canjeado, seg&uacute;n la Tabla de Premios Publicada en www.lan.com. </li>
                                    <li><strong>9.7</strong> La solicitud de un Premio puede hacerla cualquier persona, presentando un poder simple debidamente suscrito por el Socio, indicando: nombre completo del Socio, n&uacute;mero de cuenta y/o n&uacute;mero de R.U.T., y determinaci&oacute;n del Premio que solicita. Debe adjuntarse adem&aacute;s, fotocopia simple de un documento que acredite la identidad del Socio (c&eacute;dula de identidad, equivalente o pasaporte). </li>
                                    <li><strong>9.8</strong> Los Premios tienen un a&ntilde;o de vigencia (12 meses), a partir desde la fecha de su emisi&oacute;n; transcurrida la cual, caducan inmediatamente. </li>
                                    <li><strong>9.9 </strong>Los Premios se otorgan &quot;ida y vuelta&quot;. No se canjean Premios Oneway. No se permitir&aacute; el embarque del Socio en el tramo correspondiente al vuelo de regreso si no ha volado el tramo correspondiente al vuelo de ida. Si el Socio usa el Premio s&oacute;lo en el tramo de ida no se le devolver&aacute; el saldo de kilometraje ni dinero pagado, por el tramo de regreso no utilizado. </li>
                                    <li><strong>9.10</strong> Los Upgrade se pueden canjear One way (s&oacute;lo para el tramo de ida o para el tramo de regreso) o bien &ldquo;ida y vuelta&rdquo;. </li>
                                    <li><strong>9.11</strong> Los Premios emitidos son nominativos y no pueden cederse o transferirse a terceros. </li>
                                    <li><strong>9.13</strong> La reserva y la emisi&oacute;n de un Premio debe ocurrir de manera simult&aacute;nea. </li>
                                    <li><strong>9.14 </strong>LANPASS se reserva el derecho de retener Premios en caso de constatar alguna irregularidad en su solicitud o utilizaci&oacute;n. Toda contravenci&oacute;n a los presentes t&eacute;rminos y condiciones podr&aacute; dar lugar a la negativa de LANPASS a emitir un Premio y/o al t&eacute;rmino de la participaci&oacute;n del Socio en el Programa LANPASS, caducando inmediatamente todos los kil&oacute;metros de la cuenta. </li>
                                    <li><strong>9.15</strong> El Socio puede solicitar cambios de un Premio con anterioridad a la fecha en que haya comenzado el viaje y con una anticipaci&oacute;n m&iacute;nima de 48 horas. No se permiten cambios por remanentes de Premios (una vez que ya comenzaron a ser usados). En caso de cambio, la validez del Premio no se extiende. En consecuencia, el Premio cambiado tendr&aacute; una validez equivalente al remanente de la validez que ten&iacute;a el Premio original. </li>
                                    <li><strong>9.16</strong> S&oacute;lo se permite el cambio de Premios por otros que exijan una igual o menor cantidad de kil&oacute;metros.</li>
                                    <li><strong>9.17</strong> Se puede solicitar el cambio de fecha de un Premio, s&oacute;lo si hay disponible un Premio que exija una cantidad igual o menor de kil&oacute;metros.</li>
                                    <li><strong>9.18</strong> Por el hecho de cambiar un Premio por otro que requiera menor cantidad de kil&oacute;metros, la diferencia de kil&oacute;metros no utilizada en el nuevo Premio no se devuelve al Socio, salvo que solicite un nuevo cambio por un Premio que requiera un cantidad igual o inferior a los kil&oacute;metros a los utilizados en el Premio original; en cuyo caso podr&aacute; utilizar el saldo de kil&oacute;metros en el segundo nuevo Premio. Para posteriores cambios de fecha se mantiene la cantidad de kil&oacute;metros inicial.</li>
                                    <li><strong>9.19</strong> Los cambios voluntarios deben realizarse en la misma cabina emitida originalmente, salvo que en el nuevo vuelo no exista la cabina original. En este caso se podr&aacute; emitir el Premio en una cabina inferior, debiendo el Socio renunciar a la diferencia de kil&oacute;metros no utilizada.</li>
                                    <li><strong>9.20</strong> Los cambios de Premios emitidos con anterioridad al 4 de agosto de 2009 se regir&aacute;n por los t&eacute;rminos y condiciones vigentes a la fecha de su emisi&oacute;n.</li>
                                    <li><strong>9.21</strong> El cambio de fecha, ruta o vuelo de los Premios, s&oacute;lo esta permitido en caso de no haber sido utilizado alguno de los cupones. Este cambio tiene asociado un cargo por concepto de dicho cambio. El cargo es variable seg&uacute;n el pa&iacute;s de emisi&oacute;n del boleto y de la ruta. Los cargos por cambios est&aacute;n publicados en www.lan.com. Los Premios emitidos para ser volados en las L&iacute;neas A&eacute;reas Asociadas a la alianza <strong>one</strong>world solo permiten cambios de fecha y/u hora y no permiten cambios de itinerario, l&iacute;nea a&eacute;rea o stopover previamente programados. </li>
                                    <li><strong>9.22</strong> En caso que el Socio solicite la devoluci&oacute;n un Premio emitido, deber&aacute; pagar una cargo en kil&oacute;metros. La cargo es variable dependiendo del Premio y de acuerdo a la informaci&oacute;n publicada en www.lan.com. La devoluci&oacute;n de un premio requiere que el pasaje emitido est&eacute; vigente (la vigencia comienza a regir a partir de la fecha de emisi&oacute;n del boleto), que sea antes de la salida del vuelo y, sin ning&uacute;n tramo volado, excepto para Upgrades en <strong>one</strong>world y que los kil&oacute;metros utilizados para su emisi&oacute;n no est&eacute;n vencidos al momento de solicitar la devoluci&oacute;n. La devoluci&oacute;n podr&aacute; solicitarse en Call Center de LAN (opci&oacute;n LANPASS) o en Oficinas LAN. Gestionada la devoluci&oacute;n, los kil&oacute;metros no vencidos ser&aacute;n abonados nuevamente en la cuenta de kil&oacute;metros LANPASS del Socio. </li>
                                    <li><strong>9.23</strong> Los Premios son nominativos, no tienen valor en dinero y son intransferibles. En caso que por cualquier causa o motivo un Premio no sea -total o parcialmente- utilizado en el tiempo y forma emitidos, dicho Premio perder&aacute; todo valor. </li>
                                    <li><strong>9.24</strong> Es responsabilidad del Socio revisar la cantidad de kil&oacute;metros LANPASS requeridas para un Premio en &nbsp;Vuelos LAN y en Vuelos <strong>one</strong>world y asociados, ya que para una misma ruta las cantidades de Kms. solicitadas pueden variar.
    </li></ul>
    <h3>10. Restricciones para el uso de premios</h3>
                                      <ul><li><strong>10.1</strong> Los Premios est&aacute;n sujetos a disponibilidad de espacio, la que ser&aacute; confirmada al momento de su emisi&oacute;n.</li>
                                        <li><strong>10.2</strong> Los Premios permiten un (1) Stopover (parada voluntaria del pasajero en una de las Escalas consideradas en el tramo de ida o de regreso del viaje) o un (1) Openjaw (ciudad de destino distinta a la ciudad de origen de la vuelta), tanto en rutas nacionales como internacionales. Algunas aerol&iacute;neas <strong>one</strong>world o asociadas no permiten Stopover y Openjaw. <a href="/sitio_personas/lanpass/como_canjear/oneworld_asociadas.htm">Vea m&aacute;s  informaci&oacute;n</a>.</li>
                                        <li><strong>10.3</strong> No est&aacute; permitida la emisi&oacute;n de Premios abiertos, es decir, sin fecha de salida o llegada. </li>
                                        <li><strong>10.4</strong> En ning&uacute;n caso los Premios podr&aacute;n ser usados en otras compa&ntilde;&iacute;as a&eacute;reas que no sean las indicadas en el Premio. En caso de cancelaci&oacute;n del vuelo indicado en el Premio por un hecho no imputable a LAN, por razones de seguridad o por caso fortuito o fuerza mayor, LAN har&aacute; el mejor esfuerzo por embarcar al pasajero en el vuelo siguiente o en una combinaci&oacute;n de vuelos que permitan transportarlo al destino del Premio. En ning&uacute;n caso se embarcar&aacute; al Socio en otra l&iacute;nea a&eacute;rea por estos u otros motivos. </li>
                                        <li><strong>10.5</strong> En caso de Premios con vuelos que contemplan conexiones con cambios de avi&oacute;n, los gastos de estad&iacute;a en el lugar de conexi&oacute;n y cualquier otro gasto asociado a ello ser&aacute; de cargo y cuenta exclusivos del pasajero. </li>
                                        <li><strong>10.7</strong> Los Premios no podr&aacute;n ser combinados con otras promociones, cupones, descuentos u ofertas especiales, no tienen validez en aquellos lugares donde lo proh&iacute;be la ley y est&aacute;n sujetos a las restricciones propias de la industria. </li>
                                        <li><strong>10.8</strong> Los Premios otorgados corresponden exclusivamente al valor neto de tarifa, siendo de responsabilidad y cargo del pasajero el pago de cualquier tasa, impuesto, tributo y/o derecho que su emisi&oacute;n la imponga, incluyendo, pero no limitado, a la correspondiente tasa de embarque. </li>
                                        <li><strong>10.9</strong> Ser&aacute; de exclusiva responsabilidad del Socio informarse adecuadamente sobre todas las restricciones en la solicitud y el uso de los Premios a la fecha de su utilizaci&oacute;n. </li>
                                        <li><strong>10.10</strong> Si el Premio incluye vuelos operados por aerol&iacute;neas oneworld o asociadas, es responsabilidad del Socio informarse sobre las &nbsp;Condiciones de Transporte de la aerol&iacute;nea que opera el vuelo. Esta informaci&oacute;n se encuentra disponible en www.lan.com.</li>
    </ul>
                                          <h3>11. Uso cupones de upgrade</h3>
                                          <ul><li><strong>11.1</strong> Los cupones de Ugrade son v&aacute;lidos hasta la fecha en ellos indicada, y otorgan al pasajero un Upgrade a la clase inmediatamente superior, en un vuelo operado y vendido por LAN a la ida o al regreso, condicionado al cumplimiento de las tarifas m&iacute;nimas correspondientes a la ruta, a la cantidad de cupones requeridos por ruta y a la disponibilidad de asientos al momento del embarque.</li>
                                            <li><strong>11.2 </strong>Las tarifas m&iacute;nimas exigidas para el pasaje pagado est&aacute;n disponibles en www.lan.com. </li>
                                            <li><strong>11.3</strong> El cup&oacute;n de Upgrade no tendr&aacute; validez alguna en caso de alteraci&oacute;n, reproducci&oacute;n o uso incorrecto. Carece de valor monetario, ser&aacute; nulo si se lo emplea para cualquier tipo de intercambio y no ser&aacute; reemplazado en caso de robo, hurto o p&eacute;rdida. </li>
                                            <li><strong>11.4 </strong>Todos los Cupones de Upgrade son exclusivamente para el socio y/o su acompa&ntilde;ante. El acompa&ntilde;ante podr&aacute; usar el Cup&oacute;n de Upgrade siempre y cuando viaje junto al socio (no necesariamente en la misma clase de cabina). </li>
                                            <li><strong>11.5</strong> Ser&aacute; responsabilidad del pasajero efectuar el pago de cualquier impuesto requerido para hacer uso de su Certificado de Upgrade.
                                            </li></ul>
                                              <h3>12. Generalidades</h3>
                                              <ul><li><strong>12.1</strong> La participaci&oacute;n en el Programa LANPASS est&aacute; sujeta a los t&eacute;rminos y condiciones aqu&iacute; establecidos, los que pueden cambiar, peri&oacute;dicamente, a sola discreci&oacute;n de LANPASS. Todo cambio en los t&eacute;rminos y condiciones ser&aacute; de observaci&oacute;n obligatoria para los socios a los 30 d&iacute;as de su notificaci&oacute;n, por cualquier medio. Esto incluye el derecho a modificar la Gu&iacute;a de Beneficios del socio, modificar la tabla de Premios, el sistema de acumulaci&oacute;n de kil&oacute;metros, el sistema de concesi&oacute;n de premios y la participaci&oacute;n de otras organizaciones en el Programa.</li>
                                                <li><strong>12.2 </strong>LANPASS se reserva el derecho a dar por concluido el Programa LANPASS en cualquier momento, con o sin notificaci&oacute;n previa, quedando sin efecto o valor todos los kil&oacute;metros acumulados del socio. En todo caso, LANPASS har&aacute; todo lo posible por comunicar previamente y con una anticipaci&oacute;n prudente la conclusi&oacute;n del Programa a sus socios, a fin de que puedan utilizar los kil&oacute;metros acumulados.</li>
                                                <li><strong>12.3 </strong>LANPASS no ser&aacute; responsable, en ning&uacute;n caso, por p&eacute;rdidas o da&ntilde;os que pudieran resultar de la conclusi&oacute;n del Programa LANPASS o cambios o modificaciones del mismo. </li>
                                                <li><strong>12.4</strong> Todos los Premios y/o Beneficios est&aacute;n sujetos a cambio y disponibilidad, siendo de exclusiva responsabilidad del socio solicitar la correspondiente reserva v&aacute;lida y cumplir todas las dem&aacute;s etapas necesarias para el goce de los mismos. </li>
                                                <li><strong>12.5</strong> Algunos de los Premios, Beneficios, y oportunidades para obtener kil&oacute;metros son o pueden ser proporcionados por organizaciones con las cuales LANPASS tiene acuerdos, pero sobre las cuales LANPASS no posee control alguno. De cualquier modo, LANPASS tratar&aacute; de asegurar que los Premios y Beneficios ofrecidos a los socios como disponibles est&aacute;n, de hecho, disponibles.<br>
                                                No obstante, LANPASS no garantiza ni responde por la disponibilidad de dichos Premios y Beneficios, por lo que no ser&aacute; responsable por cualquier da&ntilde;o o p&eacute;rdida que pudiesen resultar de la provisi&oacute;n, o falta de provisi&oacute;n, total o parcial, de cualquier premio o beneficio. Tampoco LANPASS ser&aacute; responsable en caso de abandono del Programa LANPASS por parte de una de estas organizaciones. </li>
                                                <li><strong>12.6</strong> La provisi&oacute;n o suministro de los Premios y/o Beneficios ofrecidos por las L&iacute;neas A&eacute;reas Asociadas y/o por las Empresas Asociadas estar&aacute;n sujetos a los t&eacute;rminos y condiciones que dicha organizaci&oacute;n imponga. </li>
                                                <li><strong>12.7</strong> LANPASS es responsable de ninguna p&eacute;rdida, perjuicio, demora o da&ntilde;o resultantes de, o conectados con el Programa LANPASS o cualquier Premio y/o Beneficio ofrecido, excepto en la medida en que dicha p&eacute;rdida, perjuicio, demora o da&ntilde;o sean causados por negligencia grave o dolo de LANPASS. </li>
                                                <li><strong>12.8 </strong>LANPASS es responsable por los errores u omisiones que, a pesar de todas las precauciones tomadas, pudieran producirse en la informaci&oacute;n relativa a cualquier parte del Programa LANPASS. Tampoco es responsable por la demora, p&eacute;rdida o entrega equivocada de la correspondencia dirigida al socio. </li>
                                                <li><strong>12.9</strong> Toda comunicaci&oacute;n escrita del socio dirigida al Programa LANPASS, deber&aacute; llevar su firma y el n&uacute;mero de socio. </li>
                                                <li><strong>12.10</strong> LANPASS es la &uacute;nico responsable por la interpretaci&oacute;n y aplicaci&oacute;n de los presentes t&eacute;rminos y condiciones. </li>
                                                <li><strong>12.11</strong> Salvo autorizaci&oacute;n expresa y por escrito de LAN, la compra, venta, intercambio o transferencia, a cualquier t&iacute;tulo, de Premios y/o Beneficios, certificados y/o kil&oacute;metros LANPASS est&aacute; absolutamente prohibida. Toda persona que sea sorprendida comprando, vendiendo, intercambiando o transfiriendo Premios y/o Beneficios, certificados y/o kil&oacute;metros LANPASS podr&aacute; ser obligada al pago de la tarifa completa asociada, de los perjuicios y da&ntilde;os causados y de los costos legales involucrados, todo ello de conformidad a la legislaci&oacute;n vigente. </li>
                                                <li><strong>12.12 </strong>Los Premios y/o Beneficios, certificados y/o kil&oacute;metros LANPASS que hayan sido vendidos, o comprados a cualquier t&iacute;tulo sin aprobaci&oacute;n de LAN, y las personas que se encuentren utilizando dichos premios no podr&aacute;n continuar el viaje o dejar&aacute;n de recibir el servicio asociado al premio, excepto pagando la tarifa completa del mismo. </li>
                                                <li><strong>12.13</strong> LANPASS no ser&aacute; responsable por los Premios otorgados por Empresas Asociadas o L&iacute;neas A&eacute;reas Asociadas, siendo estas &uacute;ltimas las &uacute;nicas responsables frente al socio por los Premios que otorguen. </li>
                                                <li><strong>12.14 </strong>Los vuelos que aparezcan contabilizados en los estados de cuenta del Programa LANPASS, no constituyen prueba alguna de que el socio efectu&oacute; realmente el vuelo indicado. </li>
                                                <li><strong>12.15 </strong>Los presentes t&eacute;rminos y condiciones, est&aacute;n sujetos a modificaci&oacute;n sin previo aviso, manteniendo una versi&oacute;n electr&oacute;nica actualizada en www.lan.com o disponible para ser solicitada en cualquier oficina LAN.
                                                  </p>
                                                  </li>
                                                <li><strong>12.16 </strong>Los presentes t&eacute;rminos y condiciones, se rigen por las leyes de la Rep&uacute;blica de Chile y, cualquier dificultad, contienda o litigio que suscite su aplicaci&oacute;n, cumplimiento, interpretaci&oacute;n o validez, ser&aacute; resuelta por sus Tribunales Ordinarios de Justicia.
                                                  </li>
                                                             
                      </ul>
                      <h2>Condiciones aplicables al Contrato de trasnporte a&eacute;reo de pasajeros y equipaje</h2>
                      <h3>Definiciones</h3>
                      <ul>
                        <li>Para los efectos de las presentes condiciones se entender&aacute; lo siguiente por cada uno de los t&eacute;rminos que a continuaci&oacute;n se indican: </li>
                        <li>1.1<strong> "Billete"</strong> o <strong>&ldquo;Billete  de Pasaje&rdquo;, </strong>significa el conjunto de documentos &nbsp;que dan cuenta y hacen fe de la celebraci&oacute;n y de las condiciones del contrato de transporte a&eacute;reo y control de equipaje, y que est&aacute;n comprendidos por todos o algunos de los siguientes documentos: <strong>(i)</strong> las presentes Condiciones del  Contrato de Transporte A&eacute;reo; <strong>(ii)</strong> las disposiciones contenidas en el&nbsp; documento denominado &ldquo;Informaci&oacute;n de su Compra&rdquo; entregado por la compa&ntilde;&iacute;a o detalles de la reserva entregados por cualquier agente; <strong>(iii)</strong> el billete electr&oacute;nico registrado magn&eacute;ticamente;<strong> (iv)</strong> las condiciones espec&iacute;ficas  aplicables a la tarifa pagada por el pasajero;&nbsp; <strong>(v)</strong> la Tarjeta de Embarque o <em>Boarding Pass</em>; y <strong>(vi)</strong> las comunicaciones y las tarifas de contrataci&oacute;n que se encuentren registradas ante las autoridades aeron&aacute;uticas en los pa&iacute;ses que lo requieran.</li>
                        <li>1.2 <strong>"Transportista"</strong> o <strong>"Transportador",</strong> significa la l&iacute;nea a&eacute;rea que transporte o se comprometa a transportar al pasajero y/o su equipaje en virtud de este contrato o que realice cualquier otro servicio relacionado con dicho transporte a&eacute;reo.</li>
                        <li>1.3 <strong>&ldquo;Convenci&oacute;n de  Varsovia&rdquo;,</strong> significa el Convenio para la Unificaci&oacute;n de ciertas reglas relativas al Transporte A&eacute;reo Internacional de 1929 suscrito en Varsovia y las modificaciones introducidas por el Protocolo de La Haya de 1955 y los Protocolos de Montreal de 1975.</li>
                        <li>1.4 <strong>&ldquo;Convenci&oacute;n de Montreal&rdquo;</strong>, significa el Convenio para la Unificaci&oacute;n de ciertas reglas para el Transporte A&eacute;reo Internacional firmado en Montreal, Canad&aacute;, el 18 de Mayo de 1999.</li>
                        
                      </ul>
                      <h3>Normas generales del transporte a&eacute;reo</h3>
                      <ul><li>2.1 La emisi&oacute;n del Billete de Pasaje da fe de la celebraci&oacute;n y aceptaci&oacute;n de las condiciones del transporte a&eacute;reo y del contrato de transporte suscrito entre el pasajero y el Transportador cuyos nombres aparecen en el Billete. El Billete emitido a nombre del pasajero es nominativo, personal e intransferible, y su emisi&oacute;n podr&aacute; realizarse total o parcialmente a trav&eacute;s de medios f&iacute;sicos o electr&oacute;nicos.</li>
                        <li>2.2 Las escalas convenidas son aquellas mencionadas en el Billete de Pasaje o las que figuren en los itinerarios del Transportador como escalas previstas en la ruta del pasajero. El transporte a realizar en virtud de este contrato por varios transportadores, sucesivamente, se considera como una sola operaci&oacute;n.</li>
                        <li>2.3 Si el Transportador emite un Billete para el transporte en tramos operados por otro transportador a&eacute;reo, el Transportador se encontrar&aacute; actuando s&oacute;lo como agente de este &uacute;ltimo.</li>
                        <li>2.4 Cualquier exenci&oacute;n o limitaci&oacute;n de responsabilidad del Transportador en virtud de la normativa local o internacional vigente, se aplicar&aacute; e ir&aacute; en beneficio de los agentes, empleados y representantes del Transportador y cualquier otra persona o empresa cuya aeronave utilice el Transportador para efectuar el transporte y los agentes, empleados o representantes de dicha persona o empresa.</li>
                        <li>2.5 El Transportador se reserva la facultad irrestricta denegar el transporte en cualquiera de los tramos del itinerario contratado por el pasajero, si la tarifa contratada no se ha pagado en todo o parte, o si el medio de pago utilizado ha sido rechazado, revocado o dejado sin efecto o si se ha obtenido el Billete con infracci&oacute;n a la ley.</li>
                        <li>2.6 De igual manera, el Transportador negar&aacute; el embarque de un pasajero, o dispondr&aacute; su desembarque, si estima que el pasajero pudiera afectar la seguridad del vuelo o de los pasajeros. Especialmente, se negar&aacute; el embarque a cualquier pasajero que presente cualquier actitud o comportamiento que en tierra y/o a bordo de la aeronave constituya <strong>(i) </strong>un acto contrario a las instrucciones impartidas por la tripulaci&oacute;n de la aeronave o de cualquiera de los empleados del Transportador; y/o <strong>(ii)</strong> una conducta contraria  al comportamiento razonable que debe mantener una persona o pasajero; y/o <strong>(iii)</strong> una infracci&oacute;n o delito que en opini&oacute;n del Transportador puedan poner en peligro o riesgo la seguridad de la aeronave o de las personas o bienes en la misma, o que ponga en peligro o comprometa el buen orden y disciplina a bordo; y/o <strong>(iv)</strong> en general, cualquier actitud o comportamiento que en opini&oacute;n del Transportador constituya una negaci&oacute;n al cumplimiento de instrucciones impartidas por la tripulaci&oacute;n y/o actitudes que pudieran poner en peligro o someter a alg&uacute;n riesgo la operaci&oacute;n y/o que perturben el orden y/o la disciplina; y/o <strong>(v)</strong> una muestra o signos de haber ingerido bebidas alcoh&oacute;licas  en exceso y/o alguna sustancia psicotr&oacute;picas; y/o <strong>(vi)</strong> el incumplimiento de cualquier ley o regulaci&oacute;n que aplique o que no acate cualquier requerimiento realizado por la autoridad gubernamental respectiva.</li>
                        <li>2.7 En caso de necesidad (incluyendo pero no limitado a caso fortuito o fuerza mayor), el Transportador, puede cancelar la operaci&oacute;n, hacerse sustituir por otros transportadores y/o cambiar la aeronave destinada a la operaci&oacute;n y/o alterar u omitir paradas indicadas en el Billete si fuere necesario. El Transportador no asume la responsabilidad de garantizar las conexiones contratadas por un pasajero con un tercero.</li>
                        <li>2.8 &nbsp;Todo pasajero que no se presente a viajar o  que llegue tarde para su embarque y/o chequeo en el vuelo correspondiente (check-in), perder&aacute; su Billete, o podr&aacute; revalidarlo para otra fecha, si lo permite la tarifa pagada de acuerdo a lo convenido en el Billete. Cualquier cambio de fecha, origen, destino, itinerario del Billete de Pasaje, as&iacute; como la devoluci&oacute;n del valor pagado por el mismo, queda sujeto a las condiciones y restricciones de la tarifa contratada por el pasajero. Con todo, en caso que el pasajero no efect&uacute;e el viaje y aunque su tarifa no permita devoluci&oacute;n del Billete, podr&aacute; solicitar al Transportador la devoluci&oacute;n de aquellas tasas aeroportuarias que son reembolsables de acuerdo a las normas o limitaciones del respectivo pa&iacute;s. En caso que dichas tasas no hayan sido incluidas en el valor pagado (i.e. fueron recaudadas directamente por el aeropuerto), el pasajero deber&aacute; solicitar su reembolso directamente ante la autoridad aeroportuaria respectiva, sujeto a las limitaciones o normas antes indicadas.</li>
                        <li>2.9 Los vuelos o tramos que componen el itinerario deber&aacute;n volarse en el orden consecutivo indicado. El Transportista, sujeto a las condiciones previstas en la legislaci&oacute;n aplicable, podr&aacute; negar el embarque a un pasajero que no cumpla con el orden del itinerario antes referido o si el pasajero no ha volado alguno de los tramos indicados en su pasaje. El pasajero entiende que si no se vuela alguno de los tramos indicados en el itinerario, &eacute;ste se cancelar&aacute; en su totalidad, sin previo aviso, no procediendo ning&uacute;n tipo de reembolso salvo que las condiciones de la tarifa de su Billete lo permitan. A modo de ejemplo y sin que esta condici&oacute;n se limite a este caso en espec&iacute;fico, si el pasajero no vuela el primer tramo que se especifica en el itinerario (entendi&eacute;ndose como ida), este no podr&aacute; volar ning&uacute;n otro (entendi&eacute;ndose como vuelo de escala o&nbsp; de vuelta).</li>
                        <li>2.10 Se encuentra estrictamente prohibido fumar dentro de la cabina de los aviones del Transportador. El Transportador se reserva el derecho de negar el transporte a cualquier pasajero que no est&eacute; dispuesta a aceptar esta condici&oacute;n.</li>
                        <li>2.11 El Billete es v&aacute;lido por un a&ntilde;o desde la fecha de su emisi&oacute;n o v&aacute;lido hasta la fecha que se indique espec&iacute;ficamente para la tarifa adquirida por el pasajero. Transcurrido dicho plazo, o cualquier otro plazo inferior indicado en las condiciones de la tarifa, el Billete no podr&aacute; ser utilizado.</li>
                        <li>2.12 Es de exclusiva responsabilidad del pasajero informarse, obtener y cumplir con los requisitos para viajar que impone cualquier autoridad y deber&aacute; presentar los documentos de identificaci&oacute;n, &nbsp;de salida, tr&aacute;nsito, entrada, visas y dem&aacute;s exigidos dependiendo del lugar de destino, sin caberle al Transportador responsabilidad alguna por los atrasos o negativas de embarque que sufra el pasajero asociados o derivados del incumplimiento por parte de &eacute;ste &uacute;ltimo de la obligaci&oacute;n anterior. El Transportador negar&aacute; el embarque a aquellos pasajeros que no presenten la documentaci&oacute;n necesaria o cuya identidad no corresponda con la indicada en la Tarjeta de Embarque o <em>Boarding Pass</em>, sin ulterior responsabilidad para el Transportador. El Transportador no ser&aacute; responsable por cualquier informaci&oacute;n o ayuda brindada a un pasajero por cualquier agente, empleado o representante de la l&iacute;nea a&eacute;rea o por terceros, en relaci&oacute;n a la obtenci&oacute;n de dichos documentos y/o el cumplimiento de las leyes y regulaciones aplicables.</li>
                        <li>2.13 Los vuelos operados por  el Transportador entre pa&iacute;ses que forman parte de la Uni&oacute;n Europea (i.e.  vuelos entre Madrid, Espa&ntilde;a y Frankfurt, Alemania) son considerados vuelos <em>No-Schengen</em> (no intracomunitarios) por las autoridades respectivas en dichos pa&iacute;ses, y por lo tanto los pasajeros de estos vuelos pasar&aacute;n obligatoriamente por aduana y por el control de pasaportes en cada uno de ellos, debiendo portar toda la documentaci&oacute;n de identidad, visas, permisos de extranjer&iacute;a y autorizaciones exigidas por los pa&iacute;ses intracomunitarios. Es la obligaci&oacute;n y la responsabilidad de cada pasajero informarse acerca de la documentaci&oacute;n necesaria. El Transportador&nbsp; no ser&aacute; responsable por da&ntilde;os y perjuicios ocasionados por el incumplimiento de dicha obligaci&oacute;n por parte de los pasajeros. Las mismas condiciones rigen para vuelos hacia/desde Canada.</li>
                        <li>2.14 El pasajero deber&aacute; presentarse en el mes&oacute;n de embarque o mes&oacute;n de counter o check-in, a la hora que el Transportador le indique, y si no se hubiera fijado alguna, con suficiente anticipaci&oacute;n para cumplir con los tr&aacute;mites de salida, la que no podr&aacute; ser inferior a 02 horas de antelaci&oacute;n a la fijada para la salida del vuelo.</li>
                        <li>2.15 En el caso de que en un vuelo existan m&aacute;s pasajeros con reserva confirmada que espacios disponibles siempre y cuando hayan efectuado los tr&aacute;mites de check-in con el tiempo m&iacute;nimo requerido, el Transportador pedir&aacute; voluntarios para que cedan su cupo confirmado a cambio de una indemnizaci&oacute;n pactada. Si no se encontraran suficientes voluntarios y se tuviera que denegar el embarque a pasajeros contra su voluntad, estos pasajeros tendr&aacute;n derecho a las prestaciones que establezca la legislaci&oacute;n aplicable.</li>
                        <li>2.16 El Transportador se compromete a hacer todo esfuerzo posible para transportar al pasajero y su equipaje con razonable puntualidad. Las horas que se indican en el Billete de Pasaje o en alguna otra publicaci&oacute;n no est&aacute;n garantizadas en cuanto a su cumplimiento&nbsp; ya que pueden variar por motivos de fuerza mayor sobreviniente, seguridad u otras circunstancias extraordinarias. El Transportador adoptar&aacute; todas las medidas razonables y que sean posibles para evitar demoras en el transporte de sus pasajeros y equipajes. El Transportador no asume la responsabilidad de garantizar las conexiones, por hechos que no le sean imputables.</li>
                        <li>2.17 En algunos casos, el Transportista podr&aacute; requerir notificaci&oacute;n previa para viajes de ciertos pasajeros con alguna discapacidad o enfermedad (i.e. si requieren camilla, oxigeno, etc.), o con necesidad de transporte con un animal de asistencia y/o de soporte emocional. Los pasajeros deben informarse con la antelaci&oacute;n necesaria al viaje, acerca de ciertos requisitos o condiciones especiales del transporte que deber&aacute;n cumplirse y coordinarse antes de la aceptaci&oacute;n de dichos pasajeros para el embarque (i.e. transporte de un menor de edad no acompa&ntilde;ado, infante, etc.), liberando desde ya al Transportador de cualquier responsabilidad en caso que &eacute;ste negare el embarque por no haber cumplido con las normas y/o pol&iacute;ticas de la compa&ntilde;&iacute;a vigentes sobre el particular.</li>
                      </ul>
                      <h3>Normas para el transporte de equipaje</h3>
                      <ul><li>3.1 En cumplimiento de normas internacionales y locales, el Transportador negar&aacute; el transporte como equipaje (de mano o facturado), de aquellos art&iacute;culos y sustancias peligrosas que pueden constituir un riesgo importante para la salud, la seguridad del vuelo o la propiedad, tales como:
                          <ul>
                            <li>Gases (comprimidos, licuados, en soluci&oacute;n o intensamente refrigerados), incluidos los aerosoles, que sean inflamables, t&oacute;xicos o inocuos tales como, butano, ox&iacute;geno, nitr&oacute;geno l&iacute;quido, aerosoles conteniendo gases paralizantes, tubos de relleno para encendedores de gas licuado, etc.</li>
                            <li>Corrosivos, s&oacute;lidos o  l&iacute;quidos, tales como: &aacute;cidos, alcal&iacute;es, mercurio, bater&iacute;as de electr&oacute;lito  l&iacute;quido, etc.</li>
                            <li>Explosivos tales como municiones, fuegos artificiales y bengalas, maletines con dispositivos de alarma, fulminantes para pistolas de juguetes, etc. </li>
                            <li>L&iacute;quidos inflamables  tales como combustibles, pinturas, diluyentes, etc. </li>
                            <li>Materiales radioactivos  cualesquiera que sea su categor&iacute;a. </li>
                            <li>Materiales oxidantes y  per&oacute;xidos org&aacute;nicos, tales como: blanqueadores, abonos, etc. </li>
                            <li>Sustancias t&oacute;xicas e infecciosas tales como: insecticidas, plaguicidas, productos biol&oacute;gicos que contengan g&eacute;rmenes pat&oacute;genos, etc. </li>
                            <li>S&oacute;lidos inflamables  tales como cerillas(f&oacute;sforos) </li>
                            <li>Armas, entendi&eacute;ndose por tales a todo elemento u objeto que est&eacute; hecho, o pueda ser utilizado, para el ataque o defensa, tales como: armas de fuego, armas blancas, gases, elementos de choque el&eacute;ctrico, punzantes, con filo, contundentes, entre las que se pueden incluir porras, hachas y bastones o palos con un peso en su interior o en forma de espig&oacute;n. </li>
                             </ul><li>3.2 Con el objeto de velar por la seguridad del vuelo y cumplir con la normativa vigente, el Transportador y el personal de seguridad del aeropuerto, podr&aacute;n hacer retiro, de los art&iacute;culos y sustancias peligrosas transportados por el Pasajero o en su equipaje de mano, con el objeto de ponerlos a disposici&oacute;n de las autoridades respectivas de acuerdo a las normativas locales aplicables al respecto.</li>
                       
                             <li>3.3 Existe una cantidad limitada de art&iacute;culos medicinales y de tocador que les est&aacute; permitido transportar a los pasajeros. Antes de incluirlos en su equipaje el pasajero deber&aacute; informarse con el personal del Transportador.</li>
                             <li>3.4 Algunos de los art&iacute;culos mencionados anteriormente, pueden ser transportados por v&iacute;a a&eacute;rea bajo ciertas condiciones especiales, amparado por un conocimiento de embarque y bajo una tarifa de carga a&eacute;rea, para lo cual el pasajero deber&aacute; consultar previamente al Transportador.</li>
                             <li>3.5 Se  entender&aacute; por equipaje, solamente los efectos personales necesarios para  efectuar el viaje.</li>
                             <li>3.6 El pasajero no podr&aacute;  facturar el equipaje a transportar en ning&uacute;n otro vuelo que no sea en el que  vaya a abordar.</li>
                             <li>3.7 El Transportador no  registrar&aacute; el equipaje a un destino que no sea el final que figura en el  Billete del pasajero.</li>
                             <li>3.8 El  pasajero deber&aacute; ajustarse al peso, medidas y m&aacute;ximo de equipaje permitido que  se indican en <a href="/index.html">www.lan.com</a> y en el documento Informaci&oacute;n de su Compra referido en el n&uacute;mero 1.1. anterior. La franquicia de equipaje y los pagos o recargos a que quedar&aacute; afecto el exceso de equipaje deber&aacute;n consultarse directamente con la l&iacute;nea a&eacute;rea o en <a href="/index.html">www.lan.com</a>.</li>
                             <li>3.9 El equipaje permitido, puede variar seg&uacute;n condiciones de la tarifa, cabina y ruta, y estar&aacute; expresado en piezas o kilos. El Transportista se reserva el derecho de alterar dichas franquicias y las dimensiones del equipaje. Las condiciones y las tarifas de contrataci&oacute;n ser&aacute;n registradas ante las autoridades aeron&aacute;uticas locales correspondientes en la medida que as&iacute; se exija.</li>
                             <li>3.10 Como precauci&oacute;n y seguridad, s&oacute;lo se permite llevar una pieza de equipaje en cabina, con dimensiones y peso que permitan ubicarlos en los compartimentos superiores del avi&oacute;n o bajo los asientos. El pasajero deber&aacute; ajustarse al peso, medidas y m&aacute;ximo de equipaje de mano permitido que se indican en <a href="/index.html">www.lan.com</a> y en el documento Informaci&oacute;n de su Compra  referido en el n&uacute;mero 1.1. anterior.</li>
                             <li>3.11 El equipaje facturado ser&aacute; entregado al portador del tal&oacute;n de equipaje. En caso de da&ntilde;o al equipaje durante el transporte, deber&aacute; presentarse el reclamo por escrito inmediatamente despu&eacute;s de descubrirse el da&ntilde;o y, a lo sumo, dentro de los 7 d&iacute;as siguientes a la fecha de recibido el equipaje o en el menor tiempo que indique la normativa aplicable en caso de vuelos dom&eacute;sticos. En caso de retraso, el reclamo debe hacerse dentro de los 21 d&iacute;as siguientes a la fecha de entrega del equipaje o en el menor tiempo que indique la normativa aplicable en caso de vuelos dom&eacute;sticos. Para los efectos del p&aacute;rrafo anterior, se entender&aacute; por "retraso", toda demora que se provoque en la recepci&oacute;n del equipaje y que se haya producido por responsabilidad directa del Transportista. </li>
                        </li>
                      </ul>
                      <h3>L&iacute;mites de Responsabilidad</h3>
                      <ul><li>
                        4.1 Si el viaje de un pasajero se inicia y termina dentro de un mismo pa&iacute;s, el servicio de transporte y los l&iacute;mites de responsabilidad estar&aacute;n regulados por la legislaci&oacute;n aplicable de dicho pa&iacute;s. En caso que el viaje de un pasajero tenga el car&aacute;cter de internacional, ser&aacute;n aplicables la Convenci&oacute;n de Varsovia o la Convenci&oacute;n de Montreal o cualquier otra normativa internacional aplicable, seg&uacute;n corresponda. Estas convenciones y normativas regular&aacute;n, cuando corresponda, los l&iacute;mites de responsabilidad del Transportador por muerte o lesiones personales del pasajero y la p&eacute;rdida, retraso o da&ntilde;o del equipaje.</li>
                  
                        <li>
                        4.2 El Transportador declara que en todo transporte regulado por la Convenci&oacute;n de Varsovia, no invocar&aacute; los l&iacute;mites de responsabilidad civil prescritos en su art&iacute;culo 22(1), en los reclamos por da&ntilde;os compensatorios que surjan por muerte o lesiones personales. En este tipo de reclamos el Transportador no har&aacute; uso de las defensas del art&iacute;culo 20(1) de la Convenci&oacute;n de Varsovia, respecto de aquellos reclamos que no superen los 100.000 DEG. Salvo por lo aqu&iacute; previsto, el Transportador podr&aacute; valerse del resto de defensas previstas en la Convenci&oacute;n de Varsovia y de los recursos en contra de terceros que sean procedentes.</li>
                        <li>4.3 Respecto de los art&iacute;culos de alto valor comercial y art&iacute;culos electr&oacute;nicos, el pasajero deber&aacute; transportar estos objetos como equipaje de mano, con el objeto de mantener siempre la custodia de los mismos, ya que el Transportista no responder&aacute; por &eacute;stos m&aacute;s all&aacute; de los l&iacute;mites establecidos en la ley o convenciones internacionales aplicables en caso de ser transportados como equipaje facturado.</li>
                        <li>4.4 La responsabilidad del Transportador en caso de muerte o lesiones corporales del pasajero y/o por la p&eacute;rdida, retraso o da&ntilde;o al equipaje en caso de transporte dentro de dos puntos de un mismo pa&iacute;s, est&aacute; limitada por las leyes y legislaci&oacute;n aplicable del pa&iacute;s correspondiente. Asimismo, la responsabilidad del Transportador en caso de muerte o lesiones corporales del pasajero y/o por la p&eacute;rdida, retraso o da&ntilde;o al equipaje en vuelos internacionales, est&aacute; limitada por los convenios internacionales relativos al transporte a&eacute;reo internacional, ya sea por el Convenci&oacute;n de Varsovia, como por la Convenci&oacute;n de Montreal &nbsp;seg&uacute;n fuere aplicable.</li>
                        <li>Estas condiciones &uacute;nicamente aplican y regulan las rutas del Transportista. Ning&uacute;n agente, empleado o representante del Transportista tiene autoridad para cambiar o renunciar a cualquier disposici&oacute;n de estas condiciones.</li>
                      </ul>
</div>
</div>
</body>
</html>
