<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>T&eacute;rminos y Condiciones</title>
<link rel="stylesheet" href="/es_cl/css/base.css" type="text/css"> 
<link rel="stylesheet" href="/es_cl/css/contenido.css" type="text/css"></head>
<body>
<div id="contenido">
<div id="contenido_popup">
  <h2>Termos e condi&ccedil;&otilde;es</h2>

    

  <h3>1. Defini&ccedil;&otilde;es </h3>
  <ul><li> <strong>1.1 Programa de Passageiro Frequente, Programa LANPASS. Programa ou LANPASS</strong>: &eacute; o Programa de passageiros frequentes de LAN, mediante o qual, s&atilde;o acumulados quil&ocirc;metros voando em todas as rotas da LAN e das Linhas A&eacute;reas Associadas, bem como utilizando os servi&ccedil;os das empresas associadas; tudo sujeito &agrave;s condi&ccedil;&otilde;es e requisitos que detalhamos mais adiante. <br>
    O Programa LANPASS, n&atilde;o implica na exist&ecirc;ncia de um conv&ecirc;nio de nenhuma natureza entre a LAN e o s&oacute;cio, sendo os Pr&ecirc;mios ou Benef&iacute;cios LANPASS, uma mera liberalidade da LAN para seus membros que aderem voluntariamente a ele, para quem os Pr&ecirc;mios ou Benef&iacute;cios LANPASS, salvo pelo indicado neste regulamento, t&ecirc;m um car&aacute;ter gratuito. </li>
    <li><strong>1.2 S&oacute;cio do Programa LANPASS ou s&oacute;cio</strong>: &eacute; a pessoa que cumpre com os requisitos do Programa, que completou e entregou o formul&aacute;rio de inscri&ccedil;&atilde;o atrav&eacute;s de qualquer das formas estabelecidas na cl&aacute;usula 2.2, cuja solicita&ccedil;&atilde;o foi aceita pelo LANPASS e que sua qualidade de s&oacute;cio n&atilde;o haja sido revogada ou deixada sem efeito conforme as normas do presente regulamento. Para o caso das categorias Premium, Premium Silver e Comodoro do LANPASS, seu nome estar&aacute; impresso no cart&atilde;o, com o respectivo n&uacute;mero de s&oacute;cio, que por sua vez &eacute; o n&uacute;mero de sua conta. <br>
      A conta &eacute; unipessoal, reconhecendo um &uacute;nico titular, n&atilde;o admitindo a possibilidade de s&oacute;cios adicionais. </li>
    <li><strong>1.3 Quil&ocirc;metros LANPASS ou simplesmente quil&ocirc;metros</strong>: &eacute; a unidade de medida do Programa LANPASS, e que podem ser utilizados exclusivamente por passagens a&eacute;reas segundo o indicado no cap&iacute;tulo 7 deste Regulamento. </li>
    <li><strong>1.4 Estado da Conta</strong>: &eacute; a informa&ccedil;&atilde;o que periodicamente o LANPASS envia aos s&oacute;cios do Programa LANPASS. Nele se mostra a quantidade de quil&ocirc;metros dispon&iacute;veis, todos os movimentos associados a atividades do Programa LANPASS e qualquer outra informa&ccedil;&atilde;o pertinente do mesmo. O estado de conta, e o dispon&iacute;vel online, constituem a &uacute;nica informa&ccedil;&atilde;o v&aacute;lida sobre os movimentos na conta do s&oacute;cio.</li>
    <li><strong>1.5 Cart&atilde;o de S&oacute;cio ou Cart&atilde;o LANPASS</strong>: &eacute; o cart&atilde;o do s&oacute;cio do Programa LANPASS, para categorias de s&oacute;cio Premium, Premium Silver e Comodoro, emitida e distribu&iacute;da pelo LANPASS, desde que seja obtida a correspondente categoria de s&oacute;cio. </li>
    <li><strong>1.6 Linhas A&eacute;reas Associadas</strong>: s&atilde;o as companhias a&eacute;reas, diferentes da LAN, cujos voos permitem acumular quil&ocirc;metros e/ou desfrutar dos Pr&ecirc;mios ou Benef&iacute;cios ou Benef&iacute;cios do Programa LANPASS, todo ele sujeito &agrave;s condi&ccedil;&otilde;es e requisitos deste regulamento e das companhias a&eacute;reas associadas. </li>
    <li><strong>1.7 Empresas Associadas</strong>: s&atilde;o todas as empresas participantes no Programa LANPASS, exceto as Linhas A&eacute;reas Associadas, cujos servi&ccedil;os permitem acumular quil&ocirc;metros e/ou desfrutar os Pr&ecirc;mios ou Benef&iacute;cios ou Benef&iacute;cios do Programa LANPASS; sujeito &agrave;s condi&ccedil;&otilde;es e requisitos deste regulamento e as citadas empresas assinaladas.</li>
    <li><strong>1.8 Pr&ecirc;mios ou Benef&iacute;cios ou Benef&iacute;cios</strong>: Aquelas passagens que podem ser obtidas utilizando os quil&ocirc;metros LANPASS, segundo descrito no Guia de Benef&iacute;cios do S&oacute;cio. </li>
    <li><strong>1.9 Guia de Benef&iacute;cios do S&oacute;cio</strong>: documento que explica aos s&oacute;cios, os Pr&ecirc;mios ou Benef&iacute;cios ou Benef&iacute;cios que outorga o Programa LANPASS, a forma e requisitos para utilizar ditos Pr&ecirc;mios ou Benef&iacute;cios e Benef&iacute;cios e os termos e condi&ccedil;&otilde;es m&iacute;nimas que devem ser satisfeitos para isso. Esta guia est&aacute; dispon&iacute;vel em www.lan.com. </li>
    <li><strong>1.10 Tabela de Pr&ecirc;mios ou Benef&iacute;cios</strong>: &eacute; a tabela confeccionada pela LAN, que pode ser modificada a qualquer momento, conforme a LAN determinar, que indica os quil&ocirc;metros LANPASS necess&aacute;rios para solicitar um determinado Pr&ecirc;mio ou Beneficio. </li>
    <li><strong>1.11 Certificado de Pr&ecirc;mio</strong>: certificado outorgado pelo LANPASS que d&aacute; conta da entrega de um determinado Pr&ecirc;mio, e que pode ser trocado por uma passagem, segundo o indicado no certificado. </li>
    <li><strong>1.12 Embargo</strong>: per&iacute;odo no qual n&atilde;o se podem utilizar os Pr&ecirc;mios ou Benef&iacute;cios trocados por quil&ocirc;metros LANPASS, seja na LAN, nas Linhas A&eacute;reas Associadas e/ou nas Empresas Associadas. <br>
      Os per&iacute;odos de Embargo de cada entidade ser&atilde;o informados oportunamente, aos s&oacute;cios. </li>
    <li><strong>1.13 Stop Over</strong>: &eacute; uma parada entre o ponto de origem e o ponto de destino, no qual um passageiro pode permanecer, por um determinado tempo, para depois continuar a seu destino final na mesma linha a&eacute;rea. </li>
    <li><strong>1.14 Open Jaw</strong>: voo no qual o ponto de destino da viagem, na ida, &eacute; diferente ao ponto de origem do trecho da volta (exemplo: uma viagem de ida de Santiago a Nova Iorque, voltando de Los Angeles a Santiago). </li>
    <li><strong>1.15 Escala</strong>: &eacute; uma parada t&eacute;cnica entre o ponto de origem e o ponto de destino, no qual o passageiro deve permanecer geralmente no avi&atilde;o ou aeroporto, por um tempo breve, para depois continuar para seu destino final. </li>
    <li><strong>1.16 Conex&atilde;o</strong>: &eacute; uma parada entre o ponto de origem e o ponto de destino, por no m&aacute;ximo de 24 horas, para depois continuar para seu destino final na mesma linha a&eacute;rea. </li>
    <li><strong>1.17 Segmento</strong>: &Eacute; considerado como segmento, um voo direto entre uma cidade e outra, que pode ou n&atilde;o considerar escalas. </li>
    <li><strong>1.18 Upgrade</strong>: &Eacute; a ascens&atilde;o de um passageiro a uma classe de cabina superior, sem haver adquirido o bilhete que corresponda a esta classe. </li></ul>
    <h3> 2. CONDI&Ccedil;&Otilde;ES PARA O INGRESSO </h3>
    <ul><li> <strong>2.1</strong> Podem ser s&oacute;cios do Programa LANPASS, somente pessoas naturais, maiores de 2 anos, n&atilde;o importando sua nacionalidade nem lugar de resid&ecirc;ncia, sempre que (i) cumpram com todos os requisitos do Programa, (ii) completem e entreguem o correspondente formul&aacute;rio de inscri&ccedil;&atilde;o, (iii) que hajam sido expressamente aceitos no Programa LANPASS e que sua qualidade como tal n&atilde;o haja sido cancelada ou deixada sem efeito em conformidade com as normas do presente regulamento. </li>
      <li><strong>2.2</strong> A solicita&ccedil;&atilde;o de ingresso ao Programa LANPASS, ser&aacute; efetuada atrav&eacute;s do correspondente formul&aacute;rio de inscri&ccedil;&atilde;o, dispon&iacute;vel, acessando o site: <a href="/cgi-bin/profile/usuario.cgi">www.lan.com</a>. </li>
      <li><strong>2.3</strong> Recebida a correspondente solicita&ccedil;&atilde;o de incorpora&ccedil;&atilde;o, LANPASS informar&aacute; ao solicitante que foi sido aceito como s&oacute;cio mediante o envio de um correio eletr&ocirc;nico de boas vindas ao endere&ccedil;o de e-mail indicado pelo s&oacute;cio. Caso n&atilde;o haja recebido a mencionada confirma&ccedil;&atilde;o de aceita&ccedil;&atilde;o, o solicitante dever&aacute; chamar ao n&uacute;mero de telefone do Programa LANPASS, para informar-se do resultado de sua solicita&ccedil;&atilde;o. </li>
      <li><strong>2.4</strong> Esse e-mail de boas-vindas entregar&aacute; informa&ccedil;&atilde;o b&aacute;sica do programa, confirmar&aacute; o n&uacute;mero de s&oacute;cio LANPASS do rec&eacute;m inscrito e enviar&aacute; um link para <a href="/index.html">www.lan.com</a> onde o s&oacute;cio poder&aacute; criar a senha de acesso LANPASS.</li>
      <li><strong>2.5</strong> Os quil&ocirc;metros LANPASS acumulados por um solicitante de inscri&ccedil;&atilde;o, antes que seja expressamente aceito como s&oacute;cio, n&atilde;o poder&atilde;o ser trocados por Pr&ecirc;mios a menos que a pessoa seja rapidamente aceita como s&oacute;cio. </li>
      <li><strong>2.6</strong> Os dados apresentados na solicita&ccedil;&atilde;o de incorpora&ccedil;&atilde;o, bem como sua atualiza&ccedil;&atilde;o, s&atilde;o de exclusiva responsabilidade do s&oacute;cio. </li>
      <li><strong>2.7</strong> O endere&ccedil;o de correio especificado pelo s&oacute;cio n&atilde;o pode ser uma caixa postal nem outro tipo de endere&ccedil;o que n&atilde;o tenha cobertura por parte dos correios. A LANPASS n&atilde;o se faz respons&aacute;vel pela n&atilde;o entrega de correspond&ecirc;ncia neste tipo de endere&ccedil;os. </li>
      <li><strong>2.8 </strong>Todo cart&atilde;o LANPASS, &eacute; estritamente pessoal e intransfer&iacute;vel. O uso inadequado, impr&oacute;prio ou em desacordo com as condi&ccedil;&otilde;es e termos aqui estabelecidos de qualquer cart&atilde;o LANPASS, poder&aacute; significar a elimina&ccedil;&atilde;o do Programa LANPASS, com o correspondente cancelamento de todos os quil&ocirc;metros LANPASS acumulados, sem preju&iacute;zo das a&ccedil;&otilde;es legais a que haja lugar. </li>
      <li><strong>2.9 </strong>O solicitante e/ou o s&oacute;cio reconhecem e aceitam ser os &uacute;nicos respons&aacute;veis de qualquer soma de dinheiro, seja em forma de impostos, taxas, diretos ou outra qualquer, que deva ser paga a qualquer pessoa, natural ou jur&iacute;dica, p&uacute;blica ou privada, como resultado do ac&uacute;mulo ou uso dos quil&ocirc;metros LANPASS ou consequ&ecirc;ncia de sua admiss&atilde;o no Programa LANPASS, ou do uso de qualquer Pr&ecirc;mio o Benef&iacute;cio do mesmo. </li>
      <li><strong>2.10</strong> Qualquer altera&ccedil;&atilde;o dos dados informados dever&aacute; ser solicitada por escrito, com a correspondente assinatura do S&oacute;cio, atrav&eacute;s do call-center uma vez validada a identidade do s&oacute;cio, ou atrav&eacute;s da p&aacute;gina web do Programa. N&atilde;o ser&atilde;o aceitas mudan&ccedil;as solicitadas em forma verbal, salvo para mudar o domic&iacute;lio e o n&uacute;mero de telefone. Para realizar as respectivas mudan&ccedil;as, o s&oacute;cio pode enviar uma carta ao programa LANPASS ou via Internet. </li>
      <li><strong>2.11</strong> Somente ser&aacute; permitida uma conta por s&oacute;cio. No caso de existir duas ou mais contas, as mais recentes ser&atilde;o canceladas. Todos os quil&ocirc;metros LANPASS acumulados nas contas canceladas ser&atilde;o traspassados &agrave; conta original, sempre e quando esses quil&ocirc;metros n&atilde;o hajam sido acumulados em ambas as contas. </li>
      <li><strong>2.12</strong> N&atilde;o &eacute; permitido o traspasso de quil&ocirc;metros LANPASS entre as contas do Programa LANPASS, como tamb&eacute;m entre as contas do programa LANPASS e contas das Linhas A&eacute;reas Associadas e/ou Empresas Associadas.<br>
      Est&aacute; estritamente proibida a venda, cess&atilde;o ou transfer&ecirc;ncia de quil&ocirc;metros LANPASS ou de pr&ecirc;mios associados aos mesmos por qualquer meio ou canal, incluindo Internet.</li>
      <li><strong>2.13</strong> Para efeitos de solicitar um Pr&ecirc;mio, n&atilde;o poder&atilde;o ser somados quil&ocirc;metros LANPASS de diferentes contas do Programa LANPASS, nem de contas das Linhas A&eacute;reas Associadas e/ou das Empresas Associadas. </li>
      <li><strong>2.14</strong> Pelo fato de completar o formul&aacute;rio de inscri&ccedil;&atilde;o, o s&oacute;cio aceita receber em seu endere&ccedil;o de correio eletr&ocirc;nico informa&ccedil;&atilde;o do Programa, e outras comunica&ccedil;&otilde;es que a LAN envie periodicamente, seja relacionada ou n&atilde;o com o Programa LANPASS. </li>
      <li><strong>2.15</strong> A forma e periodicidade de envio dos Estados de Conta, Informa&ccedil;&atilde;o de Benef&iacute;cios ou de s&oacute;cios, e demais comunica&ccedil;&otilde;es, ser&aacute; determinada livremente pela LAN, utilizando meios eletr&ocirc;nicos (e-mail). </li>
      <li><strong>2.16</strong> Adicionalmente o estabelecido no par&aacute;grafo anterior, pelo fato de completar o formul&aacute;rio de inscri&ccedil;&atilde;o, o candidato ao programa ou o s&oacute;cio, aceita que a LAN possa dispor livremente dos dados incorporados no referido formul&aacute;rio, seja em benef&iacute;cio do Programa, da LAN ou de terceiros.<br>
      &Eacute; condi&ccedil;&atilde;o essencial para a participa&ccedil;&atilde;o no programa LANPASS que o ac&uacute;mulo de quil&ocirc;metros seja realizado de acordo aos termos e condi&ccedil;&otilde;es deste programa e em pleno cumprimento da normativa que seja aplic&aacute;vel.</li></ul>
      <h3> 3. TERMOS DA PARTICIPA&Ccedil;&Atilde;O NO PROGRAMA </h3>
      <ul><li> <strong>3.1 </strong>A participa&ccedil;&atilde;o de um s&oacute;cio no Programa LANPASS, terminar&aacute; nos seguintes casos: </li>
        <li><strong>3.1.1</strong> Se o s&oacute;cio deixa de cumprir qualquer dos termos e condi&ccedil;&otilde;es aqui referidos, ou se o uso do programa LANPASS ou o ac&uacute;mulo de quil&ocirc;metros for realizado com infra&ccedil;&atilde;o &agrave; lei ou normativa aplic&aacute;veis. </li>
        <li><strong>3.1.2</strong> Se o s&oacute;cio, propositalmente, entrega qualquer informa&ccedil;&atilde;o incorreta ou err&ocirc;nea (incluindo informa&ccedil;&atilde;o sobre voos), seja na solicita&ccedil;&atilde;o de incorpora&ccedil;&atilde;o ou no momento de solicitar os Pr&ecirc;mios correspondentes. </li>
        <li><strong>3.1.3</strong> Se o s&oacute;cio n&atilde;o cumpre com as condi&ccedil;&otilde;es do contrato de transporte de passageiros (que se aplicam a todos os passageiros). </li>
        <li><strong>3.1.4</strong> Se o s&oacute;cio faz um uso inadequado ou impr&oacute;prio dos Pr&ecirc;mios e/ou Benef&iacute;cios entregues. </li>
        <li><strong>3.1.5</strong> Se o s&oacute;cio tem uma d&iacute;vida vencida da qual a LAN, ou algumas de suas companhias filiais ou relacionadas, &eacute; credora, ou que existam ind&iacute;cios ou suposi&ccedil;&otilde;es da participa&ccedil;&atilde;o do s&oacute;cio em delitos cometidos contra as mencionadas sociedades, tal como o giro doloso de cheques, ou outros. </li>
        <li><strong>3.1.6</strong> Por peti&ccedil;&atilde;o expressa do s&oacute;cio, o que pode ser feito a qualquer momento, por escrito, e no caso de s&oacute;cios Elite, anexando seu cart&atilde;o de s&oacute;cio cortado pela metade. </li>
        <li><strong>3.1.7</strong> Por falecimento do s&oacute;cio. </li>
        <li><strong>3.1.8</strong> Se o Programa LANPASS terminasse por qualquer raz&atilde;o. </li>
        <li><strong>3.1.9</strong> Por determina&ccedil;&atilde;o da LANPASS, em qualquer momento, dando um aviso pr&eacute;vio. </li>
        <li><strong>3.2. </strong>Em caso de t&eacute;rmino da participa&ccedil;&atilde;o no Programa LANPASS ou de t&eacute;rmino do mesmo, todos os quil&ocirc;metros acumulados ser&atilde;o cancelados e n&atilde;o poder&atilde;o ser utilizados sob nenhum conceito, nem poder&atilde;o ser trocados por bilhetes e/ou dinheiro. </li></ul>
        <h3> 4. SUSPENS&Atilde;O DOS DIREITOS DO S&Oacute;CIO </h3>
        <ul><li> <strong>4.1 </strong>A LANPASS poder&aacute; suspender temporalmente os direitos e benef&iacute;cios do s&oacute;cio, sem que este perca a qualidade de tal, isto &eacute;, o s&oacute;cio continuar&aacute; acumulando seus quil&ocirc;metros, mas ele n&atilde;o poder&aacute; trocar Pr&ecirc;mios nem solicitar nenhum beneficio pr&oacute;prio do Programa, enquanto o LANPASS n&atilde;o lhe restitua sua qualidade de s&oacute;cio pleno. </li>
          <li><strong>4.2</strong> O direito de suspens&atilde;o poder&aacute; ser exercido pela LANPASS nos casos em que o s&oacute;cio mantenha uma d&iacute;vida vencida com a LAN ou algumas de suas companhias filiais ou relacionadas, ou bem que existam ind&iacute;cios ou suposi&ccedil;&otilde;es da participa&ccedil;&atilde;o do s&oacute;cio em delitos cometidos contra as citadas sociedades, tal como o giro doloso de cheques, ou outros. </li>
          <li><strong>4.3</strong> O anteriormente mencionado &eacute; sem preju&iacute;zo que o s&oacute;cio perca a qualidade de tal, conforme o disposto no presente regulamento. </li></ul>
          <h3> 5. CART&Atilde;O DE S&Oacute;CIO OU CART&Atilde;O LANPASS </h3>
          <ul><li> <strong>5.1</strong> O cart&atilde;o de s&oacute;cio LANPASS tem dura&ccedil;&atilde;o indefinida. Por sua parte, os cart&otilde;es de s&oacute;cio LANPASS Premium, LANPASS Premium Silver, e LANPASS Comodoro possuem a dura&ccedil;&atilde;o da correspondente categoria, tal como se indica nos detalhes do Programa em <a href="/index.html">www.lan.com</a>, podendo ser renovado de acordo ao estabelecido no par&aacute;grafo 6. Para todos os efeitos deste regulamento, "ano calend&aacute;rio" compreende desde o dia 1 de janeiro at&eacute; o dia 31 de dezembro de cada ano. </li>
            <li><strong>5.2</strong> Os cart&otilde;es emitidos pelas Empresas Associadas ser&atilde;o v&aacute;lidos de acordo aos termos e condi&ccedil;&otilde;es da respectiva empresa, sem preju&iacute;zo de estarem sempre sujeitas ao estabelecido na presente regulamenta&ccedil;&atilde;o, no que seja pertinente. </li>
            <li><strong>5.3</strong> A pessoa cujo nome figura no cart&atilde;o de s&oacute;cio &eacute; a &uacute;nica que tem direito a utiliz&aacute;-lo, para qualquer finalidade. </li>
            <li><strong>5.4</strong> O cart&atilde;o de s&oacute;cio n&atilde;o &eacute; um cart&atilde;o de cr&eacute;dito nem um documento que acredite identidade, raz&atilde;o pela qual n&atilde;o lhe outorga mais direitos que os indicados na presente regulamenta&ccedil;&atilde;o. </li>
            <li><strong>5.5</strong> Todos os cart&otilde;es de s&oacute;cio s&atilde;o de exclusiva propriedade da LANPASS. </li>
            <li><strong>5.6</strong> O s&oacute;cio deve comunicar, imediatamente, via telefone, a perda ou roubo de seu cart&atilde;o de s&oacute;cio. Avaliados os antecedentes do caso por parte da LANPASS, um novo cart&atilde;o poder&aacute; ser emitido num prazo de at&eacute; 30 dias. </li></ul>
            <h3> 6. CATEGORIA DE S&Oacute;CIO </h3>
            <ul><li> <strong>6.1</strong> O Programa LANPASS possui quatro categorias de s&oacute;cio: (a) LANPASS, (b) Premium, (c) Premium Silver e (d) Comodoro. Somente as tr&ecirc;s &uacute;ltimas possuem cart&atilde;o de s&oacute;cio associada. </li>
              <li><strong>6.2</strong> As diferentes categorias de s&oacute;cio est&atilde;o determinadas pelo cumprimento dos requisitos estabelecidos para integrar cada categoria, que s&atilde;o descritos na sess&atilde;o LANPASS da p&aacute;gina web <a href="/index.html">www.lan.com</a>. </li>
              <li><strong>6.3</strong> A categoria que corresponde a um s&oacute;cio est&aacute; determinada pelo: n&uacute;mero de quil&ocirc;metros voados em tarifas que permitam o ac&uacute;mulo de quil&ocirc;metros na LAN ou qualquer das Linhas A&eacute;reas Associadas &agrave; <strong>one</strong>world, al&eacute;m das bonifica&ccedil;&otilde;es por classe de servi&ccedil;o de voos LAN (classe executiva) a que se haja tornado merecedor o s&oacute;cio. O anterior, com a condi&ccedil;&atilde;o de ter um m&iacute;nimo de quatro segmentos voados na LAN. Ou, pela quantidade de segmentos voados na LAN em tarifas que permitam o ac&uacute;mulo de quil&ocirc;metros. Qualquer das condi&ccedil;&otilde;es anteriores deve ser cumprida em um ano calend&aacute;rio. <br>
                As categorias Comodoro e Premium Silver tamb&eacute;m s&atilde;o determinadas por uma quantidade menor de km dos quais deve haver uma quantidade de segmentos voados na LAN em Classe Executiva em voos de longo alcance. O detalhe dos voos definidos como de longo alcance e a quantidade de km requeridos para cada categoria s&atilde;o detalhados em www.lan.com. </li>
              <li><strong>6.4</strong> N&atilde;o ser&atilde;o contabilizados para determinar uma categoria de s&oacute;cio os quil&ocirc;metros LANPASS acumulados nas Empresas Associadas e nas Linhas A&eacute;reas Associadas (exceto que se indique expressamente o contr&aacute;rio). </li>
              <li><strong>6.5</strong> Tamb&eacute;m n&atilde;o ser&atilde;o contabilizados para determinar uma categoria de s&oacute;cio, os trechos voados fazendo uso de uma passagem pr&ecirc;mio ou qualquer outra passagem que n&atilde;o qualifique para acumular quil&ocirc;metros LANPASS. </li>
              <li><strong>6.6 </strong>A perman&ecirc;ncia de um s&oacute;cio em uma determinada categoria corresponde ao ano seguinte e ao que resta do ano no qual cumpriu os requisitos suficientes para qualificar na mencionada categoria. </li>
              <li><strong>6.7</strong> A LANPASS poder&aacute;, discretamente, manter ou subir a categoria de um s&oacute;cio, ainda quando n&atilde;o haja cumprido com algum dos requisitos exigidos para isso, mas nunca poder&aacute; baix&aacute;-lo de categoria, na medida em que cumpra com os requisitos estabelecidos para permanecer nela. </li>
              <li><strong>6.8</strong> Se um s&oacute;cio n&atilde;o cumpre com os requerimentos para renovar sua categoria, pertencer&aacute; no ano seguinte, &agrave; categoria anterior &agrave; que pertencia, ainda que n&atilde;o cumpra com os requisitos para qualificar a esta. </li>
              <li><strong>6.9</strong> A partir do ano 2004, as renova&ccedil;&otilde;es ser&atilde;o efetuadas nos dias 31 de mar&ccedil;o de cada ano, considerando os requisitos cumpridos pelo s&oacute;cio no ano calend&aacute;rio anterior. </li>
              <li><strong>6.10</strong> As mudan&ccedil;as na categoria do s&oacute;cio, n&atilde;o afetar&atilde;o o saldo de quil&ocirc;metros que podem ser trocados por Pr&ecirc;mios e vice-versa. </li></ul>
              <h3> 7. QUIL&Ocirc;METROS </h3>
              <ul><li> <strong>7.1</strong> A unidade de medida do Programa LANPASS s&atilde;o os quil&ocirc;metros.</li>
                <li><strong>7.2</strong> Os quil&ocirc;metros apresentam as seguintes caracter&iacute;sticas e est&atilde;o sujeitos aos seguintes termos: </li>
                <li><strong>7.2.1</strong> N&atilde;o possuem nenhum valor comercial, n&atilde;o sendo negoci&aacute;veis nem podendo ser trocados por dinheiro nem por nenhum outro bem.</li>
                <li><strong>7.2.2</strong> S&atilde;o intransfer&iacute;veis, tanto a t&iacute;tulo gratuito como a t&iacute;tulo oneroso. <strong>7.2.3</strong> N&atilde;o s&atilde;o transmiss&iacute;veis. Na eventualidade da morte do s&oacute;cio, a conta e os quil&ocirc;metros nela acumulados ser&atilde;o cancelados. </li>
                <li><strong>7.2.4</strong> N&atilde;o s&atilde;o embarg&aacute;veis, por tratar-se de direitos cujo exerc&iacute;cio &eacute; inteiramente pessoal. </li>
                <li><strong>7.2.5</strong> N&atilde;o s&atilde;o objeto de disputa legal nem de medida judicial alguma, e s&oacute; pertencem ao s&oacute;cio titular da conta, como um direito pessoal. </li>
                <li><strong>7.2.6</strong> Os Pr&ecirc;mios trocados pelo s&oacute;cio n&atilde;o ser&atilde;o reembols&aacute;veis, caso o s&oacute;cio solicite a devolu&ccedil;&atilde;o de um Pr&ecirc;mio emitido, dever&aacute; pagar uma taxa em quil&ocirc;metros. A taxa &eacute; vari&aacute;vel dependendo do Pr&ecirc;mio e de acordo &agrave; informa&ccedil;&atilde;o publicada em www.lan.com. A devolu&ccedil;&atilde;o de um pr&ecirc;mio requer que a passagem emitida esteja vigente (a vig&ecirc;ncia come&ccedil;a a reger a partir da data da emiss&atilde;o do bilhete), que seja antes da sa&iacute;da do v&ocirc;o e, sem nenhum trecho voado, exceto para Upgrades em Oneworld e que os quil&ocirc;metros utilizados para a sua emiss&atilde;o n&atilde;o estejam vencidos no momento de solicitar a devolu&ccedil;&atilde;o. </li>
                <li><strong>7.2.7 </strong>Os Pr&ecirc;mios n&atilde;o s&atilde;o endoss&aacute;veis, raz&atilde;o pela qual n&atilde;o podem ser utilizados em outras companhias que n&atilde;o sejam a LAN ou as Linhas A&eacute;reas Associadas, nem por outras pessoas que as designadas pelo s&oacute;cio, segundo o Pr&ecirc;mio trocado. Emitida uma passagem pr&ecirc;mio, est&aacute; poder&aacute; ser utilizada unicamente na linha a&eacute;rea nela indicada. 
                </li></ul>
                <h3> 8. AC&Uacute;MULO DE QUIL&Ocirc;METROS </h3>
                <ul><li><strong>8.1</strong> Ser&atilde;o creditados os quil&ocirc;metros quando um s&oacute;cio viaje em voos de LAN ou das Linhas A&eacute;reas Associadas, sempre que se trate de voos operados por esta (s), ou que utilize os servi&ccedil;os habilitados de qualquer das empresas associadas. Caso o s&oacute;cio perten&ccedil;a ao Programa LANPASS e ao mesmo tempo ao Programa de Passageiro Frequente da linha a&eacute;rea ou empresa associada, os quil&ocirc;metros somente poder&atilde;o ser creditados em uma das contas, escolha do s&oacute;cio. Em nenhum caso os quil&ocirc;metros poder&atilde;o ser creditados em mais de uma conta. O s&oacute;cio dever&aacute; informar seu n&uacute;mero de s&oacute;cio, que dever&aacute; aparecer no cart&atilde;o de embarque.<br>
                  Para efeitos de ac&uacute;mulo de quilometragem, todo voo operado por qualquer linha a&eacute;rea, mas que utilize, por qualquer raz&atilde;o, c&oacute;digo de LAN em sua passagem, ser&aacute; considerado como voo v&aacute;lido para acumular quil&ocirc;metros e para qualificar nas categorias Premium, Premium Silver e Comodoro, sempre que tenham sido realizados em tarifas, rotas e datas que permitam o ac&uacute;mulo de quil&ocirc;metros LANPASS.</li>
                  <li><strong>8.2</strong> Em aten&ccedil;&atilde;o &agrave;s restri&ccedil;&otilde;es estabelecidas pelas Linhas A&eacute;reas Associadas, a forma e a quantidade de quil&ocirc;metros a acumular por voos realizados nestas, n&atilde;o coincidir&atilde;o necessariamente com as estabelecidas por LAN para seus voos e depender&atilde;o das restri&ccedil;&otilde;es da tarifa paga ou condi&ccedil;&otilde;es fixadas para dita Linha A&eacute;rea Associada, podendo haver tarifas ou voos que permitam acumular somente uma porcentagem da dist&acirc;ncia voada ou outras restri&ccedil;&otilde;es. Corresponder&aacute; ao s&oacute;cio averiguar os quil&ocirc;metros a acumular por voos que realize com Linhas A&eacute;reas Associadas.</li>
                  <li><strong>8.3</strong> Os voos de terceiras companhias a&eacute;reas operados por LAN, n&atilde;o acumulam quil&ocirc;metros. N&atilde;o acumulam quil&ocirc;metros tamb&eacute;m aqueles voos anunciado pelas linhas <strong>one</strong>world e operados por companhias terceiras.</li>
                  <li><strong>8.4</strong> Somente poder&atilde;o ser creditados quil&ocirc;metros voados sob pr&eacute;via inscri&ccedil;&atilde;o, sempre que os voos tenham sido realizados pela LAN e n&atilde;o mais de dois meses antes da data de inscri&ccedil;&atilde;o.</li>
                  <li><strong>8.5</strong> Os quil&ocirc;metros s&atilde;o contabilizados na conta do s&oacute;cio somente uma vez realizada a viagem e pago o respectivo bilhete. Portanto, n&atilde;o ser&atilde;o acumulados quil&ocirc;metros por bilhetes adquiridos mas n&atilde;o voados ou n&atilde;o pagos. Por este motivo, o s&oacute;cio dever&aacute; manter, e entregar, caso seja requerido, documentos que assegurem o voo realizado (bilhete ou cart&atilde;o de embarque).</li>
                  <li><strong>8.6</strong> Os quil&ocirc;metros gerados por servi&ccedil;os prestados por Linhas A&eacute;reas Associadas ou Empresas Associadas, ser&atilde;o contabilizados na conta do s&oacute;cio, somente quando a respectiva linha a&eacute;rea ou empresa, enviem a informa&ccedil;&atilde;o requerida por LAN para tal contabiliza&ccedil;&atilde;o, a qual, em geral, n&atilde;o ser&aacute; realizada depois de 30 dias desde que se prestou o respectivo servi&ccedil;o ao s&oacute;cio.</li>
                  <li><strong>8.7</strong> Os quil&ocirc;metros acumulados correspondem &agrave; dist&acirc;ncia entre o ponto de origem e o de destino do voo, dist&acirc;ncias que s&atilde;o entregues pela IATA. <br>
                    Sem preju&iacute;zo do anterior, e como medida temporal ou permanente, LANPASS poder&aacute; bonificar a dist&acirc;ncia entre o ponto de origem e o ponto de destino com quilometragem adicional.</li>
                  <li><strong>8.8 </strong>Os quil&ocirc;metros acumulados por voo em LAN t&ecirc;m uma vig&ecirc;ncia de 36 meses corridos, contados a partir da data do voo. Em todo caso, os quil&ocirc;metros vencer&atilde;o, efetivamente, no &uacute;ltimo dia do m&ecirc;s correspondente ao m&ecirc;s de vencimento.<br>
                  Os quil&ocirc;metros acumulados por voos nas Linhas A&eacute;reas Associadas, ao utilizar qualquer dos servi&ccedil;os das empresas associadas ou b&ocirc;nus promocionais, t&ecirc;m vig&ecirc;ncia de 3 anos calend&aacute;rio, o que significa que vencem no dia 31 de dezembro do terceiro ano no qual foram acumulados.<br>
                  Ent&atilde;o, cada vez que o passageiro voe na LAN e acumule 1 ou mais quil&ocirc;metros por esse voo, todos os quil&ocirc;metros acumulados vigentes em sua conta at&eacute; a data do referido voo automaticamente se renovam, passando a ter uma vig&ecirc;ncia de 36 meses corridos, contados a partir da data do mencionado voo e vencer&atilde;o, efetivamente, no &uacute;ltimo dia do trig&eacute;simo sexto m&ecirc;s.<br>
                  Em todo caso, os quil&ocirc;metros acumulados antes de 10 de maio de 1998 ser&atilde;o v&aacute;lidos at&eacute; o dia 31 de dezembro do terceiro ano em que os quil&ocirc;metros foram efetivamente voados segundo as regras indicadas nos par&aacute;grafos anteriores, qualquer que seja a que mas beneficie o s&oacute;cio.<br>
                  N&atilde;o &eacute; responsabilidade de LANPASS informar a data de expira&ccedil;&atilde;o dos quil&ocirc;metros, conforme as regras de expira&ccedil;&atilde;o de quil&ocirc;metros que aqui se assinalam.</li>
                  <li><strong>8.9</strong> Todos os quil&ocirc;metros que aparecem no estado de conta podem ser trocados por Pr&ecirc;mios. Os quil&ocirc;metros voados na LAN e linhas a&eacute;reas <strong>one</strong>world, incluindo os b&ocirc;nus por classe de servi&ccedil;o na LAN, ser&atilde;o utilizados tamb&eacute;m para determinar a categoria de s&oacute;cio LANPASS.</li>
                  <li><strong>8.10 </strong>Os bilhetes pr&ecirc;mio do programa LANPASS voados na LAN ou em qualquer das Linhas A&eacute;reas Associadas, bem como os pr&ecirc;mios correspondentes aos servi&ccedil;os das empresas associadas, n&atilde;o acumulam quilometragem. <br>
                  N&atilde;o acumulam quilometragem as passagens emitidos com tarifas reduzidas da ind&uacute;stria do turismo, voos charter, passagens para empregados de linhas a&eacute;reas, descontos governamentais, passagens gratuitas ou qualquer outra passagem que n&atilde;o indique uma tarifa publicada. A exclus&atilde;o de outros tipos de passagens fica &agrave; exclusiva discri&ccedil;&atilde;o de LANPASS, que ser&aacute; informado oportuna e adequadamente aos s&oacute;cios.</li>
                  <li><strong>8.11</strong> As passagens endossadas a outras companhias pela LAN acumular&atilde;o a quilometragem equivalente, como se houvesse sido efetivamente voadas em LAN, s&oacute; em caso de tratar-se de um evento involunt&aacute;rio. As passagens endossadas pelas linhas a&eacute;reas <strong>one</strong>world ou associadas a terceiros n&atilde;o acumulam quil&ocirc;metros.</li>
                  <li><strong>8.12</strong> Em caso de um Upgrade de classe obtido como pr&ecirc;mio ou cortesia pela LAN ou de qualquer das Linhas A&eacute;reas Associadas ou Empresas Associadas, somente ser&atilde;o acumulados na conta os quil&ocirc;metros correspondentes &agrave; classe paga pelo s&oacute;cio, e n&atilde;o os correspondentes &agrave; classe &agrave; qual foi promovido.</li>
                  <li><strong>8.13</strong> Ser&aacute; de exclusiva responsabilidade do s&oacute;cio verificar que os quil&ocirc;metros correspondentes a seus voos na LAN e/ou nas Linhas A&eacute;reas Associadas, bem como os provenientes de servi&ccedil;os das Empresas Associadas, est&atilde;o creditados corretamente em sua conta.<br>
                  Para isto, o s&oacute;cio dever&aacute; guardar todos os seus documentos de voo (cart&otilde;es de embarque, recibo do passageiro, passagem do voo) bem como, os originais de faturas ou contratos, a fim de poder reclamar um cr&eacute;dito retroativo de quil&ocirc;metros. Em nenhum caso poder&atilde;o acumular quil&ocirc;metros depois de um (1) ano de ocorrido o voo ou ato que os geraram, salvo que empresas associadas o permitam para quil&ocirc;metros provenientes delas mesmas.<br>
                  As solicita&ccedil;&otilde;es para creditar quil&ocirc;metros de maneira retroativa originadas por servi&ccedil;os prestados pelas Linhas A&eacute;reas Associadas, s&oacute; ser&atilde;o processadas se o s&oacute;cio entregar seus documentos de voo (cart&otilde;es de embarque e recibo do passageiro da passagem a&eacute;rea). Em caso de n&atilde;o entregar documentos que respaldem que o voo foi realizado, a solicita&ccedil;&atilde;o n&atilde;o ser&aacute; processada.</li>
                  <li><strong>8.14</strong> LANPASS se reserva o direito de realizar uma auditoria na conta de um s&oacute;cio em qualquer momento e sem pr&eacute;vio aviso, com a finalidade de assegurar o cumprimento destes termos e condi&ccedil;&otilde;es. LANPASS poder&aacute; descontar os quil&ocirc;metros creditados indevidamente a um s&oacute;cio, bem como demorar a entrega de Pr&ecirc;mios ou certificados enquanto se resolve qualquer discrep&acirc;ncia, devendo manter informado ao s&oacute;cio.</li>
                  <li><strong>8.15</strong> Caso as passagens que habilitam a acumular quil&ocirc;metros LANPASS sejam adquiridas a cr&eacute;dito, ou seu pagamento esteja diferido no tempo, o s&oacute;cio poder&aacute; trocar um Pr&ecirc;mio utilizando os quil&ocirc;metros, sejam os correspondentes &agrave; passagem adquirida ou qualquer outro, somente na medida que as respectivas passagens estejam sendo pagas na forma e no tempo em que se tenha acordado, no momento de comprar a passagem.</li>
                  <li><strong>8.16</strong> Ser&aacute; de exclusiva responsabilidade do s&oacute;cio dar cumprimento &agrave; lei e regulamenta&ccedil;&atilde;o que possa ser aplic&aacute;vel para efeitos de sua participa&ccedil;&atilde;o no Programa LANPASS e o ac&uacute;mulo de quil&ocirc;metros, em especial, respeito a aqueles s&oacute;cios que tenham a qualidade de funcion&aacute;rios p&uacute;blicos. 
                  </li></ul>
                  <h3>9. TROCA FLEX&Iacute;VEL LANPASS </h3>
                  <ul><li><strong>9.1</strong> Para solicitar um Pr&ecirc;mio, o S&oacute;cio deve ter um n&uacute;mero de S&oacute;cio vigente e a quantidade de quil&ocirc;metros necess&aacute;ria para trocar o Pr&ecirc;mio solicitado. A quantidade de quil&ocirc;metros necess&aacute;ria para aceder a um Pr&ecirc;mio &eacute; a indicada na Tabela de Pr&ecirc;mios vigente na data em que se apresente a solicita&ccedil;&atilde;o.</li>
                    <li><strong>9.2</strong> Os quil&ocirc;metros necess&aacute;rios para cobrar um Pr&ecirc;mio variam dependendo do tipo de Pr&ecirc;mio e da cabina cotizada. A cabina Economy possui 3 n&iacute;veis de Pr&ecirc;mios: Classic, Plus e Full (ordenados de menor a maior quantidade de quil&ocirc;metros requeridos para cobr&aacute;-los). A cabina Premium Bussiness tem um s&oacute; n&iacute;vel de Pr&ecirc;mios.</li>
                    <li><strong>9.3</strong> S&oacute; podem ser solicitados Upgrade para cabina Premium Bussiness.</li>
                    <li><strong>9.4</strong> Para cada tipo de Pr&ecirc;mio h&aacute; disponibilidade limitada de assentos.</li>
                    <li><strong>9.5</strong> Para solicitar um Pr&ecirc;mio, o S&oacute;cio pode chamar ao Call Center de LAN (op&ccedil;&atilde;o LANPASS), ingressar &agrave; p&aacute;gina web <a href="/index.html">www.lan.com</a>, ou dirigir-se aos Escrit&oacute;rios de LAN o ag&ecirc;ncias de viagem. Em todos os casos &eacute; necess&aacute;rio mostrar um documento que acredite a identidade do s&oacute;cio. Em Lan.com se necessita usu&aacute;rio e senha.</li>
                    <li><strong>9.6</strong> Para a troca de Pr&ecirc;mios atrav&eacute;s de Call Center LAN (op&ccedil;&atilde;o LANPASS ou Escrit&oacute;rios LAN ou ag&ecirc;ncias de viagem, o S&oacute;cio deve pagar um cargo por emiss&atilde;o (Service Fee LANPASS) para cada passagem emitido. Se o Pr&ecirc;mio &eacute; trocado atrav&eacute;s de <a href="/lanpass/canjee_kms/emision_service_fee.html#tabla2">www.lan.com</a>, n&atilde;o &eacute; aplicado o cargo por emiss&atilde;o. O Service Fee LANPASS &eacute; adicional &agrave;s taxas de embarque e impostos aplic&aacute;veis e variar&aacute; segundo o tipo de Pr&ecirc;mio Trocado, segundo a Tabela de Pr&ecirc;mios Publicada em <a href="/lanpass/canjee_kms/emision_service_fee.html#tabla2">www.lan.com</a>.</li>
                    <li><strong>9.7</strong> A solicita&ccedil;&atilde;o de um Pr&ecirc;mio pode ser feita por qualquer pessoa, apresentando um poder simples devidamente assinado pelo S&oacute;cio, indicando: nome completo do S&oacute;cio, n&uacute;mero de conta e/ou n&uacute;mero de R.U.T., e determina&ccedil;&atilde;o do Pr&ecirc;mio que solicita. Deve anexar, al&eacute;m disso, fotoc&oacute;pia simples de um documento que acredite a identidade do S&oacute;cio (c&eacute;dula de identidade, equivalente ou passaporte).</li>
                    <li><strong>9.8</strong> Os Pr&ecirc;mios t&ecirc;m um ano de vig&ecirc;ncia (12 meses), a partir da data de sua emiss&atilde;o; transcorrida a qual, caducam imediatamente.</li>
                    <li><strong>9.9</strong> Os Pr&ecirc;mios s&atilde;o outorgados "ida e volta". N&atilde;o se trocam Pr&ecirc;mios Oneway. N&atilde;o se permitir&aacute; o embarque do S&oacute;cio no trecho correspondente ao voo de regresso se n&atilde;o houver voado o trecho correspondente ao voo de ida. Se o S&oacute;cio usa o Pr&ecirc;mio somente no trecho de ida n&atilde;o ser&aacute; devolvido o saldo de quilometragem nem dinheiro pago, pelo trecho de regresso n&atilde;o utilizado.</li>
                    <li><strong>9.10</strong> Os Upgrade podem ser trocados One way (s&oacute; para o trecho de ida ou para o trecho de regresso) ou bem "ida e volta".</li>
                    <li><strong>9.11</strong> Os Pr&ecirc;mios emitidos s&atilde;o nominativos e n&atilde;o podem ser cedidos ou transferidos a terceiros.</li>
                    <li><strong>9.13</strong> A reserva e a emiss&atilde;o de um Pr&ecirc;mio deve ocorrer de maneira simult&acirc;nea.</li>
                    <li><strong>9.14</strong> LANPASS se reserva o direito de reter Pr&ecirc;mios em caso de constatar alguma irregularidade em sua solicita&ccedil;&atilde;o ou utiliza&ccedil;&atilde;o. Toda contraven&ccedil;&atilde;o aos presentes termos e condi&ccedil;&otilde;es poder&aacute; dar lugar &agrave; negativa do LANPASS a emitir um Pr&ecirc;mio e/ou ao termo da participa&ccedil;&atilde;o do s&oacute;cio no Programa LANPASS, caducando imediatamente todos os quil&ocirc;metros da conta.</li>
                    <li><strong>9.15</strong> O S&oacute;cio pode solicitar mudan&ccedil;as de um Pr&ecirc;mio com anterioridade &agrave; data em que haja come&ccedil;ado a viagem e com uma antecipa&ccedil;&atilde;o m&iacute;nima de 48 horas. N&atilde;o &eacute; permitido mudan&ccedil;as por remanescentes de Pr&ecirc;mios (uma vez que j&aacute; come&ccedil;aram a ser usados). Em caso de mudan&ccedil;a, a validade do Pr&ecirc;mio n&atilde;o se estende. Em consequ&ecirc;ncia, o Pr&ecirc;mio trocado ter&aacute; uma validade equivalente ao remanescente da validez que tenha o Pr&ecirc;mio original.</li>
                    <li><strong>9.16</strong> S&oacute; s&atilde;o permitidas a troca de Pr&ecirc;mios por outros que exijam uma igual ou menor quantidade de quil&ocirc;metros.</li>
                    <li><strong>9.17</strong> S&oacute; &eacute; poss&iacute;vel mudar a data de um Pr&ecirc;mio, somente se h&aacute; disponibilidade de um Pr&ecirc;mio que exija uma quantidade igual ou menor de quil&ocirc;metros.</li>
                    <li><strong>9.18</strong> Se mudar um Pr&ecirc;mio por outro que requeira menor quantidade de quil&ocirc;metros, a diferen&ccedil;a de quil&ocirc;metros n&atilde;o utilizados no novo Pr&ecirc;mio n&atilde;o &eacute; devolvida ao S&oacute;cio, salvo que solicite uma nova mudan&ccedil;a por um Pr&ecirc;mio que requeira uma quantidade igual ou inferior aos quil&ocirc;metros aos utilizados no Pr&ecirc;mio original; em cujo caso poder&aacute; utilizar o saldo de quil&ocirc;metros no segundo novo Pr&ecirc;mio. Para posteriores mudan&ccedil;as de data se mant&eacute;m a quantidade de quil&ocirc;metros inicial.</li>
                    <li><strong>9.19</strong> As mudan&ccedil;as volunt&aacute;rios devem ser realizadas na mesma cabina emitida originalmente, salvo que no novo voo n&atilde;o exista a cabina original. Neste caso se poder&aacute; emitir o Pr&ecirc;mio em una cabina inferior, devendo o S&oacute;cio renunciar &agrave; diferen&ccedil;a de quil&ocirc;metros n&atilde;o utilizada.</li>
                    <li><strong>9.20</strong> As trocas de Pr&ecirc;mios emitidos com anterioridade ao 4 de agosto de 2009 ser&atilde;o regidas pelos termos e condi&ccedil;&otilde;es vigentes na data de sua emiss&atilde;o.</li>
                    <li><strong>9.21</strong> A mudan&ccedil;a de data, rota ou voo dos Pr&ecirc;mios, somente est&aacute; permitida em caso de n&atilde;o haver sido utilizado algum dos cupons. Esta troca tem associada um cargo por conceito de dita mudan&ccedil;a. O cargo &eacute; vari&aacute;vel segundo o pa&iacute;s de emiss&atilde;o do bilhete e da rota. Os cargos por trocas est&atilde;o publicados em <a href="/lanpass/canjee_kms/emision_service_fee.html">www.lan.com</a>. Os Pr&ecirc;mios emitidos para serem voados nas Linhas A&eacute;reas Associadas &agrave; alian&ccedil;a <strong>one</strong>world s&oacute; permitem mudan&ccedil;as de data e/ou hora e n&atilde;o permitem mudan&ccedil;as de itiner&aacute;rio, linha a&eacute;rea ou stopover previamente programados.</li>
                    <li><strong>9.22</strong> Caso o S&oacute;cio solicite a devolu&ccedil;&atilde;o de um Pr&ecirc;mio emitido, dever&aacute; pagar um cargo em quil&ocirc;metros. O cargo &eacute; vari&aacute;vel dependendo do Pr&ecirc;mio e de acordo &agrave; informa&ccedil;&atilde;o publicada no <a href="/lanpass/canjee_kms/emision_service_fee.html#tabla">www.lan.com</a>. A devolu&ccedil;&atilde;o de um Pr&ecirc;mio requer que a passagem emitida esteja vigente (a vig&ecirc;ncia come&ccedil;a a reger a partir da data de emiss&atilde;o do bilhete), que seja antes da sa&iacute;da do v&ocirc;o e, sem nenhum trecho voado, exceto para Upgrades em Oneworld e que os quil&ocirc;metros utilizados para sua emiss&atilde;o n&atilde;o estejam vencidos no momento de solicitar a devolu&ccedil;&atilde;o. A devolu&ccedil;&atilde;o poder&aacute; ser solicitada somente no Call Center de LAN (op&ccedil;&atilde;o LANPASS). Agenciada a devolu&ccedil;&atilde;o, os quil&ocirc;metros n&atilde;o vencidos ser&atilde;o reembolsados na conta de quil&ocirc;metros LANPASS do S&oacute;cio.</li>
                    <li><strong>9.23 </strong> Os Pr&ecirc;mios s&atilde;o nominativos, n&atilde;o t&ecirc;m valor em dinheiro e s&atilde;o intransfer&iacute;veis. Em caso que por qualquer causa ou motivo um Pr&ecirc;mio n&atilde;o seja -total ou parcialmente- utilizado no tempo e forma emitidos, este Pr&ecirc;mio perder&aacute; todo valor. <br>
                    </li>
                    <li>  <strong>9.24</strong> &Eacute; responsabilidade do Membro LANPASS verificar a quantidade de quil&ocirc;metros necess&aacute;rios para trocar um pr&ecirc;mio LANPASS em v&ocirc;os da LAN e em v&ocirc;os da oneworld e associadas, uma vez que para a mesma rota podem variar a quantidade a ser aplicada. </li></ul>
    <h3> 10. RESTRI&Ccedil;&Otilde;ES DE USO DE PR&Ecirc;MIOS </h3>
                    <ul><li><strong>10.1</strong> Os Pr&ecirc;mios est&atilde;o sujeitos a disponibilidade de espa&ccedil;o, que ser&aacute; confirmada no momento de sua emiss&atilde;o.</li>
                      <li><strong>10.2</strong> Os pr&ecirc;mios permitem um (1) Stopover (parada volunt&aacute;ria do passageiro em uma das escalas consideradas no trecho de ida ou de volta da viagem) ou um (1) Openjaw (cidade de destino diferente &agrave; cidade de origem da volta) em rotas nacionais e internacionais. Algumas companhias a&eacute;reas da oneworld ou associadas n&atilde;o permitem Stopover e Openjaw. Para obter mais informa&ccedil;&otilde;es, visite: <a href="/sitio_personas/lanpass/como_canjear/oneworld_asociadas.html">LAN.com/Como usar seus km</a></li>
                      <li><strong>10.3</strong> N&atilde;o est&aacute; permitida a emiss&atilde;o de Pr&ecirc;mios abertos, isto &eacute;, sem data de sa&iacute;da ou chegada.</li>
                      <li><strong>10.4</strong> Em nenhum caso os Pr&ecirc;mios poder&atilde;o ser usados em outras companhias a&eacute;reas que n&atilde;o sejam as indicadas no Pr&ecirc;mio.<br>
                      Em caso de cancelamento do voo indicado no Pr&ecirc;mio por um fato n&atilde;o imput&aacute;vel LAN, por raz&otilde;es de seguran&ccedil;a ou por caso fortuito ou for&ccedil;a maior, LAN realizar&aacute; o melhor esfor&ccedil;o para embarcar o passageiro no voo seguinte ou em uma combina&ccedil;&atilde;o de voos que permitam transport&aacute;-lo ao destino do Pr&ecirc;mio. Em nenhum caso o S&oacute;cio ser&aacute; embarcado em outra linha a&eacute;rea por estes ou outros motivos.</li>
                      <li><strong>10.5</strong> Em caso de Pr&ecirc;mios com voos que contemplam conex&otilde;es com mudan&ccedil;as de avi&atilde;o, os gastos de estadia no lugar de conex&atilde;o e qualquer outro gasto associado a ele ser&aacute; de cargo e conta exclusivos do passageiro.</li>
                      <li><strong>10.6</strong> Os Pr&ecirc;mios n&atilde;o poder&atilde;o ser combinados com outras promo&ccedil;&otilde;es, cupons, descontos e ofertas especiais, n&atilde;o t&ecirc;m validade naqueles lugares onde a lei o pro&iacute;be e est&atilde;o sujeitos &agrave;s restri&ccedil;&otilde;es pr&oacute;prias da ind&uacute;stria.</li>
                      <li><strong>10.7</strong> Os Pr&ecirc;mios outorgados correspondem exclusivamente ao valor neto da tarifa, sendo de responsabilidade e cargo do passageiro o pagamento de qualquer taxa, imposto, tributo e/ou direito que sua emiss&atilde;o a imponha, incluindo, mas n&atilde;o limitado, correspondente taxa de embarque.</li>
                      <li><strong>10.8</strong> Ser&aacute; de exclusiva responsabilidade do S&oacute;cio informar-se adequadamente sobre todas as restri&ccedil;&otilde;es na solicita&ccedil;&atilde;o e o uso dos Pr&ecirc;mios &agrave; data de sua utiliza&ccedil;&atilde;o.<br>
                      </li>
                      <li>  <strong>10.9</strong> Se o pr&ecirc;mio inclui v&ocirc;os operados pelas companhias a&eacute;reas oneworld ou associadas, &eacute; responsabilidade do membro Lanpass informar sobre as Condi&ccedil;&otilde;es de Transporte da companhia a&eacute;rea que opera o v&ocirc;o. Esta informa&ccedil;&atilde;o est&aacute; dispon&iacute;vel no site www.lan.com.</li>
                      <li><strong>10.10</strong> Se o pr&ecirc;mio inclui v&ocirc;os operados pelas companhias a&eacute;reas oneworld ou associadas, &eacute; responsabilidade do membro Lanpass informar sobre as Condi&ccedil;&otilde;es de Transporte da companhia a&eacute;rea que opera o v&ocirc;o. Esta informa&ccedil;&atilde;o est&aacute; dispon&iacute;vel no site <a href="/index.html" target="_blank">www.lan.com</a>.</li></ul>
    <h3> 11. USO DE CUPONS DE UPGRADE </h3>
                      <ul>
                        <li> <strong>11.1 </strong>Os cupons  de Ugrade s&atilde;o v&aacute;lidos at&eacute; a data neles indicada, e outorgam ao passageiro um  Upgrade para a classe imediatamente superior, em um v&ocirc;o operado e vendido por  LAN na ida ou no regresso, condicionado ao cumprimento das <a href="http://www.lan.com/es_un/sitio_personas/lanpass/como_canjear/familias_tarifarias.html" target="_blank">fam&iacute;lias tarif&aacute;rias</a>, &agrave; quantidade de cupons requeridos  pela rota e &agrave; disponibilidade de assentos no momento do embarque.  </li>
                        <li><strong>11.2 </strong>As tarifas m&iacute;nimas exigidas para a passagem paga est&atilde;o dispon&iacute;veis acessando o site <a href="/index.html">www.lan.com</a>.</li>
                        <li><strong>11.3</strong> O cupom de Upgrade ser&aacute; nulo em caso de altera&ccedil;&atilde;o, reprodu&ccedil;&atilde;o ou uso incorreto. Carece de valor monet&aacute;rio, ser&aacute; nulo se for empregado para qualquer tipo de interc&acirc;mbio e n&atilde;o ser&aacute; substitu&iacute;do em caso de roubo, furto ou perda. </li>
                        <li><strong>11.4</strong> Todos os cupons de Upgrade s&atilde;o para s&oacute;cio ou acompanhante. O acompanhante poder&aacute; usar o Cupom de Upgrade sempre e quando viaje junto ao S&oacute;cio (n&atilde;o necessariamente na mesma classe de cabina). </li>
                        <li><strong>11.5</strong> Ser&aacute; responsabilidade do passageiro efetuar o pagamento de qualquer imposto requerido para fazer uso de seu Certificado de Upgrade. </li></ul>
    <h3> 12. GENERALIDADES </h3>
                        <ul><li> <strong>12.1</strong> A participa&ccedil;&atilde;o no Programa LANPASS est&aacute; sujeita aos termos e condi&ccedil;&otilde;es aqui estabelecidos, que podem mudar, periodicamente, a crit&eacute;rio do LANPASS. Toda mudan&ccedil;a nos termos e condi&ccedil;&otilde;es ser&aacute; de observa&ccedil;&atilde;o obrigat&oacute;ria para os s&oacute;cios uma vez publicadas ou anunciadas por LANPASS, atrav&eacute;s de qualquer meio. Isto inclui o direito a modificar a Guia de Benef&iacute;cios do s&oacute;cio, modificar a tabela de Pr&ecirc;mios, o sistema de ac&uacute;mulo de quil&ocirc;metros, o sistema de concess&atilde;o de pr&ecirc;mios e a participa&ccedil;&atilde;o de outras organiza&ccedil;&otilde;es no Programa.</li>
                          <li><strong>12.2</strong> O LANPASS se reserva o direito a dar por conclu&iacute;do o Programa LANPASS a qualquer momento, com ou sem notifica&ccedil;&atilde;o pr&eacute;via, ficando sem efeito ou valor todos os quil&ocirc;metros acumulados pelo s&oacute;cio.<br>
                          Em todo caso, o LANPASS far&aacute; todo o poss&iacute;vel para comunicar previamente e com uma antecipa&ccedil;&atilde;o prudente a conclus&atilde;o do Programa a seus s&oacute;cios, a fim de que possam utilizar os quil&ocirc;metros acumulados. </li>
                          <li><strong>12.3 </strong>O LANPASS n&atilde;o ser&aacute; respons&aacute;vel, em nenhum caso, por perdas ou danos que pudessem resultar do t&eacute;rmino do Programa LANPASS ou mudan&ccedil;as ou altera&ccedil;&otilde;es do mesmo. </li>
                          <li><strong>12.4 </strong>Todos os Pr&ecirc;mios e Benef&iacute;cios est&atilde;o sujeitos a altera&ccedil;&otilde;es e disponibilidade, sendo de exclusiva responsabilidade do s&oacute;cio solicitar a correspondente reserva v&aacute;lida e cumprir todas as outras etapas necess&aacute;rias para o uso dos mesmos. </li>
                          <li><strong>12.5</strong> Alguns dos Pr&ecirc;mios, Benef&iacute;cios, e oportunidades para obter quil&ocirc;metros s&atilde;o ou podem ser proporcionados por organiza&ccedil;&otilde;es com as quais a LANPASS tem acordos, mas sobre as quais a LANPASS n&atilde;o possui controle algum. <br>
                            De qualquer modo, a LANPASS tratar&aacute; de assegurar que os Pr&ecirc;mios e Benef&iacute;cios oferecidos aos s&oacute;cios como dispon&iacute;veis est&atilde;o, de fato, dispon&iacute;veis. N&atilde;o obstante, a LANPASS n&atilde;o garante nem responde pela disponibilidade desses Pr&ecirc;mios e Benef&iacute;cios, pelos quais n&atilde;o ser&aacute; respons&aacute;vel por qualquer dano ou perda que pudesse resultar da provis&atilde;o, ou falta de provis&atilde;o, total ou parcial, de qualquer pr&ecirc;mio ou benef&iacute;cio. <br>
                            A LANPASS tamb&eacute;m n&atilde;o ser&aacute; respons&aacute;vel em caso de abandono do Programa LANPASS por parte de uma destas organiza&ccedil;&otilde;es. </li>
                          <li><strong>12.6 </strong>A provis&atilde;o ou subministro dos Pr&ecirc;mios e Benef&iacute;cios oferecidos pelas Linhas A&eacute;reas Associadas e/ou pelas Empresas Associadas estar&atilde;o sujeitos aos termos e condi&ccedil;&otilde;es que dita organiza&ccedil;&atilde;o imponha. </li>
                          <li><strong>12.7</strong> A LANPASS n&atilde;o ser&aacute; respons&aacute;vel por nenhuma perda, preju&iacute;zo, demora ou dano resultantes de, ou conectados com o Programa LANPASS ou qualquer Pr&ecirc;mio ou Benef&iacute;cio oferecido, exceto na medida em que a perda, preju&iacute;zo, demora ou dano seja causado por neglig&ecirc;ncia grave da LANPASS. </li>
                          <li><strong>12.8 </strong>O LANPASS n&atilde;o ser&aacute; respons&aacute;vel pelos erros ou omiss&otilde;es que, apesar de todas as precau&ccedil;&otilde;es tomadas, pudessem produzir-se na informa&ccedil;&atilde;o relativa a qualquer parte do Programa LANPASS. <br>
                          Tamb&eacute;m n&atilde;o ser&aacute; respons&aacute;vel pela demora, perda ou entrega equivocada da correspond&ecirc;ncia dirigida ao s&oacute;cio. </li>
                          <li><strong>12.9 </strong>Toda comunica&ccedil;&atilde;o escrita do s&oacute;cio dirigida ao Programa LANPASS, dever&aacute; levar sua assinatura e o n&uacute;mero de s&oacute;cio. </li>
                          <li><strong>12.10</strong> O LANPASS &eacute; a &uacute;nica respons&aacute;vel pela interpreta&ccedil;&atilde;o e aplica&ccedil;&atilde;o dos presentes termos e condi&ccedil;&otilde;es. </li>
                          <li>certificados e quil&ocirc;metros LANPASS est&atilde;o absolutamente proibidas. Toda pessoa que seja surpreendida comprando, vendendo, trocando ou transferindo Pr&ecirc;mios, certificados ou quil&ocirc;metros LANPASS poder&aacute; ser obrigada ao pagamento da tarifa completa associada, dos preju&iacute;zos e danos causados e dos custos legais envolvidos, tudo em conformidade com a legisla&ccedil;&atilde;o vigente. </li>
                          <li><strong>12.12</strong> Os certificados, Pr&ecirc;mios, e quil&ocirc;metros que tenham sido vendidos, ou comprados a qualquer t&iacute;tulo sem aprova&ccedil;&atilde;o da LAN, e as pessoas que se encontrem utilizando esses pr&ecirc;mios n&atilde;o poder&atilde;o continuar a viagem ou deixar&atilde;o de receber o servi&ccedil;o associado ao pr&ecirc;mio, exceto pagando a tarifa completa do mesmo.</li>
                          <li><strong>12.13</strong> A LANPASS n&atilde;o ser&aacute; respons&aacute;vel pelos Pr&ecirc;mios outorgados pelas Empresas Associadas ou Linhas A&eacute;reas Associadas, sendo estas &Uacute;ltimas as &uacute;nicas respons&aacute;veis frente ao s&oacute;cio pelos Pr&ecirc;mios que outorguem.</li>
                          <li><strong>12.14</strong> Os voos que apare&ccedil;am contabilizados nos estados de conta do Programa LANPASS, n&atilde;o constituem prova alguma de que o s&oacute;cio realizou realmente o voo indicado. </li>
                          <li><strong>12.15</strong> Os presentes termos e condi&ccedil;&otilde;es est&atilde;o sujeitos a modifica&ccedil;&otilde;es sem pr&eacute;vio aviso, mantendo uma vers&atilde;o eletr&ocirc;nica atualizada em <a href="/index.html">www.lan.com</a>. </li>
                          <li><strong>12.16</strong> Os presentes termos e condi&ccedil;&otilde;es s&atilde;o regidos pela lei da Rep&uacute;blica do Chile e, qualquer dificuldade, contenda ou lit&iacute;gio que suscite sua aplica&ccedil;&atilde;o, cumprimento, interpreta&ccedil;&atilde;o ou validade, ser&aacute; resolvido pelos Tribunais Ordin&aacute;rios de Justi&ccedil;a. </li>
                          </li>
   </ul>
                        <h2>CONDI&Ccedil;&Otilde;ES APLIC&Aacute;VEIS AO  CONTRATO DE&nbsp; TRANSPORTE A&Eacute;REO DE PASSAGEIROS  E BAGAGEM</h2>
  

                        <h3><strong>1. DEFINI&Ccedil;&Otilde;ES</strong></h3>
                        
                          <ul><li>Para os efeitos das presentes condi&ccedil;&otilde;es  entender&#8209;se&#8209;&aacute; o seguinte para cada um dos termos indicados a seguir:</li>
                          <li>1.1 <strong>"Bilhete"</strong> ou <strong>&ldquo;Bilhete  de Passagem&rdquo;, </strong>significa o conjunto de documentos que d&atilde;o conta e f&eacute; da celebra&ccedil;&atilde;o e das condi&ccedil;&otilde;es do contrato de transporte a&eacute;reo e controle de bagagem, e que est&atilde;o compreendidos por todos ou alguns dos seguintes documentos: <strong>(i)</strong> as presentes Condi&ccedil;&otilde;es do Contrato  de Transporte A&eacute;reo; <strong>(ii)</strong> as disposi&ccedil;&otilde;es contidas no documento denominado &ldquo;Informa&ccedil;&atilde;o de sua Compra&rdquo; entregue pela companhia ou detalhes da reserva entregues por qualquer agente; <strong>(iii)</strong> o bilhete eletr&ocirc;nico registrado  magneticamente;<strong> (iv)</strong> as condi&ccedil;&otilde;es  espec&iacute;ficas aplic&aacute;veis &agrave; tarifa paga pelo passageiro; <strong>(v)</strong> o Cart&atilde;o de Embarque ou &ldquo;<em>Boarding  Pass&rdquo;</em>; e <strong>(vi)</strong> as comunica&ccedil;&otilde;es e as tarifas de contrata&ccedil;&atilde;o que se encontram registradas perante as autoridades aeron&aacute;uticas nos pa&iacute;ses que o requeiram.</li>
                          <li>1.2 <strong>"Transportadora"</strong> ou <strong>"Transportador",</strong> significa a linha a&eacute;rea que transporte ou se comprometa a transportar o passageiro e/ou sua bagagem em virtude deste contrato ou que realize qualquer outro servi&ccedil;o relacionado com o referido transporte a&eacute;reo.</li>
                          <li>1.3 <strong>&ldquo;Conven&ccedil;&atilde;o de Vars&oacute;via&rdquo;,</strong> significa o Acordo para a Unifica&ccedil;&atilde;o de certas regras relativas ao Transporte A&eacute;reo Internacional de 1929 subscrito em Vars&oacute;via e as modifica&ccedil;&otilde;es introduzidas pelo Protocolo de Haia de 1955 e os Protocolos de Montreal de 1975.</li>
                          <li>1.4 <strong>&ldquo;Conven&ccedil;&atilde;o de Montreal&rdquo;</strong>, significa o Acordo para a Unifica&ccedil;&atilde;o de certas regras para o Transporte A&eacute;reo Internacional assinado em Montreal, Canad&aacute;, em 18 de Maio de 1999.                        </li></ul>
                          <h3>2.&nbsp;NORMAS GERAIS DO  TRANSPORTE A&Eacute;REO</h3>
                      <ul>  <li>2.1 A emiss&atilde;o do Bilhete de Passagem d&aacute; f&eacute; da celebra&ccedil;&atilde;o e aceita&ccedil;&atilde;o das condi&ccedil;&otilde;es do transporte a&eacute;reo e do contrato de transporte subscrito entre o passageiro e o Transportador cujos nomes aparecem no Bilhete. O Bilhete emitido em nome do passageiro &eacute; nominal, pessoal e intransfer&iacute;vel, e sua emiss&atilde;o poder&aacute; ser realizada total ou parcialmente atrav&eacute;s de meios f&iacute;sicos ou eletr&ocirc;nicos.</li>
                        <li>2.2 As escalas combinadas s&atilde;o aquelas mencionadas no Bilhete de Passagem ou as que figurem nos itiner&aacute;rios do Transportador como escalas previstas na rota do passageiro. O transporte a ser realizado em virtude deste contrato por v&aacute;rios transportadores, sucessivamente, ser&aacute; considerada como uma &uacute;nica opera&ccedil;&atilde;o.</li>
                        <li>2.3 Se o Transportador emite um Bilhete para o transporte em trechos operados por outro transportador a&eacute;reo, o Transportador estar&aacute; atuando apenas como agente deste &uacute;ltimo.</li>
                        <li>2.4 Qualquer isen&ccedil;&atilde;o ou limita&ccedil;&atilde;o de responsabilidade do Transportador em virtude da normativa local ou internacional vigente ser&aacute; aplicada e ir&aacute; em benef&iacute;cio dos agentes, empregados e representantes do Transportador e qualquer outra pessoa ou empresa cuja aeronave utilize o Transportador para efetuar o transporte e os agentes, empregados ou representantes da referida pessoa ou empresa.</li>
                        <li>2.5 Ao Transportador reserva&#8209;se a faculdade irrestrita de recusar o transporte em qualquer dos trechos do itiner&aacute;rio contratado pelo passageiro, se a tarifa contratada n&atilde;o for paga em sua totalidade ou parte, ou se o meio de pagamento utilizado foi recusado, revogado ou tornado sem efeito ou se obteve o Bilhete infringindo a lei.</li>
                        <li>2.6 De igual forma, o Transportador recusar&aacute; o embarque de um passageiro, ou determinar&aacute; seu desembarque, se julgar que o passageiro pode afetar a seguran&ccedil;a do v&ocirc;o ou dos passageiros. Especialmente, recusar&aacute; o embarque de qualquer passageiro que apresente qualquer atitude ou comportamento que em terra e/ou a bordo da aeronave constitua <strong>(i)</strong> um ato contr&aacute;rio &agrave;s instru&ccedil;&otilde;es  comunicadas pela tripula&ccedil;&atilde;o da aeronave ou de qualquer dos empregados do  Transportador; e/ou <strong>(ii)</strong> uma conduta contr&aacute;ria ao comportamento razo&aacute;vel que uma  pessoa ou passageiro deve manter; e/ou <strong>(iii)</strong> uma infra&ccedil;&atilde;o ou delito que na opini&atilde;o do Transportador possa por em perigo ou risco a seguran&ccedil;a da aeronave, das pessoas ou bens na mesma, ou que ponha em perigo ou comprometa a boa ordem e disciplina a bordo; e/ou <strong>(iv)</strong> em geral, qualquer atitude ou comportamento que na opini&atilde;o do Transportador constitua uma recusa ao cumprimento das instru&ccedil;&otilde;es comunicadas pela tripula&ccedil;&atilde;o e/ou atitudes que possam por em perigo ou submeter a algum risco a opera&ccedil;&atilde;o e/ou que perturbem a ordem e/ou a disciplina; e/ou <strong>(v)</strong> uma mostra ou sinais  de ter ingerido bebidas alco&oacute;licas em excesso e/ou alguma subst&acirc;ncia  psicotr&oacute;pica; e/ou <strong>(vi)</strong> o descumprimento de qualquer lei ou regulamenta&ccedil;&atilde;o seja aplicada ou que n&atilde;o acate qualquer solicita&ccedil;&atilde;o realizada pela autoridade governamental respectiva.</li>
                        <li>2.7 No caso de necessidade (incluindo mas n&atilde;o limitado a caso fortuito ou for&ccedil;a maior), o Transportador, pode cancelar a opera&ccedil;&atilde;o, substituir&#8209;se por outros transportadores e/ou trocar a aeronave destinada &agrave; opera&ccedil;&atilde;o e/ou alterar ou omitir paradas indicadas no Bilhete se for necess&aacute;rio. O Transportador n&atilde;o assume a responsabilidade de garantir as conex&otilde;es contratadas por um passageiro com um terceiro.</li>
                        <li>2.8 Todo passageiro que n&atilde;o se apresente para viajar ou que alegue estar atrasado para seu embarque e/ou n&atilde;o se apresente para verifica&ccedil;&atilde;o para o v&ocirc;o correspondente (&ldquo;check-in&rdquo;), perder&aacute; seu Bilhete, ou poder&aacute; revalid&aacute;&#8209;lo para outra data, se a tarifa paga permitir de acordo com o pactuado no Bilhete. Qualquer mudan&ccedil;a de data, origem, destino, itiner&aacute;rio do Bilhete de Passagem, assim como a devolu&ccedil;&atilde;o do valor pago pelo mesmo, fica sujeito &agrave;s condi&ccedil;&otilde;es e restri&ccedil;&otilde;es da tarifa contratada pelo passageiro. Com tudo, no caso em que o passageiro n&atilde;o efetue a viagem e ainda sua tarifa n&atilde;o permita devolu&ccedil;&atilde;o do Bilhete, poder&aacute; solicitar ao Transportador a devolu&ccedil;&atilde;o daquelas taxas aeroportu&aacute;rias que s&atilde;o reembols&aacute;veis de acordo com as normas ou limita&ccedil;&otilde;es do respectivo pa&iacute;s. No caso em que as referidas taxas n&atilde;o tenham sido inclu&iacute;das no valor pago (isto &eacute;, foram cobradas diretamente pelo aeroporto), o passageiro dever&aacute; solicitar seu reembolso diretamente perante a autoridade aeroportu&aacute;ria respectiva, sujeito &agrave;s limita&ccedil;&otilde;es ou normas anteriormente indicadas.</li>
                        <li>2.9 Os v&ocirc;os ou trechos que comp&otilde;em o itiner&aacute;rio dever&atilde;o ser voados na ordem consecutiva indicada. A Transportadora, sujeita as condi&ccedil;&otilde;es previstas na legisla&ccedil;&atilde;o aplic&aacute;vel, poder&aacute; recusar o embarque de um passageiro que n&atilde;o cumpra com a ordem do itiner&aacute;rio anteriormente referido ou se o passageiro n&atilde;o voou algum dos trechos indicados em sua passagem. O passageiro entende que se n&atilde;o voar algum dos trechos indicados no itiner&aacute;rio, este ser&aacute; cancelado em sua totalidade, sem pr&eacute;vio aviso, n&atilde;o procedendo nenhum tipo de reembolso salvo aquelas condi&ccedil;&otilde;es permitidas pela tarifa de seu Bilhete. A t&iacute;tulo de exemplo e sem que esta condi&ccedil;&atilde;o se limite a este caso em espec&iacute;fico, se o passageiro n&atilde;o voar o primeiro trecho especificado no itiner&aacute;rio (entendendo&#8209;se como ida), este n&atilde;o poder&aacute; voar nenhum outro (entendendo&#8209;se como v&ocirc;o de escala ou de volta).</li>
                        <li>2.10 &Eacute; estritamente proibido fumar dentro da cabine dos avi&otilde;es do Transportador. O Transportador reserva&#8209;se no direito de recusar o transporte de qualquer passageiro que n&atilde;o esteja disposto a aceitar esta condi&ccedil;&atilde;o.</li>
                        <li>2.11 O Bilhete &eacute; v&aacute;lido por um ano a partir da data de sua emiss&atilde;o ou v&aacute;lido at&eacute; a data que seja indicada especificamente para a tarifa adquirida pelo passageiro. Transcorrido o referido prazo, ou qualquer outro prazo inferior indicado nas condi&ccedil;&otilde;es da tarifa, o Bilhete n&atilde;o poder&aacute; ser utilizado.</li>
                        <li>2.12 &Eacute; de exclusiva responsabilidade do passageiro informar&#8209;se, obter e cumprir com os requisitos para viajar impostor por qualquer autoridade e dever&aacute; apresentar os documentos de identifica&ccedil;&atilde;o,&nbsp; de sa&iacute;da, tr&acirc;nsito, entrada, vistos e demais exigidos dependendo do lugar de destino, sem caber ao Transportador responsabilidade alguma pelos atrasos ou negativas de embarque que o passageiro sofra associados ou derivados do descumprimento por parte deste &uacute;ltimo da obriga&ccedil;&atilde;o anterior. O Transportador recusar&aacute; o embarque daqueles passageiros que n&atilde;o apresentem a documenta&ccedil;&atilde;o necess&aacute;ria ou cuja identidade n&atilde;o corresponda com a indicada no Cart&atilde;o de Embarque ou &ldquo;<em>Boarding Pass&rdquo;</em>, sem ulterior responsabilidade para o Transportador. O Transportador n&atilde;o ser&aacute; respons&aacute;vel por qualquer informa&ccedil;&atilde;o ou ajuda oferecida a um passageiro por qualquer agente, empregado ou representante da linha a&eacute;rea ou por terceiros, em rela&ccedil;&atilde;o &agrave; obten&ccedil;&atilde;o dos referidos documentos e/ou o cumprimento das leis e regulamenta&ccedil;&otilde;es aplic&aacute;veis.</li>
                        <li>2.13 Os v&ocirc;os operados pelo Transportador entre pa&iacute;ses que formam parte da Uni&atilde;o Europ&eacute;ia (isto &eacute;, v&ocirc;os entre Madrid, Espanha e Frankfurt, Alemanha) s&atilde;o considerados v&ocirc;os &ldquo;<em>No-Schengen&rdquo;</em> (n&atilde;o intra&#8209;comunit&aacute;rios) pelas respectivas autoridades nos referidos pa&iacute;ses, e, portanto, os passageiros destes v&ocirc;os passar&atilde;o obrigatoriamente pela aduana e pelo controle de passaportes em cada um deles, devendo portar toda a documenta&ccedil;&atilde;o de identidade, vistos, licen&ccedil;as de estrangeiro e autoriza&ccedil;&otilde;es exigidas pelos pa&iacute;ses intra&#8209;comunit&aacute;rios. S&atilde;o obriga&ccedil;&atilde;o e responsabilidade de cada passageiro informar&#8209;se sobre a documenta&ccedil;&atilde;o necess&aacute;ria. O Transportador n&atilde;o ser&aacute; respons&aacute;vel por danos e preju&iacute;zos provocados pelo descumprimento da referida obriga&ccedil;&atilde;o por parte dos passageiros. As mesmas condi&ccedil;&otilde;es regem os v&ocirc;os para/a partir do Canad&aacute;.</li>
                        <li>2.14 O passageiro dever&aacute; se apresentar no guich&ecirc; de embarque ou balc&atilde;o ou &ldquo;check-in&rdquo;, no hor&aacute;rio que o Transportador lhe indicar, e se n&atilde;o houver algum fixado, com suficiente anteced&ecirc;ncia para cumprir com os tr&acirc;mites de sa&iacute;da, que n&atilde;o poder&aacute; ser inferior a 02 horas de anteced&ecirc;ncia ao fixado para a sa&iacute;da do v&ocirc;o.</li>
                        <li>2.15 No caso de que em um v&ocirc;o existam mais passageiros com reserva confirmada que espa&ccedil;os dispon&iacute;veis sempre e quando tenham efetuado os tr&acirc;mites de &ldquo;check-in&rdquo; com o tempo m&iacute;nimo requerido, o Transportador pedir&aacute; volunt&aacute;rios para que ceda seu cupom confirmado em troca de uma indeniza&ccedil;&atilde;o pactuada. Se n&atilde;o houver volunt&aacute;rios suficientes e se tiver que recusar o embarque de passageiros contra sua vontade, estes passageiros ter&atilde;o direito &agrave;s presta&ccedil;&otilde;es que a legisla&ccedil;&atilde;o aplic&aacute;vel estabele&ccedil;a.</li>
                        <li>2.16 O Transportador se compromete a fazer todo o esfor&ccedil;o poss&iacute;vel para transportar o passageiro e sua bagagem com razo&aacute;vel pontualidade. Os hor&aacute;rios indicados no Bilhete de Passagem ou em alguma outra publica&ccedil;&atilde;o n&atilde;o est&atilde;o garantidos quanto a seu cumprimento uma vez que podem variar por motivos de for&ccedil;a maior superveniente, seguran&ccedil;a ou outras circunst&acirc;ncias extraordin&aacute;rias. O Transportador adotar&aacute; todas as medidas razo&aacute;veis e que sejam poss&iacute;veis para evitar demoras no transporte de seus passageiros e bagagens. O Transportador n&atilde;o assume a responsabilidade de garantir as conex&otilde;es, por fatos que n&atilde;o lhe sejam imput&aacute;veis.</li>
                        <li>2.17 Em alguns casos, a Transportadora poder&aacute; requerer notifica&ccedil;&atilde;o pr&eacute;via para viagens de certos passageiros com alguma incapacidade ou doen&ccedil;a (isto &eacute;, se requerem maca, oxig&ecirc;nio, etc.), ou com necessidade de transporte com um animal de assist&ecirc;ncia e/ou de suporte emocional. Os passageiros devem se informar com anteced&ecirc;ncia necess&aacute;ria &agrave; viagem, sobre certos requisitos ou condi&ccedil;&otilde;es especiais do transporte que dever&atilde;o ser cumpridos e coordenarem&#8209;se antes da aceita&ccedil;&atilde;o dos referidos passageiros para o embarque (isto &eacute;, transporte de um menor de idade n&atilde;o acompanhado, crian&ccedil;a, etc.), liberando desde j&aacute; o Transportador de qualquer responsabilidade no caso deste negar o embarque por n&atilde;o ter cumprido com as normas e/ou pol&iacute;ticas da companhia vigentes sobre o particular.</li>
                       
</ul>
                        <h3><strong>3. NORMAS  PARA O TRANSPORTE DE BAGAGEM</strong></h3>
                        <ul><li>3.1 Em cumprimento &agrave;s normas internacionais e locais, o Transportador recusar&aacute; o transporte como bagagem (de m&atilde;o ou faturada), daqueles artigos e subst&acirc;ncias perigosas que podem constituir um risco importante para a sa&uacute;de, a seguran&ccedil;a do v&ocirc;o ou a propriedade, tais como:
                        <ul>
                          <li>Gases (comprimidos, liquefeitos, em solu&ccedil;&atilde;o ou intensamente refrigerados), inclu&iacute;dos os aeross&oacute;is, que sejam inflam&aacute;veis, t&oacute;xicos ou in&oacute;cuos tais como, butano, oxig&ecirc;nio, nitrog&ecirc;nio l&iacute;quido, aeross&oacute;is contendo gases paralisantes, tubos de enchimento para acendedores de g&aacute;s liquefeito, etc.</li>
                          <li>Corrosivos, s&oacute;lidos ou l&iacute;quidos, tais como: &aacute;cidos,  &aacute;lcalis, merc&uacute;rio, baterias de eletr&oacute;lito l&iacute;quido, etc.</li>
                          <li>Explosivos tais como muni&ccedil;&otilde;es, fogos de artif&iacute;cio e de bengalas, maletas com dispositivos de alarme, espoletas para pistolas de brinquedos, etc. </li>
                          <li>L&iacute;quidos inflam&aacute;veis tais como combust&iacute;veis,  pinturas, diluentes, etc. </li>
                          <li>Materiais radioativos qualquer que seja sua categoria. </li>
                          <li>Materiais oxidantes e per&oacute;xidos org&acirc;nicos, tais como:  branqueadores, adubos, etc. </li>
                          <li>Subst&acirc;ncias t&oacute;xicas e infecciosas tais como: inseticidas, praguicidas, produtos biol&oacute;gicos que contenham germes patog&ecirc;nicos, etc. </li>
                          <li>S&oacute;lidos inflam&aacute;veis tais como f&oacute;sforos</li>
                          <li>Armas, entendendo&#8209;se por tais a todo elemento ou objeto que seja de fato, ou possa ser utilizado, para o ataque ou defesa, tais como: armas de fogo, armas brancas, gases, elementos de choque el&eacute;trico, pungentes, com corte, contundentes, entre os quais possam incluir porretes, machados e bast&otilde;es ou paus com um peso em seu interior ou em forma de ponta.</li>
                        </ul>
                        <li>3.2 Com o objetivo de velar pela seguran&ccedil;a do v&ocirc;o e cumprir com a normativa vigente, o Transportador e o pessoal de seguran&ccedil;a do aeroporto poder&atilde;o fazer a retirada dos artigos e subst&acirc;ncias perigosas transportados pelo Passageiro ou em sua bagagem de m&atilde;o, com o objetivo de coloc&aacute;&#8209;los &agrave; disposi&ccedil;&atilde;o das respectivas autoridades de acordo com as normativas locais aplic&aacute;veis a respeito.</li>
                        <li>3.3 Existe uma quantidade limitada de artigos medicinais e de toucador que &eacute; permitida que os passageiros transportem. Antes de inclu&iacute;&#8209;los em sua bagagem o passageiro dever&aacute; se informar com o pessoal do Transportador.</li>
                        <li>3.4 Alguns dos artigos mencionados anteriormente podem ser transportados por via a&eacute;rea sob certas condi&ccedil;&otilde;es especiais, amparado por um conhecimento de embarque e sob uma tarifa de carga a&eacute;rea, para o que o passageiro dever&aacute; consultar previamente o Transportador.</li>
                        <li>3.5 Entender&#8209;se&#8209;&aacute;  por bagagem, unicamente os objetos pessoais necess&aacute;rios para efetuar a viagem.</li>
                        <li>3.6 O passageiro n&atilde;o poder&aacute; faturar a bagagem a  transportar em nenhum outro v&ocirc;o que n&atilde;o seja aquele que ir&aacute; abordar.</li>
                        <li>3.7 O Transportador n&atilde;o registrar&aacute; a bagagem a um  destino que n&atilde;o seja o final que figura no Bilhete do passageiro.</li>
                        <li>3.8 O passageiro dever&aacute; adequar o peso, medida e limite  de bagagem permitido ao indicado no site <a href="/index.html">www.lan.com</a> e no documento de Informa&ccedil;&atilde;o de Compra mencionado no item 1.1. As franquias de bagagem e respectivas tarifas ou pagamentos adicionais decorrentes de eventual excesso ao limite permitido, dever&atilde;o ser consultados diretamente com a companhia a&eacute;rea ou em <a href="/index.html">www.lan.com</a></li>
                        <li>3.9 O limite de bagagem permitido poder&aacute; variar conforme as condi&ccedil;&otilde;es da tarifa, cabine e da rota contratada, e estar&aacute; discriminado em pe&ccedil;as ou quilos. O transportador se reserva no direito de alterar os limites de franquia e dimens&atilde;o da bagagem. As condi&ccedil;&otilde;es e as tarifas da contrata&ccedil;&atilde;o ser&atilde;o registradas perante a autoridade aeron&aacute;utica correspondente, quando assim exigido.</li>
                        <li>3.10 Como medida de precau&ccedil;&atilde;o e seguran&ccedil;a, apenas ser&aacute; permitida uma pe&ccedil;a de bagagem na cabine, com dimens&atilde;o e peso que possam ser acomodados nos compartimentos superiores do avi&atilde;o ou abaixo dos assentos. O passageiro dever&aacute; se adequar ao peso, medida e limite de bagagem de m&atilde;o permitido indicado em <a href="/index.html">www.lan.com</a> e no documento de  Informa&ccedil;&atilde;o de Compra j&aacute; mencionado no item 1.1.</li>
                        <li>3.11 A bagagem faturada ser&aacute; entregue ao portador do tal&atilde;o de bagagem. Em caso de dano &agrave; bagagem durante o transporte, dever&aacute; ser apresentada reclama&ccedil;&atilde;o por escrito imediatamente ap&oacute;s descobrir&#8209;se o dano e, no m&aacute;ximo, dentro dos 7 dias seguintes &agrave; data de recebimento da bagagem ou no menor tempo que indique a normativa aplic&aacute;vel no caso de v&ocirc;os dom&eacute;sticos. Em caso de atraso, a reclama&ccedil;&atilde;o deve ser feita dentro dos 21 dias seguintes &agrave; data de entrega da bagagem ou no menor tempo que indique a normativa aplic&aacute;vel no caso de v&ocirc;os dom&eacute;sticos. Para os efeitos do par&aacute;grafo anterior, entender&#8209;se&#8209;&aacute; por "atraso", toda demora que seja provocada na recep&ccedil;&atilde;o da bagagem e que seja produzida por responsabilidade direta da Transportadora. </li>
                     </ul>
                        <h3><strong>4.&nbsp; LIMITES  DE RESPONSABILIDAD</strong>E</h3>
                        <ul><li>4.1 Se a viagem de um passageiro inicia e termina dentro de um mesmo pa&iacute;s, o servi&ccedil;o de transporte e os limites de responsabilidade ser&atilde;o regulados pela legisla&ccedil;&atilde;o aplic&aacute;vel do referido pa&iacute;s. No caso da viagem de um passageiro ter o car&aacute;ter de internacional, ser&atilde;o aplic&aacute;veis a Conven&ccedil;&atilde;o de Vars&oacute;via ou a Conven&ccedil;&atilde;o de Montreal ou qualquer outra normativa internacional aplic&aacute;vel, segundo corresponda. Estas conven&ccedil;&otilde;es e normativas regular&atilde;o, quando corresponda, os limites de responsabilidade do Transportador por morte ou les&otilde;es pessoais do passageiro e a perda, atraso ou dano da bagagem.</li>
<li>4.2 O Transportador declara que em todo transporte regulado pela Conven&ccedil;&atilde;o de Vars&oacute;via, n&atilde;o invocar&aacute; os limites de responsabilidade civil prescritos em seu art&iacute;culo 22(1), nas reclama&ccedil;&otilde;es por danos compensat&oacute;rios que surjam por morte ou les&otilde;es pessoais. Neste tipo de reclama&ccedil;&atilde;o o Transportador n&atilde;o far&aacute; uso das defesas do art&iacute;culo 20(1) da Conven&ccedil;&atilde;o de Vars&oacute;via, com respeito &agrave;quelas reclama&ccedil;&otilde;es que n&atilde;o superem os 100.000 DEG. Salvo pelo aqui previsto, o Transportador poder&aacute; valer&#8209;se do restante das defesas previstas na Conven&ccedil;&atilde;o de Vars&oacute;via e dos recursos contra terceiros que sejam procedentes.                        
                        <li>4.3 Com respeito aos artigos de alto valor comercial e artigos eletr&ocirc;nicos, o passageiro dever&aacute; transportar estes objetos como bagagem de m&atilde;o, com o objetivo de manter sempre a cust&oacute;dia dos mesmos, uma vez que a Transportadora n&atilde;o responder&aacute; por estes al&eacute;m dos limites estabelecidos na lei ou conven&ccedil;&otilde;es internacionais aplic&aacute;veis no caso de serem transportados como bagagem faturada.                        
                        <li>4.4 A responsabilidade do Transportador em caso de morte ou les&otilde;es corporais do passageiro e/ou pela perda, atraso ou dano &agrave; bagagem no caso de transporte dentro dos dois pontos de um mesmo pa&iacute;s, est&aacute; limitada pelas leis e legisla&ccedil;&atilde;o aplic&aacute;veis do pa&iacute;s correspondente. Da mesma forma, a responsabilidade do Transportador em caso de morte ou les&otilde;es corporais do passageiro e/ou pela perda, atraso ou dano &agrave; bagagem em v&ocirc;os internacionais, est&aacute; limitada pelos acordos internacionais relativos ao transporte a&eacute;reo internacional, seja pela Conven&ccedil;&atilde;o de Vars&oacute;via, como pela Conven&ccedil;&atilde;o de Montreal conforme seja aplic&aacute;vel.<br>
                          Estas condi&ccedil;&otilde;es unicamente se aplicam e regulam sobre as rotas da Transportadora. Nenhum agente, empregado ou representante da Transportadora tem autoridade para alterar ou renunciar a qualquer disposi&ccedil;&atilde;o de estas condi&ccedil;&otilde;es.</li></ul>
                        
                        </div>
</div>
</body>
</html>
