<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>T&eacute;rminos y Condiciones</title>
<link rel="stylesheet" href="/es_cl/css/base.css" type="text/css"> 
<link rel="stylesheet" href="/es_cl/css/contenido.css" type="text/css">
</head>
<body>
<div id="contenido">
<div id="contenido_popup">
  <h2>Terms and Conditions </h2>
  <h3>Definitions</h3>
  <ul>
    <li>
      <strong>1.1 Frequent Flyer Program, LANPASS Program, Program, or LANPASS: </strong>refers to LAN's frequent flyer Program, which allows members to earn kilometers by flying on all LAN and Associated Airline routes, as well as by using the services of Partner Companies; subject to the conditions and requirements detailed below. The LANPASS Program does not imply the existence of an agreement of any kind between LAN and the member. The LANPASS Awards and/or Benefits are freely offered by LAN to its members, who adhere to them voluntarily and for whom the Awards and/or Benefits, except wherever indicated in this regulation, are free of charge.</li>
      <li><strong>1.2 LANPASS Program Member or member: </strong> is the person who meets the Program's requirements, who has completed and handed in the registration form by any of the means established in clause 2.2, whose application has been accepted by LANPASS, and whose membership has not been revoked or become void in accordance with the norms of the present regulation. In the case of LANPASS's Premium, Premium Silver, or Commodore categories the member's name shall appear printed on the card, with the respective membership number, which is also the member's account number. The account is personal, recognizing one sole account holder, and not admitting the possibility of additional members.</li>
      <li><strong>1.3 LANPASS kilometers, or simply kilometers: </strong> is the unit of measurement of the LANPASS Program, and which can be redeemed exclusively for air tickets according to the indications in chapter 7 of the present regulation.</li>
      <li><strong>1.4 Account Statement: </strong> is the information that LANPASS periodically sends its LANPASS Program members. It contains the amount of kilometers available, all the transactions associated with LANPASS Program activities, and all other information pertinent to the Program. Said account statement, as well as its online equivalent, constitutes the only valid information regarding the member's account movements.</li>
      <li><strong>1.5 Membership Card or LANPASS Card: </strong> is the member's LANPASS Program card for Premium, Premium Silver, and Commodore categories, when such a corresponding member category has been obtained.</li>
      <li><strong>1.6 Associated Airlines: </strong> are the airline companies, other than LAN, whose flights allow members to earn kilometers and/or enjoy the LANPASS Program Awards and/or Benefits; subject to the conditions and requirements of the present regulation and of those established by said airlines.</li>
      <li><strong>1.7 Partner Companies: </strong> are all the companies that participate in the LANPASS Program, other than the Associated Airlines, whose services allow members to earn kilometers and/or enjoy the LANPASS Program Awards and/or Benefits; subject to the conditions and requirements of the present regulation and of those established by said companies.</li>
      <li><strong>1.8 Awards or Benefits: </strong> Those tickets that can be obtained by redeeming LANPASS kilometers, as described in the Membership Benefits Guide.</li>
      <li><strong>1.9 Membership Benefits Guide: </strong> is the document that explains the LANPASS Program Awards and Benefits to the members, the means and requirements for using said Awards and Benefits, and the minimum terms and conditions that must be satisfied to do so. This guide is available at www.lan.com.</li>
      <li><strong>1.10 Awards and Benefits Table: </strong>is the table elaborated by LAN, which may be modified periodically as determined by LAN, that indicates the LANPASS kilometers necessary to request a specific Award or Benefit.</li>
      <li><strong>1.11 Award Certificate: </strong> certificate issued by LANPASS that accounts for the granting of a particular Award and that is redeemed for a ticket, as indicated on the certificate.</li>
      <li><strong>1.12 Blackout period: </strong> period during which Awards or Benefits that can be redeemed for LANPASS kilometers cannot be used, be it on LAN, on Associated Airlines, and/or at Partner Companies. Each organization's Blackout periods shall be informed in a timely manner to the members.</li>
      <li><strong>1.13 Stop Over: </strong> is a stop between the point of origin and the destination, at which the passenger may stay for a definite period of time, to later continue to his or her final destination on the same airline.</li>
      <li><strong>1.14 Open Jaw: </strong> flight in which the trip's destination on the first segment is different from the point of origin of the return segment (i.e.: a trip starting from Santiago to New York, and returning from Los Angeles to Santiago).</li>
      <li><strong>1.15 Stop: </strong> is a technical stop between the point of origin and the destination, during which the passenger must usually stay on board or at the airport for a brief period of time, to later continue to the final destination.</li>
      <li><strong>1.16 Connection: </strong> is a stop between the point of origin and the destination, for a maximum of 24 hours, to later continue to the final destination on the same airline.</li>
      <li><strong>1.17 Segment: </strong> A direct flight between two cities, which may or may not include stops, is considered a segment.</li>
      <li><strong>1.18 Upgrade: </strong> is a passenger's upgrade to a higher-level cabin class without having purchased the ticket corresponding to that class. </li>
      </li>
</ul>
    <h3>2. Conditions for admission</h3>
      <ul>
      <li>
        <strong>2.1 </strong> LANPASS Program members can be natural persons, 2 years of age and older, without regard to nationality or place of residence, as long as they (i) meet all the Program's requirements, (ii) complete and hand in the corresponding registration form, (iii) have been expressly accepted by the LANPASS Program and whose membership has not been cancelled or become void in accordance with the norms of the present regulation.</li>
      <li><strong>2.2 </strong> The application for the LANPASS Program shall be carried out by completing the corresponding registration form available at all LAN offices and www.lan.com, through the Partner Companies, or else, by telephone registration at LAN's reservation offices.</li>
      <li><strong>2.3 </strong> Once the corresponding application form has been received, LANPASS will inform the applicant that he or she has been accepted as member through a welcome email sent to the email address given by the member. If the applicant has not received the said membership confirmation, he or she must call the LANPASS Program telephone number to gain information on the application results.</li>
      <li><strong>2.4 </strong> The welcome email shall contain basic information on the program, confirm the new member's LANPASS membership number, and include a link to www.lan.com where the member can create a LANPASS password in case the registration was completed on a printed registration form or by any other means that does not give an access password to the LANPASS website.</li>
      <li><strong>2.5 </strong> Any LANPASS kilometers earned by an applicant before he or she has been expressly accepted as member, cannot be redeemed for Awards unless the applicant is effectively accepted as member.</li>
      <li><strong>2.6 </strong> The member shall be exclusively responsible for all information given on the registration form, as well as any later information updates.</li>
      <li><strong>2.7 </strong> The mailing address specified by the member cannot be a P.O. Box address or any other type of address where regular mail services are unavailable. LANPASS is not responsible for mail delivery to these types of addresses.</li>
      <li><strong>2.8 </strong> Every LANPASS card is strictly personal and non-transferable. Inadequate or improper use, or breach of the conditions and terms hereby established, of any LANPASS card can result in LANPASS Program membership termination, with the corresponding cancellation of all earned LANPASS kilometers, apart from any pertinent legal actions that may arise.</li>
      <li><strong>2.9 </strong> The applicant and/or member recognizes and accepts being solely responsible for any sum of money, be it in the form of taxes, fees, dues, or any other, that must be paid to any individual or legal entity, public or private, as a result of earning or using LANPASS kilometers or as a consequence of his or her admission to the LANPASS Program, or of the use of any of its Awards or Benefits.</li>
      <li><strong>2.10 </strong> Any changes in the information given by the member must be requested either (i) in writing by sending a letter, with the member's corresponding signature, to the LANPASS Program, (ii) through the call center (once the member's identity has been verified), or (iii) online at the Program's website. Only changes in home address and telephone number will be accepted verbally. All other respective changes must be done in writing or online.</li>
      <li><strong>2.11 </strong> Only one account per member is allowed. If two or more accounts exist, the most recent will be cancelled. All the kilometers earned through the cancelled accounts will be transferred to the original account, as long as said kilometers have not been accounted for in both accounts.</li>
      <li><strong>2.12 </strong> Transferring LANPASS kilometers among LANPASS Program accounts is not permitted, nor among LANPASS Program accounts and accounts from Associate Airlines and/or Partner Companies. It is strictly forbidden the sale or transfer of LANPASS kilometers or of associated awards by any mean, including Internet.</li>
      <li><strong>2.13 </strong> When requesting an Award, LANPASS kilometers from different LANPASS Program accounts cannot be added, nor from Associate Airline and/or Partner Company accounts.</li>
      <li><strong>2.14 </strong> By completing the registration form, the member agrees to receiving at his or her email or home address information about the Program and any other communications LAN periodically sends, be they pertinent to the LANPASS Program or not.</li>
      <li><strong>2.15 </strong> LAN shall freely determine the means and frequency of delivery of Account Statements, information on Benefits or membership, and any other communications, allowing for the use of physical (such as private or public mail), or electronic (such as email accounts or other) means.</li>
      <li><strong>2.16 </strong> In addition to what has been established in the above clause, by completing the registration form, the program applicant or member accepts that LAN can freely dispose of the information included in such form, be it in the Program's, LAN's, or a third party's benefit. In order to participate in the LANPASS program, it is an essential condition that the accumulation of kilometers must be performed in accordance with the terms and conditions of this program and in full compliance with the rules to be applicable.</li>
      </ul>
       
    <h3>3. Termination of program participation </h3>
    <ul><li>
      <strong>3.1 </strong> A member's participation in the LANPASS Program will end in the following cases:</li>
            <li><strong>3.1.1 </strong> If the associate fails to meet any of the terms and conditions mentioned here, or if the use of the LANPASS program or the accumulation of kilometers is made violating the law or applicable rule.</li>
            <li><strong>3.1.2 </strong> If the member knowingly gives incorrect or erroneous information (including flight information), be it on the registration form or when requesting the corresponding Awards.</li>
            <li><strong>3.1.3 </strong> If the member does not comply with the conditions of the passenger air transport contract (which apply to all passengers).</li>
            <li><strong>3.1.4 </strong> If the member incorrectly or improperly uses any Awards and/or Benefits granted.</li>
            <li><strong>3.1.5 </strong> If the member has an overdue debt of which LAN, or any of its affiliated or related companies, is creditor, or if there is any evidence or presumption of the member's participation in crimes or offences committed against said organizations, such as willfully or knowingly issuing fraudulent cheques or cheques without adequate balance, among others.</li>
            <li><strong>3.1.6 </strong> By the member's deliberate request, which he or she can impart at any moment in writing and, in the case of Elite members, by enclosing their membership card cut in half.</li>
            <li><strong>3.1.7 </strong> In case of the member's death.</li>
            <li><strong>3.1.8 </strong> If the LANPASS Program ends for whatever reason.</li>
            <li><strong>3.1.9 </strong> At LANPASS's sole discretion, at any moment, with prior notice.</li>
            <li><strong>3.2 </strong> In case the LANPASS Program or a member's participation in it ends, all kilometers earned will be cancelled and by no means will they be used or redeemed for tickets and/or money. </li>
    </ul>
    <h3>4. Suspension of membership rights</h3>
    <ul><li>
      <strong>4.1 </strong> LANPASS may temporarily suspend a member's rights and benefits without his or her losing membership, so that the member will continue to earn kilometers but will not be allowed to redeem Awards or request any of the Program's Benefits as long as LANPASS doesn't restore his or her full member status.</li>
      <li><strong>4.2 </strong> LANPASS may exercise the right of suspension in cases where the member has an overdue debt of which LAN, or any of its affiliated or related companies, is creditor, or if there is any evidence or presumption of the member's participation in crimes or offences committed against said organizations, such as willfully or knowingly issuing fraudulent cheques or cheques without adequate balance, among others.</li>
      <li><strong>4.3 </strong> The above-mentioned, notwithstanding the member's loss of his or her membership in accordance with the present regulation. </li>
      </li></ul>
      <h3>5. Membership card or LANPASS Card</h3> 
      <ul><li>
        <strong>5.1 </strong> The LANPASS membership card has an indefinite duration. However, the Premium, Premium Silver, and Commodore LANPASS membership card duration varies depending on its corresponding member category, as specified in the Program's details at www.lan.com. These cards can be renewed in accordance with paragraph 6. For the effects of the present regulation, the "calendar year" starts on January 1st and ends on December 31st of each year.</li>
        <li><strong>5.2 </strong> The cards issued by Partner Companies will be valid according to the terms and conditions of the respective company, while also being subject to the present regulation whenever pertinent.</li>
        <li><strong>5.3 </strong> The person whose name appears on the member card is the only person who has the right to use it, for any given purpose.</li>
        <li><strong>5.4 </strong> The membership card is not a credit card or a document that certifies identity, therefore it does not grant any more rights than those indicated in the present regulation.</li>
        <li><strong>5.5 </strong> All membership cards are the exclusive property of LANPASS.</li>
        <li><strong>5.6 </strong> In case of loss or theft of the membership card, the member must communicate it immediately to a LAN office, in person or by telephone. Once the case has been evaluated by LAN, a new card can be issued within 30 days. </li>
       
      </ul>         
<h3>6. Membership categories</h3>
<ul>
                      <li>
           <strong>6.1 </strong> The LANPASS Program has four membership categories: a) LANPASS, b) Premium, c) Premium Silver, and d) Commodore. Only the last three have an associated membership card.</li>
                        <li><strong>6.2 </strong> The different membership categories are determined by observance of the requirements established for each category, which are described in the LANPASS section of the www.lan.com website.</li>
                        <li><strong>6.3 </strong> A member's corresponding category is determined by: the number of kilometers flown on fares that earn kilometers on LAN or any of the <strong>one</strong>world Associated Airlines, as well as the bonuses earned by members for service class on LAN flights (executive class). The latter is on condition that the member has flown a minimum of four segments with LAN. The category can also be determined by the number of segments flown on LAN on fares that earn kilometers. Any of the above conditions must be met within a calendar year. The Commodore and Premium Silver categories are determined by a smaller amount of kilometers, of which a certain number of segments must be flown on LAN long range flights in Executive Class. The detail of flights defined as long range and the amount of kilometers required for each category can be found at www.lan.com.</li>
                        <li><strong>6.4 </strong> The LANPASS kilometers earned with Partner Companies and/or Associated Airlines will not be taken into account to determine a membership category (unless otherwise specified).</li>
                        <li><strong>6.5 </strong> Likewise, segments flown using Award-tickets or any other ticket that does not qualify to earn LANPASS kilometers will not be taken into account to determine a membership category.</li>
                        <li><strong>6.6 </strong> The member's permanence within a certain category corresponds to the following year and what remains of the year during which he or she met the necessary requirements to qualify for such a category.</li>
                        <li><strong>6.7 </strong> LANPASS will be able to, at its discretion, maintain or upgrade a member's category, even when he or she has not met all the necessary requirements for it, but will never be able to downgrade the category as long as the member meets the requirements established to remain within it.</li>
                        <li><strong>6.8 </strong> If a member does not meet the requirements necessary to renew his or her category, the following year he or she will belong to the category directly preceding the one he or she belonged to, even if the member does not meet the conditions to qualify for it.</li>
                        <li><strong>6.9 </strong> As of 2004, renewals will take effect on March 31st of each year, taking into account the requirements met by the member during the preceding calendar year.</li>
                        <li><strong>6.10 </strong> Changes in membership category will not affect the balance of kilometers that can be redeemed for Awards and vice versa. </li>
                      </li>
</ul>
    <h3>7. Kilometers </h3>
                          <ul><li>
                            <strong>7.1 </strong> Kilometers are the unit of measurement of the LANPASS Program.</li>
                            <li><strong>7.2 </strong> Kilometers present the following characteristics and are subject to the following terms:</li>
                            <li><strong>7.2.1 </strong> They have no commercial value, are non-negotiable, and cannot be exchanged for money or any other goods.</li>
                            <li><strong>7.2.2 </strong> They are non-transferable, whether free of cost or against payment.</li>
                            <li><strong>7.2.3 </strong> They are non-transmissible. In the event of the member's death, the account and its associated earned kilometers will be cancelled.</li>
                            <li><strong>7.2.4 </strong> They cannot be seized, being considered rights whose exercise is entirely personal.</li>
                            <li><strong>7.2.5 </strong> They are not subject to legal dispute or judicial measures of any sort, and belong only to the account holder, as a personal right.</li>
                            <li><strong>7.2.6 </strong> The Awards redeemed by the member are non-refundable.If a member requests the refund of an reward that has already been issued, a charge in kilometers must be paid. This charge varies depending on the reward and according to the information published at www.lan.com. For a reward refund, the issued ticket must be valid (validity begins on the date the ticket is issued), it must be requested before the flight's departure with no segment having been flown already, except for Oneworld upgrades and the kilometers used for its issue must not have expired at the time it is requested.</li>
                            <li><strong>7.2.7 </strong> The Awards are non-endorsable, so that they cannot be used on airlines other than LAN or the Associated Airlines, or by persons other than those designated by the member, depending on the Award redeemed. Once an award ticket has been issued, it can only be used on the airline indicated on it. </li>
                            </li>
</ul>
    <h3>8. Earning kilometers </h3>
                              <ul>
                                <li>
                                <strong>8.1 </strong> Kilometers will be credited whenever the member travels on LAN or Associated Airline flights, as long as these are operated by them, or else, whenever he or she uses the services of any of the Partner Companies. When the member belongs to the LANPASS program and, at the same time, to another airline or company&rsquo;s Frequent Traveler Program, the kilometers will only be credited to one of the accounts, of the member's choice. Under no circumstances will kilometers be credited to more than one account. The member must give his or her membership number, which must appear on the boarding pass. All flights operated by any airline that uses, for whatever reason, LAN's code on its ticket will be considered a valid flight for earning kilometers and qualifying for Premium, Premium Silver, and Commodore categories, as long as it has been flown on fares, routes, and dates that allow for accrual of LANPASS kilometers.</li>
                                <li><strong>8.2 </strong> Taking into account restrictions established by the Associated Airlines, the means to earn kilometers and amount of kilometers earned per flight flown on such airlines will not necessarily coincide with those established by LAN for its flights and will depend on the fare restrictions or the conditions fixed by the specific Associated Airline. There could be fares or flights that allow for earning only a percentage of the distance flown, or other restrictions. The member is responsible for ascertaining the amount of kilometers to be earned for flights flown with Associated Airlines.</li>
                                <li><strong>8.3 </strong> Third-party flights operated by LAN do not earn kilometers. Neither do those marketed by <strong>one</strong>world airlines and operated by a third party.</li>
                                <li><strong>8.4 </strong> Kilometers flown before registering for the Program can only be credited if the flights were LAN and no more than two months prior to the date of registration.</li>
                                <li><strong>8.5 </strong> Kilometers will be credited to the member's account only after completion of the trip and payment for the respective ticket has been made. Therefore, kilometers will not be earned for tickets that have been acquired but not flown or paid. In view of the above- mentioned, the member must keep and hand in, if requested, documents that prove the flight has been taken (ticket and boarding pass).</li>
                                <li><strong>8.6 </strong> Kilometers earned through services rendered by Associated Airlines or Partner Companies will be credited to the member's account only after the respective airline or company has submitted the information requested by LAN for such effects, which, in general, will take place no more than 30 days following the date when such services were rendered.</li>
                                <li><strong>8.7 </strong> The kilometers earned correspond to the distance between the flight's origin and destination, based on distances provided by IATA. The above notwithstanding, and as a temporary or permanent measure, LANPASS can credit the distance between the origin and destination with additional kilometers.</li>
                                <li><strong>8.8 </strong> The kilometers earned on LAN flights are valid for 36 consecutive months, starting from the date of the flight. In every case, the kilometers will effectively expire on the last day of the month that corresponds to the expiration month. Kilometers earned from Associated Airline flights, services rendered by Partner Companies, or promotional bonuses are valid for 3 calendar years, which means they expire on December 31st of the third year from when they were earned. <br>
                                  However, each time a passenger flies with LAN and earns 1 or more kilometers for that flight, all the valid kilometers in the account up to the date of the flight will be renewed automatically. Thus, they will be valid for 36 consecutive months counting from the date of said flight and will effectively expire on the last day of the 36th month.<br>
                                  In any case, following the rules set forth in the preceding paragraphs, and depending on which benefits the member the most, kilometers earned before May 1st, 1998 will be valid until December 31st of the third year in which they were effectively flown.<br>
                                LANPASS is not responsible for informing kilometer expiration dates, in accordance with the expiration rules herein established.</li>
                                <li><strong>8.9 </strong> All kilometers appearing on the account statement can be redeemed for Awards. Kilometers flown on LAN and <strong>one</strong>world Airlines, including bonuses for LAN service class, are also used to determine LANPASS membership category.</li>
                                <li><strong>8.10 </strong> LANPASS Program Award-tickets flown on LAN or any of the Associated Airlines, as well as Awards corresponding to Partner Company services, do not accrue kilometers.<br>
                                Likewise, tickets issued at reduced fares in the travel industry, charter flights, airline employee tickets, government discounts, free tickets, or any other ticket that does not have a published fare do not earn kilometers. Exclusion of any other type of ticket is at LANPASS's exclusive discretion, and will be adequately and timely informed to the members.</li>
                                <li><strong>8.11 </strong> Tickets endorsed to other companies by LAN will earn the equivalent kilometers, as if they had been effectively flown on LAN, only in case of an involuntary event. Tickets endorsed by Associated or <strong>one</strong>world Airlines to a third party do not earn kilometers.</li>
                                <li><strong>8.12 </strong> In case of a class Upgrade obtained as an Award or by courtesy of LAN or any of the Associated Airlines or Partner Companies, only the kilometers corresponding to the class paid by the member will be credited to the account, and not those corresponding to the class which he or she was upgraded to.</li>
                                <li><strong>8.13 </strong> It is the member's sole responsibility to verify that the kilometers corresponding to his or her flights with LAN and/or Associated Airlines, as well as those resulting from Partner Company services, are correctly credited to his or her account.<br>
                                  To do so, and in order to claim credit for kilometers retroactively, the member must keep all the flight documents (boarding passes, passenger's ticket receipt) as well as original invoices or contracts. In no case will kilometers be accrued after (1) one year from the flight date or the acts that generated them, unless the Partner Companies allow so for kilometers earned through them.<br>
                                Requests for kilometers retroactive clearance originated due to services carried out by Associated Airlines, will only be processed if the member handle in his/her flight documentation (boarding pass and ticket receipt). In the case of not handling in the documentation to support that the flight was performed, the request will not be processed.</li>
                                <li><strong>8.14 </strong> LANPASS reserves the right to audit a member's account at any time and without prior notice, in order to ensure compliance with the present terms and conditions. LANPASS will be able to discount kilometers improperly credited to a member, as well as delay delivery of Awards or certificates as long as any discrepancy is being resolved, while duly informing the member.</li>
                                <li><strong>8.15 </strong> If a ticket that earns LANPASS kilometers is purchased on credit or its payment is deferred in time, the member will be able to redeem an Award using any kilometers, whether they correspond to such a ticket or any other, as long as the respective tickets are being paid in the manner and time frame agreed upon when the ticket was purchased.</li>
                                <li><strong>8.16</strong> It will be of exclusive responsibility of the associate to fulfill the law and rule that might be applicable for the purpose of participation in the LANPASS Program and accumulation of kilometers, specially, regarding those associates that have the category of civil servant.</li>
                              </ul>
    <h3>9. LANPASS Flexible Redemption</h3>
    <ul><li>
      <strong>9.1</strong> To redeem a reward, a member must have a valid membership number and sufficient kilometers for the reward in question. The number of kilometers needed to redeem a certain reward is indicated in the Reward Table as valid on the date on which the request is made.</li>
      <li><strong>9.2</strong> The kilometers needed to redeem a reward vary according to the type of reward and the requested class. Economy class has three reward levels: Classic, Plus and Full (with Classic being the level which requires the least number of kilometers). Premium Business class has only one reward level.</li>
      <li><strong>9.3</strong> Upgrades can only be requested for Premium Business class.</li>
      <li><strong>9.4</strong> There are a limited number of seats available for each type of reward.</li>
      <li><strong>9.5</strong> To request a reward, members can call the LAN Call Center (choosing the LANPASS option) or visit the www.lan.com website, a LAN office or a travel agency. Documentation proving the member's identity must always be shown. At Lan.com, a username and password are needed.</li>
      <li><strong>9.6</strong> To redeem rewards through the LAN Call Center (choosing the LANPASS option), a LAN office or travel agencies, members must pay a LANPASS service fee for each ticket issued. If the reward is redeemed through www.lan.com , this charge does not apply. The LANPASS service fee is in addition to the departure and local taxes that apply and varies depending on the type of reward redeemed, according to the Reward Table published at www.lan.com .</li>
      <li><strong>9.7</strong> Anyone can request a reward by presenting an authorized letter giving power of attorney to said person from a member and which indicates: the member's full name, account number and/or RUT (identity card number) and a description of the reward requested. A photocopy of a document that proves the member's identity must also be presented (an identity card, its equivalent or passport).</li>
      <li><strong>9.8</strong> Rewards are valid for one year (12 months) from the date they are issued, after which they immediately expire.</li>
      <li><strong>9.9</strong> Only round-trip rewards are available. One-way rewards cannot be redeemed. A member will not be allowed to board a return flight if they have not flown the corresponding outbound leg. If the member only uses the outbound leg, the remaining kilometers or money paid for the unused return leg will not be refunded.</li>
      <li><strong>9.10</strong> One-way upgrades can be requested (for an outbound or return leg or for a round-trip).</li>
      <li><strong>9.11</strong> Any reward issued is personal and cannot be given or transferred to a third party.</li>
      <li><strong>9.13</strong> Rewards must be reserved and issued at the same time.</li>
      <li><strong>9.14</strong> LANPASS reserves the right to retain rewards should they detect any irregularity in the way in which they are requested or used. Any infringement of the present terms and conditions may result in LAN PASS refusing to issue a reward and/or the termination of the member's participation in the LANPASS program, with all kilometers in their account immediately expiring.</li>
      <li><strong>9.15</strong> A member may request changes to a reward's flight date before the ticket has been used and as long as this is done at least 48 hours in advance. Changes are not allowed for remaining legs of rewards (once other legs have been used). If changes are made, the reward's validity is not extended and, consequently, the altered reward will be valid for the same length of time as the original reward.</li>
      <li><strong>9.16</strong> Rewards can only be changed for others worth the same number of or fewer kilometers.</li>
      <li><strong>9.17</strong> Date changes can only be requested for rewards if there is another reward available for the same number of or fewer kilometers.</li>
      <li><strong>9.18</strong> By changing a reward for one that requires fewer kilometers, the difference in kilometers not used for the new reward will not be reimbursed, unless a subsequent change, which requires the same or a lesser amount of kilometers to those used in the original reward, is requested. In this case, the balance of kilometers can be used for the subsequent new reward. For further date changes, the initial amount of kilometers is maintained.</li>
      <li><strong>9.19</strong> Voluntary changes must be made in the same class as that originally issued, except for when the original class does not exist on the new flight. In this case, the reward can be issued for a lower class and the member must forfeit the difference in unused kilometers.</li>
      <li><strong>9.20 </strong>Changes made to rewards before August 4, 2009 are subject to the terms and conditions valid at the time of their issue.</li>
      <li><strong>9.21</strong> Date, route or flight changes are only allowed if none of the legs of the reward have been used. These changes are charged and the amount varies according to the country where the ticket was issued and the route. The charges for changes are published at www.lan.com . Rewards issued for flights in <strong>one</strong>world affiliated airlines only permit date and/or time changes but not changes of itinerary, airline or previously programmed stopovers.</li>
      <li><strong>9.22</strong> If a member requests a refund for a reward that has already been issued, they must pay a charge in kilometers. The amount of this charge varies depending on the reward and according to the information published at www.lan.com . For a reward to be refunded, the issued ticket must be valid (validity begins on the date the ticket is issued) it must be requested before the flight's departure with no segment having been flown already, except for Oneworld upgrades and the kilometers used for its issue valid at the time the refund is requested. Refunds can be requested through the LAN Call Center (choosing the LANPASS option) or at LAN offices. Once the refund has been made, valid kilometers will be credited to the member's account.</li>
      <li><strong>9.23</strong> Rewards are personal, have no monetary value and are nontransferable. If, for any reason, a reward is not used in the timeframe and according to the conditions established - either partially or totally - said reward loses its value. </li>
      <li><strong>9.24</strong> The Member must check the amount of LANPASS kilometers required to redeem a LAN Flight Award as well as oneworld flights and associated airlines, since the amount of Km required for the same route could vary.</li>
    
</ul>
    <h3>10. Restrictions on use of awards </h3>
    <ul><li>
      <strong>10.1</strong> Rewards are subject to availability. This is confirmed when the reward is issued. </li>
      <li><strong>10.2</strong> &nbsp;Awards allow for (1) one Stopover (voluntary stop by the passenger on one of the stops considered on for each way on a return ticket route) &nbsp;or&nbsp; (1) one Openjaw (destination city that is different to the city of origin on the return flight),both on domestic and international tickets. Some oneworld or associated airlines do not allow for Stop-overs or Openjaw. <a href="/sitio_personas/lanpass/como_canjear/oneworld_asociadas.html">More information</a>.</li>
      <li><strong>10.3</strong> Rewards allow for one (1) stopover (where the passenger voluntarily disembarks at one of the scheduled stops on the outbound or return journey) or one (1) open jaw (when the return destination is different to the city from which the flight originated) on both national and international routes.</li>
      <li><strong>10.4</strong> Open rewards, without an outbound or return date, cannot be issued.</li>
      <li><strong>10.5</strong> Under no circumstances can rewards be used on airlines that are different to those indicated in the reward.<br>
      If the indicated flight is cancelled for reasons beyond LAN's control, for security reasons or because of acts of nature or force majeure, LAN will do everything possible to board the passenger on the following flight or on a combination of flights that allow them to reach the reward's destination. Under no circumstances will a member be allowed to travel with another airline for this or any other reason.</li>
      <li><strong>10.6 </strong>For rewards whose flights involve connections with aircraft changes, the costs incurred as a result of the connection and any other associated costs must be borne exclusively by the passenger.</li>
      <li><strong>10.7</strong> Rewards cannot be combined with other promotions, coupons, discounts or special offers, are not valid in places where they are prohibited by law and are subject to the airline industry's own restrictions.</li>
      <li><strong>10.8</strong> Rewards are issued exclusively for the fare's net value and the costs of any local or other kind of taxes or duties required for the ticket to be issued, including but not limited to the corresponding departure taxes, must be borne by the passenger.</li>
      <li><strong>10.9</strong> It is the member's exclusive responsibility to be adequately informed of the restrictions of their request and of their reward on the date it is to be used.</li>
      <li><strong>10.10</strong> If the award includes flights operated by oneworld or associated airlines, the Member must find out the Transportation Conditions of the airline operating the flight. This information is available on www.lan.com.
      </li>
</ul>
    <h3>11. Use of upgrade coupons</h3>
    <ul>
      <li>
     <strong>11.1 </strong>Upgrade  coupons are valid up to the date indicated on them. They entitle the passenger  to an upgrade to the next cabin class on return flights operated and sold by  LAN, when complying with <a href="http://www.lan.com/es_un/sitio_personas/lanpass/como_canjear/familias_tarifarias.html">fare groups</a>,  the number of coupons required per route and seat availability when boarding.</li>
      <li><strong>11.2 </strong> The minimum fares required for tickets purchased are available at www.lan.com.</li>
      <li><strong>11.3 </strong> The Upgrade Coupon will become void in case of alteration, duplication, or improper use. It has no monetary value, will become void if it is used for any kind of exchange, and will not be replaced in case of theft or loss.</li>
      <li><strong>11.4 </strong> All Upgrade Coupons are for Members or their Accompanying Party. The latter can use the Upgrade Coupon as long as he or she travels with the Member (not necessarily in the same cabin class).</li>
      <li><strong>11.5 </strong> The passenger will be responsible for paying any taxes required to make use of the Upgrade Coupon. </li></ul>
    <h3>12. General provisions</h3>
      <ul>
      <li><strong>12.1</strong> Participation in the LANPASS program is subject to the terms and conditions established herein. These may be changed from time to time, exclusively at LANPASS&acute;s discretion. Members must adhere to any changes in said terms and conditions once these have been published or informed - in whatever way - by LANPASS. This includes the right to modify the members Guide to Benefits and Rewards Table, the way in which kilometers can be earned and rewards awarded and the participation of other organizations in the program.</li>
      <li><strong>12.2</strong> LANPASS reserves the right to terminate the LANPASS Program at any time, with or without prior notice, resulting in the cancellation of all kilometers earned by the member.
        
        However, LANPASS will make all possible efforts to previously inform its members of the Program's termination with due anticipation, so they may use any or all earned kilometers.</li>
      <li> <strong>12.3</strong> LANPASS will not be liable, in any event, for losses or damages resulting from the termination of the LANPASS Program, or from any changes or amendments to it.        </li>
      <li><strong>12.4</strong> All Awards and Benefits are subject to changes and availability, it being the member's exclusive responsibility to make the corresponding valid reservation and fulfill all the steps necessary to enjoy them.        </li>
      <li><strong>12.5</strong> Some Awards, Benefits, and kilometer earning opportunities are or can be provided by organizations with which LANPASS has agreements but over which LANPASS has no control.
        
        In any case, LANPASS will try to ensure that the Awards and Benefits offered to members as available are, in fact, available. However, LANPASS does not guarantee and is not liable for the availability of such Awards and Benefits. Therefore, LANPASS is not responsible for any loss or damage that could result in the provision, or total or partial lack of provision, of any Award or Benefit.
        
        Likewise, LANPASS will not be liable in case one such organization abandons the LANPASS Program.</li>
      <li> <strong>12.6</strong> The provision of Awards and Benefits offered by Associated Airlines and/or Partner Companies will be subject to the terms and conditions imposed by the respective organization.        </li>
      <li><strong>12.7</strong> LANPASS will not be liable for any loss, harm, damages, or delays resulting from or in connection to the LANPASS Program or any Award or Benefit offered, except when such loss, harm, damage, or delay has been caused by LANPASS's gross negligence.        </li>
      <li><strong>12.8</strong> LANPASS will not be responsible for errors or omissions that, despite all necessary precautions taken, could appear in information relating to any part of the LANPASS Program.
        
        Likewise, it will not be responsible for the delay, loss, or mistaken delivery of mail addressed to the member.        </li>
      <li><strong>12.9</strong> All written communication from the member to the LANPASS Program must include the member's signature and membership number.</li>
      <li> <strong>12.10</strong> LANPASS is solely responsible for the interpretation and enforcement of the present terms and conditions.</li>
      <li> <strong>12.11</strong> The purchase, sale, exchange, or transfer by any means of LANPASS Awards, certificates, and kilometers is strictly forbidden except under LAN's express and written authorization. Any person who is caught purchasing, selling, exchanging, or transferring LANPASS Awards, certificates, or kilometers may be forced to pay for the associated full fare, any harm or damages caused, and legal charges involved, in accordance with the valid legislation.</li>
      <li> <strong>12.12</strong> Persons who are using Awards, certificates, and kilometers that have been sold or purchased by any means without LAN's approval will not be able to continue their trip or will stop receiving the services associated with the Award, unless the associated full fare is cancelled.</li>
      <li> <strong>12.13</strong> LANPASS will not be responsible for Awards granted by Partner Companies or Associated Airlines. Such organizations will be solely responsible for any Awards granted to members.</li>
      <li> <strong>12.14</strong> Flights appearing on LANPASS Program account statements do not in any way constitute proof that the member actually flew on the indicated flight.        </li>
      <li><strong>12.15</strong> The present terms and conditions are subject to amendment without prior notice. An updated electronic version will be available at www.lan.com or can be requested at any LAN office.</li>
      <li> <strong>12.16</strong> The present terms and conditions are governed by the law of the Republic of Chile. Any trouble, dispute, or lawsuit resulting from their enforcement, compliance, interpretation, or validity will be resolved before its Ordinary Courts of Law. </li>
      </ul>
      
    <h2>Air Transport Agreement Conditions</h2>
    <h3>Terms Applicable to the Air Transport Agreement for International Passengers and Within Chile (Domestic/ National Flights). </h3>
    
    <p><strong>Overall</strong></p>
    <ul><li> 1. For the purposes of this contract, "ticket" or "passage ticket" shall mean "ticket for passage and luggage control", which comprises the terms and notices stated herein; "transport agent" or "carrier" shall signify each and every airline which shall transport or which shall stand committed to carry a given passenger or his luggage pursuant to this Agreement, or which shall render any other service related with such air transport, including but not limited to LAN; "electronic ticket" shall refer to the ticket for passage that appears magnetically registered and, in this case, the Boarding Pass having been delivered, same shall constitute the passage ticket. </li>
    <li> 2. The passage ticket shall constitute evidence of the entry into and acceptance of the terms of the "LAN Air Transport Agreement" ("Agreement") entered into by and between the Carrier and the Passenger whose names appear issued on such ticket. </li>
    <li>3. The name of Carrier may appear abbreviated on the ticket, provided the full name and abbreviation shall appear on the rate schedules, manuals, the terms of carriage, regulations and/or itineraries of Carrier. The address of Carrier shall be that of the airport of exit indicated on the ticket, on the side opposite to the first abbreviation of Carrier. The agreed stopovers shall be those stated on the passage ticket or, in the event of absence of same, those which shall appear on the itineraries of Carrier as scheduled stopovers within the route of the passenger. The carriage to be effected in conformity with this Agreement by several carriers successively shall be deemed to be one single operation. </li>
    <li>4. A given carrier who shall issue a ticket for carriage for a route of another air carrier, said issuing carrier shall only act as an agent of the transporting carrier. </li>
    <li> 5. Any given exemption or restriction of liability of Carrier shall be applicable to and shall inure to the benefit of the agents, employees and representatives of Carrier as well of that of any person whose aircraft shall be used Carrier to effect such carriage and its agents, employees or representatives. </li>
    <li> 6. Carrier shall be entitled to refuse carriage in the event that the applied rate shall be unpaid or if the ticket has been obtained by any infringement of law. In like manner, Carrier shall refuse to board any given passenger or shall make arrangements to disembark him if it considers that such passenger might jeopardize the security of the flight or of the passengers. </li>
    <li>7. Carrier shall stand committed to make all possible efforts to carry the passenger and his baggage with reasonable punctuality. The times that appear set forth in the itineraries or in any other publication shall not be guaranteed in terms of performance/ fulfillment and shall not form part of this Agreement. In the event of need, and without prior notice, Carrier may take action to be substituted by other carriers or to change the aircraft/ flight equipment, and it shall also be entitled to alter or omit stopovers signalled on the ticket if need be. Itineraries shall be subject to change without previous notice. Carrier shall not assume liability in terms of guaranteeing connections. </li>
    <li> 8. Each and every passenger which shall not appear for travel or which shall arrive late for boarding, shall lose his ticket or may be allowed to revalidate it for some other date, provided the rate paid allows for this. </li>
    <li>9. No agent, employee or representative of Carrier shall have authority to alter, modify or waive any stipulation set forth in this Agreement. </li>
    <li> 10.
      <!--The ticket coupons shall only be submitted to and accepted by Carrier, following the correlative order that appears within the ticket. -->
Scheduled flights must be flown in the exact order indicated on the ticket.Carrier will not &nbsp;board any passenger who does not comply with the order shown in the ticket.Therefore, Carrier will not board any passenger who has not flown any of the routes listed on his/her ticket.&nbsp; The passenger understands that if he/she has not flown any of the routes in the exact sequence indicated on the ticket, the ticket shall be cancelled in its entirety, and not subject to reimbursement unless permitted by the specific fare conditions. For example, and not withstanding any other applicable&nbsp;situation, if a passenger does not fly the first segment indicated in his/her ticket (in the case, first departure flight listed in the ticket), he/she may not board any other subsequent flight listed in the ticket (for example, a return or connecting flight).    
    <li>11. The passage ticket shall additionally be subject to the conditions applicable to the rate with regard to issues such as changes of dates and name, reissuance and refunds.</li></ul>
      <p> <strong>Hazardous articles within luggage </strong></p>
      <ul><li>1. Carrier shall refuse to carry as luggage, whether hand-baggage or invoiced/ paid luggage, any such hazardous articles and substances that might entail an important risk in terms of health, security/ safety or personal property, such as: </li>
      <ul>
        <li>Gases (compressed, liquid, in solution or highly refrigerated), including aerosols, which shall be combustible, toxic or harmless, such as: butane, oxygen, liquid nitrogen, aerosols containing paralyzing gases, refill tubes for liquid gas lighters, etc.</li>
        <li>Corrosives, solid or liquid, such as: acids, acid or alkali ones, mercury, liquid elecrolyte batteries, etc.</li>
        <li>Explosives such as: munitions, fireworks and signal flares, briefcases containing alarm devices, fulminating powder for toy pistols, etc.</li>
        <li>Inflammable liquids, such as: fuels, paints, diluting agents, etc.</li>
        <li>Radioactive materials, whichsoever category they may belong to.</li>
        <li>Oxidizing agents and organic peroxides, such as: bleaches, fertilizers. Toxic and infectious substances such as: insecticides, plaguicides, biological products containing pathogen germs, etc.</li>
        <li>Inflammable solids, such as: wax (matches);</li>
        <li>Arms/ Weapons, meaning as such each and every element or object that has been fabricated, or might be utilized, for attack or defense, such as: fire arms, blade weapons, gases, electric shock elements, sharp devices, exhibiting a cutting edge, : bruising elements, which might comprise clubs/ sledgehammers, axes and canes or sticks/ poles having some weight inside, or that display a pointed shape.</li>
      </ul>
      <li> 2. With the object of keeping a vigil over flight safety and abiding with current regulations, both Carrier and the security staff at the airport shall stand empowered to take away, for the purposes of proceeding to destruct, hazardous articles and substances carried by the Passenger or in his hand luggage.</li>
      <li>3. There is a limited humber of medical articles and toiletries which passengers shall be allowed on board. Before putting them in your luggage, kindly verify with company staff.</li>
      <li>4. Many of the articles mentioned above may be carried by air under certain special conditions, covered by a bill of lading and subject to an air cargo rate. </li></ul>
      <p><strong>Carry-on baggage</strong></p>
      <ul><li>As a precaution and security, only one piece of baggage is allowed to be carried on cabin, with dimension and weight that enable them to be placed at the upper compartments of the aircraft or under the seats. This package may not exceed 8 kg in Economy class or 16 kg in Premium Bussines or Premium Economy class and its dimension may not exceed 115 cm (55 cm long + 35 cm high + 25 cm wide).</li></ul>
      <p><strong>Notice of Overbookings</strong></p>
      <ul><li>
        <p> In the event of overbookings, certain flights may appear with more seats reserved/ booked than the capacity of the aircraft, therefore, a given seat might not be available on a flight for a passenger who possesses a confirmed reservation. In such case, and subsequent to any efforts made to remedy the situation, including a voluntary request for passengers to relinquish their confirmed space, the Carrier may find itself in need to refuse boarding to a given passenger, who shall be entitled to receive compensation, provided he shall have arrived on time for the departure of the flight. In the event of overbookings, the law, rates and conventions of each and every country shall apply. </p>
      </li></ul>
    <h3>International Air Transport Agreement </h3>
      <p> <strong>Notice</strong></p>
      <ul>
        <li>If the trip of a given passenger ends or has a stopover in a country different from that of the commencement of the trip, the Convention for the Unification of Certain Rules relating to International Carriage by Air signed at Warsaw October 12, 1929 (hereinunder called the "Convention"), as amended by the Protocol signed at the Hague, September 28, 1995 ("Hague Protocol") shall apply and shall regulate, whensoever appropriate, the boundaries of liability of Carrier in terms of death or personal injuries and of loss or damages to luggage. Kindly also refer to the note entitled "Notice for International Passengers regarding Boundaries of Liability" and "Notice of Boundaries of Liability in Terms of Luggage" as provided to you by Carrier. </li></ul>
          <p> <strong>Special conditions within the international transport agreement</strong></p>
          <ul><li>1. Carriage which shall be effected pursuant to this Agreement shall be subject to the norms and boundaries in terms of liability that appear set forth by the Convention and Hague Protocol System, unless such carriage shall not be "international transport/ carriage" as per the definition contained in such covenant. </li>
            <li>2. Without prejudice to the foregoing, the carriage or other service to be rendered by each and every Carrier shall be subject to: (I) the stipulations contained in the ticket of passage ; (II) the conditions established in the applicable rate (III) the terms and conditions of carriage set out by Carrier and the rest of the related regulations that form part of this Agreement (and which may be consulted at the offices of Carrier), except in the event of carriage between a given point in the United States of America or Canada and any other point beyond such countries, in which case the rates current therein shall apply.</li>
            <li>3. Paid/ Invoiced luggage shall be delivered to bearer of the luggage ticket. In the event of damage to the luggage during the course of international transport/ carriage, a written claim must be submitted immediately after such damage is discovered and, at the most, within the seven (7) days following the date when such luggage was received. Should delay be incurred, the claim must be submitted within twenty-one (21) days following the date of delivery of the luggage. For purposes of this paragraph, delay shall mean any delay in the receipt of baggage which is directly attributable to the Carrier's handling of the baggage (i.e., delayed shipping, etc.). </li>
            <li>4. The ticket shall be valid for one year starting from the date of its issuance, unless indicated to the contrary appears stated on same, in the rate schedules of Carrier, in the carriage conditions or in regulations pertaining thereto. Once such time frame shall have elapsed, such ticket shall have lost all of its value. The rate pursuant to this Agreement shall be subject to changes prior to the start of such carriage. </li>
            <li>5. Passenger must abide with the requirements for travel set forth by any given authority and shall submit the exit and entry documents that shall berequired, and must likewise appear before the boarding desk at the time that Carrier indicates and, in the event the latter shall not have signalled one, with sufficient anticipation to meet the requirements for departure, which shall not be less than two (2) hours prior to the time fixed for departure of the flight. </li>
            <li>6.- Flights between Madrid and Frankfurt and vice versa with LAN are considered "No-Schengen" (no inter-community) by the authorities, and therefore passengers on these flights will pass through customs and passport control. It is the passenger's responsibility and obligation to carry the required documentation. LAN is not responsible for damages or inconveniences caused by the passenger failing to comply with this obligation. </li></ul>
            <p> <strong>Notice to international passengers on boundaries of liability</strong></p>
    <ul><li> 1. With the exception of what appears set forth in any applicable treaty or law, civil liability of LAN ("Carrier") regarding international flights, may be governed by the Convention for the Unification of Certain Rules relating to International Carriage by Air signed at Warsaw October 12, 1929 (hereinunder called the "Convention"), as amended by the Protocol signed at the Hague, September 28, 1995 ("Hague Protocol"). </li>
            <li> 2. Carrier hereby declares that during each and every flight that shall be governed by the Convention and Hague Protocol System, it shall not invoke the boundaries of civil liability set forth in its Article 22(1) during the course of claims for compensation damages arising from death or personal injuries. In such type of claims, Carrier shall not make use of the defenses/ protections contained in Article 20(1) of the Convention and Hague Protocol System, inasmuch as those claims under 100,000 DEG shall be concerned. With the exception of what appears contained herein, Carrier shall be entitled to resort to the rest of the defenses set out in such Convention and Hague Protocol as well as the claims against third parties that shall be in order. </li>
            <li>3. As a case in point, flights operated by Carrier towards and from the European Union, Carrier shall, without delay and at the very latest within the fifteen (15) days following the determination of the identity of the person legally empowered to sue/ claim, shall advance compensation in cash as required to meet the needs of such person entitled to the indemnity, in proportion to the prejudice/harm suffered. Such advances shall in no way constitute an acknowledgement of liability, may be disbursed instead of providing future payments. Said payment shall not be refundable, unless the damage shall have been provoked either wholly or in part by the passenger or by the person receiving same, or whensoever the latter shall not have been entitled to receive indemnity. </p>
            <p><strong> Notice of limited responsibility for luggage</strong></p>
            <p>The Carrier responsibility for loss, delay or damage of luggage is limited by the international agreements established with respect to international air transport, be it the Agreement for the Unification of certain rules relative to International Air Transport signed in Warsaw, modified by the Hague and Montreal Protocols, as well as the Agreement for the Unification of certain rules for International Air Transport &ndash; signed in Montreal, Canada on May 18, 1999 &ndash; where applicable.</p>
            <p>With respect to items of high commercial value and electronic items, it is recommended that the passenger transports these items as carry-on luggage whenever possible, so that the passengers maintains possession of these items at all times, as the transporter will not be held responsible for these items beyond the limits established by law.</p>
            </li>
</ul>
<h3>National Air Transport Agreement</h3>

  <p> <strong>Notices</strong></p>
  <ul><li>
   If the trip is between places located within the Republic of Chile, it shall be governed by the National Agreement on the Air Transport of Passengers as well as by the Aeronautical Code of Chile, which shall govern, wheresoever pertinent, the boundaries of liability of Carrier in terms of death or personal injuries and of loss or damages to luggage. </li></ul>
  <p> <strong>Special conditions contained in the national transport agreement </strong></p>
  <ul><li>1. The Aeronautical Code of Chile shall supplementarily govern the transport /carriage Agreement and shall prevail as non-revocable in terms of the parties thereto. </li>
  <li>2. Without prejudice to the above, the transport or other service that shall be rendered by each and every Carrier shall be subject to: (I) the stipulations set forth in the passage ticket; (II) the conditions set out in the applicable rate; (III) the terms of carriage set forth by Carrier and the rest of the related rules that form part of this Agreement (and which may be consulted at the offices of Carrier ).</li>
  <li>3. Passenger must appear at the airport desk at least one (1) hour prior to the time set for the departure of the flight. The Carrier reserves unto itself the right to refuse to board and carry any passenger who does not show up at the signalled time.</li>
  <li>4. The ticket shall be valid for one year starting from the date of its issuance, unless indicated to the contrary appears stated on same, in the rate schedules of Carrier, in the carriage conditions or in regulations pertaining thereto. Once such time frame shall have elapsed, such ticket shall have lost all of its value. The rate pursuant to this Agreement shall be subject to changes prior to the start of such carriage. </li></ul>
  <p><strong> Notice of limited responsibility for luggage </strong></p>
 <ul> <li>The Carrier responsibility for loss, delay or damage of luggage is limited by the Chilean Aeronautic Code.</li>
  <li>With respect to items of high commercial value and electronic items, it is recommended that the passenger transports these items as carry-on luggage whenever possible, so that the passengers maintains possession of these items at all times, as the transporter will not be held responsible for these items beyond the limits established by law.</li>
 
  </ul>
  </div>
</div>
</body>
</html>
