<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>T&eacute;rminos y Condiciones</title>
<link rel="stylesheet" href="/es_cl/css/base.css" type="text/css"> 
<link rel="stylesheet" href="/es_cl/css/contenido.css" type="text/css">
</head>
<body>
<div id="contenido">
<div id="contenido_popup">
  <h2>Conditions g&eacute;n&eacute;rales</h2>

  <h3>1.D&eacute;finitions</h3>
  <ul><li><strong>1.1 Programme de Fid&eacute;lit&eacute;, Programme  LANPASS, Programme ou LANPASS&nbsp;</strong>: Programme de fid&eacute;lit&eacute; de LAN, gr&acirc;ce auquel il est  possible d&rsquo;accumuler des kilom&egrave;tres en voyageant sur tous les vols op&eacute;r&eacute;s par  LAN, les Compagnies A&eacute;riennes Partenaires, ainsi qu&rsquo;en utilisant les services  qualifiants des soci&eacute;t&eacute;s partenaires&nbsp;; le tout &eacute;tant soumis aux conditions  et requis d&eacute;taill&eacute;s ci-apr&egrave;s. Le programme LANPASS ne suppose pas l&rsquo;existence  d&rsquo;une convention d&rsquo;une quelconque nature entre LAN et le membre, les Primes  et/ou avantages LANPASS &eacute;tant une simple lib&eacute;ralit&eacute; que LAN propose aux membres  qui y adh&egrave;rent volontairement. Sauf disposition contraire prescrite par ce  r&egrave;glement, ils sont gratuits.  
  <li><strong>1.2</strong> <strong>Membre  du Programme LANPASS ou membre&nbsp;:</strong> Personne qui remplit les crit&egrave;res  requis du Programme, qui a compl&eacute;t&eacute; et remis le formulaire d&rsquo;adh&eacute;sion par  n&rsquo;importe quel moyen d&eacute;crit &agrave; l&rsquo;article 2.2, dont la demande a &eacute;t&eacute; accept&eacute;e par  LANPASS et dont la qualit&eacute; de membre n&rsquo;a pas &eacute;t&eacute; r&eacute;voqu&eacute;e ou laiss&eacute;e sans effet  conform&eacute;ment aux r&egrave;gles du pr&eacute;sent r&egrave;glement. Pour les statuts Premium, Premium  Silver et Comodoro de LANPASS, le nom du membre sera inscrit sur sa carte, au  m&ecirc;me titre que son num&eacute;ro de membre, qui est aussi son num&eacute;ro de compte. Le  membre du programme disposera d&rsquo;un compte o&ugrave; il accumulera des kilom&egrave;tres  LANPASS. Ledit compte est personnel, n&rsquo;a qu&rsquo;un seul titulaire et n&rsquo;accepte pas  de membres suppl&eacute;mentaires.  
  <li><strong>1.3</strong> <strong>Kilom&egrave;tres  LANPASS ou simplement kilom&egrave;tres&nbsp;: </strong>unit&eacute; de mesure du Programme LANPASS.  Les kilom&egrave;tres sont &eacute;changeables exclusivement contre des billets d&rsquo;avion  conform&eacute;ment au chapitre 7 du pr&eacute;sent R&egrave;glement.  
  <li><strong>1.4 Relev&eacute; de Compte&nbsp;:</strong> information  envoy&eacute;e p&eacute;riodiquement par LANPASS aux membres du Programme LANPASS afin de les  informer sur leur compte. Le relev&eacute; de compte est &eacute;galement disponible en  ligne. Le relev&eacute; de compte indique le nombre de kilom&egrave;tres disponibles,  l&rsquo;ensemble des mouvements li&eacute;s aux activit&eacute;s du Programme LANPASS et toute  information pertinente le concernant. Le relev&eacute; de compte constitue la seule  information valable sur les mouvements effectu&eacute;s dans le compte du membre.  
  <li><strong>1.5 Carte de membre ou Carte  LANPASS&nbsp;:</strong> carte qui accr&eacute;dite la qualit&eacute; de membre du programme LANPASS. Elle n&rsquo;est  &eacute;mise que pour les membres Premium, Premium Silver et Comodoro. LANPASS remet  ladite carte directement au membre une fois qu&rsquo;il atteint le statut  correspondant, sans qu&rsquo;il ait &agrave; la solliciter.  
  <li><strong>1.6 Compagnies A&eacute;riennes  Partenaires&nbsp;: </strong>ce sont les compagnies a&eacute;riennes autres que LAN, dont les vols permettent  d&rsquo;accumuler des kilom&egrave;tres et/ou b&eacute;n&eacute;ficier des Primes ou Avantages ou  Avantages du Programme LANPASS, le tout &eacute;tant soumis aux conditions et  dispositions du pr&eacute;sent r&egrave;glement et aux conditions signal&eacute;es par lesdites  compagnies a&eacute;riennes.  
  <li><strong>1.7 Soci&eacute;t&eacute;s Partenaires&nbsp;:</strong> l&rsquo;ensemble des  soci&eacute;t&eacute;s participant au Programme LANPASS (&agrave; l&rsquo;exception des Compagnies  A&eacute;riennes Partenaires) dont les services permettent d&rsquo;accumuler des kilom&egrave;tres  et/ou b&eacute;n&eacute;ficier de Primes et Avantages ou Avantages du Programme  LANPASS&nbsp;; le tout &eacute;tant soumis aux conditions et dispositions du pr&eacute;sent  r&egrave;glement et aux conditions signal&eacute;es par lesdites soci&eacute;t&eacute;s.  
  <li><strong>1.8 Primes et/ou Avantages&nbsp;:</strong> billets qui  peuvent &ecirc;tre obtenus en &eacute;changeant les kilom&egrave;tres LANPASS, conform&eacute;ment aux dispositions  du Guide des Avantages du Membre.  
  <li><strong>1.9 Guide des Avantages du  Membre&nbsp;:</strong> document qui explique aux membres les Primes et/ou Avantages accord&eacute;s par  le Programme LANPASS, le moyen et les crit&egrave;res requis pour les obtenir, et les  conditions minimales requises pour cela. Ce guide est disponible sur <a href="/sitio_personas/index.html">www.lan.com</a>.  
  <li><strong>1.10 Bar&egrave;me de Primes ou  d&rsquo;Avantages&nbsp;:</strong> bar&egrave;me con&ccedil;u par LAN, qui indique les kilom&egrave;tres LANPASS n&eacute;cessaires pour  demander une Prime et/ou un Avantage.  
  <li><strong>1.11 Certificat de Prime&nbsp;:</strong> certificat  accord&eacute; par LANPASS qui fait &eacute;tat de l&rsquo;octroi d&rsquo;une Prime et/ou d&rsquo;un Avantage,  y qui correspond &agrave; l&rsquo;&eacute;change de kilom&egrave;tres contre un ou plusieurs billets  primes, selon ce qui est indiqu&eacute; dans le certificat.  
  <li><strong>1.12 Embargo&nbsp;:</strong> p&eacute;riode au cours  de laquelle les kilom&egrave;tres LANPASS ne peuvent pas &ecirc;tre &eacute;chang&eacute;s contre des  Primes et/ou Avantages, que ce soit sur LAN, les Compagnies A&eacute;riennes  Partenaires ou les Soci&eacute;t&eacute;s Partenaires. Les p&eacute;riodes d&rsquo;Embargo de chaque  entit&eacute; sont variables et les membres en seront inform&eacute;s opportun&eacute;ment.  
  <li><strong>1.13 Stop Over&nbsp;:</strong> arr&ecirc;t entre le  point de d&eacute;part et le point d&rsquo;arriv&eacute;e, o&ugrave; un passager peut demeurer pour une  p&eacute;riode donn&eacute;e avant de continuer son voyage vers sa destination finale avec la  m&ecirc;me compagnie a&eacute;rienne.  
  <li><strong>1.14 Open Jaw&nbsp;:</strong> vol o&ugrave; la  destination finale &agrave; l&rsquo;aller diff&egrave;re du point de d&eacute;part du voyage retour.  (exemple&nbsp;: un vol aller Santiago - New York et un vol retour Los Angeles &ndash;  Santiago)  
  <li><strong>1.15 Escale&nbsp;:</strong> arr&ecirc;t technique  entre le point de d&eacute;part et le point de destination, o&ugrave; un passager doit rester  (en g&eacute;n&eacute;ral &agrave; bord de l&rsquo;avion ou dans l&rsquo;enceinte de l&rsquo;a&eacute;roport) bri&egrave;vement  avant de poursuivre son voyage vers sa destination finale.  
  <li><strong>1.16 Connexion&nbsp;:</strong> arr&ecirc;t entre le  point de d&eacute;part et le point de destination afin de changer de vol, pour  emprunter un vol vers la destination finale op&eacute;r&eacute; par la m&ecirc;me compagnie  a&eacute;rienne.  
  <li><strong>1.17 Segment&nbsp;:</strong> on d&eacute;signe par  segment un vol direct entre une ville et une autre, qui peut comporter ou non  des escales.  
  <li><strong>1.18 Surclassement&nbsp;:</strong> transfert d&rsquo;un  passager &agrave; une classe de transport sup&eacute;rieure &agrave; celle correspondant au billet  acquitt&eacute;.</li></ul>
    <h3>2. CONDITIONS  D&rsquo;ADH&Eacute;SION</h3>
    <ul><li><strong>2.1</strong> Le programme est ouvert uniquement aux personnes  physiques &acirc;g&eacute;es de 2 ans et plus, quelle que soit leur nationalit&eacute; ou leur lieu  de r&eacute;sidence, &agrave; condition qu&rsquo;elles (i) remplissent tous les crit&egrave;res requis,  (ii) compl&egrave;tent et remettent le formulaire d&rsquo;adh&eacute;sion, (iii) aient &eacute;t&eacute;  formellement accept&eacute;s par le Programme LANPASS et que leur qualit&eacute; de membre  n&rsquo;ait pas &eacute;t&eacute; r&eacute;voqu&eacute;e ou laiss&eacute;e sans effet conform&eacute;ment aux r&egrave;gles du pr&eacute;sent  r&egrave;glement.    
    <li><strong>2.2</strong> La demande d&rsquo;adh&eacute;sion au Programme LANPASS se fait en remplissant le  formulaire d&rsquo;adh&eacute;sion, disponible dans toutes les agences LAN, aupr&egrave;s des  Soci&eacute;t&eacute;s Partenaires ou par t&eacute;l&eacute;phone au Centre d&rsquo;Appels de LAN ou au moyen du  formulaire d&rsquo;adh&eacute;sion sur <a href="/sitio_personas/index.html">www.lan.com</a>.    
    <li><strong>2.3</strong> Une fois que LANPASS recevra la demande d&rsquo;adh&eacute;sion, le demandeur sera  inform&eacute; qu&rsquo;il a &eacute;t&eacute; accept&eacute; comme membre par l&rsquo;envoi d&rsquo;un courrier &eacute;lectronique  de bienvenue &agrave; l&rsquo;adresse &eacute;lectronique fournie par le membre. Au cas o&ugrave; il  n&rsquo;aurait pas re&ccedil;u la confirmation de son admission, le demandeur devra  t&eacute;l&eacute;phoner au num&eacute;ro de contact du Programme LANPASS, pour s&rsquo;informer du  r&eacute;sultat de sa demande.    
    <li><strong>2.4</strong> Ce courriel de bienvenue fournira des informations de base sur le  programme, confirmera le num&eacute;ro de membre LANPASS du nouveau membre et  indiquera un lien vers <a href="/sitio_personas/index.html">www.lan.com</a>, o&ugrave; le  membre pourra cr&eacute;er un mot de passe si l&rsquo;inscription a &eacute;t&eacute; faite par demande  &eacute;crite ou par un autre moyen ne fournissant pas de mot de passe pour l&rsquo;acc&egrave;s au  site Internet de LANPASS.    
    <li><strong>2.5</strong> Les kilom&egrave;tres LANPASS accumul&eacute;s par un candidat &agrave; l&rsquo;adh&eacute;sion au Programme  ne pourront pas &ecirc;tres &eacute;chang&eacute;s pour des Primes avant que le candidat ne soit  formellement accept&eacute; comme membre.    
    <li><strong>2.6</strong> Le membre est tenu responsable des donn&eacute;es fournies lors de la demande  d&rsquo;adh&eacute;sion ainsi que de leur mise &agrave; jour.    
    <li><strong>2.7</strong> L&rsquo;adresse postale indiqu&eacute;e par le membre ne peut pas &ecirc;tre une case postale  ou tout autre type d&rsquo;adresse qui ne soit pas desservie par la poste. LANPASS ne  saurait &ecirc;tre tenu responsable pour la non-distribution de correspondance &agrave; ce  type d&rsquo;adresse.    
    <li><strong>2.8</strong> Toute carte LANPASS est strictement personnelle et intransmissible.  L&rsquo;utilisation inad&eacute;quate, impropre ou non conforme aux pr&eacute;sentes conditions de  toute carte LANPASS pourra entra&icirc;ner la r&eacute;siliation du membre au programme  LANPASS et l&rsquo;annulation de tous les kilom&egrave;tres accumul&eacute;s, sans pr&eacute;judice des  actions l&eacute;gales n&eacute;cessaires.    
    <li><strong>2.9</strong> La personne &eacute;ligible et/ou le membre reconnaissent et acceptent &ecirc;tre les  seuls et uniques responsables de toute somme d&rsquo;argent, sous forme d&rsquo;imp&ocirc;ts,  taxes, droits ou autre, devant &ecirc;tre pay&eacute;e &agrave; toute personne, physique ou morale,  publique ou priv&eacute;e, r&eacute;sultant de l&rsquo;accumulation ou de l&rsquo;utilisation de  kilom&egrave;tres LANPASS, de l&rsquo;adh&eacute;sion au Programme LANPASS, ou de l&rsquo;utilisation de  toute Prime ou Avantage dudit Programme.    
    <li><strong>2.10</strong> Toute modification des donn&eacute;es fournies devra se faire par &eacute;crit en  apposant la signature du membre, aupr&egrave;s du Centre d&rsquo;Appels LAN une fois que  l&rsquo;identit&eacute; du membre est reconnue, ou sur la page Internet de LAN. Les demandes  de modifications faites verbalement ne seront pas trait&eacute;es, &agrave; l&rsquo;exception des  demandes de changement d&rsquo;adresse ou de num&eacute;ro de t&eacute;l&eacute;phone. Le membre peut  demander ces modifications en ligne ou par &eacute;crit aupr&egrave;s du Programme LANPASS.    
    <li><strong>2.11</strong> Un membre ne peut souscrire qu&rsquo;une seule adh&eacute;sion. Au cas o&ugrave; le membre  aurait deux ou plus de comptes, les comptes les plus r&eacute;cents seront supprim&eacute;s.  Tous les kilom&egrave;tres LANPASS accumul&eacute;s dans les comptes supprim&eacute;s seront  cr&eacute;dit&eacute;s sur le compte initial, &agrave; conditions que lesdits kilom&egrave;tres n&rsquo;aient pas  &eacute;t&eacute; accumul&eacute;s sur les deux comptes.    
    <li><strong>2.12</strong> Le transfert de kilom&egrave;tres LANPASS entre comptes du Programme LANPASS ou  entre des comptes du Programme LANPASS et des comptes des Compagnies A&eacute;riennes  Partenaires et/ou des Soci&eacute;t&eacute;s Partenaires n&rsquo;est pas autoris&eacute;. Il est  strictement interdit de vendre, c&eacute;der ou transf&eacute;rer des kilom&egrave;tres LANPASS ou  des primes obtenues gr&acirc;ce &agrave; ces kilom&egrave;tres par n&rsquo;importe quel moyen ou canal, y  compris Internet.    
    <li><strong>2.13</strong> Pour l&rsquo;obtention de Primes, les kilom&egrave;tres LANPASS de diff&eacute;rents comptes  du Programme LANPASS, ou de comptes des Compagnies A&eacute;riennes Partenaires et/ou  de Soci&eacute;t&eacute;s Partenaires ne pourront pas &ecirc;tre cumul&eacute;s.    
    <li><strong>2.14</strong> En compl&eacute;tant le formulaire d&rsquo;adh&eacute;sion, le membre accepte formellement de  recevoir &agrave; son adresse &eacute;lectronique et postale les informations du Programme et  les communications que LAN envoie de fa&ccedil;on p&eacute;riodique, qu&rsquo;elles soient li&eacute;es ou  non au Programme LANPASS.    
    <li><strong>2.15</strong> La forme et la p&eacute;riodicit&eacute; de l&rsquo;envoi des Relev&eacute;s de Compte, des  Informations sur les Avantages ou les membres, et autres communications seront  fix&eacute;es librement par LAN, qui pourra &agrave; cette fin utiliser des moyens physiques  (comme les services postaux publics ou priv&eacute;s) ou &eacute;lectroniques (comme les  adresses &eacute;lectroniques ou autres).    
    <li><strong>2.16</strong> Outre ce qui est &eacute;tabli au paragraphe pr&eacute;c&eacute;dent, en compl&eacute;tant le  formulaire d&rsquo;adh&eacute;sion, la personne &eacute;ligible au programme ou le membre acceptent  que LAN peut disposer librement des donn&eacute;es fournies dans ledit formulaire, que  ce soit au b&eacute;n&eacute;fice du Programme, de LAN ou de tiers. La participation au  Programme LANPASS a pour condition sine qua non que l&rsquo;accumulation de  kilom&egrave;tres se fasse conform&eacute;ment aux conditions g&eacute;n&eacute;rales de ce Programme et  dans la stricte conformit&eacute; aux normes applicables.</li></ul>
      <h3>3. R&Eacute;SILIATION DE LA PARTICIPATION  D&rsquo;UN MEMBRE AU PROGRAMME</h3>
      <ul><li><strong>3.1</strong> La participation d&rsquo;un membre au Programme LANPASS sera r&eacute;sili&eacute;e dans les  cas suivants:</li>
      <li><strong>3.1.1</strong> Si le membre cesse de remplir tout crit&egrave;re ou condition ici d&eacute;crits, ou si  l&rsquo;utilisation du Programme LANPASS ou de l&rsquo;accumulation de kilom&egrave;tres comporte  une infraction de la loi ou des normes applicables.</li>
      <li><strong>3.1.2</strong> Si le membre, en connaissance de cause, fournit des informations  incorrectes ou erron&eacute;es (y compris des informations sur les vols), que ce soit  lors de sa demande d&rsquo;adh&eacute;sion ou au moment de demander les Primes.</li>
      <li><strong>3.1.3</strong> Si le membre viole les conditions du contrat de transport de passagers  (qui s&rsquo;appliquent &agrave; tous les passagers).</li>
      <li><strong>3.1.4</strong> Si le membre utilise de fa&ccedil;on impropre ou inad&eacute;quate les Primes et/ou  Avantages accord&eacute;s.</li>
      <li><strong>3.1.5</strong> Si le membre a une dette &eacute;chue pour laquelle LAN, ou toute soci&eacute;t&eacute;  partenaire ou associ&eacute;e, est accr&eacute;diteur, ou qu&rsquo;il y a des indices ou des  pr&eacute;somptions que le membre participe &agrave; des d&eacute;lits commis &agrave; l&rsquo;encontre desdites  soci&eacute;t&eacute;s, comme l&rsquo;encaissement frauduleux de cheques ou autre.</li>
      <li><strong>3.1.6</strong> Suite &agrave; une demande formelle du membre, qu&rsquo;il peut faire &agrave; tout moment,  par &eacute;crit et, dans le cas d&rsquo;un membre Elite, en joignant sa carte de membre  coup&eacute;e en deux.</li>
      <li><strong>3.1.7</strong> Suite au d&eacute;c&egrave;s du membre.</li>
      <li><strong>3.1.8</strong> S&rsquo;il serait mis fin au Programme LANPASS pour une quelconque raison.</li>
      <li><strong>3.1.9</strong> Unilat&eacute;ralement par LANPASS, &agrave; tout moment, avec un pr&eacute;avis notifi&eacute;.</li>
      <li><strong>3.2</strong> Au cas o&ugrave; la participation du membre au Programme LANPASS &eacute;tait r&eacute;sili&eacute;e,  ou que ledit programme &eacute;tait supprim&eacute;, tous les kilom&egrave;tres accumul&eacute;s seront  annul&eacute;s et ne pourront &ecirc;tre utilis&eacute;s d&rsquo;aucune fa&ccedil;on ni &ecirc;tre &eacute;chang&eacute;s pour des  billets et/ou de l&rsquo;argent.</li></ul>
      <h3>4. SUSPENSION DES  DROITS DU MEMBRE</h3>
      <ul><li><strong>4.1</strong> LANPASS pourra suspendre temporairement les droits et avantages du membre.  Celui-ci ne perdra pas son statut, il pourra continuer d&rsquo;accumuler des  kilom&egrave;tres mais ne pourra pas les &eacute;changer contre des primes ni demander aucun  Avantage du Programme tant que LANPASS, en sa qualit&eacute; de membre de plein droit,  ne r&eacute;voque pas cette suspension.</li>
      <li><strong>4.2</strong> Le droit de suspension pourra &ecirc;tre exerc&eacute; par LANPASS si le membre a une  dette &eacute;chue avec LAN ou ses soci&eacute;t&eacute;s partenaires ou affili&eacute;es, ou qu&rsquo;il y ait  des indices ou des pr&eacute;somptions que le membre a particip&eacute; &agrave; des d&eacute;lits commis &agrave;  l&rsquo;encontre desdites soci&eacute;t&eacute;s, comme le virement d&rsquo;un ch&egrave;que frauduleux ou autre.</li>
      <li><strong>4.3</strong> L&rsquo;article 4.2 est sans pr&eacute;judice des dispositions sur la perte du statut,  conform&eacute;ment au pr&eacute;sent r&egrave;glement.</li></ul>
      <h3>5. CARTE DE MEMBRE OU CARTE LANPASS</h3>
      <ul><li><strong>5.1</strong> Uniquement dans le cas des statuts concern&eacute;s, la carte a une p&eacute;riode de  validit&eacute; ind&eacute;finie. Les cartes de membre LANPASS Premium, LANPASS Premium  Silver et LANPASS Comodoro ont une p&eacute;riode de validit&eacute; conforme &agrave; ce qui est  &eacute;nonc&eacute; dans les d&eacute;tails du Programme sur <a href="/sitio_personas/index.html">www.lan.com</a>,  d&eacute;tails qui peuvent &ecirc;tre modifi&eacute;s selon les dispositions du paragraphe 6. Pour  les effets de ce r&egrave;glement, &laquo;&nbsp;ann&eacute;e civile&nbsp;&raquo; d&eacute;signe la p&eacute;riode entre  le 1er janvier et le 31 d&eacute;cembre de chaque ann&eacute;e.</li>
      <li><strong>5.2</strong> Les cartes &eacute;mises par les Soci&eacute;t&eacute;s Partenaires sont valables conform&eacute;ment  aux conditions des soci&eacute;t&eacute;s respectives, mais restent toujours soumises au  pr&eacute;sent r&egrave;glement, lorsque c&rsquo;est pertinent.</li>
      <li><strong>5.3</strong> La personne dont le nom figure sur la carte de membre est la seule  personne qui a le droit de l&rsquo;utiliser &agrave; toutes fins.</li>
      <li><strong>5.4</strong> La carte de membre n&rsquo;est pas une carte de cr&eacute;dit ni une pi&egrave;ce d&rsquo;identit&eacute;,  elle ne conf&egrave;re donc nul autre droit que ceux qui sont &eacute;nonc&eacute;s dans le pr&eacute;sent  r&egrave;glement.</li>
      <li><strong>5.5</strong> Les cartes de membre appartiennent exclusivement &agrave; LAN.</li>
      <li><strong>5.6</strong> En cas de perte ou de vol de sa carte, le membre est tenu d&rsquo;informer  imm&eacute;diatement LANPASS &agrave; l&rsquo;agence LAN la plus proche ou par t&eacute;l&eacute;phone. Apr&egrave;s  avoir &eacute;valu&eacute; les ant&eacute;c&eacute;dents du cas, LANPASS pourra &eacute;mettre une nouvelle carte  dans un d&eacute;lai de 30 jours, &agrave; compter de la date o&ugrave; la perte a &eacute;t&eacute; communiqu&eacute;e.</li></ul>
      <h3>6. STATUT DE MEMBRE</h3>
      <ul><li><strong>6.1</strong> Le Programme LANPASS comporte quatre statuts de membre&nbsp;: (a) LANPASS,  (b) Premium, (c) Premium Silver et (d) Comodoro. Seuls les trois derniers  statuts donnent droit &agrave; une carte de membre.</li>
      <li><strong>6.2</strong> Les diff&eacute;rents statuts de membre sont fix&eacute;s selon les crit&egrave;res &eacute;tablis  pour acc&eacute;der &agrave; chaque statut, d&eacute;crits &agrave; la rubrique LANPASS de la page Internet <a href="/sitio_personas/index.html">www.lan.com</a>.</li>
      <li><strong>6.3</strong> Le statut qui correspond &agrave; chaque membre est fix&eacute; par&nbsp;: le nombre de  kilom&egrave;tres parcourus dans les tarifs qui permettent d&rsquo;accumuler des kilom&egrave;tres  avec LAN ou avec n&rsquo;importe quelle Compagnie A&eacute;rienne Associ&eacute;e &agrave; oneworld, outre  les bonus par classes de transport sur les vols LAN (classe Affaires) dont le  membre ait pu b&eacute;n&eacute;ficier. Ceci &agrave; condition d&rsquo;avoir parcouru quatre segments au  minimum avec LAN&nbsp;; ou par le nombre de segments parcourus avec LAN dans  des tarifs qui permettent d&rsquo;accumuler des kilom&egrave;tres. N&rsquo;importe laquelle de ces  conditions doit &ecirc;tre remplie en une ann&eacute;e civile au maximum. Les statuts  Comodoro et Premium Silver sont fix&eacute;s par un nombre inf&eacute;rieur de kilom&egrave;tres,  parmi lesquels doivent figurer certains vols en classe Affaires dans des vols  long-courriers. Les vols d&eacute;finis comme long-courriers et le nombre de  kilom&egrave;tres requis pour chaque statut sont d&eacute;crits sur <a href="/sitio_personas/index.html">www.lan.com</a>.</li>
      <li><strong>6.4</strong> Les kilom&egrave;tres LANPASS accumul&eacute;s aupr&egrave;s des Soci&eacute;t&eacute;s Partenaires et/ou des  Compagnies A&eacute;riennes Partenaires ne seront pas comptabilis&eacute;s pour d&eacute;terminer le  statut de membre, sauf disposition contraire.</li>
      <li><strong>6.5</strong> Les tron&ccedil;ons effectu&eacute;s lors de l&rsquo;utilisation d&rsquo;une Prime ou d&rsquo;un Avantage  ou de tout autre billet ne seront pas non plus qualifiants pour accumuler des  kilom&egrave;tres LANPASS.</li>
      <li><strong>6.6</strong> La dur&eacute;e d&rsquo;appartenance &agrave; un statut donn&eacute; correspond &agrave; l&rsquo;ann&eacute;e qui suit  l&rsquo;ann&eacute;e d&rsquo;accumulation des kilom&egrave;tres et au temps qu&rsquo;il reste de l&rsquo;ann&eacute;e o&ugrave; le  membre a rempli les crit&egrave;res &eacute;tablis pour conserver son statut.</li>
      <li><strong>6.7</strong> LANPASS pourra librement maintenir ou augmenter le statut d&rsquo;un membre m&ecirc;me  s&rsquo;il n&rsquo;a pas rempli tous les crit&egrave;res &eacute;tablis, mais ne pourra jamais diminuer  son statut s&rsquo;il remplit les crit&egrave;res requis pour le conserver.</li>
      <li><strong>6.8</strong> Si un membre ne remplit pas les crit&egrave;res pour renouveler son statut, il  passera l&rsquo;ann&eacute;e suivante au statut imm&eacute;diatement inf&eacute;rieur au statut auquel il  appartenait, m&ecirc;me s&rsquo;il ne remplit pas les crit&egrave;res pour acc&eacute;der &agrave; ce statut.</li>
      <li><strong>6.9</strong> &Agrave; partir de l&rsquo;ann&eacute;e 2004, les renouvellements se feront le 31 mars de  chaque ann&eacute;e, et prennent en compte les crit&egrave;res remplis par le membre l&rsquo;ann&eacute;e  civile pr&eacute;c&eacute;dente.</li>
      <li><strong>6.10</strong> Les changements de statut de membre ne modifieront pas le solde des  kilom&egrave;tres &eacute;changeables contre des primes et vice-versa.</li></ul>
      <h3>7. KILOM&Egrave;TRES</h3>
      <ul><li><strong>7.1</strong> L&rsquo;unit&eacute; de mesure du Programme LANPASS est le  kilom&egrave;tre.</li>
      <li><strong>7.1.1</strong> Les demandes de cr&eacute;dit r&eacute;troactif de kilom&egrave;tres accumul&eacute;s par les services  des Compagnies A&eacute;riennes Partenaires ne seront trait&eacute;es que si le membre remet  ses documents de vols (carte d&rsquo;embarquement et re&ccedil;u du Billet). Si le membre ne  remet pas ces documents certifiant que le vol a &eacute;t&eacute; effectu&eacute;, la demande ne  sera pas trait&eacute;e.</li>
      <li><strong>7.2</strong> Les kilom&egrave;tres pr&eacute;sentent les caract&eacute;ristiques suivantes et sont soumis  aux conditions &eacute;nonc&eacute;es ci-apr&egrave;s&nbsp;:</li>
      <li><strong>7.2.1</strong> Ils n&rsquo;ont aucune valeur marchande, ne peuvent &ecirc;tre achet&eacute;s, vendus ou &eacute;chang&eacute;s  contre de l&rsquo;argent ou une quelconque contrepartie.</li>
      <li><strong>7.2.2 </strong>Ils ne peuvent pas &ecirc;tre transf&eacute;r&eacute;s, &agrave; titre gratuit comme &agrave; titre on&eacute;reux.</li>
      <li><strong>7.2.3</strong> Ils sont intransmissibles, par cons&eacute;quent, en cas de d&eacute;c&egrave;s du membre, le  compte et les kilom&egrave;tres qui y sont accumul&eacute;s seront annul&eacute;s.</li>
      <li><strong>7.2.4</strong> Ils sont insaisissables, car il s&rsquo;agit de droits dont l&rsquo;exercice est  enti&egrave;rement individuel.</li>
      <li><strong>7.2.5</strong> Ils ne font pas l&rsquo;objet de disputes l&eacute;gales ou d&rsquo;aucune mesure judiciaire,  et n&rsquo;appartiennent qu&rsquo;au membre titulaire du compte, comme un droit individuel.</li>
      <li><strong>7.2.6</strong> Les primes &eacute;chang&eacute;es ne sont pas remboursables. Si le membre demande  l&rsquo;annulation d&rsquo;une prime &eacute;mise, il devra s&rsquo;acquitter d&rsquo;une surcharge en  kilom&egrave;tres. Ladite surcharge varie selon le type de prime, conform&eacute;ment aux  dispositions indiqu&eacute;es sur <a href="/sitio_personas/index.html">www.lan.com</a>. Pour  qu&rsquo;une prime soit annul&eacute;e, le billet &eacute;mis doit &ecirc;tre valable (la p&eacute;riode de  validit&eacute; du billet commence au moment de son &eacute;mission), la d&eacute;marche doit se  faire avant le d&eacute;part du vol sans avoir parcouru aucun segment de celui-ci, &agrave;  l&rsquo;exception des surclassements &agrave; Oneworld, et les kilom&egrave;tres &eacute;chang&eacute;s pour  l&rsquo;&eacute;mission du billet prime doivent encore &ecirc;tre valables au moment de solliciter  l&rsquo;annulation.</li>
      <li><strong>7.2.7</strong> Les primes ne sont pas endossables, et ne peuvent donc pas &ecirc;tre utilis&eacute;es  dans d&rsquo;autres soci&eacute;t&eacute;s que LAN ou les Compagnies A&eacute;riennes Partenaires, ni par  d&rsquo;autres personnes que celles que le membre d&eacute;signe, suivant la prime obtenue.  Une fois qu&rsquo;un billet prime est &eacute;mis, il ne pourra &ecirc;tre utilis&eacute; qu&rsquo;avec la  compagnie a&eacute;rienne qui y est indiqu&eacute;e.</li></ul>
      <h3>8. Accumulation de kilom&egrave;tres</h3>
      <ul><li><strong>8.1</strong> Les kilom&egrave;tres sont cr&eacute;dit&eacute;s lorsqu&rsquo;un membre empruntera des vols LAN ou  des Compagnies A&eacute;riennes Partenaires, &agrave; condition qu&rsquo;il s&rsquo;agisse de vols op&eacute;r&eacute;s  par lesdites compagnies, ou lorsqu&rsquo;il utilise les services autoris&eacute;s dans les  soci&eacute;t&eacute;s partenaires. Si le membre est &agrave; la fois membre du programme LANPASS et  du programme de fid&eacute;lit&eacute; de la Soci&eacute;t&eacute; Partenaire, les kilom&egrave;tres ne pourront  &ecirc;tre cr&eacute;dit&eacute;s que sur un compte, au choix du membre. Les kilom&egrave;tres ne pourront  en aucun cas &ecirc;tre cr&eacute;dit&eacute;s sur plus d&rsquo;un compte. Le membre devra indiquer son  num&eacute;ro de membre, qui devra figurer sur la carte d&rsquo;embarquement.<br>
        En ce qui concerne l&rsquo;accumulation de kilom&egrave;tres,  tout vol op&eacute;r&eacute; par n&rsquo;importe quelle compagnie a&eacute;rienne, mais qui pour une  quelconque raison utilise un code LAN sur son billet sera consid&eacute;r&eacute; valable  pour accumuler des kilom&egrave;tres et devenir &eacute;ligible aux statuts Premium, Premium  Silver et Comodoro, &agrave; condition qu&rsquo;il ait &eacute;t&eacute; &eacute;mis dans des tarifs qui  permettent d&rsquo;accumuler des kilom&egrave;tres LANPASS.</li>
      <li><strong>8.2</strong> Conform&eacute;ment aux restrictions fix&eacute;es par les Compagnies A&eacute;riennes  Partenaires, la forme et la quantit&eacute; des kilom&egrave;tres &agrave; accumuler par les vols  op&eacute;r&eacute;s par celles-ci ne co&iuml;ncideront pas forc&eacute;ment avec les conditions fix&eacute;es  par LAN pour ses vols et d&eacute;pendront des restrictions du tarif acquitt&eacute; ou des  conditions fix&eacute;es par ladite Compagnie A&eacute;rienne Partenaire, certains tarifs ou  vols ne permettant de cumuler qu&rsquo;un certain pourcentage de la distance  parcourue, ou d&rsquo;autres restrictions pouvant exister. Le membre est tenu de se  renseigner sur les kilom&egrave;tres &agrave; accumuler par les vols r&eacute;alis&eacute;s avec les  Compagnies A&eacute;riennes Partenaires.</li>
      <li><strong>8.3</strong> Les vols de compagnies a&eacute;riennes tierces op&eacute;r&eacute;s par LAN ne permettent pas  d&rsquo;accumuler des kilom&egrave;tres, au m&ecirc;me titre que les vols commercialis&eacute;s par des  compagnies a&eacute;riennes oneworld et op&eacute;r&eacute;s par des compagnies tierces.</li>
      <li><strong>8.4</strong> Les kilom&egrave;tres parcourus avant l&rsquo;adh&eacute;sion au programme ne pourront &ecirc;tre  cr&eacute;dit&eacute;s qu&rsquo;&agrave; condition que le voyage ait &eacute;t&eacute; fait avec LAN, et pas au plus de  deux mois avant la date d&rsquo;adh&eacute;sion.</li>
      <li><strong>8.5</strong> Les kilom&egrave;tres seront cr&eacute;dit&eacute;s sur le compte du membre une fois que le  voyage aura &eacute;t&eacute; r&eacute;alis&eacute; et que le billet respectif aura &eacute;t&eacute; pay&eacute;. Par  cons&eacute;quent, les kilom&egrave;tres obtenus par des billets acquis mais non utilis&eacute;s ou  non pay&eacute;s ne seront pas cr&eacute;dit&eacute;s. Le membre devra donc conserver et fournir si  on le lui demandait les documents accr&eacute;ditant le vol r&eacute;alis&eacute; (billet et carte  d&rsquo;embarquement).</li>
      <li><strong>8.6</strong> Les kilom&egrave;tres obtenus par les services pr&ecirc;t&eacute;s par les Compagnies  A&eacute;riennes Partenaires ou les Soci&eacute;t&eacute;s Partenaires ne seront cr&eacute;dit&eacute;s sur le  compte du membre qu&rsquo;une fois que la Compagnie A&eacute;rienne ou Soci&eacute;t&eacute; Partenaire  respective remettront les informations requises par LAN pour ce cr&eacute;dit, qui, en  g&eacute;n&eacute;ral, se fera dans les 30 jours apr&egrave;s le service fourni au membre.</li>
      <li><strong>8.8</strong> Les kilom&egrave;tres cumul&eacute;s par vol avec LAN sont valables 36 mois continus, &agrave;  compter de la date du vol. En tous cas, la date de p&eacute;remption des kilom&egrave;tres  est fix&eacute;e au dernier jours du mois de p&eacute;remption.<br>
      Les kilom&egrave;tres accumul&eacute;s par vol avec les Compagnies  A&eacute;riennes Partenaires, en utilisant n&rsquo;importe quel service des soci&eacute;t&eacute;s  partenaires ou des bons promotionnels, ont une p&eacute;riode de validit&eacute; de 3 ann&eacute;es  civiles, c&rsquo;est-&agrave;-dire qu&rsquo;ils arrivent &agrave; &eacute;ch&eacute;ance le 31 d&eacute;cembre de la troisi&egrave;me  ann&eacute;e apr&egrave;s l&rsquo;ann&eacute;e d&rsquo;accumulation desdits kilom&egrave;tres.<br>
      Cependant, &agrave; chaque fois que le passager voyage avec  LAN et accumule 1 kilom&egrave;tre ou plus par ce vol, tous les kilom&egrave;tres accumul&eacute;s  en vigueur sur son compte avant la date dudit vol seront automatiquement  renouvel&eacute;s, et seront d&egrave;s lors valables 36 mois d&rsquo;affil&eacute;e, &agrave; compter de la date  dudit vol et arriveront &agrave; &eacute;ch&eacute;ance le dernier jour du trente-sixi&egrave;me mois.<br>
      En tous cas, les kilom&egrave;tres accumul&eacute;s avant le 1er  mai 1998 seront valables jusqu&rsquo;au 31 d&eacute;cembre de la troisi&egrave;me ann&eacute;e apr&egrave;s  l&rsquo;ann&eacute;e o&ugrave; les kilom&egrave;tres ont effectivement &eacute;t&eacute; parcourus, conform&eacute;ment aux  r&egrave;gles indiqu&eacute;es dans les paragraphes pr&eacute;c&eacute;dents, quelle que soit la r&egrave;gle qui  b&eacute;n&eacute;ficie le plus le membre.<br>
      LANPASS d&eacute;cline toute responsabilit&eacute; d&rsquo;informer les  membres sur la date d&rsquo;expiration de leurs kilom&egrave;tres, conform&eacute;ment aux r&egrave;gles  sur l&rsquo;expiration des kilom&egrave;tres indiqu&eacute;es dans les pr&eacute;sentes conditions.</li>
      <li><strong>8.9</strong> Les kilom&egrave;tres qui figurent sur le Relev&eacute; de compte sont &eacute;changeables  contre des Primes et/ou Avantages. Les kilom&egrave;tres parcourus avec LAN et les  compagnies a&eacute;riennes de oneworld, y compris les bonus de classe de transport  sur LAN, servent aussi &agrave; d&eacute;terminer le statut de membre LANPASS.</li>
      <li><strong>8.10</strong> Les Primes et/ou B&eacute;n&eacute;fices du programme LANPASS parcourus avec LAN ou tout  autre Compagnie A&eacute;rienne Partenaire, ainsi que les primes de services des  soci&eacute;t&eacute;s partenaires ne permettent pas d&rsquo;accumuler des kilom&egrave;tres.<br>
      Les Primes et/ou Avantages &eacute;mis dans les tarifs  r&eacute;duits du secteur du tourisme, des vols charters, les bilets &eacute;mis pour les  employ&eacute;s des compagnies a&eacute;riennes, les r&eacute;ductions pour les membres du  gouvernement, les billets gratuits ou tout autre type de billet o&ugrave; le tarif  n&rsquo;est pas indiqu&eacute; ne permettent pas d&rsquo;accumuler des kilom&egrave;tres. L&rsquo;exclusion  d&rsquo;autres types de billets peut &ecirc;tre d&eacute;cid&eacute;e &agrave; tout moment par LAN qui en  informera opportun&eacute;ment et conform&eacute;ment ses membres.</li>
      <li><strong>8.11</strong> Les Primes et/ou B&eacute;n&eacute;fices endoss&eacute;s &agrave; d&rsquo;autres compagnies a&eacute;riennes par  LAN accumuleront les kilom&egrave;tres &eacute;quivalents, comme s&rsquo;ils avaient effectivement  &eacute;t&eacute; parcourus avec LAN, uniquement dans les situations ind&eacute;pendantes de la  volont&eacute; de LAN. Les Primes et/ou B&eacute;n&eacute;fices endoss&eacute;s par les compagnies  a&eacute;riennes oneworld ou associ&eacute;es &agrave; des tiers ne sont pas qualifiants.</li>
      <li><strong>8.12</strong> En cas de surclassement obtenu comme prime ou comme courtoisie de LAN ou  de toute Compagnie A&eacute;rienne Partenaire ou Soci&eacute;t&eacute; Partenaire, seuls les  kilom&egrave;tres accumul&eacute;s par la classe pay&eacute;e par le membre, et non les kilom&egrave;tres  correspondant &agrave; la classe sup&eacute;rieure dans laquelle le membre a voyag&eacute; de par ce  surclassement, seront cr&eacute;dit&eacute;s.</li>
      <li><strong>8.13</strong> Le membre est tenu de v&eacute;rifier que les kilom&egrave;tres correspondant &agrave; ses vols  avec LAN et/ou avec les Compagnies A&eacute;riennes Partenaires, ainsi que les  kilom&egrave;tres accumul&eacute;s par les services des Soci&eacute;t&eacute;s Partenaires, soient cr&eacute;dit&eacute;s  correctement sur son compte.<br>
      Pour cela, le membre devra conserver tous ses  documents de vol (cartes d&rsquo;embarquement, re&ccedil;u passager du Billet) ainsi que les  originaux des factures ou contrats, afin de pouvoir r&eacute;clamer le cr&eacute;dit  r&eacute;troactif desdits kilom&egrave;tres. Les kilom&egrave;tres non cr&eacute;dit&eacute;s ne pourront en aucun  cas &ecirc;tre cr&eacute;dit&eacute;s au-del&agrave; d&rsquo;un (1) an&nbsp;  apr&egrave;s le vol ou acte qui les a accumul&eacute;s, &agrave; moins que les Soci&eacute;t&eacute;s  Partenaires ne l&rsquo;autorisent pour les kilom&egrave;tres accumul&eacute;es par leur biais.</li>
      <li><strong>8.14</strong> LANPASS se r&eacute;serve le droit d&rsquo;auditer le compte d&rsquo;un membre &agrave; tout moment  et sans pr&eacute;avis notifi&eacute;, afin de s&rsquo;assurer du respect de ces conditions  g&eacute;n&eacute;rales. LANPASS pourra annuler les kilom&egrave;tres accumul&eacute;s ind&ucirc;ment par un  membre, ainsi que reporter le traitement de Primes ou certificats jusqu&rsquo;&agrave; ce  que les irr&eacute;gularit&eacute;s soient r&eacute;solues. Le membre devra en &ecirc;tre inform&eacute;.</li>
      <li><strong>8.15</strong> Au cas o&ugrave; les Primes et/ou Avantages qualifiants pour accumuler des  kilom&egrave;tres LANPASS soient acquis &agrave; cr&eacute;dit, ou que le paiement de ceux-ci soit  diff&eacute;r&eacute; dans le temps, le membre pourra obtenir des Primes et/ou Avantages avec  les kilom&egrave;tres correspondant au billet acquis ou &agrave; tout autre billet, &agrave;  condition que les billets respectifs soient acquitt&eacute;s conform&eacute;ment &agrave; ce qui a  &eacute;t&eacute; accord&eacute; au moment d&rsquo;acheter la Prime et/ou l&rsquo;Avantage.</li>
      <li><strong>8.16</strong> Le membre est tenu responsable de respecter la loi et les r&eacute;glementations qui  pourraient &ecirc;tre applicables aux effets de sa participation au Programme LANPASS  et &agrave; l&rsquo;accumulation de kilom&egrave;tres, en particulier les membres qui sont  fonctionnaires publics.</li></ul>
      
      <h3>9. Echange Flexible LANPASS</h3>
      <ul><li><strong>9.1</strong> Pour demander un Prime et/ou Avantage, le membre doit disposer d&rsquo;un num&eacute;ro  de membre en vigueur et des kilom&egrave;tres requis pour obtenir la Prime souhait&eacute;e.  Le nombre de kilom&egrave;tres requis pour acc&eacute;der &agrave; une Prime et/ou un Avantage est  indiqu&eacute; dans le Bar&egrave;me de Primes en vigueur &agrave; la date de la demande.</li>
      <li><strong>9.2</strong> Les kilom&egrave;tres requis pour obtenir une Prime et/ou Avantage varient  suivant le type de Prime et la classe souhait&eacute;e. La classe Economy a trois  niveaux de Primes&nbsp;: Classic, Plus et Full (ordonn&eacute;s en ordre croissant  selon le nombre de kilom&egrave;tres requis). La cabine Premium Business n&rsquo;a qu&rsquo;un  seul niveau de Primes.</li>
      <li><strong>9.3</strong> Le surclassement ne peut &ecirc;tre demand&eacute; que pour la classe Premium Business.</li>
      <li><strong>9.4</strong> Le nombre de places pour chaque type de Prime et/ou Avantage est limit&eacute;.</li>
      <li><strong>9.5</strong> Pour solliciter une Prime, le membre peut t&eacute;l&eacute;phoner au Centre d&rsquo;Appels de  LAN (option LANPASS), se rendre sur la page web <a href="/sitio_personas/index.html">www.lan.com</a> ou s&rsquo;adresser aux agences LAN ou aux agences de voyage. Il faut dans tous les  cas fournir une pi&egrave;ce d&rsquo;identit&eacute;. Sur lan.com, un nom d&rsquo;utilisateur et un mot  de passe sont requis.</li>
      <li><strong>9.6</strong> Pour obtenir des primes par le biais du Centre d&rsquo;Appels LAN (option  LANPASS), des Agences LAN ou des agences de voyage, le membre doit s&rsquo;acquitter  de frais de dossier (Service Fee LANPASS) pour chaque billet &eacute;mis. Si la Prime  est demand&eacute;e sur <a href="/sitio_personas/index.html">www.lan.com</a>, les frais de  dossier ne sont pas factur&eacute;s. Le Service Fee LANPASS est ind&eacute;pendant des taxes  d&rsquo;embarquement et imp&ocirc;ts applicables et varie selon le type de Prime obtenue,  selon le Bar&egrave;me de Primes publi&eacute; sur <a href="/sitio_personas/index.html">www.lan.com</a>.</li>
      <li><strong>9.7</strong> La demande de Prime peut &ecirc;tre faite par toute personne fournissant un  pouvoir d&ucirc;ment souscrit par le membre, indiquant&nbsp;: le nom complet du  membre, son num&eacute;ro de compte et/ou son num&eacute;ro de carte d&rsquo;identit&eacute; (R.U.T), et  le nom de la Prime sollicit&eacute;e. Il faut y joindre une photocopie d&rsquo;une pi&egrave;ce  d&rsquo;identit&eacute; (carte d&rsquo;identit&eacute;, passeport ou &eacute;quivalent).</li>
      <li><strong>9.8</strong> Les primes ont une p&eacute;riode validit&eacute; d&rsquo;un an (12 mois), &agrave; compter de leur  date d&rsquo;&eacute;mission&nbsp;; au-del&agrave; de laquelle elles arrivent imm&eacute;diatement &agrave;  &eacute;ch&eacute;ance.</li>
      <li><strong>9.9</strong> Les Primes accord&eacute;es sont des primes &laquo;&nbsp;aller et retour&nbsp;&raquo;. Il  n&rsquo;est pas possible d&rsquo;obtenir des primes Oneway. L&rsquo;embarquement sur le vol  retour sera refus&eacute; au membre s&rsquo;il n&rsquo;a pas effectu&eacute; le vol aller. Si le membre  n&rsquo;utilise sa Prime que pour le vol aller, les kilom&egrave;tres correspondant au vol  retour ne lui seront pas rendus ou rembours&eacute;s.</li>
      <li><strong>9.10</strong> Les surclassements peuvent &ecirc;tre obtenus Oneway (uniquement pour le trajet  aller ou uniquement pour le trajet retour) ou &laquo;&nbsp;aller et retour&nbsp;&raquo;.</li>
      <li><strong>9.11</strong> Les primes &eacute;mises sont nominatives, elles ne peuvent pas &ecirc;tre c&eacute;d&eacute;es ou  transf&eacute;r&eacute;es &agrave; des tiers.</li>
      <li><strong>9.13</strong> La r&eacute;servation et l&rsquo;&eacute;mission d&rsquo;une Prime doivent se faire simultan&eacute;ment.</li>
      <li><strong>9.14</strong> LANPASS se r&eacute;serve le droit de reporter des Primes s&rsquo;il constate une  irr&eacute;gularit&eacute; dans la demande ou l&rsquo;utilisation de celles-ci. Toute infraction  des pr&eacute;sentes conditions g&eacute;n&eacute;rales pourra pousser LANPASS &agrave; refuser d&rsquo;accorder  une Prime ou &agrave; r&eacute;silier le contrat d&rsquo;adh&eacute;sion du membre au Programme LANPASS,  cette r&eacute;siliation entra&icirc;nant imm&eacute;diatement l&rsquo;annulation de tous les kilom&egrave;tres  accumul&eacute;s sur le compte du membre.</li>
      <li><strong>9.15</strong> Le membre peut demander l&rsquo;&eacute;change d&rsquo;une Prime avant le d&eacute;but de son voyage,  et au plus tard 48 heures avant le d&eacute;part. L&rsquo;&eacute;change de Primes d&eacute;j&agrave; utilis&eacute;es  en partie n&rsquo;est pas autoris&eacute;. En cas d&rsquo;&eacute;change, la validit&eacute; de la Prime n&rsquo;est  pas &eacute;tendue. Par cons&eacute;quent, la Prime &eacute;chang&eacute;e restera valable pendant la  p&eacute;riode de validit&eacute; qu&rsquo;il restait &agrave; la Prime initiale.</li>
      <li><strong>9.16 </strong>L&rsquo;&eacute;change des Primes n&rsquo;est possible que contre des Primes qui requi&egrave;rent  autant ou moins de kilom&egrave;tres.</li>
      <li><strong>9.17 </strong>L&rsquo;&eacute;change des Primes n&rsquo;est possible qu&rsquo;&agrave; condition que des Primes qui  requi&egrave;rent autant ou moins de kilom&egrave;tres soient disponibles.</li>
      <li><strong>9.18</strong> Lors de l&rsquo;&eacute;change d&rsquo;une Prime contre une autre Prime qui requi&egrave;re moins de  kilom&egrave;tres, les kilom&egrave;tres non utilis&eacute;s ne seront pas rendus au membre, &agrave; moins  qu&rsquo;il ne demande un autre &eacute;change contre une Prime qui requi&egrave;re autant ou moins  de kilom&egrave;tres que ceux qui &eacute;taient requis par la Prime initiale, auquel cas il  pourra utiliser son solde de kilom&egrave;tres pour sa seconde Prime. Pour les  modifications ult&eacute;rieures de date, le nombre initial de kilom&egrave;tres est  maintenu.</li>
      <li><strong>9.19</strong> Les &eacute;changes volontaires doivent se faire dans la m&ecirc;me classe que le  billet d&rsquo;origine, &agrave; moins que la classe d&rsquo;origine n&rsquo;existe pas sur le nouveau  vol.&nbsp;Dans ce cas, la Prime pourra &ecirc;tre &eacute;mise dans une classe inf&eacute;rieure,  le membre devant d&egrave;s lors renoncer &agrave; la diff&eacute;rence de kilom&egrave;tres non utilis&eacute;e.</li>
      <li><strong>9.20</strong> Les &eacute;changes de Primes &eacute;mis avant le 4 ao&ucirc;t 2009 seront soumis aux  conditions g&eacute;n&eacute;rales en vigueur au moment de l&rsquo;&eacute;mission.</li>
      <li><strong>9.21</strong> La modification de date, de trajet ou de vol des Primes n&rsquo;est autoris&eacute;e  qu&rsquo;&agrave; condition de n&rsquo;avoir utilis&eacute; aucun des coupons. Cette modification demande  le paiement d&rsquo;une amende pour modification. Celle-ci est variable suivant le  pays d&rsquo;&eacute;mission du billet et le trajet. Les amendes pour modification sont  d&eacute;crites sur <a href="/sitio_personas/index.html">www.lan.com</a>. Les Primes &eacute;mises  pour des vols avec les Compagnies A&eacute;riennes Partenaires de l&rsquo;alliance oneworld  ne permettent que des changements de date et/ou d&rsquo;heure, et ne permettent pas  de modifications d&rsquo;itin&eacute;raire, de compagnie a&eacute;rienne ou de stopover programm&eacute;  au pr&eacute;alable.</li>
      <li><strong>9.22</strong> Dans les cas o&ugrave; le membre demande l&rsquo;annulation d&rsquo;une Prime &eacute;mise, il devra  s&rsquo;acquitter d&rsquo;une surcharge en kilom&egrave;tres. Celle-ci est variable suivant la  Prime et conform&eacute;ment aux informations indiqu&eacute;es sur <a href="/sitio_personas/index.html">www.lan.com</a>. L&rsquo;annulation d&rsquo;une prime est  possible &agrave; condition que le billet &eacute;mis soit valable (un billet est valable &agrave;  compter de sa date d&rsquo;&eacute;mission), que le vol n&rsquo;ait pas encore eu lieu, qu&rsquo;aucun  segment n&rsquo;ait &eacute;t&eacute; effectu&eacute;, &agrave; l&rsquo;exception des surclassements &agrave; oneworld, et que  les kilom&egrave;tres utilis&eacute;s pour son &eacute;mission soient encore valables au moment de  la demande d&rsquo;annulation. L&rsquo;annulation pourra &ecirc;tre demand&eacute;e au Centre d&rsquo;Appels  de LAN (option LANPASS) ou dans les agences LAN. Une fois que l&rsquo;annulation aura  &eacute;t&eacute; r&eacute;alis&eacute;e, les kilom&egrave;tres non &eacute;chus seront nouvellement cr&eacute;dit&eacute;s sur le  compte de kilom&egrave;tres LANPASS du membre.</li>
      <li><strong>9.23</strong> Les Primes sont nominatives, elles n&rsquo;ont aucune valeur marchande et sont  intransmissibles. Si pour une quelconque raison une Prime n&rsquo;est pas &ndash;totalement  ou partiellement- utilis&eacute;e dans les d&eacute;lais et la forme fix&eacute;s lors de son  &eacute;mission, ladite Prime perdra toute sa valeur.</li>
      <li><strong>9.24</strong> Il est de la responsabilit&eacute; du Membre de v&eacute;rifier la quantit&eacute; de km LANPASS requise pour une Prime sur les Vols LAN et sur les vols oneworld et associ&eacute;s, en effet les quantit&eacute;s de km sollicit&eacute;es peuvent varier pour un m&ecirc;me itin&eacute;raire. </li></ul>
  <h3><strong>10. RESTRICTIONS DANS L&rsquo;UTILISATION  DES PRIMES</strong></h3>
      <ul><li><strong>10.1</strong> Les Primes sont soumises &agrave; la disponibilit&eacute; de places, qui sera confirm&eacute;e  au moment de l&rsquo;&eacute;mission.</li>
      <li><strong>10.2</strong> Les Primes permettent un (1) Stop-over (arr&ecirc;t volontaire du passager lors d&rsquo;une des Escales comprises lors du tron&ccedil;on aller ou retour du voyage) ou un (1) Openjaw (ville d&rsquo;arriv&eacute;e diff&eacute;rente de la ville de retour), tant sur les itin&eacute;raires nationaux qu&rsquo;internationaux. Certaines compagnies oneworld ou associ&eacute;es ne permettent pas le Stop-over ni l&rsquo;Openjaw. <a href="/sitio_personas/lanpass/como_canjear/oneworld_asociadas.html">Plus d&rsquo;informations</a>.</li>
      <li><strong>10.3</strong> Les Primes permettent un (1) Stopover (arr&ecirc;t volontaire du passager &agrave; une  des Escales fix&eacute;es au tron&ccedil;on aller ou au tron&ccedil;on retour du voyage) ou un (1)  Openjaw (ville de destination diff&eacute;rente de la ville de d&eacute;part du vol retour),  sur les trajets nationaux comme internationaux.</li>
      <li><strong>10.4 </strong>L&rsquo;&eacute;mission de Primes ouvertes, c&rsquo;est-&agrave;-dire sans date de d&eacute;part ou  d&rsquo;arriv&eacute;e, n&rsquo;est pas autoris&eacute;e.</li>
      <li><strong>10.5</strong> Les Primes ne pourront en aucun cas &ecirc;tre utilis&eacute;es aupr&egrave;s d&rsquo;autres  compagnies a&eacute;riennes qui ne soient pas celles qui sont indiqu&eacute;es sur la Prime.  En cas d&rsquo;annulation du vol indiqu&eacute; sur le billet Prime par un &eacute;v&eacute;nement  ind&eacute;pendant de la volont&eacute; de LAN, pour des raisons de s&eacute;curit&eacute; ou par cas  fortuit ou de force majeure, LAN prendra toutes les mesures possibles pour  embarquer le passager sur le vol suivant ou lui proposer des vols de connexion  pour qu&rsquo;il parvienne &agrave; la destination de son billet Prime. Le membre ne sera en  aucun cas embarqu&eacute; sur un vol d&rsquo;une autre compagnie a&eacute;rienne pour aucune  raison.</li>
      <li><strong>10.6</strong> En cas de Primes a&eacute;riennes dont les vols pr&eacute;voient des connexions avec  changements d&rsquo;appareil, les d&eacute;penses occasionn&eacute;es par le s&eacute;jour dans la ville  de transit ou toute autre d&eacute;pense li&eacute;e &agrave; ce transit seront exclusivement &agrave; la  charge du passager.</li>
      <li><strong>10.7</strong> Les Primes ne pourront pas &ecirc;tre combin&eacute;es &agrave; d&rsquo;autres offres  promotionnelles, bons, r&eacute;ductions ou offres sp&eacute;ciales, elle ne sont pas  valables lorsqu&rsquo;elles sont interdites par la loi et sont soumises aux  restrictions li&eacute;es &agrave; l&rsquo;industrie.</li>
      <li><strong>10.8</strong> Les Primes octroy&eacute;es correspondent exclusivement &agrave; la valeur nette du  tarif, et il incombe au passager de s&rsquo;acquitter de toutes taxes, imp&ocirc;ts, frais  et/ou droits qu&rsquo;imposent l&rsquo;&eacute;mission desdites Primes, y compris mais non  seulement de la taxe d&rsquo;embarquement.</li>
      <li><strong>10.9</strong> Le membre est r&eacute;put&eacute; avoir d&ucirc;ment pris connaissance des restrictions dans  la demande et l&rsquo;utilisation de Primes &agrave; l&rsquo;heure de les utiliser.</li>
      <li><strong>10.10</strong> Si la Prime comprend des vols op&eacute;r&eacute;s par des compagnies oneworld ou associ&eacute;es, il est de la responsabilit&eacute; du Membre de s&rsquo;informer sur les Conditions de Transport de la compagnie qui op&egrave;re le vol. Cette information est disponible sur www.lan.com.</li>
      </ul>
    <h3>11. Utilisation de bons de surclassement</h3>
      <ul>
        <li><strong>11.1 </strong>Les coupons de Surclassement sont valides jusqu&acute;&agrave;  la date qui y est indiqu&eacute;e, et attribuent au passager un Surclassement  en&nbsp;classe imm&eacute;diatement sup&eacute;rieure, sur&nbsp;un vol op&eacute;r&eacute; et vendu par LAN  &agrave; l&acute;aller ou au retour, en fonction des <a href="http://www.lan.com/es_un/sitio_personas/lanpass/como_canjear/familias_tarifarias.html" target="_blank">familles  tarifaires</a><strong>,</strong> de la quantit&eacute; de coupons requis par itin&eacute;raire et  de la disponibilit&eacute; des places&nbsp;au moment de l&acute;embarquement.  </li>
      <li><strong>11.2</strong> Les tarifs seuil exig&eacute;s pour le&nbsp;  billet sont disponibles sur <a href="/sitio_personas/index.html">www.lan.com</a>.</li>
      <li><strong>11.3</strong> Le bon de surclassement ne sera pas valable en cas d&rsquo;endommagement, de  reproduction ou d&rsquo;utilisation incorrecte. Ledit bon n&rsquo;a aucune valeur  marchande, il sera invalid&eacute; s&rsquo;il est utilis&eacute; pour un &eacute;change quelconque et ne  sera pas restitu&eacute; en cas de vol ou de perte.</li>
      <li><strong>11.4</strong> Tous les bons de surclassement sont destin&eacute;s uniquement au membre et/ou au  passager qui l&rsquo;accompagne. Ledit passager pourra utiliser le bon de  surclassement &agrave; condition de voyager avec le membre (pas forc&eacute;ment dans la m&ecirc;me  classe).</li>
      <li><strong>11.5</strong> Le passager est tenu responsable de s&rsquo;acquitter de toute taxe requise pour  utiliser son Certificat de Surclassement.</li></ul>
    <h3><strong>12. GEN&Eacute;RALIT&Eacute;S</strong></h3>
      <ul><li><strong>12.1</strong> La participation au Programme LANPASS est soumise aux pr&eacute;sentes conditions  g&eacute;n&eacute;rales, qui peuvent &ecirc;tre amend&eacute;es p&eacute;riodiquement et unilat&eacute;ralement par  LANPASS. Tout amendement apport&eacute; aux conditions g&eacute;n&eacute;rales devra obligatoirement  &ecirc;tre observ&eacute; par les membres 30 jours apr&egrave;s le pr&eacute;avis, notifi&eacute; par n&rsquo;importe  quel moyen.</li>
      <li><strong>12.2</strong> LANPASS se r&eacute;serve le droit de mettre fin au Programme LANPASS &agrave; tout  moment, avec ou sans pr&eacute;avis notifi&eacute;. Les kilom&egrave;tres accumul&eacute;s par le membre  perdraient d&egrave;s lors toute valeur. En tous cas, LANPASS fera son possible pour  notifier, avec une anticipation raisonnable, la suppression du programme aux  membres afin qu&rsquo;ils puissent utiliser leurs kilom&egrave;tres accumul&eacute;s.</li>
      <li><strong>12.3</strong> LANPASS n&rsquo;assume en aucun cas la responsabilit&eacute; pour les pertes et  dommages r&eacute;sultant de la suppression du Programme LANPASS ou les changements ou  amendements apport&eacute;s audit Programme.</li>
      <li><strong>12.4</strong> Les Primes et/ou Avantages sont soumis aux changements et aux  disponibilit&eacute;s, le membre est tenu responsable de demander la r&eacute;servation  valable et de respecter toutes les &eacute;tapes n&eacute;cessaires pour la jouissance  desdits Primes et/ou Avantages.</li>
      <li><strong>12.5</strong> Certaines Primes, certains Avantages et certaines possibilit&eacute;s d&rsquo;accumuler  des kilom&egrave;tres sont ou peuvent &ecirc;tre fournis par des organisations avec qui  LANPASS a des accords, mais sur lesquelles LANPASS n&rsquo;exerce aucun pouvoir. Quoi  qu&rsquo;il en soit, LANPASS prendra toutes les mesures n&eacute;cessaires pour que les  Primes et Avantages propos&eacute;s aux membres comme disponibles le soient  r&eacute;ellement.<br>
      Cependant, LANPASS ne saurait &ecirc;tre tenu responsable  de la disponibilit&eacute; desdites Primes et/ou desdits Avantages, et d&eacute;cline donc  toute responsabilit&eacute; pour les dommages ou pertes occasionn&eacute;s par l&rsquo;accord, le  non accord, total ou partiel, de toute Prime et/ou de tout Avantage. LANPASS  d&eacute;cline aussi toute responsabilit&eacute; en cas de r&eacute;siliation de ces organisations  du partenariat avec LANPASS.</li>
      <li><strong>12.6</strong> L&rsquo;octroi ou la distribution des Primes et/ou Avantages propos&eacute;s par les  Compagnies A&eacute;riennes Partenaires et/ou par les Soci&eacute;t&eacute;s Partenaires sont soumis  aux conditions g&eacute;n&eacute;rales impos&eacute;es par ladite organisation.</li>
      <li><strong>12.7</strong> LANPASS d&eacute;cline toute responsabilit&eacute; pour les pertes, pr&eacute;judices, d&eacute;lais  ou dommages occasionn&eacute;s par, ou li&eacute;s avec le Programme LANPASS ou toute Prime  et/ou Avantage, &agrave; l&rsquo;exception des cas ou lesdits pr&eacute;judices, pertes, d&eacute;lais ou  dommages sont occasionn&eacute;s par grave n&eacute;gligence ou dol de la part de LANPASS.</li>
      <li><strong>12.8</strong> LANPASS d&eacute;cline toute responsabilit&eacute; pour les erreurs et/ou omissions qui  pourraient, malgr&eacute; toutes les pr&eacute;cautions prises, figurer dans les informations  relatives au Programme LANPASS. LANPASS n&rsquo;est pas non plus tenu responsable  pour le d&eacute;lai, la perte ou la remise erron&eacute;e de courrier adress&eacute; au membre.</li>
      <li><strong>12.9</strong> Lors de toute communication &eacute;crite adress&eacute;e au Programme LANPASS, le  membre devra apposer sa signature et son num&eacute;ro de membre.</li>
      <li><strong>12.10</strong> LANPASS est le seul responsable de l&rsquo;interpr&eacute;tation et de l&rsquo;application  des pr&eacute;sentes conditions g&eacute;n&eacute;rales.</li>
      <li><strong>12.11</strong> Sous r&eacute;serve d&rsquo;autorisation formelle et par &eacute;crit de LAN, la vente,  l&rsquo;achat, l&rsquo;&eacute;change ou le transfert &agrave; n&rsquo;importe quel titre, de Primes et/ou  d&rsquo;Avantages, certificats et/ou kilom&egrave;tres LANPASS sont formellement interdits.</li>
      <li><strong>12.12</strong> Les Primes et/ou Avantages, certificats et/ou kilom&egrave;tres LANPASS qui ont  &eacute;t&eacute; vendus ou achet&eacute;s &agrave; n&rsquo;importe quel titre sans l&rsquo;autorisation de LAN, et les  personnes qui utilisent lesdites primes ne pourront pas continuer leur voyage,  ou cesseront de recevoir le service associ&eacute; &agrave; la prime, &agrave; moins qu&rsquo;elle  s&rsquo;acquittent du plein tarif dudit service.</li>
      <li><strong>12.13</strong> LANPASS d&eacute;cline toute responsabilit&eacute; pour les Primes remises par des  Soci&eacute;t&eacute;s Partenaires ou des Compagnies A&eacute;riennes Partenaires, seules  responsables, vis-&agrave;-vis du membre, des Primes accord&eacute;es.</li>
      <li><strong>12.14</strong> Les vols comptabilis&eacute;s dans le Relev&eacute; de Compte ne prouvent pas que le  membre ait r&eacute;ellement effectu&eacute; les vol indiqu&eacute;s.</li>
      <li><strong>12.15</strong> Les pr&eacute;sentes conditions g&eacute;n&eacute;rales peuvent &ecirc;tre amend&eacute;es &agrave; tout moment  sans pr&eacute;avis. La version actualis&eacute;e desdites conditions est disponible sur <a href="/sitio_personas/index.html">www.lan.com</a> ou dans n&rsquo;importe quelle agence LAN.</li>
      <li><strong>12.16</strong> Les pr&eacute;sentes conditions g&eacute;n&eacute;rales sont soumises aux lois de la R&eacute;publique  du Chili, tout contentieux ou litige li&eacute; &agrave; leur application, respect,  interpr&eacute;tation ou validit&eacute; sera r&eacute;solu par les Tribunaux de Justice dudit pays.</li></ul>
      <h2>CONDITIONS APPLICABLES AU CONTRAT DE TRANSPORT A&Eacute;RIEN DE PASSAGERS ET DE BAGAGES</h2>

<h3><strong>1.  D&Eacute;FINITIONS</strong> </h3>
<p>Au sens des pr&eacute;sentes conditions,  les termes suivants sont employ&eacute;s avec le sens indiqu&eacute; ci-apr&egrave;s&nbsp;:</p>
<ul>
<li> 1.1<strong> Le &quot;Billet&quot;</strong> d&eacute;signe l&rsquo;ensemble des documents qui font &eacute;tat et font foi de l&rsquo;existence et  des conditions du Contrat de Transport a&eacute;rien et de contr&ocirc;le des bagages,  comprenant certains ou tous les documents suivants&nbsp;: <strong>(i)</strong> les  pr&eacute;sentes Conditions du Contrat de Transport a&eacute;rien; <strong>(ii)</strong> les  dispositions &eacute;nonc&eacute;es dans le document appel&eacute; &laquo;&nbsp;Informations sur votre  voyage&nbsp;&raquo; remis par la compagnie a&eacute;rienne, ou les d&eacute;tails sur la  r&eacute;servation fournis par n&rsquo;importe quel agent&nbsp;; <strong>(iii)</strong> le billet  &eacute;lectronique enregistr&eacute; magn&eacute;tiquement&nbsp;; <strong>(iv)</strong> les conditions  sp&eacute;cifiques applicables au tarif acquitt&eacute; par le passager&nbsp;; <strong>(v)</strong> la  Carte d&rsquo;Embarquement ou <em>Boarding Pass&nbsp;</em>; et <strong>(vi)</strong> les  communications et les tarifs du contrat de transport d&eacute;clar&eacute;s aupr&egrave;s des  autorit&eacute;s a&eacute;ronautiques dans les pays o&ugrave; ceci est requis.</li>
<li>1.2 Le &laquo;&nbsp;<strong>Transporteur&nbsp;</strong>&raquo;  d&eacute;signe la compagnie a&eacute;rienne qui transporte ou s&rsquo;engage &agrave; transporter le  passager et/ou ses bagages en vertu de ce contrat ou qui fournit toute autre  prestation li&eacute;e audit transport a&eacute;rien.</li>
<li>1.3 La <strong>&ldquo;Convention de Varsovie&rdquo; </strong>d&eacute;signe  la Convention pour l&rsquo;unification de certaines r&egrave;gles relatives au transport  a&eacute;rien international, sign&eacute;e &agrave; Varsovie en 1929, et les modifications  introduites par le Protocole de la Haye de 1955 et par le Protocole de Montr&eacute;al  de 1975.</li>
<li>1.4 La <strong>&ldquo;Convention de Montr&eacute;al&rdquo;</strong>,  d&eacute;signe la Convention pour l&acute;unification de certaines r&egrave;gles relatives au  transport a&eacute;rien international sign&eacute;e &agrave; Montr&eacute;al, au Canada, le 28 mai 1999.</li></ul>

<h3><strong>2. R&Egrave;GLES GENERALES DU TRANSPORT A&Eacute;RIEN</strong></h3>
<ul><li>2.1 L&rsquo;&eacute;mission du Billet  donne foi de l&rsquo;existence et de l&rsquo;acceptation des conditions du transport a&eacute;rien  et du Contrat de Transport souscrit entre le Passager et le Transporteur dont  les noms figurent sur le billet. Le Billet &eacute;mis au nom du passager est  nominatif, personnel et non cessible, y l&rsquo;&eacute;mission de celui-ci pourra se faire  partiellement ou int&eacute;gralement par le biais de moyens physiques ou  &eacute;lectroniques.</li>
<li>2.2 Les escales convenues  sont celles qui figurent sur le Billet ou sur les itin&eacute;raires du Transporteur  comme escales pr&eacute;vues sur le trajet du passager. Le transport &agrave; r&eacute;aliser en  vertu de ce contrat successivement par plusieurs Transporteurs est consid&eacute;r&eacute;  comme une seule op&eacute;ration.</li>
<li>2.3 Si le Transporteur &eacute;met  un Billet pour le transport sur des tron&ccedil;ons op&eacute;r&eacute;s par un autre Transporteur,  le Transporteur ne fera office que d&rsquo;agent de ce dernier.</li>
<li>2.4 Toute exemption ou limitation  de la responsabilit&eacute; du Transporteur en vertu de la r&eacute;glementation locale ou  internationale en vigueur sera appliqu&eacute;e et ira au b&eacute;n&eacute;fice des agents, des  employ&eacute;s et repr&eacute;sentants du Transporteur ou de toute autre personne ou  entreprise dont l&rsquo;appareil est utilis&eacute; par le Transporteur pour r&eacute;aliser le  transport, et des agents, employ&eacute;s et repr&eacute;sentants de ladite personne ou  entreprise.</li>
<li>2.5 Le Transporteur se  r&eacute;serve le droit absolu de refuser le transport sur tout tron&ccedil;on de  l&rsquo;itin&eacute;raire r&eacute;serv&eacute; par le passager s&rsquo;il ne s&rsquo;est pas acquitt&eacute; ou s&rsquo;il ne  s&rsquo;est acquitt&eacute; que partiellement du prix contractuel, si le moyen de paiement  utilis&eacute; a &eacute;t&eacute; refus&eacute; ou annul&eacute; ou si le billet a &eacute;t&eacute; acquis frauduleusement.</li>
<li>2.6 De m&ecirc;me, le Transporteur  refusera l&rsquo;embarquement d&rsquo;un passager ou proc&eacute;dera au d&eacute;barquement de celui-ci  s&rsquo;il estime que ledit passager pourrait mettre en danger la s&eacute;curit&eacute; du vol ou  des passagers. Tout particuli&egrave;rement, l&rsquo;embarquement sera refus&eacute; &agrave; tout  passager dont l&rsquo;attitude au sol et/ou &agrave; bord de l&rsquo;appareil constitue&nbsp;: (i)  un acte d&rsquo;insoumission aux instructions donn&eacute;es par le personnel d&rsquo;&eacute;quipage &agrave;  bord ou par tout employ&eacute; du Transporteur et/ou <strong>(ii)</strong> un comportement  irraisonn&eacute;, inappropri&eacute; pour une personne ou un passager&nbsp;; et/ou <strong>(iii)</strong> une infraction ou d&eacute;lit qui pourrait selon le Transporteur mettre en p&eacute;ril ou  compromettre la s&eacute;curit&eacute; de l&rsquo;appareil ou des passagers ou biens de celui-ci,  qui mette en p&eacute;ril ou compromette le bon ordre et la discipline &agrave; bord, et/ou <strong>(iv)</strong> en g&eacute;n&eacute;ral, toute attitude ou comportement qui selon le Transporteur constitue  une d&eacute;sob&eacute;issance aux instructions donn&eacute;es par les membres de l&rsquo;&eacute;quipage, et/ou  des attitudes qui pourraient mettre en p&eacute;ril ou compromettre l&rsquo;op&eacute;ration et/ou  alt&egrave;rent le bon ordre et/ou la discipline&nbsp;; et/ou <strong>(v) </strong>des signes  r&eacute;v&eacute;lateurs de consommation excessive d&rsquo;alcool et/ou de substances  psychotropiques&nbsp;; et/ou la non-observation de toute loi ou r&eacute;glementation  ou de toute exigence de l&rsquo;autorit&eacute; comp&eacute;tente.</li>
<li>2.7 En cas de besoin (y  compris mais non seulement lors de cas fortuits ou de force majeure) le  Transporteur peut annuler l&rsquo;op&eacute;ration, se faire remplacer par d&rsquo;autres  Transporteurs et/ou remplacer l&rsquo;appareil pr&eacute;vu pour l&rsquo;op&eacute;ration et/ou modifier  ou supprimer des escales pr&eacute;vues et indiqu&eacute;es sur le Billet si c&rsquo;&eacute;tait  n&eacute;cessaire. Le transporteur ne garantit pas les vols de connexion r&eacute;serv&eacute;s  aupr&egrave;s d&rsquo;un tiers.</li>
<li>2.8 Tout passager qui ne se  pr&eacute;sente pas ou est en retard pour son embarquement et/ou enregistrement sur le  vol concern&eacute; (check-in) perdra son billet ou pourra le reprogrammer &agrave; une autre  date si le tarif acquitt&eacute; pour l&rsquo;achat du Billet le permet. Toute modification  de la date, de lieu de d&eacute;part, de destination ou de l&rsquo;itin&eacute;raire du Billet,  ainsi que le remboursement du tarif acquitt&eacute; pour l&rsquo;achat de celui-ci sont  limit&eacute;s aux conditions et aux restrictions du tarif acquitt&eacute; par le passager.  Si le passager n&rsquo;emprunte pas le vol, il pourra, m&ecirc;me si le tarif acquitt&eacute; ne  permet pas le remboursement, demander le remboursement des taxes d&rsquo;a&eacute;roport  remboursables au regard de la r&eacute;glementation et aux restrictions du pays  concern&eacute;. Dans les cas o&ugrave; lesdites taxes ne seraient pas comprises dans le  tarif acquitt&eacute; (c&rsquo;est-&agrave;-dire qu&rsquo;elles ont &eacute;t&eacute; pr&eacute;lev&eacute;es par l&rsquo;a&eacute;roport), le  passager pourra solliciter le remboursement de celles-ci aupr&egrave;s de l&rsquo;autorit&eacute;  a&eacute;roportuaire concern&eacute;e, conform&eacute;ment aux restrictions ou r&eacute;glementations  susmentionn&eacute;es.</li>
<li>2.9 Les vols ou tron&ccedil;ons qui  composent l&rsquo;itin&eacute;raire devront &ecirc;tre parcourus dans l&rsquo;ordre successif indiqu&eacute;.  Le Transporteur, soumis aux conditions pr&eacute;vues et &agrave; la r&eacute;glementation  applicable, pourra refuser l&rsquo;embarquement d&rsquo;un passager qui n&rsquo;ait pas respect&eacute;  ledit ordre successif, ou d&rsquo;un passager qui n&rsquo;ait pas effectu&eacute; un des tron&ccedil;ons  indiqu&eacute;s sur son billet. Le passager est r&eacute;put&eacute; avoir conscience que s&rsquo;il  n&rsquo;effectue pas un des tron&ccedil;ons de l&rsquo;itin&eacute;raire de vol, l&rsquo;itin&eacute;raire dans son  ensemble sera annul&eacute; sans pr&eacute;avis et ne sera pas rembours&eacute;, &agrave; moins que le  tarif du billet ne l&rsquo;autorise. &Agrave; titre d&rsquo;exemple, sans que cette condition se  limite &agrave; ce cas en particulier, si le passager n&rsquo;effectue pas le premier  tron&ccedil;on indiqu&eacute; sur l&rsquo;itin&eacute;raire (que l&rsquo;on comprend comme aller), il ne pourra  effectuer aucun autre tron&ccedil;on&nbsp;(vol d&rsquo;escale ou vol de retour).</li>
<li>2.10 Il est formellement  interdit de fumer &agrave; bord des appareils du Transporteur. Le Transporteur se  r&eacute;serve le droit de refuser de transporter tout passager qui ne soit pas pr&ecirc;t &agrave;  accepter cette condition.</li>
<li>2.11 Le billet est valable un  an &agrave; compter de la date d&rsquo;&eacute;mission ou valable jusqu&rsquo;&agrave; la date sp&eacute;cifiquement  pr&eacute;vue par le tarif acquitt&eacute; par le passager. Au-del&agrave; de cette p&eacute;riode de  validit&eacute;, ou de toute p&eacute;riode de validit&eacute; au regard des conditions tarifaires,  le billet ne pourra pas &ecirc;tre utilis&eacute;.</li>
<li>2.12 Le passager est tenu et  il est de sa responsabilit&eacute; de s&rsquo;informer et de remplir les crit&egrave;res  n&eacute;cessaires &agrave; son voyage et requis par toute autorit&eacute;. Il devra pr&eacute;senter les  documents d&rsquo;identit&eacute;, d&rsquo;entr&eacute;e, de sortie, de transit, les visas et autres  documents exig&eacute;s suivant sa destination. Le Transporteur n&rsquo;assume aucune  responsabilit&eacute; pour les retards ou refus d&rsquo;embarquement que le passager  subirait pour ne pas s&rsquo;&ecirc;tre conform&eacute; aux dispositions susmentionn&eacute;es. Le  transporteur refusera l&rsquo;embarquement des passagers qui ne pr&eacute;senteront pas les  documents requis ou dont l&rsquo;identit&eacute; ne correspond pas au nom figurant sur la  Carte d&rsquo;Embarquement ou <em>Boarding Pass. </em>Le Transporteur ne sera pas  responsable pour ce refus. Il ne saurait &ecirc;tre tenu responsable pour toute  information ou assistance fournies par tout agent, employ&eacute; ou repr&eacute;sentant de  la compagnie a&eacute;rienne ou par des tiers sur l&rsquo;obtention desdits documents et/ou  le respect des lois et r&eacute;glementations applicables.</li>
<li>2.13 Les vols op&eacute;r&eacute;s par le  Transporteur entre les pays membres de l&rsquo;Union Europ&eacute;enne (c&rsquo;est-&agrave;-dire les  vols entre Madrid, Espagne et Francfort, Allemagne) sont consid&eacute;r&eacute;s des vols <em>Non-Schengen</em> (non intracommunautaires) par les autorit&eacute;s respectives dans ces pays, par  cons&eacute;quent les passagers de ces vols devront obligatoirement se soumettre aux  contr&ocirc;les douaniers et contr&ocirc;les de passeport dans chacun de ces pays. Ils  devront &ecirc;tre munis de tous les documents d&rsquo;identit&eacute;, visas, permis de s&eacute;jour et  autorisations exig&eacute;es par les pays intracommunautaires. Le passager est tenu et  il est de sa responsabilit&eacute; de s&rsquo;informer sur les documents n&eacute;cessaires &agrave; son  voyage. Le Transporteur ne saura &ecirc;tre tenu responsable pour les dommages et  pr&eacute;judices caus&eacute;s par l&rsquo;inobservation de ladite obligation de la part du  passager. Les m&ecirc;mes conditions sont applicables pour les vols &agrave; destination et  au d&eacute;part du Canada.</li>
<li>2.14 Le passager devra se  pr&eacute;senter au comptoir d&rsquo;embarquement et au comptoir d&rsquo;enregistrement &agrave; l&rsquo;heure  indiqu&eacute;e par le Transporteur, et si celle-ci n&rsquo;avait pas &eacute;t&eacute; fix&eacute;e,  suffisamment t&ocirc;t pour accomplir les d&eacute;marches de sortie, c&rsquo;est-&agrave;-dire pas moins  de 2 heures avant l&rsquo;heure de d&eacute;part du vol.</li>
<li>2.15 En cas de surr&eacute;servation  du vol, et si l&rsquo;enregistrement des passagers s&rsquo;est fait conform&eacute;ment aux heures  limites d&rsquo;enregistrement, le Transporteur proposera &agrave; des passagers de c&eacute;der  volontairement leur place en &eacute;change d&rsquo;une compensation pr&eacute;vue. S&rsquo;il n&rsquo;y avait  pas suffisamment de volontaires et que le Transporteur &eacute;tait contraint de  refuser l&rsquo;embarquement de passagers contre leur volont&eacute;, ces passagers auraient  droit aux prestations pr&eacute;vues par le droit en vigueur.</li>
<li>2.16 Le Transporteur  s&rsquo;efforcera de prendre toutes les mesures n&eacute;cessaires pour transporter sans  retard le passager et ses bagages. Le Transporteur ne garantit pas le respect  des horaires indiqu&eacute;s sur le Billet ou sur un autre document, car ils peuvent  &ecirc;tre modifi&eacute;s pour des motifs de force majeure, de s&eacute;curit&eacute; ou toute autre  circonstance extraordinaire. Le Transporteur s&rsquo;efforcera de prendre les mesures  n&eacute;cessaires dans la limite des possibilit&eacute;s pour &eacute;viter le retard du transport  des passagers et de leurs bagages. Le Transporteur ne saurait &ecirc;tre tenu  responsable d&rsquo;assurer les connexions lors de la survenance d&rsquo;&eacute;v&eacute;nements  ind&eacute;pendants de la volont&eacute; du Transporteur.</li>
<li>2.17 Dans certains cas, le  Transporteur pourra demander une notification pr&eacute;alable pour les vols de  certains passagers souffrant d&rsquo;un handicap ou d&rsquo;une maladie (par exemple s&rsquo;ils  ont besoin d&rsquo;un brancard, d&rsquo;oxyg&egrave;ne, entre autres) ou s&rsquo;ils doivent voyager  accompagn&eacute;s d&rsquo;un animal d&rsquo;assistance et/ou de soutien. Les passagers doivent se  renseigner &agrave; l&rsquo;avance sur les conditions sp&eacute;ciales de transport qui devront  &ecirc;tre observ&eacute;es et organis&eacute;es avant l&rsquo;acceptation de ces passagers &agrave;  l&rsquo;embarquement (par exemple le transport d&rsquo;un mineur non accompagn&eacute; ou d&rsquo;un  enfant en bas &acirc;ge). Le Transporteur ne saurait &ecirc;tre tenu responsable s&rsquo;il  refusait l&rsquo;embarquement de passagers qui n&rsquo;auraient pas observ&eacute; les  r&eacute;glementations et/ou politiques en vigueur de la soci&eacute;t&eacute; &agrave; ce sujet. </li></ul>
<h3><strong>3. R&Egrave;GLES APPLICABLES AU TRANSPORT DE BAGAGES</strong></h3>
<ul>
<li>3.1 Conform&eacute;ment aux r&egrave;gles  internationales et locales, le Transporteur refusera de transporter les bagages  (&agrave; main ou enregistr&eacute;s) comprenant des articles et substances dangereuses  susceptibles de constituer un danger pour la sant&eacute;, la s&eacute;curit&eacute; du vol ou des  biens &agrave; bord, tels que:</li>
  <ul>
  <li>Gaz (sous  pression, liqu&eacute;fi&eacute;, en solution ou intens&eacute;ment r&eacute;frig&eacute;r&eacute;s), y compris les  a&eacute;rosols, les substances inflammables, toxiques ou inoffensives comme le  butane, l&rsquo;oxyg&egrave;ne, le nitrog&egrave;ne liquide, les a&eacute;rosols qui contiennent des gaz  paralysants, des vannes de remplissage de briquets &agrave; gaz, entre autres.</li>
  <li>Mat&eacute;riaux  corrosifs, solides ou liquides&nbsp;tels que: acides, alcalies, mercure,  batteries &agrave; &eacute;lectrolytes liquides, entre autres.</li>
  <li>Explosifs tels  que&nbsp;: munitions, feux d&rsquo;artifice et de bengale, mallettes munies d&rsquo;un  dispositif d&rsquo;alarme, d&eacute;tonateurs pour pistolets jouets, entre autres.</li>
  <li>Liquides  inflammables tels que&nbsp;: carburants, peintures, dissolvants, entre autres.</li>
  <li>Mat&eacute;riaux  radioactifs quelle que soit leur cat&eacute;gorie.</li>
  <li>Mat&eacute;riaux  oxydants y p&eacute;roxydes organiques, tels que&nbsp;: agents de blanchiment,  engrais, entre autres.</li>
  <li>Substances  toxiques et infectieuses telles que: insecticides, pesticides, produits  biologiques qui contiennent des germes pathog&egrave;nes, entre autres.</li>
  <li>Corps solides  inflammables tels que des allumettes.</li>
  <li>Armes, selon la  d&eacute;finition de tout &eacute;l&eacute;ment ou objet con&ccedil;u ou pouvant &ecirc;tre utilis&eacute; pour  l&rsquo;attaque ou la d&eacute;fense tels que&nbsp;: armes &agrave; feu, armes blanches, gaz,  dispositifs de choc &eacute;lectrique, articles tranchants, pointus, encombrants, y  compris des matraques, haches, b&acirc;tons lourds et pointus.</li>
</ul>
<li>3.2 Afin de veiller &agrave; la  s&eacute;curit&eacute; du vol et de respecter la r&eacute;glementation en vigueur, le Transporteur  et le personnel de s&eacute;curit&eacute; de l&rsquo;a&eacute;roport pourront confisquer les articles  dangereux et substances dangereuses transport&eacute;s par le passager ou contenus  dans son bagage &agrave; main, pour les remettre aux autorit&eacute;s comp&eacute;tentes,  conform&eacute;ment aux r&eacute;glementations locales applicables.</li>
<li>3.3 Les passagers ont le  droit de transporter de nombreux articles m&eacute;dicaux ou de toilette. Avant de les  inclure dans ses bagages, le passager devra se renseigner aupr&egrave;s du personnel  du Transporteur.</li>
<li>3.4 Certains des articles  susmentionn&eacute;s peuvent &ecirc;tre transport&eacute;s par voie a&eacute;rienne sous certaines  conditions, si le Transporteur en a pris connaissance et si le passager  s&rsquo;acquitte d&rsquo;un tarif de transport de marchandises. Le passager devra se  renseigner au pr&eacute;alable aupr&egrave;s du Transporteur.</li>
<li>3.5 On n&rsquo;entend par bagages  que les effets personnels du passager requis pour son voyage.</li>
<li>3.6 Le passager ne pourra pas  enregistrer ses bagages sur un autre vol que celui sur lequel il va  s&rsquo;embarquer.</li>
<li>3.7 Le Transporteur  n&rsquo;enregistrera pas les bagages vers une destination qui diff&egrave;re de la destination  finale indiqu&eacute;e sur le billet du passager.</li>
<li>3.8 Le passager devra  s&rsquo;adapter au poids, &agrave; la taille et &agrave; la franchise maximale autoris&eacute;e pour les  bagages, &eacute;nonc&eacute;es sur www.lan.com et sur le document d&rsquo;information de votre  voyage tel que d&eacute;crit au paragraphe 1.1. La franchise de bagages et les  suppl&eacute;ments tarifaires pour exc&eacute;dents de bagages peuvent &ecirc;tre consult&eacute;s  directement aupr&egrave;s de la compagnie a&eacute;rienne ou sur www.lan.com.</li>
<li>3.9 La franchise autoris&eacute;e  peut varier selon les conditions du tarif, de la classe de transport ou du  trajet pr&eacute;vu, et s&rsquo;exprime en pi&egrave;ce ou en poids. Le Transporteur se r&eacute;serve le  droit de modifier lesdites franchises et les dimensions des bagages. Les  conditions et les tarifs du contrat seront enregistr&eacute;s aupr&egrave;s des autorit&eacute;s  a&eacute;ronautiques locales comp&eacute;tentes si cela est requis.</li>
<li>3.10 Par mesure de pr&eacute;caution  et de s&eacute;curit&eacute;, un seul bagage &agrave; main est autoris&eacute; en cabine. Les dimensions et  le poids de celui-ci doivent permettrent au passager de le placer sous le si&egrave;ge  devant lui ou dans les compartiments pr&eacute;vus &agrave; cet effet.</li>
<li>3.11 Les bagages enregistr&eacute;s  seront remis &agrave; la personne munie du bulletin de bagages. En cas de  d&eacute;t&eacute;rioration des bagages pendant le transport, le passager devra faire une  protestation par &eacute;crit imm&eacute;diatement apr&egrave;s avoir constat&eacute; le dommage, au plus  tard dans les 7 jours &agrave; compter de la r&eacute;ception des bagages ou dans les d&eacute;lais  pr&eacute;vus par la r&eacute;glementation applicable aux vols domestiques. En cas de retard,  le passager doit faire une protestation dans un d&eacute;lai de 21 jours &agrave; compter de  la date &agrave; laquelle les bagages ont &eacute;t&eacute; mis &agrave; sa disposition ou dans les d&eacute;lais  pr&eacute;vus par la r&eacute;glementation applicable aux vols domestiques. Pour  l&rsquo;application du paragraphe ci-dessus, on comprend par &laquo;&nbsp;retard&nbsp;&raquo;  tout d&eacute;lai dans la r&eacute;ception des bagages qui soit directement imputable &agrave; la  responsabilit&eacute; du Transporteur.</li></ul>
<h3>4. LIMITES DE RESPONSABILIT&Eacute;</h3>
<ul><li>4.1 Si le voyage d&rsquo;un  passager commence et se termine sur le territoire d&rsquo;un m&ecirc;me pays, le service de  transport et les limites de responsabilit&eacute;s seront r&eacute;glement&eacute;s par la  l&eacute;gislation applicable dudit pays. Dans les cas o&ugrave; le voyage du passager rev&ecirc;t  un caract&egrave;re international, la Convention de Varsovie, la Convention de Montr&eacute;al  ou toute autre r&eacute;glementation internationale &agrave; ce sujet seront appliqu&eacute;es  suivant les cas. Ces conventions et r&eacute;glementations &eacute;tabliront, quand ce sera  n&eacute;cessaire, les limites de responsabilit&eacute; du Transporteur dans le d&eacute;c&egrave;s ou les  l&eacute;sions corporelles du passager, ainsi que dans le cas o&ugrave; des bagages sont  perdus, endommag&eacute;s ou remis en retard.</li>
<li>4.2 Le Transporteur d&eacute;clare  que dans tout transport r&eacute;glement&eacute; par la Convention de Varsovie, il  n&rsquo;invoquera pas les limites de responsabilit&eacute; civile prescrits en l&rsquo;article 22  (1) de ladite Convention lors de protestations pour dommages en cas de mort ou  de l&eacute;sions corporelles subie par les passagers. Pour les dommages ne d&eacute;passant  pas 100&nbsp;000 droits de tirages sp&eacute;ciaux (DTS), le Transporteur n&rsquo;invoquera  pas les d&eacute;fenses de l&rsquo;article 20 (1) de la Convention de Varsovie. &Agrave;  l&rsquo;exception du cas susmentionn&eacute;, le Transporteur pourra se pr&eacute;valoir des  d&eacute;fenses pr&eacute;vues par la Convention de Varsovie et d&eacute;poser les recours  pertinents contre des tiers.</li>
<li>4.3 Le passager est tenu de transporter  les articles de valeur et articles &eacute;lectroniques comme bagage &agrave; main, afin de  les maintenir constamment sous sa surveillance, car le Transporteur ne saurait  &ecirc;tre tenu responsable pour ces articles au-del&agrave; des limites fix&eacute;es par la loi  ou les conventions internationales applicables si ces articles sont transport&eacute;s  comme bagages enregistr&eacute;s.</li>
<li>4.4 La responsabilit&eacute; du  Transporteur en cas de mort ou de l&eacute;sion corporelle du passager et/ou en cas de  perte des bagages, dommage caus&eacute; aux bagages ou de retard dans la remise de  ceux-ci &agrave; l&rsquo;int&eacute;rieur d&rsquo;un m&ecirc;me pays est fix&eacute;e par la l&eacute;gislation applicable  dudit pays. De m&ecirc;me, la responsabilit&eacute; du Transporteur en cas de mort ou  l&eacute;sions corporelles du passager et/ou en cas de perte ou dommage des bagages ou  de retard dans la remise de ceux-ci sur des vols internationaux est fix&eacute;e par  les conventions internationales relatives au transport a&eacute;rien international,  que ce soit la Convention de Varsovie ou la Convention de Montr&eacute;al suivant les  cas.<br>
Ces conditions ne sont  applicables que pour les trajets du Transporteur. Nul agent, employ&eacute; ou  repr&eacute;sentant du Transporteur n&rsquo;est autoris&eacute; &agrave; refuser ou modifier toute  disposition de ces conditions. </li></ul>
</div>
</div>
</body>
</html>
