{_LABEL_FORMA_PAGO}:  RIPLEY {NUMERO_TARJETA_4}
{_LABEL_MONTO}: {CURRENCY} {MONTO}
{_LABEL_TIPO_CLIENTE_RIPLEY}: {TIPO_CLIENTE_TXT}
{_LABEL_NUM_CUOTAS}: {NUMERO_CUOTAS}
{_LABEL_VALOR_CUOTA}: {VALOR_CUOTA}
		
