{_LABEL_FORMA_PAGO_TXT}: {_LABEL_TARJETA_TXT} {MARCA_TARJETA} {NUMERO_TARJETA_4}
{_LABEL_MONTO_TXT}: {CURRENCY} {MONTO}
{_LABEL_TIPO_VENTA_TXT}: {TIPO_VENTA_TXT}
{_LABEL_NUM_CUOTAS_TXT}: {NUMERO_CUOTAS}
{_LABEL_CODIGO_AUTORIZACION_TXT}: {AUTH_TRANSBANK}
{_LABEL_FECHA_TRANSACCION_TXT}: {FECHA_TRANSACCION}
{_LABEL_HORA_TRANSACCION_TXT}: {HORA_TRANSACCION}
