{_LABEL_ESTADO_PAGO}:
{ESTADO_PAGO} {MENSAJE}
{_LABEL_FORMA_PAGO}:
{_LABEL_TARJETA}

{_LABEL_MONTO}:
{CURRENCY} {MONTO}
{_LABEL_CODIGO_COMPRA}: {CODIGO_COMPRA}
{_LABEL_CODIGO_AUTORIZACION}: {AUTH_TRANSBANK}
