{_LABEL_ESTADO_PAGO_TXT}: {ESTADO_PAGO} {MENSAJE}
{_LABEL_FORMA_PAGO_TXT}: {_LABEL_TARJETA_TXT} {MARCA_TARJETA} {NUMERO_TARJETA_4}
{_LABEL_MONTO_TXT}: {CURRENCY} {MONTO}

{_LABEL_TIPO_VENTA_TXT}: {TIPO_VENTA_TXT}
{_LABEL_NUM_CUOTAS_TXT}: {NUMERO_CUOTAS}

{TR_PROMOCION_10_PCT}
