{_LABEL_FORMA_PAGO_TXT}
{_LABEL_MONTO_A_PAGAR_TXT}
{_FORMA_DE_PAGO_PENDIENTE_TXT}
{CURRENCY} {MONTO}
{_HTML_RESERVA_RESPETADA_1_TXT} {FECHA_LIMITE_RESERVA} ({PAIS_TKXL}). {_HTML_RESERVA_RESPETADA_2_TXT}

{LINK_PAGO_RESERVA}
