<table>
	<tr>
		{*BLOQUE_HEADER_TRAMO}<th>{HEADER_TRAMO}</th>{/BLOQUE_HEADER_TRAMO}
		<th>{_LABEL_CABINA}</th>
		{*BLOQUE_HEADER_MONTO}<th>{_LABEL_MONTO}</th>{/BLOQUE_HEADER_MONTO}
	</tr>	
	<tr>
		{*BLOQUE_TRAMO}	<td>{ORIGEN} - {DESTINO} {FECHA}</td> {/BLOQUE_TRAMO}
		<td>{CABINA}</th>
		{*BLOQUE_MONTO}<th>{SIMBOLO_MONEDA}{MONTO}</th>{/BLOQUE_MONTO}
	</tr>
</table>
