<table class="tabla_formulario_pnrs" style=" background-color:#f3f4f9; margin-left: auto; margin-right: auto; text-align: left; ">
	<tr>
	  <td>
		<strong>{_LABEL_CODIGO_RESERVA}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_NUMERO_TICKET}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_CODIGO_LIBERACION}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_VUELO}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_ORIGEN_DESTINO}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_FECHA}</strong><br>
	  </td>
	  <td>
		<strong>{_LABEL_SELECCIONE}</strong><br>
	  </td>
	</tr>
	<tr>
		<td>
		<lan:widget class="Widgets::Form::Detalle_PNR">
			<lan:value>{ACTION_URL}</lan:value>
			<lan:value>{SESSION_ID}</lan:value>
			<lan:value>{PNR}</lan:value>
			<lan:value>{NUMERO_TICKET}</lan:value>
			<lan:value>{TIPO_BOLETO}</lan:value>
			<lan:value>{VUELO}</lan:value>
			<lan:value>{OD}</lan:value>
			<lan:value>{FECHA}</lan:value>
		</lan:widget>
		</td>
	</tr>
</table>
