{_LABEL_TENGA_PRESENTE_QUE}:

{_LISTA_RECOMENDACIONES_TROTAMUNDO}
{*BLOQUE_FORMA_ENTREGA_TKT}
{_TXT_ETKT_ACENTO}
{/BLOQUE_FORMA_ENTREGA_TKT}
{*BLOQUE_TC_PROMOCION_TMUNDO}
{_MSG_TROTAMUNDO_1_RESTRICCIONES}{_LINK_TC_PROMOCION_TMUNDO}{_MSG_TROTAMUNDO_2_RESTRICCIONES}
{/BLOQUE_TC_PROMOCION_TMUNDO}
{_FRASE_ATTE_TROTAMUNDO}
