{_PALABRA_TARIFA} {FAREBASIS} {_PALABRA_DESDE} {ORIGEN} {_PALABRA_HASTA} {DESTINO} {_FRASE_PARA_VIAJAR_EL} {FECHAVUELO} 
a){_LABEL_APLICABILIDAD}
	-{_TXT_ANTICIPACION_MINIMA_COMPRA}: {AP}
	-{_TXT_ESTADIA_MINIMA}: {ESTADIAMIN}
	-{_TXT_ESTADIA_MAXIMA}: {ESTADIAMAX}
b){_LABEL_CAMBIOS_DE_FECHA_RUTA}
    {_LABEL_REGULACIONES_BEFORE}
	-{FECHA}
	-{FECHAMISMODIA}
    {_TXT_REGULACIONES_AFTER}
	-{FECHA_AFTER}
c){_LABEL_DEVOLUCIONES}
    {_LABEL_REGULACIONES_BEFORE}
	-{DEVOLUCIONES}
    {_LABEL_REGULACIONES_AFTER}
	-{DEVOLUCIONES_AFTER}
d){_TXT_DESCUENTO_SEGUN_PAX}
	-{INF}
	-{CHD}
e){_LABEL_OTRAS_REGULACIONES}
	-{VALIDEZ}
	-{ACUMULA_LANPASS}
	-{UPG_LANPASS}
	-{RESERVA_ASIENTO}
	-{PRECHEQUEO}
