{LINEAS_TARIFA}
{LINEAS_DESCUENTO}

{_LABEL_TOTAL} ({CURRENCY})
{_LABEL_TARIFA} {TOTAL_TARIFA}
{_LABEL_IMPUESTO} {TOTAL_IMPUESTOS}{ENCABEZADO_SOBRECARGO}   {CAMPO_TOTAL_SOBRECARGO}
{_LABEL_TOTAL} {TOTAL}
