<TINS_XML_DATA>
	<Header>
		<Version>1.0</Version>
		<SourceId>LNW</SourceId>
		<MessageId>{MESSAGE_ID}</MessageId>
	</Header>
	<Segment>
		<TransactionType embed='true'>GenerateDoc</TransactionType>
		<TransactionId>{TRANSACTION_ID}</TransactionId>
		<PolicyIn>
			<GDSCode>LNW</GDSCode>
			<AgencyPCC>{AGENCY_PCC}</AgencyPCC>
			<AgencyCode>{AGENCY_CODE}</AgencyCode>
			<IATACntryCd>{IATA_COUNTRY_CODE}</IATACntryCd>
			<GDSProductCode>{PRODUCT_CODE}</GDSProductCode>
			<InceptionDate>{FECHA_IDA}</InceptionDate>
			<Language>{LANGUAGE}</Language>
			<PolicyNumber>{POLICY_NUMBER}</PolicyNumber>
			<TransactionNo>{TRANSACTION_NUMBER}</TransactionNo>
		</PolicyIn>
		{*INSURED}
		<Insured>
			<SequenceNo>0</SequenceNo>
			<LastNm>{LAST_NAME}</LastNm>
			<PlanCode>{PLAN_CODE}</PlanCode>
			<EmailAddr></EmailAddr>
		</Insured>
		{/INSURED}
	</Segment>
</TINS_XML_DATA>

