<TINS_XML_DATA>
	<Header>
		<MessageType>GRP1</MessageType>
		<Version>WAATS</Version>
		<SourceId>LNC</SourceId>
		<MessageId>{TRANSACTION_ID}</MessageId>
	</Header>
	<Segment>
		<TransactionId>{TRANSACTION_ID}</TransactionId>
		<TransactionType>NQuote</TransactionType>
		<PolicyIn>
			<GDSCode>LNW</GDSCode>
			<AgencyPCC>{AGENCY_PCC}</AgencyPCC>
			<AgencyCode>{AGENCY_CODE}</AgencyCode>
			<IATACntryCd>{IATA_COUNTRY_CODE}</IATACntryCd>
			<InsuranceType>{PLAN}</InsuranceType>
			<TransactionApplDate>{FECHA_TRANSACCION}</TransactionApplDate>
			<InceptionDate>{FECHA_IDA}</InceptionDate>
			<ExpirationDate>{FECHA_VUELTA}</ExpirationDate>
			<TransactionEffDate>{FECHA_IDA}</TransactionEffDate>
			<TransactionExpDate>{FECHA_VUELTA}</TransactionExpDate>
			<GDSProductCode>{COD_PRODUCTO}</GDSProductCode>
		</PolicyIn>
		{*INSURE}
		<Insured>
			<TitleNm></TitleNm>
			<FirstNm></FirstNm>
			<LastNm></LastNm>
			<InsuredTypCd>{INSURED_TYP_CD}</InsuredTypCd>
			<IsInsuredFlag>{IS_INSURED}</IsInsuredFlag>
			<BirthDt>{FECHA_NACIMIENTO}</BirthDt>
			<InsuredIdNo>PassportNo</InsuredIdNo>
			<PlanCode>{PLAN}</PlanCode>
			<BenefitIn>
				<BenefitCd>000000</BenefitCd>
			</BenefitIn>
		</Insured>
		{/INSURE}
	</Segment>
</TINS_XML_DATA>
