<TINS_XML_DATA>
	<Header>
		<MessageType>GRP1</MessageType>
		<Version>WAATS</Version> 
		<SourceId>LNC</SourceId> 
		<MessageId>{TRANSACTION_ID}</MessageId>
	</Header>
	<Segment>
		<TransactionId>{TRANSACTION_ID}</TransactionId> 
		<TransactionType>NSell</TransactionType> 
		<PolicyIn>
			<GDSCode>LNW</GDSCode>
			<AgencyPCC>{AGENCY_PCC}</AgencyPCC>
			<AgencyCode>{AGENCY_CODE}</AgencyCode>
			<IATACntryCd>{IATA_COUNTRY_CODE}</IATACntryCd>
			<InsuranceType>{PLAN}</InsuranceType>
			<TransactionApplDate>{FECHA_TRANSACCION}</TransactionApplDate>
			<InceptionDate>{FECHA_IDA}</InceptionDate>
			<ExpirationDate>{FECHA_VUELTA}</ExpirationDate>
			<TransactionEffDate>{FECHA_IDA}</TransactionEffDate>
			<TransactionExpDate>{FECHA_VUELTA}</TransactionExpDate>
			<GDSProductCode>{COD_PRODUCTO}</GDSProductCode>
			<VoucherNo>{VOUCHER_NUMBER}</VoucherNo>
			<FurthestCity>{FURTHEST_CITY}</FurthestCity>
		</PolicyIn>
		{*INSURED}
		<Insured>
			<TitleNm>Mr</TitleNm>
			<FirstNm>{NOMBRE}</FirstNm> 
			<LastNm>{PRIMER_APELLIDO}</LastNm>
			<InsuredTypCd>{INSURED_TYPE}</InsuredTypCd>
			<IsInsuredFlag>{IS_INSURED}</IsInsuredFlag> 
			<BirthDt>{FECHA_NACIMIENTO}</BirthDt>
			<InsuredIdNo>{INSURED_ID_NUMBER}</InsuredIdNo>
			<PlanCode>{PLAN}</PlanCode> 
			<BenefitIn>
				<BenefitCd>000000</BenefitCd> 
			</BenefitIn>
			{*ADDRESS}
			<Address>
				<StreetLn1Nm>{STREET_LINE_1}</StreetLn1Nm>
				<StreetLn2Nm>{STREET_LINE_2}</StreetLn2Nm>
				<StreetLn3Nm>{STREET_LINE_3}</StreetLn3Nm>
				<CityNm>{CITY_NAME}</CityNm>
				<StateNm>{STATE_NAME}</StateNm>
				<ZipCd>{ZIP_CODE}</ZipCd>
				<DistrictNm>{DISTRICT_CODE}</DistrictNm>
				<HomePhoneNo>{HOME_NUMBER}</HomePhoneNo>
				<WorkPhoneNo>{WORK_NUMBER}</WorkPhoneNo>
				<CellPhoneNo>{CELL_NUMBER}</CellPhoneNo>
				<FaxNo>{FAX_NUMBER}</FaxNo>
				<EmailAddr>{EMAIL}</EmailAddr>
				<CntryNm>{COUNTRY_NAME}</CntryNm>
			</Address>
			{/ADDRESS}
		</Insured>
		{/INSURED}
	</Segment>
</TINS_XML_DATA>
