<!--
TITLE: LAN.com T&eacute;rminos de uso
TIPO_PAGINA: LAN
KEYWORDS:
SECCION: OTROS/TERMINOS_USO
--> 

<h1>{_TITULO_DETALLE_IMPUESTOS_US}</h1>
<ul>
<li>{_FRASE_CARGO_ATO_US}
</li>
<li>{_FRASE_CARGO_SEGURIDAD_US}
</li>
<li>{_FRASE_CARGO_OTROS_IMPUESTOS_US}
</li>
</ul>