<h4>{_LABEL_RECOMENDACIONES}</h4>
<ul class=list>
  <li>{_HTML_RECOMENDACIONES_GRAL_1}</li>
  <li>{_HTML_RECOMENDACIONES_GRAL_2}</li>
  <li>{_HTML_RECOMENDACIONES_GRAL_3}</li>
  <li>{_HTML_RECOMENDACIONES_GRAL_4}</li>
  <!--<li>{_HTML_RECOMENDACIONES_GRAL_5}<a href={_URL_ANULACIONES}>{_HTML_RECOMENDACIONES_GRAL_5A}</a></li> -->
  <li>{_HTML_RECOMENDACIONES_GRAL_6}</li>
</ul>
<br>