<h4>{_LABEL_RECOMENDACIONES}</h4>
<ul class=list>
	{*BLOQUE_RECOMENDACIONES_RESERVA}
	<li>{_RECOMENDACIONES_RESERVA}</li>
	{/BLOQUE_RECOMENDACIONES_RESERVA}
	{*BLOQUE_RECOMENDACIONES_RESERVA_LAN}
	<li>{_RECOMENDACIONES_RESERVA_LAN}</li>
	{/BLOQUE_RECOMENDACIONES_RESERVA_LAN}
	{RECOMENDACIONES}
</ul>
<br>