{*BLACKOUT}<p>{ENCABEZADO}{_FRASE_TRAVEL_IS_NOT_PERMITTED} {RANGOS}.</p>{/BLACKOUT}

{*TO}{_PALABRA_TO_BO} {PLACE} {/TO}
{*FROM}{_PALABRA_FROM} {PLACE} {/FROM}
{*ORIGINATING}{_PALABRA_ORIGINATING} {PLACE} {/ORIGINATING}
{*RANGO}{_PALABRA_DESDE} {FECHA_INICIO_RANGO} {_PALABRA_HASTA} {FECHA_FIN_RANGO}{OR}{/RANGO}
{*OR} {_PALABRA_OR} {/OR}
{*AND} {_PALABRA_AND} {/AND}


{*MIN_STAY}<li>{_FRASE_MN_INICIO}{MINIMO_ESTADIA}{UNION}{NOCHE_DE}{_FRASE_MN_FIN}</li>{/MIN_STAY}
{*FRASE_ESTADIA}{ESTADIA} {UNIDAD_TIEMPO_ESTADIA}{/FRASE_ESTADIA}
{*FRASE_NOCHE_ESTADIA_MINIMA}{_FRASE_NOCHE_DE} {NOCHE_ESTADIA_MINIMA}{/FRASE_NOCHE_ESTADIA_MINIMA}
{*NEW_MIN_STAY}<li>{_FRASE_MN_INICIO}{MINIMO_ESTADIA}{_FRASE_MN_FIN}</li>{/NEW_MIN_STAY}


{*MAX_STAY}<li>{_FRASE_MX_INICIO} {MAXIMO_ESTADIA}{_FRASE_MX_FIN}</li>{/MAX_STAY}


{*TR_ON_AFTER}<li>{_FRASE_TR_ON_AFTER} {FECHA}.</li>{/TR_ON_AFTER}
{*TR_ON_BEFORE}<li>{_FRASE_TR_ON_BEFORE} {FECHA}.</li>{/TR_ON_BEFORE}
{*TR_COMPLETED_MIDNIGHT}<li>{_FRASE_TR_COMPLETED_MIDNIGHT_INI} {FECHA}{_FRASE_TR_COMPLETED_MIDNIGHT_FIN}</li>{/TR_COMPLETED_MIDNIGHT}
{*TR_COMMENCE_MIDNIGHT}<li>{_FRASE_TR_COMMENCE_MIDNIGHT} {FECHA}.</li>{/TR_COMMENCE_MIDNIGHT}
{*TVL_RESTRICTION}{TR_ON_AFTER}{TR_ON_BEFORE}{TR_COMPLETED_MIDNIGHT}{TR_COMMENCE_MIDNIGHT}{/TVL_RESTRICTION}


{*AP_RESERVA}<li>{_FRASE_AP_RESERVA_INICIO} {AP} {UNIDAD_DE_TIEMPO_AP} {_FRASE_AP_RESERVA_FIN}</li>{/AP_RESERVA}
{*AP_TICKET_CR_RESERVA}<li>{_FRASE_AP_TICKET_CR_RESERVA_INICIO} {AP} {UNIDAD_DE_TIEMPO_AP} {_FRASE_AP_TICKET_CR_RESERVA_FIN}</li>{/AP_TICKET_CR_RESERVA}
{*AP_TICKET_CR_SALIDA}<li>{_FRASE_AP_TICKET_CR_SALIDA_INICIO} {AP} {UNIDAD_DE_TIEMPO_AP} {_FRASE_AP_TICKET_CR_SALIDA_FIN}</li>{/AP_TICKET_CR_SALIDA}
{*AP_TICKET_EQ_RESERVA}<li>{_FRASE_AP_COMPRA_INMEDIATA}</li>{/AP_TICKET_EQ_RESERVA}
{*AP_RESERVATION_FOR_ALL_SECTORS}<li>{_FRASE_AP_RESERVA_REQUERIDA}</li>{/AP_RESERVATION_FOR_ALL_SECTORS}
{*ADVANCE_RES_TKT}{AP_RESERVA}{AP_TICKET_CR_RESERVA}{AP_TICKET_CR_SALIDA}{AP_RESERVATION_FOR_ALL_SECTORS}{AP_INSTANT_PURCHASE}{/ADVANCE_RES_TKT}


{*PE_CHANGE_BEFORE_CON_MULTA}<li>{_FRASE_PE_CHANGE_BEFORE_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}{_FRASE_PE_CHANGE_BEFORE_FIN}</li>{RULES}{CD_RULE}{/PE_CHANGE_BEFORE_CON_MULTA}
{*PE_CHANGE_AFTER_CON_MULTA}<li>{_FRASE_PE_CHANGE_AFTER_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}{_FRASE_PE_CHANGE_AFTER_FIN}</li>{RULES}{CD_RULE}{/PE_CHANGE_AFTER_CON_MULTA}
{*PE_REFUND_BEFORE_CON_MULTA}<li>{_FRASE_PE_REFUND_BEFORE_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}{_FRASE_PE_REFUND_BEFORE_FIN}</li>{RULES}{CD_RULE}{/PE_REFUND_BEFORE_CON_MULTA}
{*PE_REFUND_AFTER_CON_MULTA}<li>{_FRASE_PE_REFUND_AFTER_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}{_FRASE_PE_REFUND_AFTER_FIN}</li>{RULES}{CD_RULE}{/PE_REFUND_AFTER_CON_MULTA}

{*PE_NEW_CHANGE_NO_BEFORE}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_1}</li>{/PE_NEW_CHANGE_NO_BEFORE}
{*PE_NEW_CHANGE_BEFORE_CON_MULTA}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_2} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}</li>{/PE_NEW_CHANGE_BEFORE_CON_MULTA}
{*PE_NEW_CHANGE_NO_AFTER}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_3}</li>{/PE_NEW_CHANGE_NO_AFTER}
{*PE_NEW_CHANGE_BEFORE_SIN_MULTA}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_4}</li>{/PE_NEW_CHANGE_BEFORE_SIN_MULTA}
{*PE_NEW_CHANGE_AFTER_CON_MULTA}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_5} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}</li>{/PE_NEW_CHANGE_AFTER_CON_MULTA}
{*PE_NEW_CHANGE_AFTER_SIN_MULTA}<li>{_CUV_CONDICIONES_CAMBIOS_OPCION_6}</li>{/PE_NEW_CHANGE_AFTER_SIN_MULTA}

{*PE_NEW_NO_REFUND}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_1}</li>{/PE_NEW_NO_REFUND}
{*PE_NEW_REFUND_BEFORE_CON_MULTA}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_2} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}</li>{/PE_NEW_REFUND_BEFORE_CON_MULTA}
{*PE_NEW_REFUND_NO_AFTER}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_3}</li>{/PE_NEW_REFUND_NO_AFTER}
{*PE_NEW_REFUND}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_4}</li>{/PE_NEW_REFUND}
{*PE_NEW_REFUND_AFTER_CON_MULTA}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_5} {SIGNO_MONEDA_MULTA} {MONTO_MULTA}</li>{/PE_NEW_REFUND_AFTER_CON_MULTA}
{*PE_NEW_REFUND_BEFORE_SIN_MULTA}<li>{_CUV_CONDICIONES_DEVOLUCIONES_OPCION_6}</li>{/PE_NEW_REFUND_BEFORE_SIN_MULTA}

{*PENALTIES}
{_FRASE_PE_CHANGES}:
<ul>{CHANGE_GENERAL}</ul><ul>{CHANGE_BEFORE}</ul><ul>
{CHANGE_AFTER}</ul>
{_FRASE_PE_REFUND}:
<ul>{REFUND_GENERAL}</ul><ul>{REFUND_BEFORE}</ul><ul>
{REFUND_AFTER}</ul>
{/PENALTIES}
{*PE_REFUND_CON_MULTA}<li>{_FRASE_PE_REFUND_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA} {APPLY_PERCENT}{_FRASE_PE_REFUND_FIN}</li>{RULES}{CD_RULE}{/PE_REFUND_CON_MULTA}
{*CD_RULE_CHANGE}{_FRASE_CAMBIOS_CD_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA} {_FRASE_CAMBIOS_CD_FIN}{/CD_RULE_CHANGE}
{*CD_RULE_REFUND}{_FRASE_REFUND_CD_INICIO} {SIGNO_MONEDA_MULTA} {MONTO_MULTA} {_FRASE_REFUND_CD_FIN}{/CD_RULE_REFUND}



{*STOPOVERS_GRATIS}<li>{NUM} {_FRASE_SO_GRATIS}.</li>{/STOPOVERS_GRATIS}
{*STOPOVERS_GRATIS_CON_LUGAR}<li>{NUM} {_FRASE_SO_GRATIS} {PALABRA_EN} {PLACE}.</li>{/STOPOVERS_GRATIS_CON_LUGAR}
{*STOPOVERS_PAGADOS}<li>{NUM} {_FRASE_SO_PERMITIDOS}{DIRECCION}{DETALLE}</li>{/STOPOVERS_PAGADOS}
{*STOPOVERS_PAGADO}<li>{NUM} {_FRASE_SO_PERMITIDO}{DIRECCION}{DETALLE}</li>{/STOPOVERS_PAGADO}
{*STOPOVERS_MIXTO}<p>{_FRASE_LIMITADO_A} {NUM_GRATIS} {_FRASE_SO_GRATIS} {_PALABRA_AND} {NUM_PAGADOS} {_FRASE_CON_CARGO_DE} {SIGNO_MONEDA} {MONTO}.</p>{/STOPOVERS_MIXTO}
{*STOPOVERS_SOLO_CON_COBRO} {_FRASE_CON_CARGO_DE} {SIGNO_MONEDA} {MONTO}.{/STOPOVERS_SOLO_CON_COBRO}
{*STOPOVERS_DETALLE_GRATIS_CON_LUGAR}<p>{NUM_GRATIS} {_FRASE_SO_GRATIS} {_PALABRA_EN} {PLACE} {_FRASE_EN_CADA_DIRECCION} {NUM_PAGADOS} {_FRASE_CON_CARGO_DE} {SIGNO_MONEDA} {MONTO}.</p>{/STOPOVERS_DETALLE_GRATIS_CON_LUGAR}
{*STOPOVERS_DETALLE_GRATIS}<p>{NUM} {_FRASE_SO_GRATIS} {_FRASE_EN_CADA_DIRECCION}.</p>
{/STOPOVERS_DETALLE_GRATIS}
{*DIRECCION}{NUM} {_FRASE_EN_CADA_DIRECCION}.{/DIRECCION}
