{_LABEL_INFORMACION_DE_LA_EMPRESA_TXT}
    {_LABEL_RAZON_SOCIAL_TXT} {FACTURA_RAZON_SOCIAL}     {_LABEL_RUT_TXT} {FACTURA_RUT} 
    {_LABEL_DIRECCION_LEGAL_TXT} {FACTURA_DIRECCION_LEGAL} {_LABEL_COMUNA_TXT} {FACTURA_COMUNA}
    {_LABEL_GIRO_TXT} {FACTURA_GIRO} {_LABEL_TELEFONO_TXT} {FACTURA_TELEFONO} 
{_LABEL_FACTURA_ENVIADA_TXT}
    {_LABEL_NOMBRE_Y_APELLIDO_TXT} {FACTURA_NOMBRE_ENVIO} 
{_LABEL_DIRECCION_ENVIO_TXT}
    {_LABEL_DIRECCION_TXT} {FACTURA_DIRECCION_ENVIO} {_LABEL_COMUNA_TXT} {FACTURA_COMUNA_ENVIO}
    {_LABEL_CIUDAD_TXT} {FACTURA_CIUDAD_ENVIO} 
