 a) {_LABEL_APLICABILIDAD_TXT}
	-{_LABEL_ANTICIPACION_MINIMA_COMPRA_TXT}: {AP}
	-{_LABEL_ESTADIA_MINIMA_TXT}: {ESTADIAMIN}
	-{_LABEL_ESTADIA_MAXIMA_TXT}: {ESTADIAMAX}
 b) {_LABEL_CAMBIOS_DE_FECHA_RUTA_TXT}
   	-{FECHA}
   	-{FECHAMISMODIA}
 c) {_LABEL_DEVOLUCIONES_TXT}
   	-{DEVOLUCIONES}
 d) {_LABEL_DESCUENTO_SEGUN_PAX_TXT}
   	-{INF}
   	-{CHD}
 e) {_LABEL_OTRAS_REGULACIONES_TXT}
 	-{VALIDEZ}
 	-{ACUMULA_LANPASS}
 	-{UPG_LANPASS}
 	-{RESERVA_ASIENTO}
 	-{PRECHEQUEO}
	 
