{NUMERO_ITEM} {_PALABRA_CHECKIN_TXT}

{*CON_CHECKIN}
{_INVITACION_CHECKIN_TXT}
{_LINK_INFO_CHECKIN_TXT}
{/CON_CHECKIN}

{*VUELOS_NO_ABIERTOS}
{_INVITACION_CHECKIN_NO_ABIERTO_TXT}
{_LINK_INFO_CHECKIN_TXT}
{/VUELOS_NO_ABIERTOS}

{*RESERVA}
{_INVITACION_CHECKIN_RESERVA_TXT}
{_LINK_INFO_CHECKIN_TXT}
{/RESERVA}

{*SIN_E_TICKET}
{_INVITACION_CHECKIN_SIN_E_TICKET_TXT}
{_LINK_INFO_CHECKIN_TXT}
{/SIN_E_TICKET}
